### ISSUE TITLE
Enable continuous integration

### ISSUE THREAD

**Issue by femtotrader** [mrjbq7/ta-lib#104]
Hello,

it will be nice to enable continuous integration.
Travis (for Linux and OS X) and AppVeyor (for Windows) can be chosen.

Installing TA-Lib under Linux can be done using:

```bash
wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
tar -zxvf ta-lib-0.4.0-src.tar.gz
cd ta-lib
./configure --prefix=/usr
make
sudo make install
```

Installing TA-Lib under Mac OS X can be done using:

```bash
brew update
brew install ta-lib
```

Tests should probably be in a separate directory.

Some additional tests could be

```assert len(talib.get_functions()) == 158```

there is no `talib.version` but it could be also something to add to this wrapper and to tests.

Under Julia I get:

```julia
julia> GetVersionString()
"0.4.0 (Oct 20 2014 10:59:39)"
```

It's necessary to have Numpy, Pandas... to make such tests.
So you may have a look at https://github.com/pydata/pandas-datareader/blob/master/.travis.yml
it installs a Mini Conda distribution.

Kind regards

**Comment by mrjbq7** [comment]
We have Travis integration now!  Closing!
