### ISSUE TITLE
fail to install talib with error "NameError: name 'include_dirs' is not defined"

### ISSUE THREAD

**Issue by FrankYu** [mrjbq7/ta-lib#105]
Hi, there

I'm trying to install talib on startos zone.
I have install TA-Lib,
 find / -name libta_lib.so.0
/root/ta-lib/src/.libs/libta_lib.so.0
/opt/lib/libta_lib.so.0
/usr/local/lib/libta_lib.so.0

when I try to install talib, I always met error 
#pwd
/root/talib/ta-lib
#ls
AUTHORS      COPYRIGHT    LICENSE      README.md    setup.py     tools
CHANGELOG    DEVELOPMENT  Makefile     docs         talib
#python setup.py install 
Traceback (most recent call last):
  File "setup.py", line 58, in <module>
    include_dirs.insert(0, numpy.get_include())
NameError: name 'include_dirs' is not defined

**Comment by mrjbq7** [comment]
Fixed in 32773c92fa2522fe2ed32db9f666e04cd3aefd59.
