### ISSUE TITLE
import ta-lib failure

### ISSUE THREAD

**Issue by jinglunkenken** [mrjbq7/ta-lib#106]
Hi, I am working on a mac,I installed brew, then brew install ta-lib, and it was succussful, but when I try to import talib in ipython notebook, I have the error: No module named talib, is there anything anyone can suggest?

**Comment by mrjbq7** [comment]
The basic steps are:

1) Install the underlying ta-lib C library (which you seem to have done with ``brew install ta-lib``).

2) Install this ta-lib Python wrapper (which you don't mention, but I assume you also did).

Some things to try debugging:

Are you trying to use a different python than the one where this ta-lib module was installed?  Common problems here include installing it into the system site-packages but trying to use it from a brew installed python for example.

**Comment by jinglunkenken** [comment]
@mrjbq7 Thanks for the immediate reply, my mac now can use talib with no further problem. But when I try to import talib on my windows 10, I use 64 bits. I still have the error cannot import name common, in the cmd it shows I had import talib successfully'requirement already satisfied'

**Comment by mrjbq7** [comment]
I suspect on your Windows computer you need to rebuild the ta-lib C library from source as 64-bit since the binary download is 32-bit only. Or install/run on 32-bit Python.

**Comment by jinglunkenken** [comment]
@mrjbq7 if I reinstall 32-bit python on my 64bit computer, will python have any problems such as crash or slow?

**Comment by mrjbq7** [comment]
I've heard it works generally fine but there might be an issue with maximum memory address space, maybe not an issue depending on your use case. 

There have been successful 64-bit compile from source. I could find a link if you think it would help.

**Comment by jinglunkenken** [comment]
@mrjbq7 Yes please give me the link, thanks for the suggestions, all are helpful~

**Comment by mrjbq7** [comment]
From #11,

> Install VS2010 Ultimate
> Download ta-lib-0.4.0-msvc.zip and extract to c:\ta-lib
> Open C:\ta-lib\c\ide\vs2005\lib_proj\ta_lib.sln and compile 6 builds to 64-bit without errors
