### ISSUE TITLE
have to recalculate when new data arriving?

### ISSUE THREAD

**Issue by 4ever911** [mrjbq7/ta-lib#112]
for instance,   I have a  ndarray of 100 elements, and now i successful get the EMA array,

Now, i am streaming new data, when i get the new arrived data, can i generate a new EMA element and push it to the old EMA array?

**Comment by mrjbq7** [comment]
Have you tried the new experimental Streaming API that I recently added?

It takes an input array and only calculates the most recent value (e.g., the "new EMA element").

You can add a new observation to the input arrays and then call the streaming function again to get the new observation.

**Comment by mrjbq7** [comment]
I have thought about generalizing somehow so the Function API (all values) and the Streaming API (latest value) could also have another API that might calculate "some" values. But this is an experiment that seems useful to people so I wanted to push it and see how it's used.

**Comment by mrjbq7** [comment]
See #114 for some discussion of how certain indicators (including EMA) are "unstable" when used in a streaming calculation because they don't scan all previous data points that would have been used to calculate their values in the full api.
