### ISSUE TITLE
UnsatisfiableError install ta-lib via anaconda 

### ISSUE THREAD

**Issue by barbiyong** [mrjbq7/ta-lib#118]
I setup python 3.5 by using anaconda on ubuntu and i want to install ta-lib 
using command from anaconda.org/quantopian/ta-lib
> conda install -c quantopian ta-lib=0.4.9

but it have an errors by

> Fetching package metadata .........
> Solving package specifications: ....
> UnsatisfiableError: The following specifications were found to be in conflict:
>   - python 3.5*
>   - ta-lib 0.4.9*
> Use "conda info <package>" to see the dependencies for each package.

How can i solve this. Thank you.

**Comment by mrjbq7** [comment]
No idea. It does support Python 3.5, but maybe the package metadata needs to be updated. I don't maintain that, sorry. Maybe @quantopian?

**Comment by femtotrader** [comment]
According https://anaconda.org/Quantopian/ta-lib/files
uploaders are @llllllllll or @ssanderson or @richafrank
but I don't see any conda package for py35 available
latest packages being`win-64/ta-lib-0.4.9-np111py27_0.tar.bz2` and `win-64/ta-lib-0.4.9-np111py34_0.tar.bz2`

**Comment by llllllllll** [comment]
We are not currently building packages for 3.5 because we maintain our conda upload of ta-lib for zipline which does not yet support 3.5.

**Comment by mrjbq7** [comment]
Closing this as it's not something I can fix.

**Comment by spallesen** [comment]
Any idea when this 3.5 package is available on Conda?
