### ISSUE TITLE
Using DataFrames and TA-Lib in python

### ISSUE THREAD

**Issue by hnasser95** [mrjbq7/ta-lib#120]
Hello,
I'm trying to use some of the technical indicators in ta-lib but I seem to have hit a roadblock in that I can't seem to make the library work using a dataframe.
For example, when I use:

`df = web.DataReader("SPY", 'yahoo', start, today)
df = pd.DataFrame(df,df.index) 
ewmax = df['EMA_32'] = ta.EMA(df.Close,timeperiod=32)`

I get 
`----> 3 ewmax = df['EMA_32'] = ta.EMA(df.Close,timeperiod=32)
TypeError: Argument 'real' has incorrect type (expected numpy.ndarray, got Series)`

How can I get ta-lib to work using a series or a dataframe ?

Thanks

**Comment by briancappello** [comment]
pandas Series objects have a property [values](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.values.html) which you can use to get the underlying numpy array. So, this should work:
```python
df['EMA_32'] = ta.EMA(df.Close.values, timeperiod=32)
```

**Comment by hnasser95** [comment]
Thanks Brian - that did the trick

**Comment by nooq** [comment]
Gg

2016/10/24 18:52 "Brian Cappello" <notifications@github.com>:

**Comment by femtotrader** [comment]
A "higher level" version could be

```python
import pandas_datareader as web
import talib
start, today = "2015-01-01", "2016-10-26"
df = web.DataReader("SPY", 'yahoo', start, today)
df.columns = df.columns.str.lower()
talib.abstract.EMA(df, timeperiod=32, price='close')
```
