### ISSUE TITLE
ImportError Windows

### ISSUE THREAD

**Issue by timfoxmf** [mrjbq7/ta-lib#125]
Hi, I am working on a Windows (32bit), I installed talib, then install from github wrapper, and it was succussful, but when I try to import talib, I have the error:

`Traceback (most recent call last):`
`File "<stdin>", line 1, in <module>`
`File "talib\__init____.py", line 4, in <module>`
`from . import common`
`ImportError: cannot import name common`

Is there anything anyone can suggest?

**Comment by mrjbq7** [comment]
Usually that happens when there is an error installing this python module and it looks like it succeeded but didn't.

**Comment by mrjbq7** [comment]
Closing all installation issues, if someone has a specific problem please open a new one.
