### ISSUE TITLE
 is it  possible to take the advantage of the cython nogil keyword?

### ISSUE THREAD

**Issue by goldenbull** [mrjbq7/ta-lib#128]
cython has `nogil` keyword which can bypass the GIL and should be quite useful in multi-thread apps

**Comment by mrjbq7** [comment]
I'm not sure if the underlying ``TA-Lib`` C library is fully reentrant, but it seems like it could work. 

Is this a performance issue you're running into?

**Comment by goldenbull** [comment]
I have a python http server hosting an indicator calculating service, which is using ta-lib. Now many clients are using this service simultaneously. The http service is multi-threaded, so the GIL is the bottleneck.

**Comment by mrjbq7** [comment]
So we call the ta-lib C functions with a pointer to memory backing a numpy array.  What I'm not sure about, is can that pointer change on you if python runs a GC and you aren't holding the GIL, could your pointer be stale?

**Comment by goldenbull** [comment]
to my limited knowledge from [cython doc](http://cython.readthedocs.io/en/latest/src/userguide/external_C_code.html#acquiring-and-releasing-the-gil), it seems to be safe if no python object is referenced during the operation.

**Comment by mrjbq7** [comment]
The memory is owned by a python object, does that count? It's not obvious to me what happens with a GC triggered while we have a call into ta-lib with `nogil`.

**Comment by goldenbull** [comment]
GC may move the python object, but will not move the pointer value in the object.
Here is an [example](http://docs.cython.org/en/latest/src/userguide/memoryviews.html) about nogil and numpy in cython
