### ISSUE TITLE
Value of 200 in CDLHIKKAKE

### ISSUE THREAD

**Issue by x011** [mrjbq7/ta-lib#129]
As per documentation (comments on **func.py**), `CDLHIKKAKE` pattern recognition function should return values of -100, 0 or 100 (like all the other patterns). On one of my tests I got a result of 200. Any idea why this is happening ?
**General Question:**
If a return value of a pattern recognition is `-100`, does it mean it's signaling a BEAR pattern? or do I have to analyze the value based on the type of candle pattern to determine if it's a BEAR/BULL signal?

**Comment by mrjbq7** [comment]
That's odd - can you share that test case?

**Comment by x011** [comment]
I'm using 5 minute bars (last 3 days) of DRYS (stock) via IB Api. 
All other results have normal values (-100, 0 and 100).
I don't know what you mean by _test case_ but here's a gist with the output of pandas `to_csv`

https://gist.github.com/anonymous/e0da52c7fd2b25dc3f5d7a9945e92e62

Please check the c_HIKKAKE` column and you'll find several `200` values.
PS: I'm using  ta-lib 0.4.9 win-32 installed using conda

**Comment by mrjbq7** [comment]
I would have to look into it further, but looking at the [source code](https://sourceforge.net/p/ta-lib/code/HEAD/tree/trunk/ta-lib/c/src/ta_func/ta_CDLHIKKAKE.c#l395) for ``CDLHIKKAKE``, on line 395, it looks like it can produce a 200 when the "close is higher than high of the second".

As for your general question, I do think in general negative values imply bearish and positive values imply bullish, but I suppose also that depends on confirmation through your personal testing and asset class.

**Comment by x011** [comment]
Thank you for your answers.

**Comment by bkcollection** [comment]
If not mistaken, 100,-100 is pattern observed, but 200 and -200 is pattern confirmed.

**Comment by x011** [comment]
> If not mistaken, 100,-100 is pattern observed, but 200 and -200 is pattern confirmed.
Where did you get this information?

**Comment by doufunao** [comment]
> > If not mistaken, 100,-100 is pattern observed, but 200 and -200 is pattern confirmed.
> > Where did you get this information?

Source code. 
There are also some comments as your reference.
line 239 
* outInteger[confirmationbar] is equal to 100 + the bullish hikkake result or -100 - the bearish hikkake result
https://sourceforge.net/p/ta-lib/code/HEAD/tree/trunk/ta-lib/c/src/ta_func/ta_CDLHIKKAKE.c#l239
