### ISSUE TITLE
List of Function Arguments? 

### ISSUE THREAD

**Issue by masteryoda34** [mrjbq7/ta-lib#13]
I see the list of functions for talib, but is there a someplace that lists the arguments with descriptions for each function in talib?

**Comment by alexanderkoumis** [comment]
Hi, what units is "optInTimePeriod" in? Seconds? Minutes? Number of values in the array?

**Comment by mrjbq7** [comment]
It's in units of whatever the underlying array is, so "values in the array".

**Comment by alexanderkoumis** [comment]
Okay thanks, got it.
