### ISSUE TITLE
/usr/bin/ld: cannot find -lta_lib

### ISSUE THREAD

**Issue by colinDoherty** [mrjbq7/ta-lib#131]
Hello mrjbq7,

I am new to gutHub, so I will try and make this as painless as possible.

I have read threw your defs.h tickets and got around the problem that I was having with the pip install by copying the make install to usr/local/include.

The install is now throwing this error:
_________________________________________________________________________________
computer@YAY:~# pip install TA-Lib
Collecting TA-Lib
  Using cached TA-Lib-0.4.10.tar.gz
Building wheels for collected packages: TA-Lib
  Running setup.py bdist_wheel for TA-Lib ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/user/0/pip-build-n5v7Hx/TA-Lib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/user/0/tmpBJFeVjpip-wheel- --python-tag cp27:
  /tmp/user/0/pip-build-n5v7Hx/TA-Lib/setup.py:77: UserWarning: Cannot find ta-lib library, installation may fail.
    warnings.warn('Cannot find ta-lib library, installation may fail.')
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/talib
  copying talib/test_stream.py -> build/lib.linux-x86_64-2.7/talib
  copying talib/deprecated.py -> build/lib.linux-x86_64-2.7/talib
  copying talib/test_func.py -> build/lib.linux-x86_64-2.7/talib
  copying talib/__init__.py -> build/lib.linux-x86_64-2.7/talib
  copying talib/test_data.py -> build/lib.linux-x86_64-2.7/talib
  copying talib/test_abstract.py -> build/lib.linux-x86_64-2.7/talib
  running build_ext
  skipping 'talib/common.c' Cython extension (up-to-date)
  building 'talib.common' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/talib
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-XhtLrH/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include -I/usr/local/include -I/opt/include -I/opt/local/include -I/usr/include/python2.7 -c talib/common.c -o build/temp.linux-x86_64-2.7/talib/common.o
  x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-XhtLrH/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-XhtLrH/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/talib/common.o -L/usr/local/lib -L/usr/local/lib64 -L/opt/lib -L/opt/local/lib -lta_lib -o build/lib.linux-x86_64-2.7/talib/common.so
  /usr/bin/ld: cannot find -lta_lib
  collect2: error: ld returned 1 exit status
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for TA-Lib
  Running setup.py clean for TA-Lib
Failed to build TA-Lib
Installing collected packages: TA-Lib
  Running setup.py install for TA-Lib ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/user/0/pip-build-n5v7Hx/TA-Lib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/user/0/pip-ZhmMnA-record/install-record.txt --single-version-externally-managed --compile:
    /tmp/user/0/pip-build-n5v7Hx/TA-Lib/setup.py:77: UserWarning: Cannot find ta-lib library, installation may fail.
      warnings.warn('Cannot find ta-lib library, installation may fail.')
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/talib
    copying talib/test_stream.py -> build/lib.linux-x86_64-2.7/talib
    copying talib/deprecated.py -> build/lib.linux-x86_64-2.7/talib
    copying talib/test_func.py -> build/lib.linux-x86_64-2.7/talib
    copying talib/__init__.py -> build/lib.linux-x86_64-2.7/talib
    copying talib/test_data.py -> build/lib.linux-x86_64-2.7/talib
    copying talib/test_abstract.py -> build/lib.linux-x86_64-2.7/talib
    running build_ext
    skipping 'talib/common.c' Cython extension (up-to-date)
    building 'talib.common' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/talib
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-XhtLrH/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include -I/usr/local/include -I/opt/include -I/opt/local/include -I/usr/include/python2.7 -c talib/common.c -o build/temp.linux-x86_64-2.7/talib/common.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-XhtLrH/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-XhtLrH/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/talib/common.o -L/usr/local/lib -L/usr/local/lib64 -L/opt/lib -L/opt/local/lib -lta_lib -o build/lib.linux-x86_64-2.7/talib/common.so
    /usr/bin/ld: cannot find -lta_lib
    collect2: error: ld returned 1 exit status
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/user/0/pip-build-n5v7Hx/TA-Lib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/user/0/pip-ZhmMnA-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/user/0/pip-build-n5v7Hx/TA-Lib/

_______________________________________________________________________________

I thought I had install the ta-lib library from source:   untar cd ... sudo make install

But now it seems from this out put I have not. 

I placed the export path in the ./bashrc file as well. 

So, I must be missing something. I have the defs.h file does that means I have the ta-lib library?
And if so I changed the export path in bashrc so can it still not find it?

I start this issue because I cannot find anything on the ld error...

Please instruct.
Colin

**Comment by mrjbq7** [comment]
Which OS? 

What path did you install the `ta-lib` C library to? `/usr/local/include/ta-lib`?

It is possible that it can't find the header files because your `LD_LIBRARY_PATH` does not include `/usr/local/include`.  Depending on your OS, there are a couple ways to test it.

See, for example, the discussion on #6.

**Comment by colinDoherty** [comment]
Hey so I have a copy of it in /usr/local/include
       and I have a copy of it in /home

I have added export LD_LIBRARY_PATH=/usr/local/include:$LD_LIBRARY_PATH to my .bashrc file


Again my error is not like those before it is telling me that it cannot find the file in /usr/bin/ld

/usr/bin/ld: cannot find -lta_lib
    collect2: error: ld returned 1 exit status
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by colinDoherty** [comment]
OS: Kali

P.s. thanks for getting back to me.

Colin

**Comment by mrjbq7** [comment]
I meant `LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH`

Sorry not "include".

**Comment by colinDoherty** [comment]
computer@yay:~# LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH python
Python 2.7.13 (default, Dec 18 2016, 20:19:42) 
[GCC 6.2.1 20161215] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import talib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named talib
>>>

**Comment by colinDoherty** [comment]
I don't think it knows I downloded the ta-lib library but I am pretty sure I did

How can I check if I had downloaded it correctly?
I used the untar cd ... sudo make install method without error

**Comment by mrjbq7** [comment]
Okay, let me back up.

1. You need ``ta-lib`` C library, which you probably downloaded, untar'd, and make, make install'd.  Let's assume this ran correctly since you seem to have files in ``/usr/local/include/ta-lib`` and ``/usr/local/lib/libta_lib.so``, etc.

2. You need to build this ``ta-lib`` Python library so that it links against the C library.  This step appears to be failing (it finds the header files in ``/usr/local/include/ta-lib`` but not the library in ``/usr/local/lib``).

That second step probably fails because your linker (``ld``) isn't looking in ``/usr/local/lib``.  Some linux distributions set it up that way, maybe yours does?  There are different ways of adding that path to ``ld``, sometimes ``/etc/ld.so.conf`` and sometimes ``LD_LIBRARY_PATH`` environment variable.

What I assume you need to do to install it:

```bash
# make sure ld library path has /usr/local/lib
$ export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

# install ta-lib, it should not have errors
$ pip install ta-lib

# then test it to make sure it works
$ python -c "import talib; print(talib.__ta_version__)"
0.4.0 (Oct 20 2014 10:59:39)
```

**Comment by colinDoherty** [comment]
Hey I just double checked usr/local/lib and the files never hit that part of the fs?

should I copy them over there?

**Comment by colinDoherty** [comment]
Ok, so I copied the ta-lib folder to usr/local/lib added the export line to /etc/ld.so.conf and ran again with the same error.

/usr/bin/ld: cannot find -lta_lib
    collect2: error: ld returned 1 exit status
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

Why would the file not be downloaded to /usr/local/lib?
All the other dist packages are there...


Ok I have also read that the pip install might be throwing errors because of the cached failed compilations do you think this could be why? It's not reflected in error message but it starts by using cached tar file...

but I got no other ideas let me know what other info you need to help me steer through this.

Colin

**Comment by mrjbq7** [comment]
You don't see anything for this?

```
$ ls /usr/local/lib/libta_lib.*
```

You should see some variation of ``libta_lib.so``...

If you don't that probably means your ``./configure; make; sudo make install`` step didn't work for the ``ta-lib`` C library.

**Comment by mrjbq7** [comment]
What files are you copying?  You probably shouldn't try and copy manually, rather let the install step work as it expects.

**Comment by colinDoherty** [comment]
computer@yay:~# ls /usr/local/lib/libta_lib.*
ls: cannot access '/usr/local/lib/libta_lib.*': No such file or directory
computer@yay:~# ls /usr/local/lib/
python2.7  python3.5  ta-lib

**Comment by colinDoherty** [comment]
This is the ta-lib folder I have:

computer@yay:~/ta-lib# ls
aclocal.m4      config.status  install-sh   setup.py       ta-lib-config
autogen.sh      config.sub     libtool      src            ta-lib-config.in
autom4te.cache  configure      ltmain.sh    ta_abstract.h  ta-lib.dpkg
bin             configure.in   Makefile     ta_common.h    ta-lib.dpkg.in
CHANGELOG.TXT   depcomp        Makefile.am  ta_defs.h      ta-lib.spec
config.guess    HISTORY.TXT    Makefile.in  ta_func.h      ta-lib.spec.in
config.log      include        missing      ta_libc.h

**Comment by mrjbq7** [comment]
So basically ``ta-lib`` C library isn't installed properly.  It shouldn't go in ``/usr/local/lib/ta-lib`` thats probably because you copied something there that shouldn't be...

Try that step 1 again and make sure ``/usr/local/lib/libta_lib.*`` files are there.

``$ ./configure; make; sudo make install``

And if you want to install to ``/usr`` instead of ``/usr/local`` you can follow in the instructions in the README and provide ``/usr`` as the prefix used:

```
$ untar and cd
$ ./configure --prefix=/usr
$ make
$ sudo make install
```

**Comment by mrjbq7** [comment]
Maybe you forgot the ``make`` step?  Which is why it only copied header files to ``/usr/local/include`` and not the built library (which is an artifact of running ``make``)?

**Comment by colinDoherty** [comment]
computer@yay:~/Downloads/ta-lib# ./configure --prefix=/user
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for /usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognise dependent libraries... pass_all
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking for g77... no
checking for xlf... no
checking for f77... f77
checking whether we are using the GNU Fortran 77 compiler... yes
checking whether f77 accepts -g... yes
checking the maximum length of command line arguments... 32768
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC
checking if gcc PIC flag -fPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
configure: creating libtool
appending configuration tag "CXX" to libtool
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC
checking if g++ PIC flag -fPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
appending configuration tag "F77" to libtool
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for f77 option to produce PIC... -fPIC
checking if f77 PIC flag -fPIC works... yes
checking if f77 static flag -static works... yes
checking if f77 supports -c -o file.o... yes
checking whether the f77 linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for dlopen in -ldl... yes
checking for pthread_create in -lpthread... yes
checking for ANSI C header files... (cached) yes
checking float.h usability... yes
checking float.h presence... yes
checking for float.h... yes
checking for inttypes.h... (cached) yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for unistd.h... (cached) yes
checking wchar.h usability... yes
checking wchar.h presence... yes
checking for wchar.h... yes
checking wctype.h usability... yes
checking wctype.h presence... yes
checking for wctype.h... yes
checking for an ANSI C-conforming const... yes
checking for size_t... yes
checking whether struct tm is in sys/time.h or time.h... time.h
checking for working volatile... yes
checking for ptrdiff_t... yes
checking return type of signal handlers... void
checking for working strcoll... yes
checking for strftime... yes
checking for working strtod... yes
checking for vprintf... yes
checking for _doprnt... no
checking for floor... no
checking for isascii... yes
checking for localeconv... yes
checking for mblen... yes
checking for memmove... yes
checking for memset... yes
checking for modf... yes
checking for pow... no
checking for sqrt... no
checking for strcasecmp... yes
checking for strchr... yes
checking for strerror... yes
checking for strncasecmp... yes
checking for strrchr... yes
checking for strstr... yes
checking for strtol... yes
checking for strtoul... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating src/ta_abstract/Makefile
config.status: creating src/ta_common/Makefile
config.status: creating src/ta_func/Makefile
config.status: creating src/tools/Makefile
config.status: creating src/tools/gen_code/Makefile
config.status: creating src/tools/ta_regtest/Makefile
config.status: creating ta-lib-config
config.status: creating ta-lib.spec
config.status: creating ta-lib.dpkg
config.status: creating include/ta_config.h
config.status: include/ta_config.h is unchanged
config.status: executing depfiles commands

computer@yay:~/Downloads/ta-lib# make
Making all in src
make[1]: Entering directory '/root/Downloads/ta-lib/src'
Making all in ta_abstract
make[2]: Entering directory '/root/Downloads/ta-lib/src/ta_abstract'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/root/Downloads/ta-lib/src/ta_abstract'
Making all in ta_common
make[2]: Entering directory '/root/Downloads/ta-lib/src/ta_common'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/root/Downloads/ta-lib/src/ta_common'
Making all in ta_func
make[2]: Entering directory '/root/Downloads/ta-lib/src/ta_func'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/root/Downloads/ta-lib/src/ta_func'
make[2]: Entering directory '/root/Downloads/ta-lib/src'
make[2]: Nothing to be done for 'all-am'.
make[2]: Leaving directory '/root/Downloads/ta-lib/src'
make[1]: Leaving directory '/root/Downloads/ta-lib/src'
Making all in src/tools
make[1]: Entering directory '/root/Downloads/ta-lib/src/tools'
Making all in gen_code
make[2]: Entering directory '/root/Downloads/ta-lib/src/tools/gen_code'
make  gen_code
make[3]: Entering directory '/root/Downloads/ta-lib/src/tools/gen_code'
make[3]: 'gen_code' is up to date.
make[3]: Leaving directory '/root/Downloads/ta-lib/src/tools/gen_code'
cp gen_code ../../../bin
make[2]: Leaving directory '/root/Downloads/ta-lib/src/tools/gen_code'
Making all in ta_regtest
make[2]: Entering directory '/root/Downloads/ta-lib/src/tools/ta_regtest'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/root/Downloads/ta-lib/src/tools/ta_regtest'
make[2]: Entering directory '/root/Downloads/ta-lib/src/tools'
make[2]: Nothing to be done for 'all-am'.
make[2]: Leaving directory '/root/Downloads/ta-lib/src/tools'
make[1]: Leaving directory '/root/Downloads/ta-lib/src/tools'
make[1]: Entering directory '/root/Downloads/ta-lib'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/root/Downloads/ta-lib'

computer@yay:~/Downloads/ta-lib# sudo make install
Making install in src
make[1]: Entering directory '/root/Downloads/ta-lib/src'
Making install in ta_abstract
make[2]: Entering directory '/root/Downloads/ta-lib/src/ta_abstract'
make[3]: Entering directory '/root/Downloads/ta-lib/src/ta_abstract'
make[3]: Nothing to be done for 'install-exec-am'.
test -z "/user/include/ta-lib/" || /bin/mkdir -p "/user/include/ta-lib/"
 /usr/bin/install -c -m 644 '../../include/ta_defs.h' '/user/include/ta-lib//ta_defs.h'
 /usr/bin/install -c -m 644 '../../include/ta_libc.h' '/user/include/ta-lib//ta_libc.h'
 /usr/bin/install -c -m 644 '../../include/ta_abstract.h' '/user/include/ta-lib//ta_abstract.h'
make[3]: Leaving directory '/root/Downloads/ta-lib/src/ta_abstract'
make[2]: Leaving directory '/root/Downloads/ta-lib/src/ta_abstract'
Making install in ta_common
make[2]: Entering directory '/root/Downloads/ta-lib/src/ta_common'
make[3]: Entering directory '/root/Downloads/ta-lib/src/ta_common'
make[3]: Nothing to be done for 'install-exec-am'.
test -z "/user/include/ta-lib/" || /bin/mkdir -p "/user/include/ta-lib/"
 /usr/bin/install -c -m 644 '../../include/ta_defs.h' '/user/include/ta-lib//ta_defs.h'
 /usr/bin/install -c -m 644 '../../include/ta_libc.h' '/user/include/ta-lib//ta_libc.h'
 /usr/bin/install -c -m 644 '../../include/ta_common.h' '/user/include/ta-lib//ta_common.h'
make[3]: Leaving directory '/root/Downloads/ta-lib/src/ta_common'
make[2]: Leaving directory '/root/Downloads/ta-lib/src/ta_common'
Making install in ta_func
make[2]: Entering directory '/root/Downloads/ta-lib/src/ta_func'
make[3]: Entering directory '/root/Downloads/ta-lib/src/ta_func'
make[3]: Nothing to be done for 'install-exec-am'.
test -z "/user/include/ta-lib/" || /bin/mkdir -p "/user/include/ta-lib/"
 /usr/bin/install -c -m 644 '../../include/ta_defs.h' '/user/include/ta-lib//ta_defs.h'
 /usr/bin/install -c -m 644 '../../include/ta_libc.h' '/user/include/ta-lib//ta_libc.h'
 /usr/bin/install -c -m 644 '../../include/ta_func.h' '/user/include/ta-lib//ta_func.h'
make[3]: Leaving directory '/root/Downloads/ta-lib/src/ta_func'
make[2]: Leaving directory '/root/Downloads/ta-lib/src/ta_func'
make[2]: Entering directory '/root/Downloads/ta-lib/src'
make[3]: Entering directory '/root/Downloads/ta-lib/src'
test -z "/user/lib" || /bin/mkdir -p "/user/lib"
 /bin/bash ../libtool --mode=install /usr/bin/install -c  'libta_lib.la' '/user/lib/libta_lib.la'
/usr/bin/install -c .libs/libta_lib.so.0.0.0 /user/lib/libta_lib.so.0.0.0
(cd /user/lib && { ln -s -f libta_lib.so.0.0.0 libta_lib.so.0 || { rm -f libta_lib.so.0 && ln -s libta_lib.so.0.0.0 libta_lib.so.0; }; })
(cd /user/lib && { ln -s -f libta_lib.so.0.0.0 libta_lib.so || { rm -f libta_lib.so && ln -s libta_lib.so.0.0.0 libta_lib.so; }; })
/usr/bin/install -c .libs/libta_lib.lai /user/lib/libta_lib.la
/usr/bin/install -c .libs/libta_lib.a /user/lib/libta_lib.a
chmod 644 /user/lib/libta_lib.a
ranlib /user/lib/libta_lib.a
PATH="$PATH:/sbin" ldconfig -n /user/lib
----------------------------------------------------------------------
Libraries have been installed in:
   /user/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,--rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/root/Downloads/ta-lib/src'
make[2]: Leaving directory '/root/Downloads/ta-lib/src'
make[1]: Leaving directory '/root/Downloads/ta-lib/src'
Making install in src/tools
make[1]: Entering directory '/root/Downloads/ta-lib/src/tools'
Making install in gen_code
make[2]: Entering directory '/root/Downloads/ta-lib/src/tools/gen_code'
make  gen_code
make[3]: Entering directory '/root/Downloads/ta-lib/src/tools/gen_code'
make[3]: 'gen_code' is up to date.
make[3]: Leaving directory '/root/Downloads/ta-lib/src/tools/gen_code'
cp gen_code ../../../bin
make[3]: Entering directory '/root/Downloads/ta-lib/src/tools/gen_code'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/root/Downloads/ta-lib/src/tools/gen_code'
make[2]: Leaving directory '/root/Downloads/ta-lib/src/tools/gen_code'
Making install in ta_regtest
make[2]: Entering directory '/root/Downloads/ta-lib/src/tools/ta_regtest'
make[3]: Entering directory '/root/Downloads/ta-lib/src/tools/ta_regtest'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/root/Downloads/ta-lib/src/tools/ta_regtest'
make[2]: Leaving directory '/root/Downloads/ta-lib/src/tools/ta_regtest'
make[2]: Entering directory '/root/Downloads/ta-lib/src/tools'
make[3]: Entering directory '/root/Downloads/ta-lib/src/tools'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/root/Downloads/ta-lib/src/tools'
make[2]: Leaving directory '/root/Downloads/ta-lib/src/tools'
make[1]: Leaving directory '/root/Downloads/ta-lib/src/tools'
make[1]: Entering directory '/root/Downloads/ta-lib'
make[2]: Entering directory '/root/Downloads/ta-lib'
test -z "/user/bin" || /bin/mkdir -p "/user/bin"
 /usr/bin/install -c 'ta-lib-config' '/user/bin/ta-lib-config'
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/root/Downloads/ta-lib'
make[1]: Leaving directory '/root/Downloads/ta-lib'

**Comment by colinDoherty** [comment]
I found in libta-lib in /usr/local/include/ta-lib/src

**Comment by mrjbq7** [comment]
Why did you make the prefix `/user`?  It should be `/usr`.

**Comment by colinDoherty** [comment]
whoops that could be it hold on i'm gonna rm the folders I copied and run the make again

Sorry about taking so much of your time with this it is a big help and much appreciated.

**Comment by colinDoherty** [comment]
!!!SWEET!!!

root@neo:~/Downloads/ta-lib# pip install TA-Lib
Collecting TA-Lib
  Using cached TA-Lib-0.4.10.tar.gz
Building wheels for collected packages: TA-Lib
  Running setup.py bdist_wheel for TA-Lib ... done
  Stored in directory: /root/.cache/pip/wheels/60/8c/a4/d8dfd05c0dd588eaa171aa55d5cfe300e5fb8006e9147398d2
Successfully built TA-Lib
Installing collected packages: TA-Lib
Successfully installed TA-Lib-0.4.10


You're awesome thank you very much running python steup.py install now

**Comment by mrjbq7** [comment]
Great, if you have any more problems let me know. I like making sure people can use this software. 

We have an open pull request to try and bundle the C library but it's not quite ready.

**Comment by colinDoherty** [comment]
Awesome! I am going to start trying to incorporate it in my code. Thank you!
