### ISSUE TITLE
Python 3.5.2  TA-Lib 0.4.10 install error

### ISSUE THREAD

**Issue by coco101000000000** [mrjbq7/ta-lib#133]
talib/func.c: In function '__pyx_pf_5talib_4func_308VAR':
    talib/func.c:114239:15: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
         __pyx_t_2 = PyArray_GETCONTIGUOUS(__pyx_v_real); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 11021, __pyx_L1_error)
                   ^
    talib/func.c: In function '__pyx_pf_5talib_4func_310WCLPRICE':
    talib/func.c:114676:15: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
         __pyx_t_2 = PyArray_GETCONTIGUOUS(__pyx_v_high); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 11072, __pyx_L1_error)
                   ^
    talib/func.c:114781:15: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
         __pyx_t_2 = PyArray_GETCONTIGUOUS(__pyx_v_low); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 11079, __pyx_L1_error)
                   ^
    talib/func.c:114886:15: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
         __pyx_t_2 = PyArray_GETCONTIGUOUS(__pyx_v_close); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 11086, __pyx_L1_error)
                   ^
    talib/func.c: In function '__pyx_pf_5talib_4func_312WILLR':
    talib/func.c:115478:15: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
         __pyx_t_2 = PyArray_GETCONTIGUOUS(__pyx_v_high); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 11149, __pyx_L1_error)
                   ^
    talib/func.c:115583:15: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
         __pyx_t_2 = PyArray_GETCONTIGUOUS(__pyx_v_low); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 11156, __pyx_L1_error)
                   ^
    talib/func.c:115688:15: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
         __pyx_t_2 = PyArray_GETCONTIGUOUS(__pyx_v_close); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 11163, __pyx_L1_error)
                   ^
    talib/func.c: In function '__pyx_pf_5talib_4func_314WMA':
    talib/func.c:116256:15: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
         __pyx_t_2 = PyArray_GETCONTIGUOUS(__pyx_v_real); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 11224, __pyx_L1_error)
                   ^
    x86_64-linux-gnu-gcc: internal compiler error: Killed (program cc1)
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 4
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-e0bjn46w/TA-Lib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-_fsw_9au-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-e0bjn46w/TA-Lib/

**Comment by coco101000000000** [comment]
ubuntu 16.04 x64

**Comment by mrjbq7** [comment]
What version of ``gcc`` are you using?

This seems odd, but maybe my recent upgrade to cython 0.25.2 fixed it?

Can you try latest master?

**Comment by coco101000000000** [comment]
```
tey@localhost:/opt$ python3 -m pip freeze
cssselect==1.0.1
cycler==0.10.0
Cython==0.25.2
Django==1.10.5
django-mysql==1.1.0
tey@localhost:/opt$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

```

It still error .

**Comment by mrjbq7** [comment]
A couple things you can try:

1) Download latest git master and try ``python setup.py install``.

2) If that doesn't work, maybe try deleting ``talib/_ta_lib.c`` and then re-running ``python setup.py install``.

3) If that doesn't work, well I'm not sure what is triggering an ``internal compiler error`` without being able to reproduce and investigate.

**Comment by coco101000000000** [comment]
It still get some errors.

**Comment by mrjbq7** [comment]
Hmm, I have a fresh Ubuntu 16.04 64-bit VM and had no problems installing it.  And our Travis build bots do not have errors also.    That is the same ``gcc`` version that I've been using.

**Comment by mrjbq7** [comment]
Also tried a fresh Ubuntu 16.10 32-bit VM and it worked fine...

**Comment by coco101000000000** [comment]
thanks

**Comment by mrjbq7** [comment]
Sorry I'm not more helpful. I really would like to help resolve your problem. Especially if there is some potential bug here.

**Comment by coco101000000000** [comment]
Thanks once more. I'll report you when there are other bug here.

**Comment by paulcollinsiii** [comment]
Resurrecting an old thread, I ran into this exact issue as well. The root cause was I was trying to build this inside a docker image running inside a vagrant box that had limited ram. It was the Out of Memory killer coming through and killing the GCC process. Upping the ram to the Vagrant box fixed this.

**Comment by darekm101** [comment]
RAM was indeed the problem.   I was on a DigitalOcean Droplet with 1GB or RAM and kept running into the repeated error below, I bumped up the RAM to 2GB and error is gone.  

talib/_ta_lib.c:208671:15: warning: assignment from incompatible pointer type [enabled by default]
