### ISSUE TITLE
Why talib.SMA can't run & what is Abstract API ?

### ISSUE THREAD

**Issue by 631068264** [mrjbq7/ta-lib#138]
I use MacOS and python2.7. This is my first to use ta-lib

```python
import pandas as pd
import talib.abstract as ta

db = util.get_db("kline")

df = pd.read_sql(QS(T.okfuture_btc_usd_60_quarter).limit(0, 10).select("close"), db)
print df
print ta.SMA(df, timeperiod=5, price="close")
```
**result success** 
```
    close
0  230.12
1  230.13
2  230.93
3  231.23
4  231.75
5  231.89
6  231.51
7  231.18
8  230.75
9  231.02
0        NaN
1        NaN
2        NaN
3        NaN
4    230.832
5    231.186
6    231.462
7    231.512
8    231.416
9    231.270
dtype: float64
```

But when I use this ,I got a strange error, and [your document](http://mrjbq7.github.io/ta-lib/func_groups/overlap_studies.html) is too simple for me . I even don't know **which type** params should I give.

```python
import pandas as pd
import talib as ta

db = util.get_db("kline")

df = pd.read_sql(QS(T.okfuture_btc_usd_60_quarter).limit(0, 10).select("close"), db)
print df
print ta.SMA(df.values, timeperiod=5)
```
The error result
```
Traceback (most recent call last):
    close
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1580, in <module>
0  230.12
    globals = debugger.run(setup['file'], None, None, is_module)
1  230.13
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 964, in run
2  230.93
    pydev_imports.execfile(file, globals, locals)  # execute the script
3  231.23
  File "/Users/wyx/bitcoin_workspace/fibo-strategy/app.py", line 23, in <module>
    print ta.SMA(df.values, timeperiod=5)
  File "talib/func.pyx", line 9934, in talib.func.SMA (talib/func.c:104286)
Exception: real has wrong dimensions
4  231.75
5  231.89
6  231.51
7  231.18
8  230.75
9  231.02
```

**Comment by mrjbq7** [comment]
In the cython code for ``SMA`` (and others), we assert that the ``df.values.ndim == 1``.  How many dimensions does it have?

**Comment by pcawthron** [comment]
`import pandas as pd
import talib as ta

df = pd.DataFrame(pd.Series([230.12, 230.13, 230.93, 231.23, 231.75, 231.89, 231.51, 231.18, 230.75, 231.2]), columns=['close'])

ta.SMA(df.close.values, timeperiod=5)`

works for me on Windows 8.1/Python 2.7.11 i.e.

`import pandas as pd
import talib as ta

df = pd.DataFrame(pd.Series([230.12, 230.13, 230.93, 231.23, 231.75, 231.89, 231.51, 231.18, 230.75, 231.2]), columns=['close'])

ta.SMA(df.close.values, timeperiod=5)

Out[52]: 
array([     nan,      nan,      nan,      nan,  230.832,  231.186,
        231.462,  231.512,  231.416,  231.306])

In [53]:`
