### ISSUE TITLE
RSI returning NaNs for data with partial NaNs

### ISSUE THREAD

**Issue by Panoplos** [mrjbq7/ta-lib#14]
Running the following code:

``` python
In [1]: vals = ((np.random.random(2000) * 10) + 150)

In [2]: vals[:500] = np.empty(500)

In [3]: talib.RSI(vals)
```

Results in:

``` python
Out[3]: array([ nan,  nan,  nan, ...,  nan,  nan,  nan])
```

Or all the values being `nan`.

This is not a contrived example, as I am working on data sets of stock prices that are aligned via a time series wherein some of the stocks do not have values for certain periods of data due to them not existing until later in the series.

I really like the idea of using ta-lib in my project, but this makes it unusable without hacking apart the data frames (whereas other toolkits, like QSTK work as is).

Look forward to your feedback. :-)

**Comment by Yevgnen** [comment]
Hi, 

I have a question about the following snippet

```
time = np.array([10,11,12,13,14,15,16])

col1 = np.array([5,6,5,8,7,6,12], dtype=float)
col2 = np.array([1,np.nan,3,2,np.nan,5,4], dtype=float)

nans1 = np.isnan(col1)
nans2 = np.isnan(col2)

rsi1 = pandas.Series(talib.RSI(col1[~nans1], timeperiod=2), index=time[~nans1])
rsi2 = pandas.Series(talib.RSI(col2[~nans2], timeperiod=2), index=time[~nans2])

df = pandas.DataFrame(index=time)
df['rsi1'] = rsi1
df['rsi2'] = rsi2
```
which gives result
```
    rsi1  rsi2
10   NaN   NaN
11   5.5   NaN
12   5.5   2.0
13   6.5   2.5
14   7.5   NaN
15   6.5   3.5
16   9.0   4.5
```
Is that mean there's no way to get 
```
    rsi1  rsi2
10   NaN   NaN
11   5.5   NaN
12   5.5   NaN
13   6.5   2.5
14   7.5   NaN
15   6.5   NaN
16   9.0   4.5
```
which can be achieve by 
`pd.DataFrame(np.asarray([col1, col2]).T, index=time).rolling(2).mean()`
using `talib`? Thank you.

**Comment by Rainfall2013** [comment]
> Hi,
> 
> I have a question about the following snippet
> 
> ```
> time = np.array([10,11,12,13,14,15,16])
> 
> col1 = np.array([5,6,5,8,7,6,12], dtype=float)
> col2 = np.array([1,np.nan,3,2,np.nan,5,4], dtype=float)
> 
> nans1 = np.isnan(col1)
> nans2 = np.isnan(col2)
> 
> rsi1 = pandas.Series(talib.SMA(col1[~nans1], timeperiod=2), index=time[~nans1])
> rsi2 = pandas.Series(talib.SMA(col2[~nans2], timeperiod=2), index=time[~nans2])
> 
> df = pandas.DataFrame(index=time)
> df['rsi1'] = rsi1
> df['rsi2'] = rsi2
> ```
> 
> which gives result
> 
> ```
>     rsi1  rsi2
> 10   NaN   NaN
> 11   5.5   NaN
> 12   5.5   2.0
> 13   6.5   2.5
> 14   7.5   NaN
> 15   6.5   3.5
> 16   9.0   4.5
> ```
> 
> Is that mean there's no way to get
> 
> ```
>     rsi1  rsi2
> 10   NaN   NaN
> 11   5.5   NaN
> 12   5.5   NaN
> 13   6.5   2.5
> 14   7.5   NaN
> 15   6.5   NaN
> 16   9.0   4.5
> ```
> 
> which can be achieve by
> `pd.DataFrame(np.asarray([col1, col2]).T, index=time).rolling(2).mean()`
> using `talib`? Thank you.
> 
> Updated: I've changed the `RSI` to `SMA`.

I‘m just wondering whether you get a solution to your problem?

**Comment by martinzlocha** [comment]
For anyone else reading this in the future. I had a similar problem where I have a pandas Dataframe with multiple columns, each is a different stock price and in some cases there are NaNs inbetween two subarrays with prices. 

I wrote the following function which will apply another function to all non-NaN subarrays:

```
def apply_to_sub_arrays(arr, func):
    sparse_ts = arr.astype(pd.SparseDtype('float'))
    block_locs = zip(
        sparse_ts.values.sp_index.to_block_index().blocs,
        sparse_ts.values.sp_index.to_block_index().blengths,
    )

    results = arr.copy()
    results[:] = np.nan

    for (start, length) in block_locs:
        if arr.iloc[start: start + length].isna().all():
            continue

        results.iloc[start: start + length] = func(arr.iloc[start: start + length])

    return results
```

To use it I do (where prices is my Dataframe):

```
prices.apply(lambda price: apply_to_sub_arrays(price, lambda arr: talib.RSI(arr, timeperiod=duration)), axis=0)
```
