### ISSUE TITLE
SAREXT returning negative values

### ISSUE THREAD

**Issue by jackwluo** [mrjbq7/ta-lib#141]
@mrjbq7

When building my charting library using Talib I noticed during testing that the SAREXT function returns negative values on the upper points. Solution was easy to fix for me, but I'd be more than happy to submit a PR if you want to the ta-lib library

**Comment by jackwluo** [comment]
https://plot.ly/~jackluo/3278.embed

See bug above (solution could be simply running an abs() function over entire ndarray)

**Comment by jackwluo** [comment]
Bump

**Comment by mrjbq7** [comment]
That link doesn't seem to work?

Also, I'd prefer not to "fix" the underlying TA-Lib C library.  Right now, this is just a light wrapper so any logic errors should probably be fixed upstream in the C library...

That's complicated by the fact that it doesn't seem to be getting new releases these days, so maybe if we needed to we could work around it, but I'd rather not maintain a "fixes/patches" list.

**Comment by craxyz** [comment]
**It's not a bug**, please check out TA-Lib C library source code, it's well commented at line 372 of ta_SAREXT.c:
>/\* This function is the same as TA_SAR, except that the caller has
>  \* greater control on the SAR dynamic and initial state.
>  \*
>  \* **In additon**, the TA_SAREXT returns **negative** values when the position
>  \* is short. This allow to distinguish when the SAR do actually reverse.
>  \*/

**Comment by pha377** [comment]
> **It's not a bug**, please check out TA-Lib C library source code, it's well commented at line 372 of ta_SAREXT.c:
> 
> > /* This function is the same as TA_SAR, except that the caller has
> > * greater control on the SAR dynamic and initial state.
> > *
> > * **In additon**, the TA_SAREXT returns **negative** values when the position
> > * is short. This allow to distinguish when the SAR do actually reverse.
> > */

So basically if TA_SAREXT is the same as TA_SAR, there should be a way to make TA_SAREXT behave as TA_SAR
But, it's not possible because "TA_SAREXT returns **negative** values when the position ...."

So, TA_SAREXT is broken

**Comment by mrjbq7** [comment]
It seems like it's intentional, why do you think it's broken?
