### ISSUE TITLE
Patterns outputs [0,0,100,-100,200,-200]

### ISSUE THREAD

**Issue by MattinAhmed** [mrjbq7/ta-lib#145]
Hi 
Could someone please help me understand what does 200 and -200 represent.
Is it a outliner? or should i consider them as 100's. please advice
Thanks  Much!!

**Comment by mrjbq7** [comment]
Well, without knowing which indicator you're talking about it's hard to say.  But 200 and -200 are valid outputs for several of the candlestick pattern indicators.  For example, you can look at the C code for CDLHIKKAKE:

https://sourceforge.net/p/ta-lib/code/HEAD/tree/trunk/ta-lib/c/src/ta_func/ta_CDLHIKKAKE.c#l239

And see the comment seems to indicate a 200 or -200 is a "confirmation" signal.  I don't claim to know what it means for all indicators, but if you want you can look at the C code for the one you're curious about or ask me and I can try to help.

**Comment by MattinAhmed** [comment]
Thank for the reply.
My bad!! i should have given more details.
Well, I am working on a task to identify the candle stick patterns on the stock data having attributes _open high, low, close_.
I am using TA-Lib to identify the candle stick patterns.
the built-in functions in TA-Lib(for example: talib.CDLDOJI(open, high, low, close), talib.CDLHIKKAKE(open_new, high_new, low_new, close_new) and so on), outputs 0 if not patterns identified, 100 if pattern detected(bullish) and -100 if patterns detected as bearish. 
Apart from this, I am getting +200 and -200 as output for "Hikkake" and "HikkakeMod"
 pattern. 
I didn't quite understand what does +200 and -200 correspond to.
Thanks

**Comment by mrjbq7** [comment]
I think CDLDOJI can only be ``0`` or ``100``... 

https://sourceforge.net/p/ta-lib/code/HEAD/tree/trunk/ta-lib/c/src/ta_func/ta_CDLDOJI.c#l349

Are you seeing something else?

**Comment by MattinAhmed** [comment]
Oh!!No you are right..
for my current dataset,
I see the -200 and +200 
for below function
talib.CDLHIKKAKE(open_new, high_new, low_new, close_new)
And
200
for below function
talib.CDLHIKKAKEMOD(open_new, high_new, low_new, close_new)

rest of the Ta-lib function outputs are[0,100,-100]

**Comment by colinzuo** [comment]
there is comment in ta_CDLHIKKAKE.c as below:

   /* Proceed with the calculation for the requested range.
    * Must have:
    * - first and second candle: inside bar (2nd has lower high and higher low than 1st)
    * - third candle: lower high and lower low than 2nd (higher high and higher low than 2nd)
    * outInteger[hikkakebar] is positive (1 to 100) or negative (-1 to -100) meaning bullish or bearish hikkake
    * Confirmation could come in the next 3 days with:
    * - a day that closes higher than the high (lower than the low) of the 2nd candle
    * outInteger[confirmationbar] is equal to 100 + the bullish hikkake result or -100 - the bearish hikkake result
    * Note: if confirmation and a new hikkake come at the same bar, only the new hikkake is reported (the new hikkake
    * overwrites the confirmation of the old hikkake)
    */

**Comment by r-matsuzaka** [comment]
@mrjbq7 

I think help is wrong.

```
> help(CDLHIKKAKE)

Help on function CDLHIKKAKE in module talib._ta_lib:

CDLHIKKAKE(...)
    CDLHIKKAKE(open, high, low, close)
    
    Hikkake Pattern (Pattern Recognition)
    
    Inputs:
        prices: ['open', 'high', 'low', 'close']
    Outputs:
        integer (values are -100, 0 or 100)

```

**Comment by mrjbq7** [comment]
Yep, from reading the ``ta_CDLHIKKAKE.c`` source code, it looks like it produces -200 and 200 for confirmations.

This docstring is generated here:

https://github.com/mrjbq7/ta-lib/blob/master/talib/_abstract.pxi#L728

**Comment by r-matsuzaka** [comment]
Ok, then I will make a PR.
