### ISSUE TITLE
TA-Lib for .netcore

### ISSUE THREAD

**Issue by seb999** [mrjbq7/ta-lib#146]
Dear All,

Sorry to write you here. Is there any version of TA-Lib for .netcore users ?

Bets regards
Sebastien

**Comment by mrjbq7** [comment]
Hi Sebastien,

When you say .netcore are you talking about Windows .NET stuff?

**Comment by a904guy** [comment]
Yes, that is what he is talking about. They renamed .NET to .NETcore.

You're going to need to use ta-lib as a C or C++ lib inside your C# code.

C++ and C# are very similar, you could refactor the C++ pieces out or you could do this:

https://softwareengineering.stackexchange.com/questions/135083/is-it-possible-to-use-c-with-the-net-framework

**Comment by seb999** [comment]
Hello everybody,

Thanks for your email. Yes Microsoft since 2 years decided to create a new
open source .net framework.cross platform compatible.
You would find more information about it here:
https://www.microsoft.com/net/core#windowsvs2017

I will try to call the C++ library inside my project. Until now I didn't
manage.

Best regards
Sebastien


On 21 June 2017 at 15:33, Andy Hawkins — (̖̣͕̠̬̭̞̪̐̅ỉ̭̣͈̪̠ͮs̳̳̦̞̰̜̞̳͑͌͋ͪ̃̍
̩̘́͑ͨ̈́̎̋ͮ͊̀ñ͔̣͓̬̈ͮͦ́ͫ͐͛ͅͅo̩̦̳̠̙̗̯̺̐͆̽t̜̥̻̙̟̼̜͂ͩ͋̅̈́ ̠̦̹̟͕͕̱͉͒͋̅́͐ā̟̻̱ͦ̒̍͋
̗̞͚ͨͩ͊͂̉ͅh͔̼͚̩͚̪̝̝ͣa̫̫̒̓ͬc̦̲̳͍̹̃ͥͯk̲͕̗̖̤̙̜͍̊e̫͎̟̼̺̫̿r͙̰̊̑̿̅ͯͅ)̪̖͇̝̮̪͖̦͆̇ͧ͑̚

**Comment by mrjbq7** [comment]
Hi Sebastien,

Sorry we couldn't help more.  This is technically a project for just a Python wrapper of the TA-Lib C library, so perhaps there are other resources out there for TA-Lib on .NET specifically.

Best,
