### ISSUE TITLE
Cannot open include file: 'ta-libc.h'

### ISSUE THREAD

**Issue by LoudMurmur** [mrjbq7/ta-lib#148]
Hi,

This is for a windows 7 machine with python 2.7 32bits installed

I extracted the files from ta-lib-0.4.0-msvc.zip in c:\ta-lib as said then I checkouted the repo and ran `python setup.py install`

the install then fail saying : 
`python setup.py install
running install
running build
running build_py
running build_ext
building 'talib._ta_lib' extension
C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.exe /c /nologo /Ox
/MD /W3 /GS- /DNDEBUG -IC:\Python27\lib\site-packages\numpy\core\include -Ic:\ta
-lib\c\include -IC:\Python27\include -IC:\Python27\PC /Tctalib/_ta_lib.c /Fobuil
d\temp.win32-2.7\Release\talib/_ta_lib.obj
_ta_lib.c
talib/_ta_lib.c(433) : fatal error C1083: Cannot open include file: 'ta-libc.h':
 No such file or directory
error: command '"C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.ex
e"' failed with exit status 2`

However I can find this file in C:\ta-lib\c\include

What can I do?
Thanks.

**Comment by a904guy** [comment]
Can you confirm you've got both of these folders?

https://github.com/mrjbq7/ta-lib/blob/master/setup.py#L57-L58

**Comment by LoudMurmur** [comment]
yes c:\ta-lib\c\include and c:\ta-lib\c\lib are present and filled with files

**Comment by a904guy** [comment]
What about doing `pip install TA-Lib` ?

**Comment by LoudMurmur** [comment]
oh, I forgot about pip, well, it worked using pip, I can use talib in my python now. Thanks

**Comment by a904guy** [comment]
:+1: Cheers.

**Comment by a904guy** [comment]
@mrjbq7 Can close this out. Resolved.
