### ISSUE TITLE
StochRSI gives nonsensical values

### ISSUE THREAD

**Issue by pieroliviermarquis** [mrjbq7/ta-lib#149]
There is a problem with the values. I don't know if this is the issue but there is no moving average on the fastK. So, you get values that shift from 100 to 0 and so on. 

 fastk, fastd = talib.STOCHRSI(data, timeperiod=14, fastk_period=3, fastd_period=3, fastd_matype=0)

![image](https://user-images.githubusercontent.com/10508286/27706411-7b49ac5a-5cdf-11e7-8685-27132c15f8b0.png)

**Comment by mrjbq7** [comment]
If you look at the [code for STOCHRSI](https://sourceforge.net/p/ta-lib/code/HEAD/tree/trunk/ta-lib/c/src/ta_func/ta_STOCHRSI.c#l494), it [calls out to STOCHF](https://sourceforge.net/p/ta-lib/code/HEAD/tree/trunk/ta-lib/c/src/ta_func/ta_STOCHF.c) which does not seem to take a "MA_Type" for ``fastk``...

That may not be what you want, but is apparently how it's implemented.

You could always build it yourself, something like this (untested code):

```python
import pandas as pd

def EMA(c, n):
    new_weight = 2./(n+1)
    old_weight = (n-1)/(n+1.)
    out = new_weight * c
    out[0] = c[0]
    for i in range(1, len(c)):
        out[i] += old_weight * out[i-1]
    return out

def STOCHF(v, fastk_period, slowk_period, slowd_period):
    lows = pd.rolling_min(v, fastk_period, min_periods=1)
    highs = pd.rolling_max(v, fastk_period, min_periods=1)
    fast_k = np.nan_to_num(100 * (v - lows) / (highs - lows))
    slow_k = EMA(fast_k, slowk_period)
    slow_d = EMA(slow_k, slowd_period)
    return fast_k, slow_k, slow_d

def STOCHRSI(c, period0, period1, period2):
    rsi = RSI(c, period0)
    return STOCHF(rsi, period0, period1, period2)
```

That doesn't handle the lookback properly and might be totally buggy in obvious ways, but you can always build it yourself, is what I guess I'm saying...

**Comment by sunnyville01** [comment]
I have a quick question about this: Can we just ignore the values that are returned as 0, or are all the values that are returned wrong? Because in my application I don't care about the values that go below 20, I'm only trying to catch when it goes above 20 and then 80.

**Comment by sullyfischer** [comment]
@sunnyville01 no, the entire values are incorrect.

**Comment by ShayanFiroozi** [comment]
> @sunnyville01 no, the entire values are incorrect.

Give the TA-Lib more earlier values !
I mean if your RSI length is 14 give it at least 100 earlier price list , it will be more accurate as tradingview ;)

**Comment by Elyasnz** [comment]
if a Python implementation of STOCHRSI is needed this [comment](https://github.com/TA-Lib/ta-lib-python/issues/594#issuecomment-1560640283) is useful
