### ISSUE TITLE
UnsatisfiableError: The following specifications were found to be in conflict:

### ISSUE THREAD

**Issue by dukeyc138** [mrjbq7/ta-lib#155]
UnsatisfiableError: The following specifications were found to be in conflict:
  - matplotlib
  - navigator-updater
  - ta-lib 0.4.9*

could anyone help me with this? how could I solve this problem

**Comment by mrjbq7** [comment]
What is that error being produced by?

**Comment by mrjbq7** [comment]
Closing all installation issues, if someone has a specific problem please open a new one.
