### ISSUE TITLE
About the correct order in the data series

### ISSUE THREAD

**Issue by ZzAntares** [mrjbq7/ta-lib#159]
Hi, I have a simple question, what is the order of the data series I need to provide? by default I have "newer first" in the array, should I reverse this array prior passing it to an indicator or is this the correct order?

Another thing to mention is that in the README says it supports `pandas.Series` as arguments, but computing a simple `SMA` with a `Series` gives:

```
TypeError: Argument 'real' has incorrect type (expected numpy.ndarray, got Series)
```

Thanks for the clarification.

**Comment by mrjbq7** [comment]
A couple comments:

1. The old pandas.Series subclassed numpy.Array so was natively supported. 

2. The so called abstract API supports pandas. 

3. The function API has a pending pull request to add pandas back by wrapping the function (see #154)

4. The ta-lib functions want dates in old-to-new order, so you probbly need to reverse it. 

Any comments you have regarding the above are helpful!

**Comment by ZzAntares** [comment]
Thanks a lot @mrjbq7, it's all clear now. I'll keep an eye on #154 would be interesting to see that in action although of course it wouldn't be as fast as directly dealing with numpy's arrays, though is nice to have the option.

Thanks again!
