### ISSUE TITLE
RSI value is different then the RSI value on the exchange

### ISSUE THREAD

**Issue by cryptonaut1357** [mrjbq7/ta-lib#160]
Hello,
has anyone an idea why the value of the RSI could significantly deviate?
(doublechecked with other exchanges - on every exchange are similar RSI values, just the calculation from talib is way off)

BollingerBands or ATR, for example, return the same values...

regards

**Comment by mrjbq7** [comment]
Well, without any information about what the prices were that you are calculating RSI for or any ability to reproduce a test case, my best guess is either:

1. Different time period.

2. Different prices. 

I doubt the RSI calculation is done differently

**Comment by cryptonaut1357** [comment]
your right, sorry. 
This is the code and output:

```
coin_pair = 'BTC-XMR'
period = 15
unit = "thirtyMin"

def getClosingPrices(coin_pair, period, unit):

    historical_data = my_bittrex.getHistoricalData(coin_pair, period, unit)
    closing_prices = []
    for i in historical_data:
        closing_prices.append(i['C'])
    return closing_prices


def getOpeningPrices(coin_pair, period, unit):
   
def getHighPrices(coin_pair, period, unit):

def getLowPrices(coin_pair, period, unit):

def getVolume(coin_pair, period, unit):

inputs = {
    "open": np.array(getOpeningPrices(coin_pair, period, unit)),
    "close": np.array(getClosingPrices(coin_pair, period, unit)),
    "high": np.array(getHighPrices(coin_pair, period, unit)),
    "low": np.array(getLowPrices(coin_pair, period, unit)),
    "volume": np.array(getVolume(coin_pair, period, unit))
}

print "open: %s" %inputs["open"][-1]
print "close: %s" %inputs["close"][-1]
print "high: %s" %inputs["high"][-1]
print "low: %s" %inputs["low"][-1]

rsi = talib.RSI(inputs["close"], timeperiod=14)
print "RSI: %s" %rsi[-1]
```
Output:

open: 0.01600987
close: 0.01588904
high: 0.01600988
low: 0.01588904
RSI: 60.0524150618

Screenshot Exchange:
https://www.dropbox.com/s/pmge2r050vs3cuh/trex1.PNG?dl=0

**Comment by fabrom** [comment]
to my side, i noticed a very large difference from market with STOCHRSI function

**Comment by cryptonaut1357** [comment]
@fabrom With Cryptocurrency Data oder Stocks/FX?

**Comment by mrjbq7** [comment]
Hard to know, the OHLC looks a little different in the screenshot versus your output code.

Is it possible the data is backwards?  TA-Lib expects oldest to newest?

Is it possible the RSI on the exchange is being calculated on smaller candles than 30 minutes?  It looks a lot more continuous than it would be if it used 30 minute candles.

Also, your code is a lot less efficient with the API than it could be.  Your methods ``getOpeningPrices``, etc. seem to each do an API call when you could do one API call and then populate your input arrays:

```python
coin_pair = 'BTC-XMR'
period = 15
unit = "thirtyMin"

historical_data = my_bittrex.getHistoricalData(coin_pair, period, unit)

inputs = {
    'open' = np.array([i['O'] for i in historical_data]),
    'high' = np.array([i['H'] for i in historical_data]),
    'low' = np.array([i['L'] for i in historical_data]),
    'close' = np.array([i['C'] for i in historical_data]),
    'volume' = np.array([i['V'] for i in historical_data])
}

print "open: %s" %inputs["open"][-1]
print "close: %s" %inputs["close"][-1]
print "high: %s" %inputs["high"][-1]
print "low: %s" %inputs["low"][-1]

rsi = talib.RSI(inputs["close"], timeperiod=14)
print "RSI: %s" %rsi[-1]
```

I can't reproduce that without a fair amount of work to configure an API key to whatever exchange that is, etc.

**Comment by cryptonaut1357** [comment]
Thank you for your suggestions, i am still learning python so the feedback is very usefull! :)

**Comment by John1231983** [comment]
Hello, I have same issue. This is the comparison between trade view and RSI, stochRSI. 

```
// RSI settings:
config.RSI = {
  interval: 14,
  thresholds: {
    low: 30,
    high: 70,
    // How many candle intervals should a trend persist
    // before we consider it real?
    persistence: 1
  }
};

// StochRSI settings
config.StochRSI = {
  interval: 14,
  thresholds: {
    low: 20,
    high: 80,
    // How many candle intervals should a trend persist
    // before we consider it real?
    persistence: 3
  }
};
```

![untitled](https://user-images.githubusercontent.com/24875971/32585969-731cf0f6-c543-11e7-9a05-136ec9d9f13d.png)

**Comment by mrjbq7** [comment]
@John1231983 I'm a little unclear what I'm looking at?  Are you saying you get different RSI values with ``ta-lib`` and with some other product?  You should make sure the inputs are the same because the ``RSI`` calculation is pretty simple...
