### ISSUE TITLE
Running setup.py bdist_wheel for ta-lib ... error

### ISSUE THREAD

**Issue by deppxj** [mrjbq7/ta-lib#161]
Excuse me , but when I install ta-lib by "pip install ta-lib" , an error raised as follows:

Building wheels for collected packages: ta-lib
  Running setup.py bdist_wheel for ta-lib ... error
  Complete output from command /home/depp/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-h7uQ7Z/ta-lib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpwitDvWpip-wheel- --python-tag cp27:
  /tmp/pip-build-h7uQ7Z/ta-lib/setup.py:77: UserWarning: Cannot find ta-lib library, installation may fail.
    warnings.warn('Cannot find ta-lib library, installation may fail.')
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-i686-2.7
  creating build/lib.linux-i686-2.7/talib
  copying talib/test_func.py -> build/lib.linux-i686-2.7/talib
  copying talib/test_data.py -> build/lib.linux-i686-2.7/talib
  copying talib/deprecated.py -> build/lib.linux-i686-2.7/talib
  copying talib/test_stream.py -> build/lib.linux-i686-2.7/talib
  copying talib/test_abstract.py -> build/lib.linux-i686-2.7/talib
  copying talib/__init__.py -> build/lib.linux-i686-2.7/talib
  running build_ext
  skipping 'talib/common.c' Cython extension (up-to-date)
  building 'talib.common' extension
  creating build/temp.linux-i686-2.7
  creating build/temp.linux-i686-2.7/talib
  gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/depp/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/usr/include -I/usr/local/include -I/opt/include -I/opt/local/include -I/home/depp/anaconda2/include/python2.7 -c talib/common.c -o build/temp.linux-i686-2.7/talib/common.o
  talib/common.c:242:28: error: ta-lib/ta_defs.h: No such file or directory
  talib/common.c:243:30: error: ta-lib/ta_common.h: No such file or directory
  talib/common.c:244:32: error: ta-lib/ta_abstract.h: No such file or directory
  talib/common.c:245:28: error: ta-lib/ta_func.h: No such file or directory
  talib/common.c:708: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘__Pyx_PyInt_As_TA_RetCode’
  talib/common.c:710: error: expected ‘)’ before ‘value’
  talib/common.c:712: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘__Pyx_PyInt_As_TA_FuncUnstId’
  talib/common.c:734: error: expected declaration specifiers or ‘...’ before ‘TA_RetCode’
  talib/common.c:933: error: expected declaration specifiers or ‘...’ before ‘TA_RetCode’
  talib/common.c:983: error: expected declaration specifiers or ‘...’ before ‘TA_RetCode’
  talib/common.c: In function ‘__pyx_f_5talib_6common__ta_check_success’:
  talib/common.c:1003: error: ‘__pyx_v_ret_code’ undeclared (first use in this function)
  talib/common.c:1003: error: (Each undeclared identifier is reported only once
  talib/common.c:1003: error: for each function it appears in.)
  talib/common.c:1003: error: ‘TA_SUCCESS’ undeclared (first use in this function)
  talib/common.c:1065: warning: implicit declaration of function ‘__Pyx_PyInt_From_TA_RetCode’
  talib/common.c: In function ‘__pyx_pw_5talib_6common_1_ta_check_success’:
  talib/common.c:1132: error: ‘TA_RetCode’ undeclared (first use in this function)
  talib/common.c:1132: error: expected ‘;’ before ‘__pyx_v_ret_code’
  talib/common.c:1172: error: ‘__pyx_v_ret_code’ undeclared (first use in this function)
  talib/common.c:1172: warning: implicit declaration of function ‘__Pyx_PyInt_As_TA_RetCode’
  talib/common.c:1183: error: too many arguments to function ‘__pyx_pf_5talib_6common__ta_check_success’
  talib/common.c: At top level:
  talib/common.c:1194: error: expected declaration specifiers or ‘...’ before ‘TA_RetCode’
  talib/common.c: In function ‘__pyx_pf_5talib_6common__ta_check_success’:
  talib/common.c:1203: error: ‘__pyx_v_ret_code’ undeclared (first use in this function)
  talib/common.c:1203: error: too many arguments to function ‘__pyx_f_5talib_6common__ta_check_success’
  talib/common.c: In function ‘__pyx_pf_5talib_6common_2_ta_initialize’:
  talib/common.c:1243: error: ‘TA_RetCode’ undeclared (first use in this function)
  talib/common.c:1243: error: expected ‘;’ before ‘__pyx_v_ret_code’
  talib/common.c:1259: error: ‘__pyx_v_ret_code’ undeclared (first use in this function)
  talib/common.c:1259: warning: implicit declaration of function ‘TA_Initialize’
  talib/common.c:1268: error: too many arguments to function ‘__pyx_f_5talib_6common__ta_check_success’
  talib/common.c: In function ‘__pyx_pf_5talib_6common_4_ta_shutdown’:
  talib/common.c:1316: error: ‘TA_RetCode’ undeclared (first use in this function)
  talib/common.c:1316: error: expected ‘;’ before ‘__pyx_v_ret_code’
  talib/common.c:1332: error: ‘__pyx_v_ret_code’ undeclared (first use in this function)
  talib/common.c:1332: warning: implicit declaration of function ‘TA_Shutdown’
  talib/common.c:1341: error: too many arguments to function ‘__pyx_f_5talib_6common__ta_check_success’
  talib/common.c: In function ‘__pyx_pf_5talib_6common_6_ta_set_unstable_period’:
  talib/common.c:1757: error: ‘TA_RetCode’ undeclared (first use in this function)
  talib/common.c:1757: error: expected ‘;’ before ‘__pyx_v_ret_code’
  talib/common.c:1758: error: ‘TA_FuncUnstId’ undeclared (first use in this function)
  talib/common.c:1758: error: expected ‘;’ before ‘__pyx_v_id’
  talib/common.c:1763: error: expected ‘;’ before ‘__pyx_t_3’
  talib/common.c:1782: error: ‘__pyx_t_3’ undeclared (first use in this function)
  talib/common.c:1782: warning: implicit declaration of function ‘__Pyx_PyInt_As_TA_FuncUnstId’
  talib/common.c:1784: error: ‘__pyx_v_id’ undeclared (first use in this function)
  talib/common.c:1794: error: ‘__pyx_v_ret_code’ undeclared (first use in this function)
  talib/common.c:1794: warning: implicit declaration of function ‘TA_SetUnstablePeriod’
  talib/common.c:1803: error: too many arguments to function ‘__pyx_f_5talib_6common__ta_check_success’
  talib/common.c: In function ‘__pyx_pf_5talib_6common_8_ta_get_unstable_period’:
  talib/common.c:1853: error: ‘TA_FuncUnstId’ undeclared (first use in this function)
  talib/common.c:1853: error: expected ‘;’ before ‘__pyx_v_id’
  talib/common.c:1858: error: expected ‘;’ before ‘__pyx_t_3’
  talib/common.c:1876: error: ‘__pyx_t_3’ undeclared (first use in this function)
  talib/common.c:1878: error: ‘__pyx_v_id’ undeclared (first use in this function)
  talib/common.c:1886: warning: implicit declaration of function ‘TA_GetUnstablePeriod’
  talib/common.c: In function ‘initcommon’:
  talib/common.c:2288: warning: implicit declaration of function ‘TA_GetVersionString’
  talib/common.c:2288: warning: passing argument 1 of ‘PyString_FromString’ makes pointer from integer without a cast
  /home/depp/anaconda2/include/python2.7/stringobject.h:63: note: expected ‘const char *’ but argument is of type ‘int’
  talib/common.c: At top level:
  talib/common.c:4258: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘__Pyx_PyInt_As_TA_RetCode’
  talib/common.c:4442: error: expected ‘)’ before ‘value’
  talib/common.c:4468: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘__Pyx_PyInt_As_TA_FuncUnstId’
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for ta-lib
  Running setup.py clean for ta-lib
Failed to build ta-lib
Installing collected packages: ta-lib
  Running setup.py install for ta-lib ... error
    Complete output from command /home/depp/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-h7uQ7Z/ta-lib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-f8e239-record/install-record.txt --single-version-externally-managed --compile:
    /tmp/pip-build-h7uQ7Z/ta-lib/setup.py:77: UserWarning: Cannot find ta-lib library, installation may fail.
      warnings.warn('Cannot find ta-lib library, installation may fail.')
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-i686-2.7
    creating build/lib.linux-i686-2.7/talib
    copying talib/test_func.py -> build/lib.linux-i686-2.7/talib
    copying talib/test_data.py -> build/lib.linux-i686-2.7/talib
    copying talib/deprecated.py -> build/lib.linux-i686-2.7/talib
    copying talib/test_stream.py -> build/lib.linux-i686-2.7/talib
    copying talib/test_abstract.py -> build/lib.linux-i686-2.7/talib
    copying talib/__init__.py -> build/lib.linux-i686-2.7/talib
    running build_ext
    skipping 'talib/common.c' Cython extension (up-to-date)
    building 'talib.common' extension
    creating build/temp.linux-i686-2.7
    creating build/temp.linux-i686-2.7/talib
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/depp/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/usr/include -I/usr/local/include -I/opt/include -I/opt/local/include -I/home/depp/anaconda2/include/python2.7 -c talib/common.c -o build/temp.linux-i686-2.7/talib/common.o
    talib/common.c:242:28: error: ta-lib/ta_defs.h: No such file or directory
    talib/common.c:243:30: error: ta-lib/ta_common.h: No such file or directory
    talib/common.c:244:32: error: ta-lib/ta_abstract.h: No such file or directory
    talib/common.c:245:28: error: ta-lib/ta_func.h: No such file or directory
    talib/common.c:708: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘__Pyx_PyInt_As_TA_RetCode’
    talib/common.c:710: error: expected ‘)’ before ‘value’
    talib/common.c:712: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘__Pyx_PyInt_As_TA_FuncUnstId’
    talib/common.c:734: error: expected declaration specifiers or ‘...’ before ‘TA_RetCode’
    talib/common.c:933: error: expected declaration specifiers or ‘...’ before ‘TA_RetCode’
    talib/common.c:983: error: expected declaration specifiers or ‘...’ before ‘TA_RetCode’
    talib/common.c: In function ‘__pyx_f_5talib_6common__ta_check_success’:
    talib/common.c:1003: error: ‘__pyx_v_ret_code’ undeclared (first use in this function)
    talib/common.c:1003: error: (Each undeclared identifier is reported only once
    talib/common.c:1003: error: for each function it appears in.)
    talib/common.c:1003: error: ‘TA_SUCCESS’ undeclared (first use in this function)
    talib/common.c:1065: warning: implicit declaration of function ‘__Pyx_PyInt_From_TA_RetCode’
    talib/common.c: In function ‘__pyx_pw_5talib_6common_1_ta_check_success’:
    talib/common.c:1132: error: ‘TA_RetCode’ undeclared (first use in this function)
    talib/common.c:1132: error: expected ‘;’ before ‘__pyx_v_ret_code’
    talib/common.c:1172: error: ‘__pyx_v_ret_code’ undeclared (first use in this function)
    talib/common.c:1172: warning: implicit declaration of function ‘__Pyx_PyInt_As_TA_RetCode’
    talib/common.c:1183: error: too many arguments to function ‘__pyx_pf_5talib_6common__ta_check_success’
    talib/common.c: At top level:
    talib/common.c:1194: error: expected declaration specifiers or ‘...’ before ‘TA_RetCode’
    talib/common.c: In function ‘__pyx_pf_5talib_6common__ta_check_success’:
    talib/common.c:1203: error: ‘__pyx_v_ret_code’ undeclared (first use in this function)
    talib/common.c:1203: error: too many arguments to function ‘__pyx_f_5talib_6common__ta_check_success’
    talib/common.c: In function ‘__pyx_pf_5talib_6common_2_ta_initialize’:
    talib/common.c:1243: error: ‘TA_RetCode’ undeclared (first use in this function)
    talib/common.c:1243: error: expected ‘;’ before ‘__pyx_v_ret_code’
    talib/common.c:1259: error: ‘__pyx_v_ret_code’ undeclared (first use in this function)
    talib/common.c:1259: warning: implicit declaration of function ‘TA_Initialize’
    talib/common.c:1268: error: too many arguments to function ‘__pyx_f_5talib_6common__ta_check_success’
    talib/common.c: In function ‘__pyx_pf_5talib_6common_4_ta_shutdown’:
    talib/common.c:1316: error: ‘TA_RetCode’ undeclared (first use in this function)
    talib/common.c:1316: error: expected ‘;’ before ‘__pyx_v_ret_code’
    talib/common.c:1332: error: ‘__pyx_v_ret_code’ undeclared (first use in this function)
    talib/common.c:1332: warning: implicit declaration of function ‘TA_Shutdown’
    talib/common.c:1341: error: too many arguments to function ‘__pyx_f_5talib_6common__ta_check_success’
    talib/common.c: In function ‘__pyx_pf_5talib_6common_6_ta_set_unstable_period’:
    talib/common.c:1757: error: ‘TA_RetCode’ undeclared (first use in this function)
    talib/common.c:1757: error: expected ‘;’ before ‘__pyx_v_ret_code’
    talib/common.c:1758: error: ‘TA_FuncUnstId’ undeclared (first use in this function)
    talib/common.c:1758: error: expected ‘;’ before ‘__pyx_v_id’
    talib/common.c:1763: error: expected ‘;’ before ‘__pyx_t_3’
    talib/common.c:1782: error: ‘__pyx_t_3’ undeclared (first use in this function)
    talib/common.c:1782: warning: implicit declaration of function ‘__Pyx_PyInt_As_TA_FuncUnstId’
    talib/common.c:1784: error: ‘__pyx_v_id’ undeclared (first use in this function)
    talib/common.c:1794: error: ‘__pyx_v_ret_code’ undeclared (first use in this function)
    talib/common.c:1794: warning: implicit declaration of function ‘TA_SetUnstablePeriod’
    talib/common.c:1803: error: too many arguments to function ‘__pyx_f_5talib_6common__ta_check_success’
    talib/common.c: In function ‘__pyx_pf_5talib_6common_8_ta_get_unstable_period’:
    talib/common.c:1853: error: ‘TA_FuncUnstId’ undeclared (first use in this function)
    talib/common.c:1853: error: expected ‘;’ before ‘__pyx_v_id’
    talib/common.c:1858: error: expected ‘;’ before ‘__pyx_t_3’
    talib/common.c:1876: error: ‘__pyx_t_3’ undeclared (first use in this function)
    talib/common.c:1878: error: ‘__pyx_v_id’ undeclared (first use in this function)
    talib/common.c:1886: warning: implicit declaration of function ‘TA_GetUnstablePeriod’
    talib/common.c: In function ‘initcommon’:
    talib/common.c:2288: warning: implicit declaration of function ‘TA_GetVersionString’
    talib/common.c:2288: warning: passing argument 1 of ‘PyString_FromString’ makes pointer from integer without a cast
    /home/depp/anaconda2/include/python2.7/stringobject.h:63: note: expected ‘const char *’ but argument is of type ‘int’
    talib/common.c: At top level:
    talib/common.c:4258: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘__Pyx_PyInt_As_TA_RetCode’
    talib/common.c:4442: error: expected ‘)’ before ‘value’
    talib/common.c:4468: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘__Pyx_PyInt_As_TA_FuncUnstId’

How should I fix it?
os:centos 6.5
python2.7

**Comment by mrjbq7** [comment]
Looks like you don’t have the underlying TA-Lib C library installed. Is that the case?

**Comment by deppxj** [comment]
problem solved,thank you.
I didn't install lib before

**Comment by mrjbq7** [comment]
Great, glad It’s fixed! Any feedback you’d like to give about using the library or suggested improvements are welcome!
