### ISSUE TITLE
ADXR set_unstable_period not working?

### ISSUE THREAD

**Issue by seanippolito** [mrjbq7/ta-lib#162]
I am working with ADXR and when I try to set the unstable period to 100 it seems it has no effect on the values returned by the real. 

`talib.set_unstable_period('ADXR', 100)`
`real = talib.ADXR(high, low, close, timeperiod=14)`
`trend = self.trend(high, low, close)`
`unstable_period = talib.get_unstable_period('ADXR')`

 unstable_period = 100, however I am not receiving 100 nan values in the beginning of the returned array. No matter what the value is for talib.set_unstable_period the returned array always has the same values. Is this a bug or does ADXR not have an unstable period?

Note: It works fine with ADX, so I'm not sure why it isn't correct for ADXR.

UPDATE: So I added talib.set_unstable_period('ADX', 100) above setting the ADXR unstable period and it seemed to fix this. Shouldn't setting the unstable period for ADXR call ADX's automatically?

**Comment by mrjbq7** [comment]
I don't think ADXR has an unstable period.

You can see how it works in RSI, here:

https://sourceforge.net/p/ta-lib/code/HEAD/tree/trunk/ta-lib/c/src/ta_func/ta_RSI.c#l260

But it doesn't look like ADXR uses it:

https://sourceforge.net/p/ta-lib/code/HEAD/tree/trunk/ta-lib/c/src/ta_func/ta_ADXR.c

However, ADX uses it, which is used by ADXR, so maybe try setting the unstable period of ADX:

https://sourceforge.net/p/ta-lib/code/HEAD/tree/trunk/ta-lib/c/src/ta_func/ta_ADX.c#l449
