### ISSUE TITLE
Question about BBANDS

### ISSUE THREAD

**Issue by aFluxx** [mrjbq7/ta-lib#163]
In BBands you got 4 parameters:

optInTimePeriod
optInNbDevUp
optInNbDevDn
optInMAType

I understand that the TimePeriod is the amount of candles it should look to to calculate,

But what are the other three ? optInNbDevUp optInNbDevDn & optInNbMAType

**Comment by pcawthron** [comment]
optInNbDevUp and optInNbDevDn are the number of standard deviations above and below the moving average that the upper and lower bands are calculated.

 

optInMAType is the type of moving average to use i.e.

 

SMA – Simple Moving Average

EMA – Exponential Average

WMA – Weighted Moving Average

DEMA – Double Exponential Moving Average

TEMA – Triple Exponential Moving Average

TRIMA – Triangular Moving Average

KAMA – Kaufman Adaptive Moving Average

MAMA – MESA Adaptive Moving Average

T3 – Triple Exponential Moving Average

 

e.g..  
 
upper, middle, lower = talib.BBANDS(close, matype=MA_Type.T3)

 

P.
