### ISSUE TITLE
where can I see function definitions?

### ISSUE THREAD

**Issue by AntiLopa** [mrjbq7/ta-lib#171]
I'm very new to ta-lib and python in general.
I can't figure what's the parameter each function get (beside the dataframe).  where do need to look?
Also I saw some function return more than one value which seems odd to me but anyhow - how can I know that?

can be closed, here it is:
https://github.com/mrjbq7/ta-lib/tree/master/docs/func_groups

**Comment by mrjbq7** [comment]
We also have python docstrings, so you can do something like ``help(talib.BBANDS)`` and get this:

```
Help on built-in function BBANDS in module talib.func:

BBANDS(...)
    BBANDS(real[, timeperiod=?, nbdevup=?, nbdevdn=?, matype=?])
    
    Bollinger Bands (Overlap Studies)
    
    Inputs:
        real: (any ndarray)
    Parameters:
        timeperiod: 5
        nbdevup: 2
        nbdevdn: 2
        matype: 0 (Simple Moving Average)
    Outputs:
        upperband
        middleband
        lowerband
```

**Comment by kris123456** [comment]
Guys, 

I think, I am getting BBands in reverse order. 

The end bands are being shown as zero. However the outdata in the beginning is valid. Am I missing something here. 

 

I didn’t face this issue earlier, however recently saw this and its causing errors in code. Any suggestions? 

 

Regards,

Kris.

**Comment by mrjbq7** [comment]
The inputs should be in chronological order, any chance you got it reversed?

**Comment by kris123456** [comment]
Nope. 

The tapes were in correct order. Checked it. 

 

I have passed 78 entries. 

-          OutBegin Index is 13

-          Out NB Element is 65

-          Values in double array start at index 0 and end at 65. Starting index 65, all values are 0.0. 

As per documentation, I think, the values should start at index 0 and continue till last index. 

 

Any help is greatly appreciated. Thanks for writing back. Currently debugging and ran through the code of TA Lib core.java file. Couldn’t find the exact cause. Will update once I find anything. If you know, what I am doing wrong, please do let me know. That would be of great help. Thank you John. 

 

Regards,

Kris.

**Comment by mrjbq7** [comment]
That sounds like you're working in Java?  This is the Python wrapper for the TA-Lib C library distributed at http://ta-lib.org.  You might find reading this section of documentation useful, it's for the C/C++ version of the API but probably very similar to what you're doing with Java:

https://ta-lib.org/d_api/d_api.html

Look down at section 3.1 and later.

**Comment by kris123456** [comment]
Thanks a ton John for sharing the link again. I re read the content again and again. Looks like I am doing something wrong. Will fix it now. 

Sent from hand held device.

Regards,
Kris
