### ISSUE TITLE
Help installing TA-Lib in Python (3.6.4)

### ISSUE THREAD

**Issue by pericote2017** [mrjbq7/ta-lib#173]
![picture1](https://user-images.githubusercontent.com/29669479/34451846-bffb09aa-ed00-11e7-81a2-7408595c3990.png)

Hi mrjbq7,

I am pretty new to Python, I want to develop my code using technical analysis (I am an advanced user of technical analysis). But I cannot install TA-Lib.

When you say, install from PyPI, do you refer to pip, in the cmd window?

Also, when you say: checkout the sources and run setup.py yourself. Do you think you can be more specific. Maybe you can walk me through it. Should I use the cmd window? 

BTW I have the last version of Python (3.6.4) and pip3. I already installed numpy, matplolib, pandas and Cython because I read that it was easier with cython instead SWIG wrapper. But I dont get what it really means. 

I tried all the ways but it does not work. I also downloaded the file from their web site http://ta-lib.org/hdr_dw.html and then https://sourceforge.net/projects/ta-lib/?source=typ_redirect but I dont know to make it run.

Thanks for your help I 'd appreciate tremendously your help

Pericote

**Comment by pericote2017** [comment]
Whoever can help me, I would appreciate it a lot. I want to develop a TA package for python

Thanks

Pericote

**Comment by mrjbq7** [comment]
For Windows 64-bit, since the underlying TA-Lib C library is only distributed as a 32-bit binary, you need to build your own.  Someone has made available packages that can be more easily installed in your case:

https://www.lfd.uci.edu/~gohlke/pythonlibs/#ta-lib

**Comment by mrjbq7** [comment]
If you are using Python 3.6 with Windows 64 bit, then this one is probably what you want to install:

TA_Lib‑0.4.10‑cp36‑cp36m‑win_amd64.whl

And then run:

```
pip install TA_Lib-0.4.10-cp27-cp27m-win_amd64.whl
```

**Comment by pericote2017** [comment]
@mrjbq7 Thanks for your answer!
It was very useful

I just use this way because of your advice and it seems working :) 👍  
![image](https://user-images.githubusercontent.com/29669479/34473093-5af805ec-ef3c-11e7-96e8-ea787f21a19a.png)

Pericote

**Comment by mrjbq7** [comment]
Whoops, I'm not sure why I said try the 3.6 version and then pasted in the command line for the 2.7 version.  Anyway, glad it works!
