### ISSUE TITLE
unable to install (invalid start Byte)

### ISSUE THREAD

**Issue by Tektronox** [mrjbq7/ta-lib#174]
I wanted to install ta-lib but I got the following error:

`  Running setup.py install for ta-lib ... error`
`Exception:`
`Traceback (most recent call last):`
`  File "c:\program files\python36\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str`
`    return s.decode(sys.__stdout__.encoding)`
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 80: invalid start byte`

I have no Idea what why this appears. I'm using windows 10. I tried with a 32 bit version of Python and also with a 64 bit version of both. But it's always the same error 

Can someone help me pls?

**Comment by mrjbq7** [comment]
Not sure, haven't seen that before.

Some information about that error maybe:

https://stackoverflow.com/questions/22216076/unicodedecodeerror-utf8-codec-cant-decode-byte-0xa5-in-position-0-invalid-s

**Comment by Tektronox** [comment]
Thanks for your help and sorry for leaving this open so long, was gone for a few months. 
I couldn't reproduce the same error though.
Now I had problems with VS2015 so I took the binaries and installed it via them.
Now everything is fine.
