### ISSUE TITLE
Ta-Lib: What is the Idea of Periods in MAVP - (Moving average with variable period)?

### ISSUE THREAD

**Issue by haimivan** [mrjbq7/ta-lib#175]
as posted in https://stackoverflow.com/questions/48135059/ta-lib-what-is-the-idea-of-periods-in-mavp-moving-average-with-variable-peri :

I want to use  the following function of ta-lib.

**I want to understand the meaning of `periods`.**

    MAVP
    
    MAVP([input_arrays], [minperiod=2], [maxperiod=30], [matype=0])
    
    Moving average with variable period (Overlap Studies)
    
    Inputs:
    price: (any ndarray) periods: (any ndarray)
    Parameters:
    minperiod: 2 maxperiod: 30 matype: 0 (Simple Moving Average)
    Outputs:
    real

It gives an error back when the length of `periods` is different to the length of `price` (additionally: it gives back a nparray, if `matype` is >= 0 and <= 8, else an error is thrown).

The original documentation:
https://mrjbq7.github.io/ta-lib/func_groups/overlap_studies.html

A reference to some (auto generated) documentation:
https://www.backtrader.com/docu/talibindautoref.html

**EDIT:**
The underlying c code is here:
http://svn.code.sf.net/p/ta-lib/code/trunk/ta-lib/c/src/ta_func/ta_MAVP.c

**Comment by mrjbq7** [comment]
There are only 8 types of moving averages, enumerated 0 to 8:

SMA, EMA, WMA, DEMA, TEMA, TRIMA, KAMA, MAMA, T3

**Comment by mrjbq7** [comment]
The error checking price length with periods length is a bug.

**Comment by haimivan** [comment]
thanks!

> The error checking price length with periods length is a bug.

so it seems not so wise to use MAVP at all, right?

**Comment by mrjbq7** [comment]
I just had auto-generated length checks that prevented MAVP from being used.  The checks work for all the other functions because we want to make sure any of the prices arrays have the same length as each other.

Anyway, I pushed updated MAVP so if you get latest git can you see if MAVP works as you expect?

**Comment by haimivan** [comment]
>Anyway, I pushed updated MAVP so if you get latest git can you see if MAVP works as you expect?

Thanks for that. 

As the whole topic is quite new to me, I still have to learn indicators. :-)

Does it mean that `periods` is not a vector, but a scalar value and that it just specifies the amount of time units for which averaging should be done?

**Comment by mrjbq7** [comment]
The ``periods`` is an array of ``dtype=float`` that is constrained by minperiod and maxperiod and then used by the ``MAVP`` calculation in the C code.

**Comment by mrjbq7** [comment]
Okay, so my fix was wrong.

This is what the function does.

It gets an input price array, and a periods array that are the same length.

The output price array is the moving average at the point using the specified period at the point.

So, if you have an array of [1, 5, 3, 8] and you specify periods [2,3,3,2] then the output will be:

```
[SMA(2)[0], SMA(3)[1], SMA(3)[2], SMA(2)[3]]
```

With the exception that it puts maxperiods number of nan's at the front, for some reason so you'd need to call it like:

```python
>>> prices = np.array([1,5,7,8], dtype=float)
>>> periods =np.array([2,3,3,2], dtype=float)
>>> ta.MAVP(prices, periods, maxperiod=3)
array([        nan,         nan,  4.33333333,  7.5       ])

>>> ta.SMA(prices, 2)
array([ nan,  3. ,  6. ,  7.5])

>>> ta.SMA(prices, 3)
array([        nan,         nan,  4.33333333,  6.66666667])
```

**Comment by haimivan** [comment]
thanks!
