### ISSUE TITLE
abstract info attributes no longer reachable

### ISSUE THREAD

**Issue by mementum** [mrjbq7/ta-lib#176]
https://github.com/mrjbq7/ta-lib/commit/ddce83fdb72bb0bc1b1311cc73d524d8bdb59556#diff-6611e06e7f0384b7c744cc65c94ea8b2

With that commit which reorders the modules and has been first *published* (so to say) with `0.4.14` has removed the visibility of fields previously defined in `abstract.py`.

Examples `TA_FUNC_FLAGS`, `TA_INPUT_FLAGS`, `TA_OUTPUT_FLAGS`. This can be used to automate the integration of `ta-lib` as it is done in `backtrader`

Those attributes were not marked (as it is customary) with a leading `_` to indicate its *private* nature and were taken as part of the *API*

**Comment by mrjbq7** [comment]
Can you give me an example of what worked before and no longer does?

**Comment by mrjbq7** [comment]
I think this would work for you:

```python
try:
    talib.abstract.TA_FUNC_FLAGS
except AttributeError:
    talib._ta_lib.TA_FUNC_FLAGS
```

**Comment by mrjbq7** [comment]
I suppose, I could also do something in ``talib.abstract`` to expose those for backwards compatibility...

**Comment by mrjbq7** [comment]
Okay, fixed this by exposing those in ``talib.abstract`` and releasing 0.4.15.  Can you make sure that works for you?

**Comment by mementum** [comment]
> Can you give me an example of what worked before and no longer does?

See for example: https://community.backtrader.com/topic/808/cannot-import-backtrader

> I think this would work for you:
> ```
> try:
>     talib.abstract.TA_FUNC_FLAGS
> except AttributeError:
>     talib._ta_lib.TA_FUNC_FLAGS
> ```

Indeed it would. The purpose of opening the ticket is to let you know of the *surprise* it may generate in platforms/users who may rely on previously reachable fields, which have suddenly *vanished*.

I will let the users know. Thank you for the prompt response.

**Comment by mrjbq7** [comment]
Can you post on that thread to upgrade to 0.4.15 if it works for you?

Sorry for inadvertently breaking you!

**Comment by mementum** [comment]
Thx. Believe when I tell you that I break things all the time.
