### ISSUE TITLE
TA-Lib: failed installation

### ISSUE THREAD

**Issue by Sile25** [mrjbq7/ta-lib#177]
I'm trying to install TA-Lib module on my 3.6 Python, but i'm facing many problems. First of all, i already made sure that it's the x32 version. I have two versions of python installed, 2.7 and 3.6.

Here is what i tried:

`pip install ta-lib`

I got the error error: `command 'cl.exe' failed: No such file or directory.`

After that, i tried downloading it from here, but after running `pip install TA_Lib-0.4.15-cp36-cp36m-win32.whl`, i got the following error: requirement '`TA_Lib-0.4.15-cp36-cp36m-win32.whl' looks like a filename, but the file does not exist.
`
Did anyone else experience a similar problem or knows how to solve it? Thanks in advance

**Comment by mrjbq7** [comment]
I'm sorry you're having trouble installing it.  It's hard to say exactly what's going on, but...

1) Your first error means you probably don't have Visual Studio installed, or you aren't using it from a Command Prompt with the path setup properly to find it.  When you install with ``pip install ta-lib``, it needs to compile the C code as part of the installation, unless...

2) You install using the pre-built wheel like you tried to do, but your error where it says "file does not exist" means that you did ``pip install TA_Lib-0.4.15-cp36-cp36m-win32.whl`` from a directory different from where you downloaded it.  Try to change to the download directory and then re-run that command.

Hope that helps.

**Comment by Sile25** [comment]
Alright, i don't know why i was getting that error on the first case, Visual Studio was already installed.

I tried again the second way but this time i added the directory, so `pip install TA_Lib-0.4.15-cp36-cp36m-win32.whl` and it worked.
