### ISSUE TITLE
Trouble with pandas.series inputs

### ISSUE THREAD

**Issue by rmwenzel** [mrjbq7/ta-lib#182]
Trying out example function calls from the docs. I have a series `close` of closing prices,

`type(close) == pandas.core.series.Series`
`type(close[0]) == numpy.float64 `

but the call `talib.SMA(close)` throws

`TypeError: Argument 'real' has incorrect type (expected numpy.ndarray, got Series)`

I see support for `pandas.Series` was just added and since

`pandas.Series == panda.core.series.Series` 

I'm not sure what I'm missing. I did try several other function calls and got the same error.

**Comment by mrjbq7** [comment]
What does ``talib.__version__`` return?

It sounds like you don't have the latest (unreleased) code with that improvement.  It should return 0.4.17 (which hasn't been released yet).

**Comment by rmwenzel** [comment]
`talib.__version__ == 0.4.16`

Should (of course) have thought of that. Thanks!
