### ISSUE TITLE
ta-lib-0.4.0-src.tar.gz  link is returning bad request.

### ISSUE THREAD

**Issue by mateusreyes** [mrjbq7/ta-lib#186]
http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz

ERROR
The request could not be satisfied.
Bad request. 
Generated by cloudfront (CloudFront)
Request ID: IqnYFo1TlUiiFirFyogWgspnkffE90euLpS1pFtEPNpxUyroNUnSDQ==

**Comment by mateusreyes** [comment]
Using alternative link: https://sourceforge.net/projects/ta-lib/files/ta-lib/0.4.0/ 
https://sourceforge.net/projects/ta-lib/files/ta-lib/0.4.0/ta-lib-0.4.0-src.tar.gz/download

**Comment by mrjbq7** [comment]
Not sure why that is, but I am not a maintainer for the underlying C library so I don't have access to its project on sourceforge...

**Comment by mrjbq7** [comment]
Sorry!

**Comment by mateusreyes** [comment]
Thanks @mrjbq7 

Here is a probable reason for the broken link: 
" @sfnet_ops: We now have a much better idea as to what is causing the recent performance issues. We're now executing a plan to get SourceForge back to full capacity. We may be some hours off yet, but our team is working around the clock until stability is restored. Thank you for your patience"
https://twitter.com/sfnet_ops/status/969377360129773568

**Comment by mrjbq7** [comment]
Appreciate the heads up!!

**Comment by kivo360** [comment]
Is there a backup anywhere?
