### ISSUE TITLE
talib doesn't work in ubuntu

### ISSUE THREAD

**Issue by xiaoxiaoyaozi** [mrjbq7/ta-lib#187]
I install the talib with the method below:
      `$ untar and cd`
      `$ ./configure --prefix=/usr`
      `$ make`
      `$ sudo make install`
but when I run a python file
 `Traceback (most recent call last):`
  `File "./preprocess_data.py", line 2, in <module>`
    `import talib`
`ModuleNotFoundError: No module named 'talib'`
where goes wrong?

**Comment by mrjbq7** [comment]
Did you ``pip install ta-lib``?

**Comment by xiaoxiaoyaozi** [comment]
cool！it works




| |
xxyao
邮箱：13120699637@163.com
|

签名由 网易邮箱大师 定制

On 03/03/2018 02:06, John Benediktsson wrote:

Did you pip install ta-lib?

**Comment by mrjbq7** [comment]
Yay!  Let me know if you have other feedback!
