### ISSUE TITLE
How to work with pandas panel?

### ISSUE THREAD

**Issue by DexHunter** [mrjbq7/ta-lib#191]
Hi! Thanks for sharing the awesome wrapper.

I have a panel data looks like:
```
Dimensions: 5 (items) x 2 (major_axis) x 10 (minor_axis)
Items axis: open to volume
Major_axis axis: AAPL to MSFT
Minor_axis axis: 1520234042 to 1521098025
```

So the `items` are ohlc+volume, the `major_axis` are stocks, and minor axis are timestamps of dates.

I was wondering if there is a way to easier apply ta-lib to this kind of data? Thank you.

**Comment by mrjbq7** [comment]
Do you have examples of the code you use now?

**Comment by mrjbq7** [comment]
Also, how common is this structure (items, major axis, minor axis).

Is this from an API that is used a fair amount?

**Comment by DexHunter** [comment]
Thanks for the response. I managed to use talib by decompsing the panel with some loops.
