### ISSUE TITLE
same problem even after installing the visual studio for importing the ta-lib

### ISSUE THREAD

**Issue by chaitu4492** [mrjbq7/ta-lib#198]
C:\Users\CHAITU> pip install TA-Lib
Collecting TA-Lib
  Using cached https://files.pythonhosted.org/packages/90/05/d4c6a778d7a7de0be36
6bc4a850b4ffaeac2abad927f95fa8ba6f355a082/TA-Lib-0.4.17.tar.gz
Requirement already satisfied: numpy in c:\users\chaitu\anaconda3\lib\site-packa
ges (from TA-Lib)
Building wheels for collected packages: TA-Lib
  Running setup.py bdist_wheel for TA-Lib ... error
  Complete output from command c:\users\chaitu\anaconda3\python.exe -u -c "impor
t setuptools, tokenize;__file__='C:\\Users\\CHAITU\\AppData\\Local\\Temp\\pip-bu
ild-j7184m56\\TA-Lib\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code
=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))"
 bdist_wheel -d C:\Users\CHAITU\AppData\Local\Temp\tmps7tgbv79pip-wheel- --pytho
n-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\talib
  copying talib\abstract.py -> build\lib.win-amd64-3.6\talib
  copying talib\deprecated.py -> build\lib.win-amd64-3.6\talib
  copying talib\stream.py -> build\lib.win-amd64-3.6\talib
  copying talib\test_abstract.py -> build\lib.win-amd64-3.6\talib
  copying talib\test_data.py -> build\lib.win-amd64-3.6\talib
  copying talib\test_func.py -> build\lib.win-amd64-3.6\talib
  copying talib\test_pandas.py -> build\lib.win-amd64-3.6\talib
  copying talib\test_stream.py -> build\lib.win-amd64-3.6\talib
  copying talib\__init__.py -> build\lib.win-amd64-3.6\talib
  running build_ext
  skipping 'talib\_ta_lib.c' Cython extension (up-to-date)
  building 'talib._ta_lib' extension
  creating build\temp.win-amd64-3.6
  creating build\temp.win-amd64-3.6\Release
  creating build\temp.win-amd64-3.6\Release\talib
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14
.13.26128\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\
chaitu\anaconda3\lib\site-packages\numpy\core\include -Ic:\ta-lib\c\include -Ic:
\users\chaitu\anaconda3\include -Ic:\users\chaitu\anaconda3\include "-IC:\Progra
m Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\A
TLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\
VC\Tools\MSVC\14.13.26128\include" /Tctalib\_ta_lib.c /Fobuild\temp.win-amd64-3.
6\Release\talib\_ta_lib.obj
  _ta_lib.c
  c:\users\chaitu\anaconda3\include\pyconfig.h(59): fatal error C1083: Cannot op
en include file: 'io.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Commun
ity\\VC\\Tools\\MSVC\\14.13.26128\\bin\\HostX86\\x64\\cl.exe' failed with exit s
tatus 2

  ----------------------------------------
  Failed building wheel for TA-Lib
  Running setup.py clean for TA-Lib
Failed to build TA-Lib
Installing collected packages: TA-Lib
  Running setup.py install for TA-Lib ... error
    Complete output from command c:\users\chaitu\anaconda3\python.exe -u -c "imp
ort setuptools, tokenize;__file__='C:\\Users\\CHAITU\\AppData\\Local\\Temp\\pip-
build-j7184m56\\TA-Lib\\setup.py';f=getattr(tokenize, 'open', open)(__file__);co
de=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec')
)" install --record C:\Users\CHAITU\AppData\Local\Temp\pip-u9g1s4xk-record\insta
ll-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\talib
    copying talib\abstract.py -> build\lib.win-amd64-3.6\talib
    copying talib\deprecated.py -> build\lib.win-amd64-3.6\talib
    copying talib\stream.py -> build\lib.win-amd64-3.6\talib
    copying talib\test_abstract.py -> build\lib.win-amd64-3.6\talib
    copying talib\test_data.py -> build\lib.win-amd64-3.6\talib
    copying talib\test_func.py -> build\lib.win-amd64-3.6\talib
    copying talib\test_pandas.py -> build\lib.win-amd64-3.6\talib
    copying talib\test_stream.py -> build\lib.win-amd64-3.6\talib
    copying talib\__init__.py -> build\lib.win-amd64-3.6\talib
    running build_ext
    skipping 'talib\_ta_lib.c' Cython extension (up-to-date)
    building 'talib._ta_lib' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\talib
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\
14.13.26128\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\user
s\chaitu\anaconda3\lib\site-packages\numpy\core\include -Ic:\ta-lib\c\include -I
c:\users\chaitu\anaconda3\include -Ic:\users\chaitu\anaconda3\include "-IC:\Prog
ram Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128
\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Communit
y\VC\Tools\MSVC\14.13.26128\include" /Tctalib\_ta_lib.c /Fobuild\temp.win-amd64-
3.6\Release\talib\_ta_lib.obj
    _ta_lib.c
    c:\users\chaitu\anaconda3\include\pyconfig.h(59): fatal error C1083: Cannot
open include file: 'io.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Comm
unity\\VC\\Tools\\MSVC\\14.13.26128\\bin\\HostX86\\x64\\cl.exe' failed with exit
 status 2

    ----------------------------------------
Command "c:\users\chaitu\anaconda3\python.exe -u -c "import setuptools, tokenize
;__file__='C:\\Users\\CHAITU\\AppData\\Local\\Temp\\pip-build-j7184m56\\TA-Lib\\
setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\
n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\U
sers\CHAITU\AppData\Local\Temp\pip-u9g1s4xk-record\install-record.txt --single-v
ersion-externally-managed --compile" failed with error code 1 in C:\Users\CHAITU
\AppData\Local\Temp\pip-build-j7184m56\TA-Lib\

**Comment by mrjbq7** [comment]
Well, now you're getting another error:

```
c:\users\chaitu\anaconda3\include\pyconfig.h(59): fatal error C1083: Cannot
open include file: 'io.h': No such file or directory
```

I can't really help you with every step of debugging this.  I don't have time, unfortunately.  However, I'd recommend two things:

1) Install the wheel from gohlke and everything should just work.

or

2) Google that error message, and try and resolve it yourself.  For example, the first link:

https://stackoverflow.com/questions/40018405/cython-cannot-open-include-file-io-h-no-such-file-or-directory

**Comment by mrjbq7** [comment]
It's a shame that Windows makes it so hard to configure an environment for development.  It's usually as easy as installing Visual Studio Express or whatever they call it these days.  But thats beyond the scope of my desire to support this project.  If you'd like to contribute any documentation on how to resolve the errors you come across, I'd be happy to merge it into the README.
