### ISSUE TITLE
Ta-lib time series order

### ISSUE THREAD

**Issue by rawoke083** [mrjbq7/ta-lib#199]
Hi guys... stupid question...
But when working with the time series related functions example (ATR,SMA etc) what should the order of the data be ? Latest first or last ?

**Comment by mrjbq7** [comment]
I should document that somewhere, but it's the same convention the underlying TA-Lib C library uses:

Oldest to Newest.

close[0].... to close[-1]

You can tell by using some simple indicators like ``MOM`` which is basically just the difference between values ``close[i] = close[i] - close[i-timeperiod]`` and how the NaN's are at the beginning of the period:

```python
>>> import talib
>>> import numpy
>>> a = numpy.random.randn(50)
>>> talib.MOM(a, timeperiod=10)
array([        nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
       -0.01921563,  2.65483941, -0.53771642,  0.23581401, -1.09358887,
        2.42476339, -1.75537128, -0.69052539, -0.9729937 ,  0.57394123,
        0.18812263, -1.72334877, -0.63002017,  0.37851998, -0.88143324,
       -0.24326273,  0.00643762, -1.05961495,  0.61278274, -0.7500058 ,
       -0.7538679 ,  0.00717455,  0.43323023, -0.81537358,  3.51120175,
       -1.79254359,  0.49569614,  1.96795945, -0.73740337, -0.80511636,
       -0.55453737,  0.95865948, -0.15681476, -0.35040997, -1.42661283,
        1.97432346,  0.53888517, -1.04891646,  1.72072941,  1.29076317])
```

**Comment by rawoke083** [comment]
Brilliant thank you very much !
