### ISSUE TITLE
Pattern Bearish and Bullish 

### ISSUE THREAD

**Issue by macd2** [mrjbq7/ta-lib#200]
how do i distinguish between bearish Harami and bullish Harami since in the documentation i can only find one Version:
 ```CDLHARAMI - Harami Pattern - integer = CDLHARAMI(open, high, low, close)```

same question for Engulfing

Thanks

**Comment by mrjbq7** [comment]
You can find additional documentation in the underlying TA-Lib source code:

https://sourceforge.net/p/ta-lib/code/HEAD/tree/trunk/ta-lib/c/src/ta_func/ta_CDLHARAMI.c#l228

```
   /* Proceed with the calculation for the requested range.
    * Must have:
    * - first candle: long white (black) real body
    * - second candle: short real body totally engulfed by the first 
    * The meaning of "short" and "long" is specified with TA_SetCandleSettings
    * outInteger is positive (1 to 100) when bullish or negative (-1 to -100) when bearish:
    * - 100 is returned when the first candle's real body begins before and ends after the second candle's real body
    * - 80 is returned when the two real bodies match on one end (Greg Morris contemplate this case in his book
    *   "Candlestick charting explained")
    * The user should consider that a harami is significant when it appears in a downtrend if bullish or 
    * in an uptrend when bearish, while this function does not consider the trend
    */
```

**Comment by macd2** [comment]
@mrjbq7 thanks for the fast replay but i still don't understand how to set the pattern to bullish or bearish?

**Comment by mrjbq7** [comment]
It’s not “set to bullish”. You call it once and it returns numbers indicating bullish (positive) or bearish (negative). The comment indicates you might want to consider a threshold above a certain value as significant and maybe correlated with other observable behavior. 

What is the confusion here? Maybe I’m not being clear.

**Comment by mrjbq7** [comment]
You mean something like:

```python
bullish = df['harami'] > 0
bearish = df['harami'] < 0
```

But I would suggest both that the comment indicates you might want momentum in the same direction, and also, like any technical indicator, it's value is proved or disproved through backtesting.

**Comment by kris123456** [comment]
If it is +1 it’s bullish. 
If it is -1, it is bearish. 
What part you did not understand?? It was in plain simple English. 

Sent from hand held device.

Regards,
Krishnakanth.

**Comment by macd2** [comment]
@mrjbq7 ok thank you now it is clear!

**Comment by Aqua-4** [comment]
https://sourceforge.net/p/ta-lib/code/HEAD/tree/trunk/ta-lib/c/src/ta_func/ta_CDLHAMMER.c#l246

How to identify bearish patterns when the library only returns positive value for certain patterns like hammer?
