### ISSUE TITLE
building static for AWS lambda use under python

### ISSUE THREAD

**Issue by berlinguyinca** [mrjbq7/ta-lib#205]
dear all,

are there any guidelines how to compile this library static + the python package to make it work under AWS lambda deployments?

thank you

**Comment by rappelsen** [comment]
Hi Berlinguyinca, currently struggling with the same problem. 
Did you get it work somehow?

**Comment by berlinguyinca** [comment]
yup got it to work after a week or so, you need to compile TA-lIB static on a AWS server and have it copied into the local lib folder. (assuming you are using the serverless framework)

In short, it's a pain... Once you solve this, you will now be struggling with your deployment packaged being to large for lambda constantly. My best solution at this point is to utilize aws to schedule a fargate task

**Comment by rappelsen** [comment]
@berlinguyinca works great for me, thanks.

**Comment by Kooshini** [comment]
I had issues with this also - I have created a repo here with everything built to save someone time.

https://github.com/Kooshini/ta-lib-aws-lambda
