### ISSUE TITLE
Install TA-lib on a Linux server without sudo privilege

### ISSUE THREAD

**Issue by jiagengliu** [mrjbq7/ta-lib#210]
I was wondering if I could Install TA-lib on a Linux server without a sudo privilege. It seems that I have to specify `./configure prefix=/usr` to install, is there a way to work around?

**Comment by mrjbq7** [comment]
I think it's roughly:

```
$ ./configure prefix=/some/other/path
...
```

Then, something like:

```
$ git clone git@github.com:mrjbq7/ta-lib.git
$ cd ta-lib
$ TA_INCLUDE_PATH=/some/other/path/include TA_LIBRARY_PATH=/some/other/path/lib python setup.py
```

We have two environment variables that are used by ``setup.py`` to look for other locations than the "standard ones" for TA-Lib.

**Comment by jiagengliu** [comment]
Thank you very much for the swift response. I have successfully installed it using the following 
```
$ git clone https://github.com/mrjbq7/ta-lib.git
$ cd ta-lib
$ TA_INCLUDE_PATH=/home/jiageng/opt/include TA_LIBRARY_PATH=/home/jiageng/opt/lib python setup.py install
```
I get warnings like `warning: passing argument 2 of ‘TA_GetFuncInfo’ from incompatible pointer type [enabled by default]`, but just Ctrl-C to ignore it and everything works.

**Comment by Sergey80** [comment]
i wonder how to make it apper in venv ... 
./configure --prefix=/home/sergii/projects/trading/money_pump/venv/lib/python3.9/site-packages
..
then: pip list

did not work..
