### ISSUE TITLE
reinstalling ta-lib error

### ISSUE THREAD

**Issue by machinelearner452** [mrjbq7/ta-lib#221]
I had the ta-lib issue (#127 ?).   Followed all the great suggestions and was able to get  ta-lib installed via the downloading the wheel file and pip install TA_Lib-0.4.17-cp36-cp36m-win32.whl from the root c:\ta-lib.  The file is still on the C:\.

Next i could not pip install sendkeys and tried to fix by reinstalling wheel, setuptools and ta-lib.  All good with Wheel and setutools, re install will not work on the ta-lib package?? I did check the is was install already nd it was.

C:\Users\Joe>pip install --upgrade --force-reinstall wheel
Collecting wheel
  Using cached https://files.pythonhosted.org/packages/81/30/e935244ca6165187ae8be876b6316ae201b71485538ffac1d718843025a9/wheel-0.31.1-py2.py3-none-any.whl
Installing collected packages: wheel
  Found existing installation: wheel 0.31.1
    Uninstalling wheel-0.31.1:
      Successfully uninstalled wheel-0.31.1
Successfully installed wheel-0.31.1

C:\Users\Joe>pip install --upgrade --force-reinstall setuptools
Collecting setuptools
  Using cached https://files.pythonhosted.org/packages/ff/f4/385715ccc461885f3cedf57a41ae3c12b5fec3f35cce4c8706b1a112a133/setuptools-40.0.0-py2.py3-none-any.whl
Installing collected packages: setuptools
  Found existing installation: setuptools 40.0.0
    Uninstalling setuptools-40.0.0:
      Successfully uninstalled setuptools-40.0.0
Successfully installed setuptools-40.0.0

**C:\Users\Joe>pip install ta-lib
Requirement already satisfied: ta-lib in c:\users\joe\appdata\local\programs\python\python36-32\lib\site-packages (0.4.17)**

C:\Users\Joe>pip install --upgrade --force-reinstall ta-lib
Collecting ta-lib
  Using cached https://files.pythonhosted.org/packages/90/05/d4c6a778d7a7de0be366bc4a850b4ffaeac2abad927f95fa8ba6f355a082/TA-Lib-0.4.17.tar.gz
Collecting numpy (from ta-lib)
  Using cached https://files.pythonhosted.org/packages/80/75/4c1cd85e891b97a01bc96a232c00f8e60bff4608b6be356a8aed1180fd79/numpy-1.15.0-cp36-none-win32.whl
Building wheels for collected packages: ta-lib
  **Running setup.py bdist_wheel for ta-lib ... error**
  Complete output from command c:\users\joe\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Joe\\AppData\\Local\\Temp\\pip-install-c8x25f5w\\ta-lib\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\Joe\AppData\Local\Temp\pip-wheel-f9zgnnpg --python-tag cp36:
  C:\Users\Joe\AppData\Local\Temp\pip-install-c8x25f5w\ta-lib\setup.py:79: UserWarning: Cannot find ta-lib library, installation may fail.
    **warnings.warn('Cannot find ta-lib library, installation may fail.')**
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.6
  creating build\lib.win32-3.6\talib
  copying talib\abstract.py -> build\lib.win32-3.6\talib
  copying talib\deprecated.py -> build\lib.win32-3.6\talib
  copying talib\stream.py -> build\lib.win32-3.6\talib
  copying talib\test_abstract.py -> build\lib.win32-3.6\talib
  copying talib\test_data.py -> build\lib.win32-3.6\talib
  copying talib\test_func.py -> build\lib.win32-3.6\talib
  copying talib\test_pandas.py -> build\lib.win32-3.6\talib
  copying talib\test_stream.py -> build\lib.win32-3.6\talib
  copying talib\__init__.py -> build\lib.win32-3.6\talib
  running build_ext
  building 'talib._ta_lib' extension
  creating build\temp.win32-3.6
  creating build\temp.win32-3.6\Release
  creating build\temp.win32-3.6\Release\talib
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\joe\appdata\local\programs\python\python36-32\lib\site-packages\numpy\core\include -Ic:\ta-lib\c\include -Ic:\users\joe\appdata\local\programs\python\python36-32\include -Ic:\users\joe\appdata\local\programs\python\python36-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" /Tctalib/_ta_lib.c /Fobuild\temp.win32-3.6\Release\talib/_ta_lib.obj
  _ta_lib.c
  talib/_ta_lib.c(524): fatal error C1083: Cannot open include file: 'ta_libc.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.14.26428\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2

  ----------------------------------------
  **Failed building wheel for ta-lib**
  Running setup.py clean for ta-lib
Failed to build ta-lib
Installing collected packages: numpy, ta-lib
  Found existing installation: numpy 1.15.0
    Uninstalling numpy-1.15.0:
      Successfully uninstalled numpy-1.15.0
  Found existing installation: ta-lib 0.4.17
    Uninstalling ta-lib-0.4.17:
      Successfully uninstalled ta-lib-0.4.17
  Running setup.py install for ta-lib ... error
    Complete output from command c:\users\joe\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Joe\\AppData\\Local\\Temp\\pip-install-c8x25f5w\\ta-lib\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Joe\AppData\Local\Temp\pip-record-a57z277u\install-record.txt --single-version-externally-managed --compile:
    C:\Users\Joe\AppData\Local\Temp\pip-install-c8x25f5w\ta-lib\setup.py:79: UserWarning: Cannot find ta-lib library, installation may fail.
      warnings.warn('Cannot find ta-lib library, installation may fail.')
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.6
    creating build\lib.win32-3.6\talib
    copying talib\abstract.py -> build\lib.win32-3.6\talib
    copying talib\deprecated.py -> build\lib.win32-3.6\talib
    copying talib\stream.py -> build\lib.win32-3.6\talib
    copying talib\test_abstract.py -> build\lib.win32-3.6\talib
    copying talib\test_data.py -> build\lib.win32-3.6\talib
    copying talib\test_func.py -> build\lib.win32-3.6\talib
    copying talib\test_pandas.py -> build\lib.win32-3.6\talib
    copying talib\test_stream.py -> build\lib.win32-3.6\talib
    copying talib\__init__.py -> build\lib.win32-3.6\talib
    running build_ext
    building 'talib._ta_lib' extension
    creating build\temp.win32-3.6
    creating build\temp.win32-3.6\Release
    creating build\temp.win32-3.6\Release\talib
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\joe\appdata\local\programs\python\python36-32\lib\site-packages\numpy\core\include -Ic:\ta-lib\c\include -Ic:\users\joe\appdata\local\programs\python\python36-32\include -Ic:\users\joe\appdata\local\programs\python\python36-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" /Tctalib/_ta_lib.c /Fobuild\temp.win32-3.6\Release\talib/_ta_lib.obj
    _ta_lib.c
    talib/_ta_lib.c(524): fatal error C1083: Cannot open include file: 'ta_libc.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.14.26428\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2

    ----------------------------------------
  Rolling back uninstall of ta-lib
Command "c:\users\joe\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Joe\\AppData\\Local\\Temp\\pip-install-c8x25f5w\\ta-lib\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Joe\AppData\Local\Temp\pip-record-a57z277u\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Joe\AppData\Local\Temp\pip-install-c8x25f5w\ta-lib\

C:\Users\Joe>

Thanks for any suggestions?

**Comment by machinelearner452** [comment]
Thank you, John, I must be going blind for sure.  The issue was the folder layout C:\ta-lib\ta-lib\c\... I did not notice that the ta-lib folder name was duplicated when the file was extracted....  closing!!

**Comment by mrjbq7** [comment]
No worries!
