### ISSUE TITLE
Is there any function which replace change() in pine script?

### ISSUE THREAD

**Issue by sahilr2050** [mrjbq7/ta-lib#224]
Hello Everyone,

Actually, I am looking for python function for [change() function](https://www.tradingview.com/study-script-reference/#fun_change) 

In Trading View I don't understand what this means. 
```
Difference between current value and previous, x - x[y].
```

Is this simply return difference between current value and previous value? or something else?

**Comment by mrjbq7** [comment]
All of these suppose a ``y = 1`` but you could pass any ``y``.

You could use ``numpy``:

```python
>>> import numpy as np
>>> a = np.array([1,1,2,3,5,8,13], dtype=float)
>>> a[1:] - a[:-1]
array([0., 1., 1., 2., 3., 5.])
```

Or ``pandas``:

```python
>>> import pandas as pd
>>> b = pd.Series(a)
>>> b.rolling(window=2).apply(lambda x: x[-1] - x[0], raw=True)
0    NaN
1    0.0
2    1.0
3    1.0
4    2.0
5    3.0
6    5.0
dtype: float64
```

Or maybe using ``talib``:

```python
>>> import talib as ta
>>> ta.MOM(a, 1)
array([nan,  0.,  1.,  1.,  2.,  3.,  5.])
```

**Comment by nhab** [comment]
use `ta.Change() `instead of` change()`
