### ISSUE TITLE
Why BBANDS upperband=middleband=lowerband ?

### ISSUE THREAD

**Issue by KevinLiou** [mrjbq7/ta-lib#226]
Hello Everyone: 
![](https://i.imgur.com/FC2ZUIn.png)

Is this correct？

**Comment by mrjbq7** [comment]
Probably a similar issue to https://github.com/mrjbq7/ta-lib/issues/151 and https://github.com/mrjbq7/ta-lib/issues/157, where the underlying prices are "too small".  The underlying TA-Lib C library has a "zero" concept that treats numbers "close to zero" as "zero". 

You can sometimes get around this by adjusting the price stream before and after the call to the indicator, something like this:

https://github.com/mrjbq7/ta-lib/issues/157#issuecomment-335255783

**Comment by Elyasnz** [comment]
if you're still struggling with this issue take a look at this [comment](https://github.com/TA-Lib/ta-lib-python/issues/594#issuecomment-1560640283)
