### ISSUE TITLE
Way for adding all Indicators at once

### ISSUE THREAD

**Issue by Kalelv45** [mrjbq7/ta-lib#231]
Hi, I use this library for stock indicators. 

https://github.com/bukosabino/ta

it is pretty similar but it has less indicators. 

One cool features it has is to have the possibility to add all the indicators at once. 
there is such a option in Ta-lib?

Kind Regards

**Comment by mrjbq7** [comment]
How do you parameterize “all indicators”? Seems like that could mean 100 indicators or 100,000.
