### ISSUE TITLE
talib.rsi() error!

### ISSUE THREAD

**Issue by happytaoer** [mrjbq7/ta-lib#234]
My trader bot use talib to trade btc..   when candle value is so low  like 0.00000012, talib.rsi() will return  empty!  if value * 100 ,it return ok

**Comment by fmichaud** [comment]
Hello @happytaoer,

You should see comment [comment](https://github.com/mrjbq7/ta-lib/issues/157#issuecomment-367329661) by [Domenico Silletti](https://github.com/dsilletti) related to small numbers.

If you're interested, you could use this [Docker image for Python TA-Lib wrapper](https://github.com/9fevrier/docker-python-ta-lib).

I hope I have been helpful,

Regards from Paris

**Comment by happytaoer** [comment]
Thanks man!
