### ISSUE TITLE
Cannot /bin/mkdir: cannot create directory `/usr/local/include': Permission denied

### ISSUE THREAD

**Issue by MaximusIndus** [mrjbq7/ta-lib#240]
Hi,
I am trying to install ta-lib 0.4.0 on Godaddy Deluxe Linux server (I think it is CentOS).
I have -
- Downloaded the tar file (ta-lib-0.4.0-src.tar.gz)
- untar-ed it, ran ./configure.
- ran make
- ran make clean
- ran make install ==> here is when i get an error at the end. As pasted below.

- [ ] plz note the "**Permission Denied**". I think it is because it is on a shared hosting and absolute root access is not permitted.

by the way **any version of TA-Lib0.4.1x is totally out of the question for installation for they give a gcc failure with error 1** but while configure command ---> it clearly shows the below code

**checking for gcc... gcc**
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
**checking whether gcc accepts -g... yes**
**checking for gcc option to accept ISO C89... none needed**
checking for style of include used by make... GNU
**checking dependency style of gcc... gcc3**

Any help would be appreciated.

===========================
ranlib .libs/libta_abstract_gc.a
creating libta_abstract_gc.la
(cd .libs && rm -f libta_abstract_gc.la && ln -s ../libta_abstract_gc.la libta_abstract_gc.la)
make[3]: Entering directory `/home/fzutljptf41p/Python3/ta-lib/src/ta_abstract'
make[3]: Nothing to be done for `install-exec-am'.
test -z "/usr/local/include/ta-lib/" || /bin/mkdir -p "/usr/local/include/ta-lib/"
**/bin/mkdir: cannot create directory `/usr/local/include': Permission denied**
make[3]: *** [install-libta_abstractHEADERS] Error 1
make[3]: Leaving directory `/home/fzutljptf41p/Python3/ta-lib/src/ta_abstract'
make[2]: *** [install-am] Error 2
make[2]: Leaving directory `/home/fzutljptf41p/Python3/ta-lib/src/ta_abstract'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/home/fzutljptf41p/Python3/ta-lib/src'
make: *** [install-recursive] Error 1

**Comment by mrjbq7** [comment]
This is not the TA-Lib C library project, only a Python wrapper for it.

**Comment by mrjbq7** [comment]
One suggestion might be:

If it's looking for ``/usr/local/include`` thats because it's trying to install there by default and the directory doesn't yet exist.

You could try ``./configure --prefix=/usr`` to install to ``/usr/include`` instead.

Or you could run with ``sudo make install`` which probably would create those directories.

Or you could make those directories yourself then run ``make install``...

**Comment by MaximusIndus** [comment]
Thanks @mrjbq7.

This issue is resolved. 
>>> HOW
[Its all in the ./configure command]
**_For Shared Hosting sites_** like Godaddy

1. If you go to the root (i.e. cd /) you could see /usr and /usr/include. However they are NOT under your control but, as in this case, under Godaddy's control.
2. You cannot change the folder or file permissions there. Hence you get a "Permission Denied"  error while creating the folders and files.
3. Therefore, when you are in _cd /_ you could navigate to cd /home, _cd_ to  your root user_name and choose a folder within it or creat a new one (as in my case  'ta-lib'). **Copy this path and use it post** _--prefix= 
example:  **./configure --prefix= /home/cPanelAdminName/ta-lib**

The process will run without a glitch, but you may still have a few warnings.

Hope this helps a wider audience.

Best Regards,
Maxinus Indus

**Comment by MaximusIndus** [comment]
The issue I am facing now is in answering the question-
1. Where does the execution of 'python3 setup.py install" **look for** ta-lib library? (i am trying to install TA-Lib-0.4.17)
as i get _setup.py:79: UserWarning: Cannot find ta-lib library, installation may fail.
  warnings.warn('Cannot find ta-lib library, installation may fail.')_
2. talib was well installed as per my above response.

Regards,
Maximus Indus

**Comment by mrjbq7** [comment]
It's not really documented, and it should be, but if you install with ``./configure --prefix=$PREFIX``, then when you go to install this python wrapper you can specify additional search paths to find the library and include files for the ``TA-Lib`` C library:

```sh
$ export TA_LIBRARY_PATH=$PREFIX/lib
$ export TA_INCLUDE_PATH=$PREFIX/include
$ python setup.py install # or pip install ta-lib
```

**Comment by MaximusIndus** [comment]
Hey @mrjbq7,

I get you. But what i am more confused about is the ./configure command than ever.... _what is expected of the user?_ it just seems to be a spiral... sorry for my pun, but its frustrating.

Regards,
Maximus

**Comment by mrjbq7** [comment]
You might find this link useful to learn more about how the ``./configure; make; make install`` "installation" process works.

https://robots.thoughtbot.com/the-magic-behind-configure-make-make-install

Part of the problem seems to be the environment you are operating in requires you to install software in particular (possible unusual) locations.  You then need to tell other software that depends on that (like this TA-Lib python wrapper) where that unusual location is.  In the normal cases of ``/usr``, ``/usr/local`` (or even ``/opt``), this would not be required since we have a list of typical locations we search from.  I'm not sure there is a convention for where to look for a "home directory installation".

I agree that a "pure python" technical analysis library would be great, and there are a few around of varying performance and code quality.  I've implemented a bunch of indicators similarly, but have not really packaged them up and open-sourced them.

It's unclear to me what your main complaint is, but I wish I could be of more help.  Good luck!

**Comment by MaximusIndus** [comment]
Hi @mrjbq7,

Outright - I have and will continue to appreciate your efforts; they are commentable without doubt.

Me, as a learner and as an inquisitive coder, I find it difficult to _grasp_ the peculiar locations. The Library works to perfection locally. But as soon as you go to **_Shared Hosting_** everything comes crashing down - please google.
Now please allow me to address the points you raised -
* Part of the problem seems to be the environment you are operating in requires you to install software in particular (possible unusual) locations
  * No shared hosting website (e.g. Godaddy) will give you rights to change there core setup. Hence, the add-on I or anyone installs need to be flexible enough to accommodate. Which TA-Lib isn't... therefore only for single machine or Corporates to copy and paste using their army of coders. Doesn't help my cause of moving code to a shared server.
* You then need to tell other software that depends on that (like this TA-Lib python wrapper) where that unusual location is.

**Comment by mrjbq7** [comment]
I fail to understand how "TA-Lib isn't [flexible enough to accommodate]".  I think I provided answers to how you can install to custom locations.

Also, this project isn't an "overlay".  It's just a python wrapper for a C library that should already be installed separately (that I did not write and do not support).  Although, I do try and help people out like yourself when there are various issues.

Regarding pure Python indicators, you might find these links useful:

* https://github.com/bukosabino/ta

* https://github.com/peerchemist/finta

* https://github.com/kylejusticemagnuson/pyti

* https://www.quantopian.com/posts/technical-analysis-indicators-without-talib-code

**Comment by MaximusIndus** [comment]
HI @mrjbq7 ,

we may be trying to hit the same nail from two opposite ends here. BUt, that's alright, at the least for me. I am sure of the google search stats on any or all the questions you have raised yourself.

My proposal is to take it a step ahead.

Would you agree?

**Comment by MaximusIndus** [comment]
> I fail to understand how "TA-Lib isn't [flexible enough to accommodate]". I think I provided answers to how you can install to custom locations.
> 
> Also, this project isn't an "overlay". It's just a python wrapper for a C library that should already be installed separately (that I did not write and do not support). Although, I do try and help people out like yourself when there are various issues.
> 
> Regarding pure Python indicators, you might find these links useful:
> 
> * https://github.com/bukosabino/ta
> * https://github.com/peerchemist/finta
> * https://github.com/kylejusticemagnuson/pyti
> * https://www.quantopian.com/posts/technical-analysis-indicators-without-talib-code

'Overlay' - When you have an underlying requirement for the other "thing" to work... it is similar to **laying** the foundations of a building. Therefore, the _0.4.0_ is an _underling requirement_ for an _OVERLAY_ of **0.4.17**
