### ISSUE TITLE
How to call TA_SetCompatibility?

### ISSUE THREAD

**Issue by wukan1986** [mrjbq7/ta-lib#244]
Hi,
   I find EMA has two algorithms

    * TA_MA_CLASSIC:
    *    Use a simple MA of the first 'period'.
    *    This is the approach most widely documented.
    *
    * TA_MA_METASTOCK:
    *    Use first price bar value as a seed
    *    from the begining of all the available
    *    data.

    https://github.com/TA-Lib/ta-lib/search?q=TA_GLOBALS_COMPATIBILITY

   If i can set TA_MA_METASTOCK, it will return what i expected.

**Comment by mrjbq7** [comment]
I just added (hopefully) support for this in f71686450702adf5f980f162dc1c419283a20356.

You should be able to:

```python
import talib as ta

print ta.get_compatibility() # DEFAULT == 0

ta.set_compatibility(1) # METASTOCK == 1

print ta.get_compatibility()
```

If it works for you, we can maybe make some nicer constants?

**Comment by wukan1986** [comment]
@mrjbq7  Great Job! Thank you very much!
