### ISSUE TITLE
Crossovers - Is there any function to identify them?

### ISSUE THREAD

**Issue by ramkumarkr** [mrjbq7/ta-lib#245]
I am trying to build signals based on crossover (For eg. +DI over -DI, EMA5 over 13 etc). Using ta-lib I can compute all the indicators, but wondering what is the easiest way to check crossovers? I would assume some function should exist, but couldn't find any in the ta-lib documentation. 

Am I missing something?

**Comment by mrjbq7** [comment]
I don't believe thats included out of the box, but presumably you can use ``numpy`` or ``pandas`` routines to look for crossovers.

**Comment by ramkumarkr** [comment]
> I don't believe thats included out of the box, but presumably you can use `numpy` or `pandas` routines to look for crossovers.
Thanks for confirming that nothing out of the box. Now off to solving that custom!
