### ISSUE TITLE
BV

### ISSUE THREAD

**Issue by Lucifer-Morning-Star** [mrjbq7/ta-lib#246]
Does it have "Moving Accumulation/ Distribution Volume（BV）" Index? If not, would the API be made in the future?

**Comment by mrjbq7** [comment]
Is that the same as ``On Balance Volume`` (OBV)?

What's the formula you're looking for? Got a link?

If it's not available, I would have no plans because this is a lightweight wrapper around the C library that I do not maintain.

**Comment by Lucifer-Morning-Star** [comment]
All right. I don't think it is OBV. BV is an index which could analyse the distribution of the players'  holding costs.
However, thanks for your answer.
