### ISSUE TITLE
Candlestick Pattern EveningStar Incorrect.

### ISSUE THREAD

**Issue by nerfherder1** [mrjbq7/ta-lib#247]
Looking at evening star and it appears to be incorrect.  Is this actually considered an evening star because this is engulfing the previous bar.

https://www.tradingview.com/chart/d3hZBVEd/
![image](https://user-images.githubusercontent.com/5192578/50355471-a9018280-0503-11e9-84d4-e77e780107a2.png)

```

date            2018-12-18 18:00:00         ...           2018-12-21 13:30:00
open                        0.33412         ...                       0.37355
high                        0.33432         ...                         0.374
low                         0.33058         ...                        0.3685
close                       0.33131         ...                       0.36913
volume                  1.10374e+06         ...                    2.2748e+06
epoch                   1.54516e+12         ...                    1.5454e+12
date            2018-12-18 18:00:00         ...           2018-12-21 13:30:00
CDLEVENINGSTAR                 -100         ...                          -100

Code Snippet
    Evening = FetchedData.loc[FetchedData['CDLEVENINGSTAR'] == -100]
    print(Evening.T)
```

**Comment by nerfherder1** [comment]
Here is the full code to reproduce
```
def binance_data(symbol='XRP/USDT',timeframe='15m'):
    exchange = 'binance'
    print("\n")
    print("STARTING BINANCE at {} and {}".format(symbol,timeframe))
    binance = ccxt.binance()
    binance.load_markets()
    pulled = False  # Defaults as false - Forces loop until successful pull from Kraken
    while not pulled:
        try:
            ########### PULL HISTORICAL DATA FROM EXCHANGE API ####################################
            ohlcv = pd.DataFrame(binance.fetch_ohlcv(symbol=symbol, timeframe=timeframe))
            print("Pulled Data Successfully! \n")
            ########### END - PULL HISTORICAL DATA FROM EXCHANGE API ##############################
            pulled = True  # Exit while loop
        except Exception:  # If Pull fails it will loop back to top
            print("PULL ERROR | {} : Could not pull {} dataframe from {} at {}".format(inspect.stack()[0][3],
                                                                                       symbol,
                                                                                       inspect.stack()[0][3],
                                                                                       timeframe))
            print("Will try again ... ")
            time.sleep(3)
            pass
    print("CHECKING NEW ENTRIES....\n")
    ########### APPEND DATAFRAME ENTRIES TO CSV ###################################
    FetchedData = pd.DataFrame(ohlcv.values, columns=["date", "open", "high", "low", "close", "volume"])
    FetchedData['epoch'] = FetchedData['date']

    FetchedData.reindex(columns=["date", "epoch","open", "high", "low", "close", "volume"])
    FetchedData['date'] = pd.to_datetime(FetchedData['date'], unit='ms')
    #FetchedData['date'] = FetchedData['date'].dt.tz_localize('utc').dt.tz_convert('US/Pacific')

    #AppendNewData = FetchedData
    FetchedData.set_index('date', inplace=True)
    FetchedData['date'] = FetchedData.index
    print(FetchedData.head(n=1))
    open = FetchedData['open']
    high = FetchedData['high']
    low = FetchedData['low']
    close = FetchedData['close']
    index = FetchedData.index
    FetchedData['CDLEVENINGSTAR'] = talib.CDLEVENINGSTAR(open,high,low,close)
    for x in FetchedData['CDLEVENINGSTAR']:
        if x != 0:

            print(x)
    Evening = FetchedData.loc[FetchedData['CDLEVENINGSTAR'] == -100]
    print(Evening.T)
```

**Comment by npatwa** [comment]
> 
> 
> Looking at evening star and it appears to be incorrect. Is this actually considered an evening star because this is engulfing the previous bar.
> 
> https://www.tradingview.com/chart/d3hZBVEd/
> ![image](https://user-images.githubusercontent.com/5192578/50355471-a9018280-0503-11e9-84d4-e77e780107a2.png)
> 
> ```
> 
> date            2018-12-18 18:00:00         ...           2018-12-21 13:30:00
> open                        0.33412         ...                       0.37355
> high                        0.33432         ...                         0.374
> low                         0.33058         ...                        0.3685
> close                       0.33131         ...                       0.36913
> volume                  1.10374e+06         ...                    2.2748e+06
> epoch                   1.54516e+12         ...                    1.5454e+12
> date            2018-12-18 18:00:00         ...           2018-12-21 13:30:00
> CDLEVENINGSTAR                 -100         ...                          -100
> 
> Code Snippet
>     Evening = FetchedData.loc[FetchedData['CDLEVENINGSTAR'] == -100]
>     print(Evening.T)
> ```

**Comment by npatwa** [comment]
https://stockcharts.com/school/doku.php?id=chart_school:chart_analysis:candlestick_pattern_dictionary#evening_star

The pattern you describe is an evening star as per the link above since the 3rd candle should close below the midpoint of the 1st candle

**Comment by nerfherder1** [comment]
Hey thanks.  That does clear it up.  I was considering the middle elevated candlestick from your link as the evening star.  My misunderstanding.  Thank you.
