### ISSUE TITLE
Got error  "has incorrect type (expected numpy.ndarray, got DataFrame)"

### ISSUE THREAD

**Issue by AlexBThomsen** [mrjbq7/ta-lib#249]
Hi,

I'm new to ta-lib and tried to use RSI on a pandas dataframe. I got the error 

TypeError                                 Traceback (most recent call last)
<ipython-input-51-89c8229bcd8a> in <module>()
      1 
----> 2 real = rsi(inputs, timeperiod=14)

talib/_abstract.pxi in talib._ta_lib.Function.__call__()

talib/_abstract.pxi in talib._ta_lib.Function.__call_function()

/anaconda3/lib/python3.6/site-packages/talib/__init__.py in wrapper(*args, **kwargs)
     22             except StopIteration:
     23                 # No pandas.Series passed in; short-circuit
---> 24                 return func(*args, **kwargs)
     25 
     26             # Use Series' float64 values if pandas, else use values as passed

TypeError: Argument 'real' has incorrect type (expected numpy.ndarray, got DataFrame)

**Code**

      #RSI
      import talib.abstract as ta

      inputs = {
            'close': df1
      }

      rsi = abstract.RSI

      real = rsi(inputs, timeperiod=14)

**Comment by mrjbq7** [comment]
What is ``df1``?  I assume a ``pandas.DataFrame``? That's not how ``inputs`` is intended to be used -- it's either a ``dict`` of columns to ``numpy.ndarray`` or ``pandas.Series``, or it's a ``pandas.DataFrame`` with columns that match the expected input names (e.g., "open", "close", "volume", etc.).

**Comment by AlexBThomsen** [comment]
ah of course! solved it with:

df_ta = pandas.DataFrame(data = df1, dtype=numpy.float64)
df_ta.apply(lambda c: talib.RSI(c, timeperiod = 14))

cheers.

**Comment by usaee** [comment]
I had a similar problem where I was getting this error message:

"TypeError: Argument has incorrect type (expected numpy.ndarray, got Series)"

####################################################################
# My Solution
####################################################################

import pandas as pd

dataframe = some_dataframe
print(type(dataframe))
>> <class 'pandas.core.frame.DataFrame'>

series = pd.Series(dataframe)
print(type(series)) 
>> <class 'pandas.core.series.Series'>

dataframe = series.to_numpy()
print(type(dataframe))
>> <class 'numpy.ndarray'>

# Now using the variable "dataframe" should make things work

**Comment by alizain5693** [comment]
i'm getting a similar error with CDLHANGINGMAN. 

expected numpy.ndarray got numpy.float64.

but the above fixes didn't work. I'm using it with another backtesting.py library which keeps data as an array. any ideas appreciated.

**Comment by otis-zeny** [comment]
hi guys can anyone help me, im constantly getting that error

data = talib.RSI(close,timeperiod=15)[-1]
TypeError: Argument 'real' has incorrect type (expected numpy.ndarray, got list)

**Comment by mrjbq7** [comment]
“close” should be a numpy.ndarray, not a list.

**Comment by otis-zeny** [comment]
Okay thank you very much but could you please give me a simple example of how I should do it, I've Been doing it for a week and still nothing, example would be truly appreciated.

**Comment by mrjbq7** [comment]
```python
close = numpy.array(close, dtype=float)
data = talib.RSI(close, timeperiod=15)[-1]
```

**Comment by otis-zeny** [comment]
close = numpy.array(close, dtype=float)
    data = talib.RSI(close,timeperiod=15)[-1]

 close = numpy.array(close, dtype=float)
TypeError: float() argument must be a string or a number, not 'dict'


this the response im getting

**Comment by mrjbq7** [comment]
What is “close”? A dict?

**Comment by otis-zeny** [comment]
Okay is the candles I want to receive, I want to receive the information of the close candles instead of the opening, min, max and volume, so basically we can replace close with candles. Open, close, min, max, volume= API.get_candles(eurusd,60,10,time_from_end)Basically I'm trying to make a trading bot for iqoption.com using rsi as a decision maker. So if I'm am then to say :Real= talib.RSI(close,timeperiod=14)[-1]And if I am to print(real) I get and type errorT. D-------- Original message --------From: John Benediktsson ***@***.***>Date: Wed, 22 Sep 2021, 15:59To: mrjbq7/ta-lib ***@***.***>Cc: otis-zeny ***@***.***>, Comment ***@***.***>Subject: Re: [mrjbq7/ta-lib] Got error  "has incorrect type (expected numpy.ndarray, got DataFrame)" (#249)

What is “close”? A dict?

**Comment by mrjbq7** [comment]
If you want to call ``talib.RSI``, it needs a ``numpy.ndarray`` of numbers -- you can make that from a ``list`` using the example I showed earlier.  If your data is a ``dict``, then perhaps you should print it out and see where the closing prices are and extract them before calling into ``talib``?

**Comment by otis-zeny** [comment]
Okay, it's numbers that I'm calling. Let me see what can do, hopefully it works. Thank you very much for the assistance. T. D-------- Original message --------From: John Benediktsson ***@***.***>Date: Thu, 23 Sep 2021, 04:49To: mrjbq7/ta-lib ***@***.***>Cc: otis-zeny ***@***.***>, Comment ***@***.***>Subject: Re: [mrjbq7/ta-lib] Got error  "has incorrect type (expected numpy.ndarray, got DataFrame)" (#249)
If you want to call talib.RSI, it needs a numpy.ndarray of numbers -- you can make that from a list using the example I showed earlier.  If your data is a dict, then perhaps you should print it out and see where the closing prices are and extract them before calling into talib?
