### ISSUE TITLE
how does the LINEARREG function works ?

### ISSUE THREAD

**Issue by Schrominger** [mrjbq7/ta-lib#251]
Hi~
I'm using talib in python to learn some technical indicators, thanks for these function wrappers.
But I cannot understand how to use the linear regression function, it only accept one array! 
`real = LINEARREG(close, timeperiod=14)`
 In doing linear regression it actually need two arrays (x, y) such as in scikit-learn or scipy. suppose I want to do regression between close and return, what should i do ?

**Comment by Schrominger** [comment]
I found the link [https://sourceforge.net/p/ta-lib/code/HEAD/tree/trunk/ta-lib/c/src/ta_func/ta_LINEARREG.c#l238](https://sourceforge.net/p/ta-lib/code/HEAD/tree/trunk/ta-lib/c/src/ta_func/ta_LINEARREG.c#l238) 
, so I know how LINEARREG works, but what if I want to regress between two arrays which is disorded ? 
>    /* Insert TA function code here. */
   /* Linear Regression is a concept also known as the
    * "least squares method" or "best fit." Linear
    * Regression attempts to fit a straight line between
    * several data points in such a way that distance
    * between each data point and the line is minimized.
    *
    * For each point, a straight line over the specified
    * previous bar period is determined in terms
    * of y = b + m*x:
    *
    * TA_LINEARREG          : Returns b+m*(period-1)
    * TA_LINEARREG_SLOPE    : Returns 'm'
    * TA_LINEARREG_ANGLE    : Returns 'm' in degree.
    * TA_LINEARREG_INTERCEPT: Returns 'b'
    * TA_TSF                : Returns b+m*(period)
    */

**Comment by mrjbq7** [comment]
You can use other numerical libraries for that.  This python project just wraps the available functionality in the underlying TA-Lib project.
