### ISSUE TITLE
Where can I get logical description of pattern recognise function

### ISSUE THREAD

**Issue by xiaoxiaoyaozi** [mrjbq7/ta-lib#256]
Hi, I can calculate all the pattern recognise indicator, but I want to know the logical description behind it. For example some paper will have detail description to its pattern construction methods like this "A Fractal must have two preceding and two following bars with lower highs (higher lows in a down move). In a buy Fractal, we are interested only in the bars’ high. In a sell Fractal, we are interests only in the bars’ low” (Williams, B. M., Williams, J. G. 2004). Can you provide this or can you enlight me where I can get his information?
Have a nice day :)

**Comment by mrjbq7** [comment]
As far as I can tell, the most specific documentation are the code functions themselves.   You can see, for example the logic in ``CDLHAMMER``:

https://github.com/TA-Lib/ta-lib/blob/master/src/ta_func/ta_CDLHAMMER.c#L239

It's not my project, I only support this wrapper for the underlying C library, but I can help with some specific guidance sometimes if people have questions.
