### ISSUE TITLE
what does the "CDL*" mean?

### ISSUE THREAD

**Issue by jackeylu** [mrjbq7/ta-lib#257]
Hello, anybody knows why the pattern recognition functions are all started with "CDL"? I can't find any explaination about it  from http://www.tadoc.org/index.htm

**Comment by pcawthron** [comment]
They’re the indicators that identify Candle patterns i.e. CDLHAMMER identifies the Hammer pattern. 

 

See https://www.ig.com/uk/trading-strategies/16-candlestick-patterns-every-trader-should-know-180615 for the briefest of introductions or try to find the PDF online of ‘Encyclopaedia of Candlestick Charts’ by Thomas N. Bulkowski which is a good 900 page reference.

 

Regards,

 

Peter

**Comment by jackeylu** [comment]
Thank you very much. CDL is short for CanDLe.
