### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by dindom999** [mrjbq7/ta-lib#260]
**try many times, but fail . what can I do?**
```
gcc -pthread -shared -B /home/stock/anaconda3/compiler_compat -L/home/stock/anaconda3/lib -Wl,-rpath=/home/stock/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/talib/_ta_lib.o -L/usr/lib -L/usr/local/lib -L/usr/lib64 -L/usr/local/lib64 -L/opt/lib -L/opt/local/lib -L/usr/lib -Wl,-R/usr/lib -lta_lib -o build/lib.linux-x86_64-3.7/talib/_ta_lib.cpython-37m-x86_64-linux-gnu.so
/home/stock/anaconda3/compiler_compat/ld: build/temp.linux-x86_64-3.7/talib/_ta_lib.o: unable to initialize decompress status for section .debug_info
/home/stock/anaconda3/compiler_compat/ld: build/temp.linux-x86_64-3.7/talib/_ta_lib.o: unable to initialize decompress status for section .debug_info
/home/stock/anaconda3/compiler_compat/ld: build/temp.linux-x86_64-3.7/talib/_ta_lib.o: unable to initialize decompress status for section .debug_info
/home/stock/anaconda3/compiler_compat/ld: build/temp.linux-x86_64-3.7/talib/_ta_lib.o: unable to initialize decompress status for section .debug_info
build/temp.linux-x86_64-3.7/talib/_ta_lib.o: file not recognized: file format not recognized
collect2: 错误：ld 返回 1
error: command 'gcc' failed with exit status 1
```

```
ll /usr/include/ta-lib
-rw-r--r--   1 root root 1.9K [2019-04-19 17:53] ta_libc.h
drwxr-xr-x   2 root root 4.0K [2019-04-19 17:53] ./
-rw-r--r--   1 root root 4.7K [2019-04-19 17:53] ta_common.h
-rw-r--r--   1 root root  13K [2019-04-19 17:53] ta_defs.h
-rw-r--r--   1 root root  20K [2019-04-19 17:53] ta_abstract.h
drwxr-xr-x 447 root root  36K [2019-04-19 17:31] ../
-rw-r--r--   1 root root 177K [2019-04-19 17:53] ta_func.h
```

```
ll /usr/lib/libta_lib.*
lrwxrwxrwx 1 root root   18 [2019-04-19 17:53] /usr/lib/libta_lib.so.0 -> libta_lib.so.0.0.0*
lrwxrwxrwx 1 root root   18 [2019-04-19 17:53] /usr/lib/libta_lib.so -> libta_lib.so.0.0.0*
-rwxr-xr-x 1 root root  831 [2019-04-19 17:53] /usr/lib/libta_lib.la*
-rwxr-xr-x 1 root root 3.0M [2019-04-19 17:53] /usr/lib/libta_lib.so.0.0.0*
-rw-r--r-- 1 root root 3.6M [2019-04-19 17:53] /usr/lib/libta_lib.a

```

**Comment by mrjbq7** [comment]
Are you doing pip install ta-lib?

**Comment by dindom999** [comment]
both pip install and git clone this repo then python setup.py install

**Comment by dindom999** [comment]
the problem happend when I install on archlinux, It works fine in ubuntu/kail

**Comment by kpatel28** [comment]
I'm on Arch and I have the same issue when trying to install TA-Lib

**Comment by dindom999** [comment]
@kpatel28 @mrjbq7 please update me if there is a solution to install on Arch, thanks!

**Comment by kpatel28** [comment]
Seems like there is a bug with binutils version 2.32 on arch. I was able to solve my problem with building the wheel by downgrading binutils to version 2.30:

`sudo pacman -U https://archive.archlinux.org/packages/b/binutils/binutils-2.30-5-x86_64.pkg.tar.xz`

More information about this here: https://bbs.archlinux.org/viewtopic.php?id=242682

I don't like to solve install issues by downgrading packages, hopefully the binutils issue will get fixed so I can reupgrade to an up to date version.

**Comment by kpatel28** [comment]
You can add the following to your shell login initialization (.bashrc for me) to prevent accidentally upgrading your binutils. This is assuming you generally use pacman or yay and always sync packaged with the -Syu option, change as necessary. I like this solution more than editing config files in /etc/ or whatever because it'll be easy to remember to change it back once binutils is fixed:

```
echo 'adding aliases to ignore binutils upgrade 2.30 >2.32';
pacman() { if [ "$@" == "-Syu" ]; then command pacman -Syu --ignore=binutils; else command pacman "$@"; fi; }
yay() { if [ "$@" == "-Syu" ]; then command yay -Syu --ignore=binutils; else command yay "$@"; fi; }
```

**Comment by dindom999** [comment]
@kpatel28 it works!,thanks a lot!

**Comment by kpatel28** [comment]
@dindom999 My original solution to ignoring the binutils upgrade wasn't as robust as it could be (trying to improve my bash), I thought I'd share an improved version with you. This will work for any '-S' subcommand and any arguments (package names) after -S / -Syu /etc. If you used my orignal functions you should replace them with this:
```
echo 'adding aliases to ignore binutils upgrade 2.30->2.32';
pacman() { if [[ "${1:0:2}" == "-S" ]] ; then command pacman "$1" --ignore=binutils "${@:2}"; else command pacman "$@"; fi; }
yay() { if [[ "${1:0:2}" == "-S" ]] ; then command yay "$1" --ignore=binutils "${@:2}"; else command yay "$@"; fi; }
```

**Comment by oblitum** [comment]
Also using Arch here. I have similar problem, but [as pointed in the ArchLinux forum](https://github.com/mrjbq7/ta-lib/issues/260#issuecomment-497979665), downgrading `pacman` packages doesn't sound about right. The issue lies in mixing conda environment with system environment.

What I did instead was to install `binutils` from `conda` (`conda install binutils_linux-64=2.31.1` for my case) and put its binaries location at the head of my $PATH (`export PATH=$HOME/.pyenv/versions/miniconda3-latest/envs/waveglow/x86_64-conda_cos6-linux-gnu/bin:$PATH` for my case).

Also, regarding avoiding pacman package upgrades, you generally simply list them in the ignore list on `/etc/pacman.conf`.

**Comment by kpatel28** [comment]
@oblitum Thanks for the explanation. It seems like binutils should be a build dependency for ta-lib, that way conda would download it and use it's own version instead of looking for it on the path.

**Comment by oblitum** [comment]
@kpatel28 I'm not sure either, I did that because `pip`, even inside `conda` environment, won't consider conda binutils binaries and pick them from my system. I had to use plain `pip` inside `conda` to install [apex](https://github.com/NVIDIA/apex/issues/280) actually.

**Comment by oblitum** [comment]
@kpatel28 Conda actually make the binaries available when inside the environment, but with different names like, `x86_64-conda_cos6-linux-gnu-ld`, and set `$LD`, etc variables accordingly.

https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html

So, compilation of custom package needs to take advantage of tools variables, if not, then you're forced to fix `$PATH`, etc, for them.

**Comment by Single430** [comment]
mark
