### ISSUE TITLE
Build the Library nmake

### ISSUE THREAD

**Issue by Jens1989** [mrjbq7/ta-lib#263]
Hi,

I've done the following steps:

- Download and Unzip ta-lib-0.4.0-msvc.zip
- Move the Unzipped Folder ta-lib to C:\
- Download and Install Visual Studio Community 2015
- Remember to Select [Visual C++] Feature
- Build TA-Lib Library
- From Windows Start Menu, Start [VS2015 x64 Native Tools Command Prompt]
- Move to C:\ta-lib\c\make\cdr\win32\msvc

I've got a problem with the last step:

- Build the Library nmake

I've just typed in NMAKE 

and I'm getting :

'NMAKE' is not recognized as an internal or external command,
operable program or batch file.

I can't figure out what's meant by "build a library"

thanks

**Comment by mrjbq7** [comment]
Typically that "native tools command prompt" would allow ``nmake`` to work.

Another idea is try running ``vsvars32.bat`` or ``vsdevcmd.bat``:

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/how-to-set-environment-variables-for-the-visual-studio-command-line

**Comment by mrjbq7** [comment]
(I don't generally support the underlying TA-Lib library, but if you have a follow up question, please post it.  Closing the bug for now).
