### ISSUE TITLE
Pycharm Import problem

### ISSUE THREAD

**Issue by chilli1234d** [mrjbq7/ta-lib#264]
Hello I am new to python and Pycharm as well. 

I have installed TA-lib in my computer as they shown on both conda list and pip list and I want to use it on Pycharm.  

C:\Windows\System32>pip list
Package                            Version
---------------------------------- --------
...
statsmodels                        0.9.0
sympy                              1.3
**TA-Lib                             0.4.17**
tables                             3.5.1
...

Since I cannot install the package through Pycharm's Project Interpreter, I moved the files
(TA_Lib-0.4.17.dist-info and talib)

from 
C:\Users\my_user_name\Anaconda3\Lib\site-packages
to 
C:\Users\my_user_name\PycharmProjects\program trade\venv\Lib\site-packages

but it still doesn't work. 

The error message shown on Pycharm is 

Traceback (most recent call last):
  File "C:/Users/chiho/PycharmProjects/program trade/talib trial.py", line 1, in <module>
    import talib
  File "C:\Users\chiho\PycharmProjects\program trade\venv\lib\site-packages\talib\__init__.py", line 43, in <module>
    from ._ta_lib import (
ModuleNotFoundError: No module named 'talib._ta_lib'

May I know how to fix this problem? Thanks a lot!

**Comment by andylauxugang2** [comment]
me too thanks

**Comment by mrjbq7** [comment]
Sounds like it didn't install properly.  Most likely the underlying TA-Lib C library wasn't installed first.  Check the installation and troubleshooting section in the README.

**Comment by Lunbi123** [comment]
I can import talib smoothly in the Terminal ,but can't import talib in Pycharm...

**Comment by mrjbq7** [comment]
Sounds like multiple Python interpreters. 

This can happen for example if PyCharm is choosing the Python that shipped with MacOS while you are installing and using the Python that comes from Homebrew.
