### ISSUE TITLE
Successive calls to BBANDS using DataFrame

### ISSUE THREAD

**Issue by pjvalla** [mrjbq7/ta-lib#269]
Getting this error when using ```master``` branch.

Error('The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().'

The test is to execute BBANDS more than once (code below).  The first one works as expected, but the second call fails with the above error.   The data is not changed between calls.

```
bband_df = BBANDS(plot_df, timeperiod=5,  nbdevup=2., nbdevdn=2.)
print("first one")
bband_df = BBANDS(plot_df, timeperiod=5, nbdevup=2., nbdevdn=2.)
print("second one")

```
Code works fine with ```TA_Lib-0.4.17``` tag.

**Comment by mrjbq7** [comment]
Should be fixed by recent changes to Abstract API.  Released 0.4.18 today.
