### ISSUE TITLE
wrong ELF class

### ISSUE THREAD

**Issue by eevleevs** [mrjbq7/ta-lib#273]
I am on a Ubuntu 16.04 x64. 
I have compiled the underlying library from source to x64 with configure / make / make install:

> giulio@vps169893:~$ file /usr/local/lib/libta_lib.so*
> /usr/local/lib/libta_lib.so:       symbolic link to libta_lib.so.0.0.0
> /usr/local/lib/libta_lib.so.0:     symbolic link to libta_lib.so.0.0.0
> /usr/local/lib/libta_lib.so.0.0.0: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=9876f8e0bccded702e9cfcc4c14fc260da8c87ef, not stripped

I have installed the wrapper from pip3, got x64:

> giulio@vps169893:~$ file /usr/local/lib/python3.5/dist-packages/talib/_ta_lib.cpython-35m-x86_64-linux-gnu.so 
> /usr/local/lib/python3.5/dist-packages/talib/_ta_lib.cpython-35m-x86_64-linux-gnu.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=6bbae6a586d186d4f047eb3cb8d035bd3f9de7f8, not stripped
 
But when I try to import the library I get the following:

> import talib
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.5/dist-packages/talib/__init__.py", line 43, in <module>
>     from ._ta_lib import (
> ImportError: libta_lib.so.0: wrong ELF class: ELFCLASS32

Any suggestion?

**Comment by mrjbq7** [comment]
Weird, not sure why it would pickup a 32-bit library like that...

Any chance you have a ``libta_lib.so.0`` somewhere else thats 32-bit?

**Comment by eevleevs** [comment]
You are right, I tried by installing the deb first, and forgot to remove it. Thanks.
