### ISSUE TITLE
Optimizing Rolling Window Indicators

### ISSUE THREAD

**Issue by G8XSU** [mrjbq7/ta-lib#275]
Regarding most of the rolling window indicators for example SMA,

Why isn't the previously calculated SMA Indicator used as an optimization similar to dynamic programming?

For e.g in SMA didn't we only need to exclude the oldest period value in average and include the latest period value to calculate one additional point in SMA ?

I see that most of the indicators are like this. Performance gain by this should be huge.
Am i missing something ?

**Comment by mrjbq7** [comment]
Sure, but this project is just a wrapper for the underlying TA-Lib C library. If that’s a feature it provides, I would be happy to expose it to python. If it’s a new feature request, better to report to upstream project...

**Comment by G8XSU** [comment]
What i am asking about is streaming interface for ta-lib

**Comment by mrjbq7** [comment]
Is that a feature that the underlying TA-Lib supports? If so, I’d be happy to expose it to Python. 

The current “streaming” feature uses the same function calls but computers only one data point. Doing more work, as you say, but I’m not sure if any of those C functions supports a history / cached work speed up.

**Comment by G8XSU** [comment]
> The current “streaming” feature uses the same function calls but computers only one data point.
Computing for only one additional data-point will mean that it is using previously computed result. This is what i was talking about. Is it currently supported ? If so, I think its missing from Readme.md

**Comment by mrjbq7** [comment]
The streaming feature is still beta, but it should probably be documented.

It's not as good as a rolling window that maintains memory for the computation, and does minimal new work when a new data point comes in.  For a 30 period indicator, it's going to look at 30 periods when it could just add the new one in, for some indicators.

**Comment by mrjbq7** [comment]
Maybe you'd be interested in the TA-Lib "real time" fork someone is working on.

https://github.com/mrjbq7/ta-lib/issues/316
