### ISSUE TITLE
unable to install TA-Lib on Linux Mint

### ISSUE THREAD

**Issue by r4VP4** [mrjbq7/ta-lib#282]
When installing TA-Lib on Linux mint i get a lot of errors

` pip3 install TA-Lib`

> talib/_ta_lib.c:66764:15: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
>          __pyx_t_2 = PyArray_GETCONTIGUOUS(__pyx_v_low); if (unlikely(!__pyx_t_2)) __PYX_ERR(2, 5409, __pyx_L1_error)
>                    ^
>     talib/_ta_lib.c:66869:15: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
>          __pyx_t_2 = PyArray_GETCONTIGUOUS(__pyx_v_close); if (unlikely(!__pyx_t_2)) __PYX_ERR(2, 5416, __pyx_L1_error)
>                    ^
>     talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_144CDLSEPARATINGLINES’:
>     talib/_ta_lib.c:67535:15: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
>          __pyx_t_2 = PyArray_GETCONTIGUOUS(__pyx_v_open); if (unlikely(!__pyx_t_2)) __PYX_ERR(2, 5483, __pyx_L1_error)
> ...
>     x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/talib/_ta_lib.o -L/usr/local/lib -L/usr/local/lib64 -L/opt/lib -L/opt/local/lib -lta_lib -o build/lib.linux-x86_64-3.6/talib/_ta_lib.cpython-36m-x86_64-linux-gnu.so
>     /usr/bin/ld: inkompatibles /usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libta_lib.so wird bei der Suche nach -lta_lib übersprungen
>     /usr/bin/ld: inkompatibles /usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libta_lib.a wird bei der Suche nach -lta_lib übersprungen
>     /usr/bin/ld: inkompatibles /usr/lib/../lib/libta_lib.so wird bei der Suche nach -lta_lib übersprungen
>     /usr/bin/ld: inkompatibles /usr/lib/../lib/libta_lib.a wird bei der Suche nach -lta_lib übersprungen
>     /usr/bin/ld: inkompatibles /usr/lib/gcc/x86_64-linux-gnu/7/../../../libta_lib.so wird bei der Suche nach -lta_lib übersprungen
>     /usr/bin/ld: inkompatibles /usr/lib/gcc/x86_64-linux-gnu/7/../../../libta_lib.a wird bei der Suche nach -lta_lib übersprungen
>     /usr/bin/ld: inkompatibles //usr/lib/libta_lib.so wird bei der Suche nach -lta_lib übersprungen
>     /usr/bin/ld: inkompatibles //usr/lib/libta_lib.a wird bei der Suche nach -lta_lib übersprungen
>     /usr/bin/ld: -lta_lib kann nicht gefunden werden
>     collect2: error: ld returned 1 exit status
>     error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: /home/tw/tbot/env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mtmitgoy/TA-Lib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mtmitgoy/TA-Lib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-w92big2f/install-record.txt --single-version-externally-managed --compile --install-headers /home/tw/tbot/env/include/site/python3.6/TA-Lib Check the logs for full command output.
> 

Linux Version:
Linux Mint 19.2 Tina \n \l
4GB RAM
gcc-Version: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

**Comment by mrjbq7** [comment]
What does this mean? I’m mobile and can’t translate easily. It’s probably the main error message:


/usr/bin/ld: inkompatibles /usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libta_lib.so wird bei der Suche nach -lta_lib übersprungen
/usr/bin/ld: inkompatibles /usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libta_lib.a wird bei der Suche nach -lta_lib übersprungen
/usr/bin/ld: inkompatibles /usr/lib/../lib/libta_lib.so wird bei der Suche nach -lta_lib übersprungen
/usr/bin/ld: inkompatibles /usr/lib/../lib/libta_lib.a wird bei der Suche nach -lta_lib übersprungen
/usr/bin/ld: inkompatibles /usr/lib/gcc/x86_64-linux-gnu/7/../../../libta_lib.so wird bei der Suche nach -lta_lib übersprungen
/usr/bin/ld: inkompatibles /usr/lib/gcc/x86_64-linux-gnu/7/../../../libta_lib.a wird bei der Suche nach -lta_lib übersprungen
/usr/bin/ld: inkompatibles //usr/lib/libta_lib.so wird bei der Suche nach -lta_lib übersprungen
/usr/bin/ld: inkompatibles //usr/lib/libta_lib.a wird bei der Suche nach -lta_lib übersprungen
/usr/bin/ld: -lta_lib kann nicht gefunden werden
collect2: error: ld returned 1 exit status
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by r4VP4** [comment]
sorry for the german linux
"wird bei der Suche nach -lta_lib übersprungen"
means
"is skipped in the search for -lta_lib"

"/usr/bin/ld: -lta_lib kann nicht gefunden werden"
means
"/usr/bin/ld: -lta_lib can not be found"

**Comment by mrjbq7** [comment]
You should follow the README instructions to install the TA-Lib C library first, before installing this Python wrapper for it.

**Comment by r4VP4** [comment]
I installed the TA-Lib C library already using the packages from http://www.zwets.com/ta-lib/

**Comment by mrjbq7** [comment]
Does that package call it something else because `ld` in your first post can’t find it.
