### ISSUE TITLE
is there a function to calculate all indicators?

### ISSUE THREAD

**Issue by amanbedi23** [mrjbq7/ta-lib#283]
is there a function to calculate all indicators?

**Comment by mrjbq7** [comment]
To list all the indicators?

What do you mean by calculate?

**Comment by amanbedi23** [comment]
i mean calculate the result values of every indicator. 
right now i have to call each separately. example - 

momentum_adx = talib.ADX(df[high], df[low], df[close], timeperiod=14)
momentum_adxr = talib.ADXR(df[high], df[low], df[close], timeperiod=14)
momentum_apo = talib.APO(df[close], fastperiod=12, slowperiod=26, matype=0)
momentum_aroondown, momentum_aroonup = talib.AROON(df[high], df[low], timeperiod=14)
momentum_aroonosc = talib.AROONOSC(df[high], df[low], timeperiod=14)
momentum_bop = talib.BOP(df[open], df[high], df[low], df[close])
momentum_cci = talib.CCI(df[high], df[low], df[close], timeperiod=14)
momentum_cmo = talib.CMO(df[close], timeperiod=14)
momentum_dx = talib.DX(df[high], df[low], df[close], timeperiod=14)

is there a function that can calculate them all and add to the df?

**Comment by mrjbq7** [comment]
No, but if you'd like to contribute that, it would be nice!

**Comment by amanbedi23** [comment]
i can fund it if there is someone willing to implement it
