### ISSUE TITLE
Really Basic Import Question (cant find indicators)

### ISSUE THREAD

**Issue by tkifelew** [mrjbq7/ta-lib#285]
![image](https://user-images.githubusercontent.com/32316442/69414520-c6b50a00-0cc7-11ea-9d66-61f4613bd0ab.png)
This is all I have in my script, TA-Lib is successfully installed, I am using python 3.7 (32bit) and I have a the C:\ta-lib folder I was supposed to make. It seems like I have the abstract and test_data, test_pandas etc. python scripts but nothing that I want here like indicators. Am I missing something really obvious? Seems like I have the shell of TA-lib but none of the meat thats supposed to come inside (the indicators lol).

Edit: Pycharm is 32bit 2018 and the highlighting says "statement has no effect" I know I should put RSI = lib.RSI([numpyarray]) but it still doesnt work then

**Comment by pcawthron** [comment]
What happens if you try a very simple exanple like?

```
import numpy
import talib
close = numpy.random.random(100)
# Calculate a simple moving average of the close prices:
output = talib.SMA(close)
print(output)
```

which gives something like:

```
[       nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan 0.54478727
 0.54387166 0.53521934 0.52089156 0.50571974 0.52658682 0.5340883
 0.51310594 0.50827556 0.49244875 0.49022145 0.47141577 0.46256018
 0.48826499 0.50355171 0.51746019 0.49385366 0.51018386 0.50679431
 0.51712184 0.50798357 0.51754853 0.52195564 0.53629382 0.53072994
 0.54413696 0.52563306 0.53644387 0.53646842 0.5481691  0.53584606
 0.5060592  0.49702537 0.50920936 0.5185425  0.49885678 0.50105245
 0.49680503 0.50499855 0.52208884 0.50462175 0.51847108 0.51944091
 0.49366931 0.50086712 0.50519488 0.51571691 0.52052862 0.53114892
 0.51119537 0.5285897  0.53052585 0.53979939 0.51874947 0.53113495
 0.52632067 0.53284399 0.54779762 0.52838453 0.52925928 0.52129913
 0.52575091 0.53435343 0.50634807 0.50514726 0.50210404 0.48627739
 0.49799236 0.50389655 0.4912608  0.48592668]
```

**Comment by mrjbq7** [comment]
You have the C library installed in C:/ta-lib?

I don’t understand why you are referencing the test files? Are those in C:/ta-lib? (They shouldn’t be.)

**Comment by tkifelew** [comment]
no those test files are not in my C:/ta-lib folder. **Inside C:/ta-lib is the C library of TA-lib.**

**Comment by tkifelew** [comment]
I went searching today and found this:
https://stackoverflow.com/questions/53751327/python-does-not-import-installed-external-library
I think I have around the same problem

**Comment by tkifelew** [comment]
> What happens if you try a very simple example like:
> 
> ```
> import numpy
> import talib
> close = numpy.random.random(100)
> # Calculate a simple moving average of the close prices:
> output = talib.SMA(close, timeperiod=10)
> print(output)
> ```
> 
> which gives:
> 
> ```
> [       nan        nan        nan        nan        nan        nan
>         nan        nan        nan 0.50848417 0.47785092 0.44339315
>  0.47102626 0.41859054 0.39691306 0.43974262 0.45788087 0.48433092
>  0.44687843 0.48397256 0.44609802 0.43755246 0.45576842 0.55075282
>  0.58838746 0.53383578 0.45677101 0.42787588 0.38490556 0.40440891
>  0.39485276 0.41941931 0.43770451 0.41972255 0.36659764 0.37111059
>  0.40614105 0.460761   0.45705851 0.3865331  0.40859976 0.45957941
>  0.40118349 0.33448226 0.38696792 0.38050275 0.41545451 0.39155694
>  0.39540307 0.46229191 0.48116515 0.39027515 0.37465502 0.43062949
>  0.44422301 0.48778201 0.49602293 0.52011107 0.58894086 0.5297185
>  0.53689661 0.55651049 0.56180553 0.55511134 0.52481007 0.49049417
>  0.50148653 0.49741455 0.49925398 0.55218697 0.56736314 0.6048379
>  0.63301799 0.63692781 0.68262981 0.68735897 0.67514633 0.61799594
>  0.55499522 0.57504391 0.56244354 0.51832063 0.51929071 0.52561207
>  0.44739146 0.47596712 0.49068171 0.52056168 0.52902488 0.49048919
>  0.43432133 0.46015367 0.51851371 0.51418772 0.500098   0.48240597
>  0.47818461 0.51058873 0.5061925  0.46510088]
> `

**Comment by tkifelew** [comment]
I fixed my Issue by deleting all my python installations and redownloading everything in python 3.8. My problem started yielding errors related to visual studio so I just did a clean wipe. Thanks for the help.

**Comment by tkifelew** [comment]
also as a sidenote: all of my indicators are not recognized by pycharm yet they still work. Not sure why but yeah.
