### ISSUE TITLE
CDL3BLACKCROWS doesn't work

### ISSUE THREAD

**Issue by donatienLef** [mrjbq7/ta-lib#286]
Hello ! 
It seems that CDL3BLACKCROWS function doesn't work
I've tried to get some value = 100, on over 10000 points on differents pairs without any result
<img width="670" alt="Screenshot 2019-12-02 at 10 54 32" src="https://user-images.githubusercontent.com/24890926/69949608-272b1f00-14f2-11ea-9dd8-caf39ad25aea.png">

CDL3WHITESOLDIERS works but CDL3BLACKCROWS doesn't
Any advice or same observation?

**Comment by pcawthron** [comment]
There is sample data and code in Issue https://github.com/mrjbq7/ta-lib/issues/250 that shows CDL3BLACKCROWS to be working.

In his 2008 book "Encyclopedia if Candlestick Charts", Thomas N. Bulkowski found this pattern just 2,660 times in 4.7 million candles so it does not occur very frequently.

**Comment by donatienLef** [comment]
Thank you for your great answer @pcawthron !
