### ISSUE TITLE
Statistic Functions Are Missing

### ISSUE THREAD

**Issue by Sinansi** [mrjbq7/ta-lib#288]
Hello,

Statistic functions are missing on your home page (https://github.com/mrjbq7/ta-lib)

Statistic Functions:

BETA - Beta
CORREL - Pearson's Correlation Coefficient (r)
LINEARREG - Linear Regression
LINEARREG_ANGLE - Linear Regression Angle
LINEARREG_INTERCEPT - Linear Regression Intercept
LINEARREG_SLOPE - Linear Regression Slope
STDDEV - Standard Deviation
TSF - Time Series Forecast
VAR - Variance

Thank you!

**Comment by mrjbq7** [comment]
Fixed in b55833092000e5280455ab403f45b4d8b4bb98a7.  

Thanks for pointing that out!
