### ISSUE TITLE
ubuntu 18.04 1core 512M install ta-lib error

### ISSUE THREAD

**Issue by caiqinghua** [mrjbq7/ta-lib#290]
(base) root@xxx:~/ python -m pip install ta-lib
Looking in indexes: http://jp.mirrors.cloud.aliyuncs.com/pypi/simple/
Collecting ta-lib
  Downloading http://jp.mirrors.cloud.aliyuncs.com/pypi/packages/90/05/d4c6a778d7a7de0be366bc4a850b4ffaeac2abad927f95fa8ba6f355a082/TA-Lib-0.4.17.tar.gz (717kB)
     |████████████████████████████████| 727kB 17.8MB/s
Requirement already satisfied: numpy in /root/miniconda3/lib/python3.7/site-packages (from ta-lib) (1.17.4)
Building wheels for collected packages: ta-lib
  Building wheel for ta-lib (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /root/miniconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mqm8urzr/ta-lib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mqm8urzr/ta-lib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-blsmfv5e --python-tag cp37
       cwd: /tmp/pip-install-mqm8urzr/ta-lib/
  Complete output (2800 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/talib
  copying talib/test_data.py -> build/lib.linux-x86_64-3.7/talib
  copying talib/__init__.py -> build/lib.linux-x86_64-3.7/talib
  copying talib/test_abstract.py -> build/lib.linux-x86_64-3.7/talib
  copying talib/abstract.py -> build/lib.linux-x86_64-3.7/talib
  copying talib/test_func.py -> build/lib.linux-x86_64-3.7/talib
  copying talib/stream.py -> build/lib.linux-x86_64-3.7/talib
  copying talib/deprecated.py -> build/lib.linux-x86_64-3.7/talib
  copying talib/test_stream.py -> build/lib.linux-x86_64-3.7/talib
  copying talib/test_pandas.py -> build/lib.linux-x86_64-3.7/talib
  running build_ext
  building 'talib._ta_lib' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/talib
  gcc -pthread -B /root/miniconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/root/miniconda3/lib/python3.7/site-packages/numpy/core/include -I/usr/include -I/usr/local/include -I/opt/include -I/opt/local/include -I/root/miniconda3/include/python3.7m -c talib/_ta_lib.c -o build/temp.linux-x86_64-3.7/talib/_ta_lib.o
  In file included from /root/miniconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1832:0,
                   from /root/miniconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                   from /root/miniconda3/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                   from talib/_ta_lib.c:533:
  /root/miniconda3/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it with " \
    ^~~~~~~
  talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_14ACOS’:
  talib/_ta_lib.c:8328:15: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
       __pyx_t_2 = PyArray_GETCONTIGUOUS(__pyx_v_real); if (unlikely(!__pyx_t_2)) __PYX_ERR(2, 48, __pyx_L1_error)

**Comment by caiqinghua** [comment]
**The problem is solved by change RAM from 512M to 2G.**

python -m pip install ta-lib
Looking in indexes: http://jp.mirrors.cloud.aliyuncs.com/pypi/simple/
Collecting ta-lib
  Downloading http://jp.mirrors.cloud.aliyuncs.com/pypi/packages/90/05/d4c6a778d7a7de0be366bc4a850b4ffaeac2abad927f95fa8ba6f355a082/TA-Lib-0.4.17.tar.gz (717kB)
     |████████████████████████████████| 727kB 18.5MB/s
Requirement already satisfied: numpy in /root/miniconda3/lib/python3.7/site-packages (from ta-lib) (1.17.4)
Building wheels for collected packages: ta-lib
  Building wheel for ta-lib (setup.py) ... done
  Created wheel for ta-lib: filename=TA_Lib-0.4.17-cp37-cp37m-linux_x86_64.whl size=2425278 sha256=3939d17f5102df36886487cce0bc537519449aa5b6e2453370bc9e6435f0763d
  Stored in directory: /root/.cache/pip/wheels/93/6c/c5/bff3d12dbd65f99c322868a8c1f1748b019bd569ce0aeb08a0
Successfully built ta-lib
Installing collected packages: ta-lib
Successfully installed ta-lib-0.4.17

**Comment by caiqinghua** [comment]
https://github.com/mrjbq7/ta-lib/issues/133
You need more RAM. On my VPS with RAM: 512 MB, I got the same error.
On my second VPS with 2GB RAM - No errors.

RAM was indeed the problem. I was on a DigitalOcean Droplet with 1GB or RAM and kept running into the repeated error below, I bumped up the RAM to 2GB and error is gone.talib/_ta_lib.c:208671:15: warning: assignment from incompatible pointer type [enabled by default]
--

**Comment by SteWolk** [comment]
> #133 You need more RAM. On my VPS with RAM: 512 MB, I got the same error. On my second VPS with 2GB RAM - No errors.
> ## RAM was indeed the problem. I was on a DigitalOcean Droplet with 1GB or RAM and kept running into the repeated error below, I bumped up the RAM to 2GB and error is gone.talib/_ta_lib.c:208671:15: warning: assignment from incompatible pointer type [enabled by default]

you saved my day! Thank you!
