### ISSUE TITLE
Cannot Install TA-Lib 

### ISSUE THREAD

**Issue by mripani** [mrjbq7/ta-lib#291]
Hello, 

I'm trying to install the TA-Lib library but when I launch the:

>  pip install TA-Lib

on the terminal I'm getting this error. I already installed Cython and the C library of TA-Lib with:

> brew install ta-lib

I'm getting this error:

xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
error: command 'gcc' failed with exit status 1

Hope someone can help,
Maximo

**Comment by mrjbq7** [comment]
Your error is this one:

xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
error: command 'gcc' failed with exit status 1

**Comment by mripani** [comment]
Thank you for your answer, so how can I figure it out?

**Comment by mrjbq7** [comment]
https://apple.stackexchange.com/questions/254380/why-am-i-getting-an-invalid-active-developer-path-when-attempting-to-use-git-a

**Comment by mripani** [comment]
Hey it worked! I really preciate your help. Thanks man.
