### ISSUE TITLE
How could we get the Monthly MACD data?

### ISSUE THREAD

**Issue by pivdets** [mrjbq7/ta-lib#297]
It seems that we could only calculate the daily MACD as this moment, I was wondering if we could make it works for Monthly as follows?

https://www.profitspi.com/stock/view.aspx?v=stock-chart&uv=209284&p=AMD#&&vs=637157023449287075

<img width="693" alt="Screen Shot 2020-01-27 at 2 16 12 PM" src="https://user-images.githubusercontent.com/37371804/73154210-8cc21300-4111-11ea-8cda-e86dbfe7290a.png">

**Comment by mrjbq7** [comment]
I don't understand this issue.  It seems particular to that website, not this project.
