### ISSUE TITLE
ImportError: cannot import name '__TA_FUNCTION_NAMES__'

### ISSUE THREAD

**Issue by quantSystemDev** [mrjbq7/ta-lib#298]
Re: Windows talib version 0.4.17 unzipped and installed in conda using 'pip install TA-Lib'

I'm getting the following import error.  Any suggestion how to resolve ?

---> 53 import talib as ta
     54 from math import sqrt
     55 

~\Anaconda3\envs\zip35\lib\site-packages\talib\__init__.py in <module>()
     41         return wrapper
     42 
---> 43 from ._ta_lib import (
     44     _ta_initialize, _ta_shutdown, MA_Type, __ta_version__,
     45     _ta_set_unstable_period as set_unstable_period,

ImportError: cannot import name '__TA_FUNCTION_NAMES__'

**Comment by quantSystemDev** [comment]
Formatting of error message wasn't great, so maybe a screen shot is better.
![error](https://user-images.githubusercontent.com/60360820/73551058-b6ca4c80-4413-11ea-8eeb-fe516a1210c4.png)

**Comment by mrjbq7** [comment]
Short version: you had some kind of compile error doing ``pip install ta-lib``.

Most likely issue is not having the underlying C library dependency, either unzip 32-bit version to ``C:\ta-lib``, or compile the 64-bit version yourself, or use the unofficial TA-Lib binaries.  See the README for more information.

Longer version: ``__TA_FUNCTION_NAMES__`` is defined in ``_func.pxi`` which is included in ``_ta_lib.pyx`` which is used to make ``_ta_lib.c`` using Cython, and then compiled as part of the installation process into ``from talib import _ta_lib`` where most of the C wrapper code lives.

**Comment by quantSystemDev** [comment]
@mrjbq7  Thank you  but I am still a little lost especially when it comes to understanding the "Longer version" of your comment.

After downloading the unofficial binary, I  did the following, but still get the same import error involving __TA_FUNCTION_NAMES__.

pip uninstall TA-Lib
pip install TA_Lib-0.4.17-cp35-cp35m-win_amd64.whl

(I assume this is the correct binary for windows 64b and python 3.5.4)

Here's what the talib directory looks like after the new pip install and after the failed "import talib as ta" statement in my code.  

Should I be seeing files with .pxi, .pyx and .c extensions?
Do I need to install Cython on my machine?

![dir](https://user-images.githubusercontent.com/60360820/73564671-0d448480-442e-11ea-9106-bff1d8f27c0f.png)

**Comment by quantSystemDev** [comment]
So it looks like there are 2 cython related pacakges installed in the environment.

![cython](https://user-images.githubusercontent.com/60360820/73566089-01a68d00-4431-11ea-9135-2c903a6dd573.png)

**Comment by mrjbq7** [comment]
Do you have the underlying C library installed per the windows 64-bit directions in the README?

**Comment by quantSystemDev** [comment]
Probably not.  I'll check.
