### ISSUE TITLE
module 'talib' has no attribute 'set_compatibility'

### ISSUE THREAD

**Issue by AdrianKeys** [mrjbq7/ta-lib#300]
[issues244](https://github.com/mrjbq7/ta-lib/issues/244)

> I just added (hopefully) support for this in [f716864](https://github.com/mrjbq7/ta-lib/commit/f71686450702adf5f980f162dc1c419283a20356).
> 
> You should be able to:
> 
> ```python
> import talib as ta
> 
> print ta.get_compatibility() # DEFAULT == 0
> 
> ta.set_compatibility(1) # METASTOCK == 1
> 
> print ta.get_compatibility()
> ```
> 
> If it works for you, we can maybe make some nicer constants?

So I tried import talib and call talib.set_compatibility(1) but what I got is "module 'talib' has no attribute 'set_compatibility'".

I'm running win 7 64 bit. Python 3.7 64 bit ver. I got whl from https://www.lfd.uci.edu/~gohlke/pythonlibs/ and  installed ta-lib via pip install TA_Lib‑0.4.17‑cp37‑cp37m‑win_amd64.whl

**Comment by mrjbq7** [comment]
I don’t believe that’s been released.  I was waiting for feedback. It’s been awhile and the master branch is clean, so I could do another release if that’s desired.

**Comment by AdrianKeys** [comment]
> I don’t believe that’s been released. I was waiting for feedback. It’s been awhile and the master branch is clean, so I could do another release if that’s desired.
> […](#)
> On Feb 24, 2020, at 12:38 AM, AdrianKeys ***@***.***> wrote: ﻿ issues244 I just added (hopefully) support for this in [f716864](https://github.com/mrjbq7/ta-lib/commit/f71686450702adf5f980f162dc1c419283a20356). You should be able to: import talib as ta print ta.get_compatibility() # DEFAULT == 0 ta.set_compatibility(1) # METASTOCK == 1 print ta.get_compatibility() If it works for you, we can maybe make some nicer constants? So I tried import talib and call talib.set_compatibility(1) but what I got is "module 'talib' has no attribute 'set_compatibility'". I'm running win 7 64 bit. Python 3.7 64 bit ver. I got whl from https://www.lfd.uci.edu/~gohlke/pythonlibs/ and installed ta-lib via pip install TA_Lib‑0.4.17‑cp37‑cp37m‑win_amd64.whl — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I'll appreciate it if do a release.

**Comment by Matoran** [comment]
Same problem for me, you just need to uninstall previous ta-lib `0.4.17` and install the last one from github.
Time saver for the next person:
```bash
pip uninstall TA-Lib
git clone https://github.com/mrjbq7/ta-lib.git
cd ta-lib
make
make install # if you don't use a venv you need to do it with sudo
```
