### ISSUE TITLE
Can't install TA-lib on Windows

### ISSUE THREAD

**Issue by ydhcoder** [mrjbq7/ta-lib#301]
I used `pip install TA-lib` but I seem to be getting this errors.
```
  Running setup.py clean for talib
Failed to build talib
Installing collected packages: talib
    Running setup.py install for talib ... error
```
I also tried to manually install by pulling your repo and installing by `python setup.py install` but I seem to be getting a similar error which is referred to in your repo homepage.

```
setup.py:79: UserWarning: Cannot find ta-lib library, installation may fail.
  warnings.warn('Cannot find ta-lib library, installation may fail.')
```

How can I fix this?

**Comment by pcawthron** [comment]
Try a pre-compiled binary from https://www.lfd.uci.edu/~gohlke/pythonlibs/#ta-lib

Regards,

Peter

**Comment by ydhcoder** [comment]
> Have you got the Ta-Lib library installed? It defaults to c:\ta-lib on Windows.
> 
> If you still have problem, try a pre-compiled binary from https://www.lfd.uci.edu/~gohlke/pythonlibs/#ta-lib
> 
> Regards,
> 
> Peter

I have got Ta-Lib installed in my c:/ta-lib directory. Just checked.

**Comment by ydhcoder** [comment]
I am also seeing this error that seems to have caught my attention.

`error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio"`

**Comment by naikshubham** [comment]
> 
> 
> Have you got the Ta-Lib library installed? It defaults to c:\ta-lib on Windows.
> 
> If you still have problem, try a pre-compiled binary from https://www.lfd.uci.edu/~gohlke/pythonlibs/#ta-lib
> 
> Regards,
> 
> Peter

Downloading this wheel file from here helped me. Python version specific wheel file works.
