### ISSUE TITLE
Error to MakeFileConfig

### ISSUE THREAD

**Issue by aarju123** [mrjbq7/ta-lib#302]
AR -o .build_release/lib/libcaffe-nv.a
LD -o .build_release/lib/libcaffe-nv.so.0.17.0
/usr/bin/ld: cannot find -lopen_cv_core
collect2: error: ld returned 1 exit status
Makefile:601: recipe for target '.build_release/lib/libcaffe-nv.so.0.17.0' failed
make: *** [.build_release/lib/libcaffe-nv.so.0.17.0] Error 1

**Comment by mrjbq7** [comment]
None of those lines have ta-lib in it?

**Comment by aarju123** [comment]
so I have to install it?

**Comment by mrjbq7** [comment]
I have no idea what project you are building, how TA-Lib fits into it, and that error message does not look related to this project. Perhaps you have the wrong project.

**Comment by aarju123** [comment]
I am trying to install caffe model
https://github.com/tidsp/caffe-jacinto/blob/caffe-0.17/INSTALL.md following this installation
system Ubuntu 16.04

**Comment by aarju123** [comment]
(caffe) aarju@abc~/Model/caffe-jacinto$ make all -j32
LD -o .build_release/lib/libcaffe-nv.so.0.17.0
/usr/bin/ld: cannot open output file .build_release/lib/libcaffe-nv.so.0.17.0: Permission denied
collect2: error: ld returned 1 exit status
Makefile:601: recipe for target '.build_release/lib/libcaffe-nv.so.0.17.0' failed
make: *** [.build_release/lib/libcaffe-nv.so.0.17.0] Error 1

**Comment by mrjbq7** [comment]
What does that have to do with TA-Lib?
