### ISSUE TITLE
Tried everything, still can’t import TA-Lib on Mac

### ISSUE THREAD

**Issue by rbdm-qnt** [mrjbq7/ta-lib#304]
I’m using Python 3.7 on MacOs 10.12.6. I’ve been trying to install talib in every way possible and I still get “no module named talib” when I try to import it in Python. I’m on Google page 10 looking for solutions, tried with brew, pip3, downloading the python wrapper from github… was anybody able to make this work?   

If it’s useful info, I don’t have Cython installed, should I? I don’t use that normally

I saw somebody trying this, but it was a fix for a different problem, it was for Windows, and it used binary, which is not available for Mac:
$ tar -xvf ta-lib-0.4.0-src.tar.gz 
$ cd ta-lib
$ ./configure --prefix=/usr
$ make
$ sudo make install
$ sudo ldconfig

**Comment by mrjbq7** [comment]
Did you follow the instructions on the README?

It should be as simple as

$ brew install ta-lib
$ pip3 install ta-lib

**Comment by rbdm-qnt** [comment]
> Did you follow the instructions on the README? It should be as simple as $ brew install ta-lib $ pip3 install ta-lib
> […](#)
> On Mar 31, 2020, at 6:17 AM, rbdm-qnt ***@***.***> wrote: ﻿ I’m using Python 3.7 on MacOs 10.12.6. I’ve been trying to install talib in every way possible and I still get “no module named talib” when I try to import it in Python. I’m on Google page 10 looking for solutions, tried with brew, pip3, downloading the python wrapper from github… was anybody able to make this work? If it’s useful info, I don’t have Cython installed, should I? I don’t use that normally I saw somebody trying this, but it was a fix for a different problem, it was for Windows, and it used binary, which is not available for Mac: $ tar -xvf ta-lib-0.4.0-src.tar.gz $ cd ta-lib $ ./configure --prefix=/usr $ make $ sudo make install $ sudo ldconfig — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Yes, that was my first attempt.

**Comment by mrjbq7** [comment]
The most common issue is not installing the underlying C library (brew install ta-lib). 

The second most common issue is several versions of python, so pip3 installs to a different python and when you go to use it, it’s not installed (because it installed somewhere else). To fix this you can just download from git and use your desired python to (python3 setup.py install).

Other common reasons can be not having a C compiler, installing 32-bit underlying C library and trying to use with 64-bit python (on Windows that’s often an issue).

**Comment by rbdm-qnt** [comment]
Turns out I didn't have a C compiler installed. I did brew install gcc, then uninstalled ta-lib from both brew and pip3, then reinstalled with both brew and pip3. Unfortunately nothing changed.

**Comment by rbdm-qnt** [comment]
Solved! Previously, when I tried to install ta-lib from Pycharm's available packages I got this error:

ERROR: Could not find a version that satisfies the requirement talib-binary (from versions: none)
ERROR: No matching distribution found for talib-binary

Now for some reason it worked, and I was able to import it. Hopefully it'll run fine. Thanks for the quick replies and for your hard work!
