### ISSUE TITLE
No module named 'talib._ta_lib'

### ISSUE THREAD

**Issue by marlon33** [mrjbq7/ta-lib#305]
When i 'import talib' 
this error show

C:\IQ-Robot\NEW_API>t.py
Traceback (most recent call last):
  File "C:\IQ-Robot\NEW_API\t.py", line 231, in <module>
    from talib import MA_Type
  File "C:\IQ-Robot\NEW_API\talib\__init__.py", line 52, in <module>
    from ._ta_lib import (
ModuleNotFoundError: No module named 'talib._ta_lib'

**Comment by mrjbq7** [comment]
You didn’t install it properly. 

That means the it couldn’t compile the cython wrapper. Please check the installation instructions in the README and see what was missed.

**Comment by marlon33** [comment]
I did the install, but when a deleted folders and install again the troubles gone
