### ISSUE TITLE
How can in  treat code output EMA, and get the last value?

### ISSUE THREAD

**Issue by marlon33** [mrjbq7/ta-lib#308]
I found thos script to calc the EMA,

> from talib.abstract import *
from iqoptionapi.stable_api import IQ_Option
import time
import numpy as np
print("login...")
I_want_money=IQ_Option("email@gmail.com","senha")
I_want_money.connect()#connect to iqoption
goal="EURUSD-OTC"
size=10#size=[1,5,10,15,30,60,120,300,600,900,1800,3600,7200,14400,28800,43200,86400,604800,2592000,"all"]
timeperiod=10
maxdict=20
print("start stream...")
I_want_money.start_candles_stream(goal,size,maxdict)
print("Start EMA Sample")
while True:
    candles=I_want_money.get_realtime_candles(goal,size)
    inputs = {
        'open': np.array([]),
        'high': np.array([]),
        'low': np.array([]),
        'close': np.array([]),
        'volume': np.array([])
    }
    for timestamp in candles:
        inputs["open"]=np.append(inputs["open"],candles[timestamp]["open"] )
        inputs["high"]=np.append(inputs["open"],candles[timestamp]["max"] )
        inputs["low"]=np.append(inputs["open"],candles[timestamp]["min"] )
        inputs["close"]=np.append(inputs["open"],candles[timestamp]["close"] )
        inputs["volume"]=np.append(inputs["open"],candles[timestamp]["volume"] )
    price = 1.07715904
    print("Show EMA")
    # print(EMA(inputs, timeperiod=timeperiod))
    ema = EMA(inputs, timeperiod=timeperiod)
    print("  ema: " + str(ema) )
    print("\n")
    time.sleep(1)
I_want_money.stop_candles_stream(goal,size)

 but the output is this how can i 'treat' this??

>  ema: [       nan        nan        nan        nan        nan        nan
       nan        nan        nan 1.0772019  1.07720755 1.07720873
1.07720278 1.07719773 1.07718196 1.07716942 1.07716771 1.07717249
1.07717967 1.07717682 1.07718013]

**Comment by mrjbq7** [comment]
The return value is a ``numpy.ndarray``, so you can use it like a sequence, getting the last value with ``ema[-1]``.
