### ISSUE TITLE
MAC import failed

### ISSUE THREAD

**Issue by dahuster** [mrjbq7/ta-lib#31]
My taptop is MAC air , with OSX 10.8.2 
After :  
$ brew install ta-lib
$ cd Cython-0.18
$ sudo python setup.py install
$ cd mrjbq7-ta-lib-283236b
$ sudo python setup.py install

everythings looks OK.so,I run python:

$ python

Enthought Python Distribution (EPD) free version -- www.enthought.com
Version: 7.3-1 (32-bit)
(type 'upgrade' or see www.enthought.com/epd/upgrade to get the full EPD)

Python 2.7.3 |EPD_free 7.3-1 (32-bit)| (default, Apr 12 2012, 11:28:34) 
[GCC 4.0.1 (Apple Inc. build 5493)] on darwin
Type "credits", "demo" or "enthought" for more information.

> > > import talib
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/talib/**init**.py", line 4, in <module>
> > >     from . import common
> > > ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/talib/common.so, 2): Symbol not found: _TA_GetVersionString
> > >   Referenced from: /Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/talib/common.so
> > >   Expected in: dynamic lookup

---

Please help me ,thanks for your time

**Comment by SlienceCoder** [comment]
hi,why my path different ,here:
''' (new_coding) ➜  ~ git:(master) ✗ brew info ta-lib
ta-lib: stable 0.4.0 (bottled)
Tools for market analysis
https://ta-lib.org/
/opt/homebrew/Cellar/ta-lib/0.4.0 (15 files, 2.3MB) *
  Poured from bottle on 2021-12-08 at 09:47:37
From: https://mirrors.ustc.edu.cn/homebrew-core.git/Formula/ta-lib.rb
==> Analytics
install: 1,683 (30 days), 4,736 (90 days), 21,886 (365 days)
install-on-request: 1,678 (30 days), 4,732 (90 days), 21,872 (365 days)
build-error: 3 (30 days)'''

'/opt/homebrew/Cellar/ta-lib' this path,i found at'/usr/local/lib/libta_lib.dylib',not found,pls help me ,thanks

**Comment by mrjbq7** [comment]
You can solve that by either:

1) running ``brew link ta-lib`` and then installing or...

2) running this before ``python setup.py install`` or ``pip install`` to indicate where the C library is:

```
$ export TA_INCLUDE_PATH="$(brew --prefix ta-lib)/include"
$ export TA_LIBRARY_PATH="$(brew --prefix ta-lib)/lib"
```
