### ISSUE TITLE
finding problems in the code parabolic sar 

### ISSUE THREAD

**Issue by abbask63** [mrjbq7/ta-lib#310]
my code :
`import talib

high=6800

low=6700

a= talib.SAR(high, low, acceleration=0.02, maximum=0.2)

print (a)`

ERROR :
`
Traceback (most recent call last):
  File "C:\Users\abbas\anaconda3\lib\site-packages\talib\__init__.py", line 20, in wrapper
    for arg in chain(args, kwargs.values())
StopIteration
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\abbas\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-ba6db8711645>", line 1, in <module>
    runfile('C:/Users/abbas/PycharmProjects/untitled/parabolicsar.py', wdir='C:/Users/abbas/PycharmProjects/untitled')
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.1\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/abbas/PycharmProjects/untitled/parabolicsar.py", line 4, in <module>
    a= talib.SAR(high, low, acceleration=0.02, maximum=0.2)
  File "C:\Users\abbas\anaconda3\lib\site-packages\talib\__init__.py", line 24, in wrapper
    return func(*args, **kwargs)
TypeError: Argument 'high' has incorrect type (expected numpy.ndarray, got int)
`

![ee1](https://user-images.githubusercontent.com/63823402/79832785-684b9f00-83bf-11ea-830d-03368acaafcb.jpg)

**Comment by mrjbq7** [comment]
High and low need to be numpy arrays, not integers. If you look at the end of your error message, it says that.

**Comment by abbask63** [comment]
hello again john 
wich way is true ?

my string on both way   j=
 {'s': 'ok', 't': [1587663000, 1587666600, 1587670200, 1587673800], 'c': [7500.0, 7509.0, 7533.0, 7540.0], 'o': [7495.0, 7500.0, 7510.0, 7530.0], 'h': [7549.0, 7527.0, 7535.0, 7540.0], 'l': [7495.0, 7493.0, 7501.0, 7530.0], 'v': [2.9331604818, 2.6694806793, 2.200094425, 0.531537]}

**way 1 :**

import json
import time
import requests
import numpy as np
import talib
.
.
.
.
r = requests.get(api_url_base)
j = r.content
class Payload(object):

       def __init__(self, j):
              self.__dict__ = json.loads(j)
p = Payload(j)
array = np.array(list(p))
print(repr(array))



**way 2 :** 

import requests
import time
import json
import numpy as np
.
.
.
.
r = requests.get(api_url_base)
j = json.loads(r.content.decode('utf-8'))
array = np.array(list(j))
print(repr(array))

**Comment by mrjbq7** [comment]
Neither of those pieces of code use ta-lib....?

**Comment by abbask63** [comment]
you say convert string to numpy 
first convert and use ta-lib

**Comment by mrjbq7** [comment]
Probably something like this:

high = np.array(j[“h”], dtype=float)

**Comment by abbask63** [comment]
thank you

show this error
![error](https://user-images.githubusercontent.com/63823402/80152553-1f6b3480-85d1-11ea-8a7f-9509e2f33bb3.jpg)

**Comment by abbask63** [comment]
john can you help me ?

**Comment by mrjbq7** [comment]
I’m busy today, but if you still need some help I can look at this tonight.

**Comment by abbask63** [comment]
thank you

**Comment by mrjbq7** [comment]
So, your code looks "good", but the problem you are having in that example above is you need more data.  SAR returns a NaN for the first entry before beginning to produce observations.

```python
In [7]: high = np.array([100,110,103,104], dtype=float)                         

In [8]: low = np.array([99,100,101,102], dtype=float)                           

In [9]: ta.SAR(high, low, acceleration=0.02, maximum=0.2)                       
Out[9]: array([    nan, 99.    , 99.22  , 99.4356])
```

**Comment by abbask63** [comment]
what mean this warning ? 
`Cannot find reference 'SAR' in '__init__.py' `

![error](https://user-images.githubusercontent.com/63823402/80688461-11417a80-8ae1-11ea-9cc2-728400dccc40.jpg)

**Comment by mrjbq7** [comment]
If the code still works, it's a false warning.

We expose all the functions in a way that your warning system might not be
aware of.

**Comment by abbask63** [comment]
thank you john code is working :)
