### ISSUE TITLE
Donchian channels

### ISSUE THREAD

**Issue by stefhenry** [mrjbq7/ta-lib#314]
Hi,

is there a way to calculate the Donchian Channels using this lib, like we can in python "ta" (https://technical-analysis-library-in-python.readthedocs.io/en/latest/ta.html)

thanks

**Comment by mrjbq7** [comment]
I don’t believe so, but it looks simple and is probably 3 lines of numpy. 

https://www.investopedia.com/terms/d/donchianchannels.asp

**Comment by mrjbq7** [comment]
Here's some sample code, untested:

```python
import pandas as pd

def DONCHIAN(hi, lo, n):
    hi = pd.Series(hi)
    lo = pd.Series(lo)
    uc = hi.rolling(n, min_periods=n).max()
    lc = lo.rolling(n, min_periods=n).min()
    mc = (uc - lc) / 2
    return lc, mc, uc
```

**Comment by rbosneag** [comment]
> Here's some sample code, untested:
> 
> ```python
> import pandas as pd
> 
> def DONCHIAN(hi, lo, n):
>     hi = pd.Series(hi)
>     lo = pd.Series(lo)
>     uc = hi.rolling(n, min_periods=n).max()
>     lc = lo.rolling(n, min_periods=n).min()
>     mc = (uc - lc) / 2
>     return lc, mc, uc
> ```
actually it should be `mc = (uc + lc) / 2` 🙂
