### ISSUE TITLE
TA-LIB INSTALLED ,BUT UNABLE TO IMPORT

### ISSUE THREAD

**Issue by PRADEEPMIG99** [mrjbq7/ta-lib#315]
I HAVE INSTALLED TA LIB USING THE WHEEL BUT UNABLE TO IMPORT THE MODULE.
![error](https://user-images.githubusercontent.com/62695876/80138875-2723dc80-85c3-11ea-9275-4492df319817.png)

**Comment by stefhenry** [comment]
did you install it for python3 or python2?

**Comment by mrjbq7** [comment]
Maybe you need to restart the server

**Comment by PRADEEPMIG99** [comment]
> 
> 
> did you install it for python3 or python2?

Python 3.7

**Comment by PRADEEPMIG99** [comment]
> 
> Maybe you need to restart the server
> […](#)
> On Apr 23, 2020, at 12:29 PM, STEPHANE HENRY ***@***.***> wrote: ﻿ did you install it for python3 or python2? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by PRADEEPMIG99** [comment]
> 
> Maybe you need to restart the server
> […](#)
> On Apr 23, 2020, at 12:29 PM, STEPHANE HENRY ***@***.***> wrote: ﻿ did you install it for python3 or python2? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

How do i restart the server?

**Comment by PRADEEPMIG99** [comment]
TA LIB INSTALLED BUT UNABLE TO IMPORT. I TRIED RESTARTING THE JUPYTER NOTEBOOK.. BUT IT DIDNT HELP....

**Comment by PRADEEPMIG99** [comment]
How do I restart the jupyter server?On 24-Apr-2020 1:03 am, John Benediktsson <notifications@github.com> wrote:

Maybe you need to restart the server

**Comment by mrjbq7** [comment]
It might be sufficient to just restart the Jupiter kernel, which you can do in the interface I think (Kernel / Restart)?

Otherwise look for documentation for your local installation. 

Sorry I can’t be of more help.
