### ISSUE TITLE
Is MACD's fastperiod > slowperiod possible?

### ISSUE THREAD

**Issue by tobiaslocker** [mrjbq7/ta-lib#334]
For e.g. slowperiod=15, fastperiod=5 I get the same results as for fastperiod=15, slowperiod=5. This raises a question:
 
*Will the bigger/smaller value always be used as slowperiod/fastperiod, although parameters are explicitly assigned the other way around?*

**Comment by mrjbq7** [comment]
It appears to be the case that the periods are swapped if passed in backwards. 

https://github.com/TA-Lib/ta-lib/blob/master/src/ta_func/ta_MACD.c#L137

**Comment by tobiaslocker** [comment]
Thanks for clarifying :+1:
