### ISSUE TITLE
Install on arm device have problem

### ISSUE THREAD

**Issue by saturn99** [mrjbq7/ta-lib#339]
I want install  on OrangePI zero (256MB RAM) ,

My OPI hangs when I try to install it, i installed successfully  `numpy` and `ta-lib` header filed without problem

I tried to do it both with ‍`pip3.8` install `TA-Lib` and by installing from source code; but i can't succefully install it 

![image](https://user-images.githubusercontent.com/5188799/90316677-eb799d80-df38-11ea-8cc9-0b108f316b1d.png)

and when i tried to install in by source code:

![image](https://user-images.githubusercontent.com/5188799/90316695-182db500-df39-11ea-9dc0-5de1226d0910.png)

how to i can installed it?
Is there no other way to install it? No pre-compiled version for `arm64‍` devices?
thank you

**Comment by saturn99** [comment]
finally i compile it on other arm device

you can download whl file at:
https://mybourse.github.io/TA-Lib-whl-Files/Files/whl/TA_Lib-0.4.19-cp38-cp38-linux_armv7l.whl

**Comment by mrjbq7** [comment]
How did you get TA-Lib underlying C library to compile? Did it require any
modifications?

Or to my python sources?

**Comment by saturn99** [comment]
No, I did not change them,
I just compiled the program with another device that has a lot of RAM

my step:
1: install `ta-lib-0.4.0-src.tar.gz`
`./configure --prefix=/usr && make && sudo make install`
2: install python3.8 from source 
3: install `numpy`
3.1: pip3.8 install numpy
3.2: or install it from source ( recommended for device with low ram)
4: pip3.8 install wheel
5: git clone this `ta-lib` repo
6: create whl file from this source
- python3.8 setup.py bdist_wheel


7: install whl (in folder dist)  to another device with `pip3.8 install `TA_Lib-0.4.19-cp38-cp38-linux_armv7l.whl`


and thank you for create this repo for python <3

**Comment by liuaifu** [comment]
This works for me:
`pip3 install TA-Lib-Precompiled`
I'm using python3.7.
