### ISSUE TITLE
Unable to install - Exception: You probably meant to install and run ta-lib

### ISSUE THREAD

**Issue by lemieuxm** [mrjbq7/ta-lib#347]
I've been running talib on my macos computer for a couple years.  I have it currently installed in one of my virtualenv's.  Of course ta-lib has also been installed for the entire time.  Something odd happened today when I tried to install on a new virtualenv (using pip install talib).  I received this rather cryptic error message:  "Exception: You probably meant to install and run ta-lib".  So, being kinda confused about what was going on there, I tried again after setting TA_LIBRARY_PATH and TA_INCLUDE_PATH, thinking that might have something to do with it.  It did not help, same result.  There is a message at the end, "Check the logs for full command output."  

Perhaps adding more detail to the error message, such as exactly what the problem is would be helpful.  The guess that I probably meant to do something is counter intuitive since I am on a system with a known working environment, and just wanted to create another.  I would also love to know where to look for the logs, because that might also be helpful.

**Comment by mrjbq7** [comment]
I’m not aware of where that exception is generated from. Did it have a trace back?

**Comment by lemieuxm** [comment]
Thank you for the quick response.  I just started using the original virtualenv until now... where I need to use the new one.  It turns out talib and ta-lib are not the same.  It was user error on my part.
