### ISSUE TITLE
Error on install in windows 10

### ISSUE THREAD

**Issue by jeffersonmello** [mrjbq7/ta-lib#353]
I tried for very times install this package, but a i receive an error.

`PS C:\Users\jeffe> pip install TA-Lib
Collecting TA-Lib
  Using cached TA-Lib-0.4.19.tar.gz (267 kB)
Requirement already satisfied: numpy in c:\users\jeffe\appdata\local\programs\python\python39\lib\site-packages (from TA-Lib) (1.19.2)
Using legacy 'setup.py install' for TA-Lib, since package 'wheel' is not installed.
Installing collected packages: TA-Lib
    Running setup.py install for TA-Lib ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\jeffe\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jeffe\\AppData\\Local\\Temp\\pip-install-fcuel8cr\\ta-lib\\setup.py'"'"'; __file__='"'"'C:\\Users\\jeffe\\AppData\\Local\\Temp\\pip-install-fcuel8cr\\ta-lib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\jeffe\AppData\Local\Temp\pip-record-28p0n5fp\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\jeffe\appdata\local\programs\python\python39\Include\TA-Lib'
         cwd: C:\Users\jeffe\AppData\Local\Temp\pip-install-fcuel8cr\ta-lib\
    Complete output (26 lines):
    C:\Users\jeffe\AppData\Local\Temp\pip-install-fcuel8cr\ta-lib\setup.py:71: UserWarning: Cannot find ta-lib library, installation may fail.
      warnings.warn('Cannot find ta-lib library, installation may fail.')
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\talib
    copying talib\abstract.py -> build\lib.win-amd64-3.9\talib
    copying talib\deprecated.py -> build\lib.win-amd64-3.9\talib
    copying talib\stream.py -> build\lib.win-amd64-3.9\talib
    copying talib\test_abstract.py -> build\lib.win-amd64-3.9\talib
    copying talib\test_data.py -> build\lib.win-amd64-3.9\talib
    copying talib\test_func.py -> build\lib.win-amd64-3.9\talib
    copying talib\test_pandas.py -> build\lib.win-amd64-3.9\talib
    copying talib\test_stream.py -> build\lib.win-amd64-3.9\talib
    copying talib\__init__.py -> build\lib.win-amd64-3.9\talib
    running build_ext
    building 'talib._ta_lib' extension
    creating build\temp.win-amd64-3.9
    creating build\temp.win-amd64-3.9\Release
    creating build\temp.win-amd64-3.9\Release\talib
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.27.29110\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\ta-lib\c\include -Ic:\users\jeffe\appdata\local\programs\python\python39\lib\site-packages\numpy\core\include -Ic:\users\jeffe\appdata\local\programs\python\python39\include -Ic:\users\jeffe\appdata\local\programs\python\python39\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.27.29110\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.27.29110\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt /Tctalib/_ta_lib.c /Fobuild\temp.win-amd64-3.9\Release\talib/_ta_lib.obj
    _ta_lib.c
    talib/_ta_lib.c(609): fatal error C1083: Cannot open include file: 'ta_libc.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\jeffe\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jeffe\\AppData\\Local\\Temp\\pip-install-fcuel8cr\\ta-lib\\setup.py'"'"'; __file__='"'"'C:\\Users\\jeffe\\AppData\\Local\\Temp\\pip-install-fcuel8cr\\ta-lib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\jeffe\AppData\Local\Temp\pip-record-28p0n5fp\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\jeffe\appdata\local\programs\python\python39\Include\TA-Lib' Check the logs for full command output.`

**Comment by mrjbq7** [comment]
The main error:

```
fatal error C1083: Cannot open include file: 'ta_libc.h': No such file or directory
```

**Comment by mrjbq7** [comment]
Did you follow these instructions for installing the underlying C library?

https://github.com/mrjbq7/ta-lib#windows

It's a little different if you want to do 64-bit, you need to build that C library yourself (binaries are not available) or use one of the unofficial wheels until we get wheel support as part of my build system.

**Comment by eabase** [comment]
Why is this such a PITA, we've been using ta-lib for ages, but nobody bother to make a Windows build!? Instead you say we should run this way outdated version. What's going here?

PS. if you're using `conda`, you can get the latest version `0.5.19` with: `conda install -c conda-forge ta-lib`

**Comment by jeffersonmello** [comment]
I solved this problem, but only install lib with wheel.

https://www.lfd.uci.edu/~gohlke/pythonlibs/#ta-lib

**Comment by mrjbq7** [comment]
What “way outdated” version are you talking about?

**Comment by mrjbq7** [comment]
Closing all installation issues, if someone has a specific problem please open a new one.
