### ISSUE TITLE
TA-Lib installation problem

### ISSUE THREAD

**Issue by AlexMouss** [mrjbq7/ta-lib#357]
I am currently having problems installing TA-Lib. I have been trying solutions for the pasts days but I couldn`t get it right. 

Specifications: 
Python version 3.9
Windows 64 core

I have tried:
1-pip install TA-Lib
2-Downloading the file from https://www.lfd.uci.edu/~gohlke/pythonlibs/#ta-lib 

For number 1, I am currently getting this error message: 
C:\Users\alexm\Downloads\talib>pip install TA-Lib
Collecting TA-Lib
  Using cached TA-Lib-0.4.19.tar.gz (267 kB)
Requirement already satisfied: numpy in c:\users\alexm\appdata\local\programs\python\python39\lib\site-packages (from TA-Lib) (1.19.4)
Using legacy 'setup.py install' for TA-Lib, since package 'wheel' is not installed.
Installing collected packages: TA-Lib
    Running setup.py install for TA-Lib ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\alexm\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\alexm\\AppData\\Local\\Temp\\pip-install-waj3majk\\ta-lib\\setup.py'"'"'; __file__='"'"'C:\\Users\\alexm\\AppData\\Local\\Temp\\pip-install-waj3majk\\ta-lib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\alexm\AppData\Local\Temp\pip-record-6l9ekcsq\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\alexm\appdata\local\programs\python\python39\Include\TA-Lib'
         cwd: C:\Users\alexm\AppData\Local\Temp\pip-install-waj3majk\ta-lib\
    Complete output (26 lines):
    C:\Users\alexm\AppData\Local\Temp\pip-install-waj3majk\ta-lib\setup.py:71: UserWarning: Cannot find ta-lib library, installation may fail.
      warnings.warn('Cannot find ta-lib library, installation may fail.')
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\talib
    copying talib\abstract.py -> build\lib.win-amd64-3.9\talib
    copying talib\deprecated.py -> build\lib.win-amd64-3.9\talib
    copying talib\stream.py -> build\lib.win-amd64-3.9\talib
    copying talib\test_abstract.py -> build\lib.win-amd64-3.9\talib
    copying talib\test_data.py -> build\lib.win-amd64-3.9\talib
    copying talib\test_func.py -> build\lib.win-amd64-3.9\talib
    copying talib\test_pandas.py -> build\lib.win-amd64-3.9\talib
    copying talib\test_stream.py -> build\lib.win-amd64-3.9\talib
    copying talib\__init__.py -> build\lib.win-amd64-3.9\talib
    running build_ext
    building 'talib._ta_lib' extension
    creating build\temp.win-amd64-3.9
    creating build\temp.win-amd64-3.9\Release
    creating build\temp.win-amd64-3.9\Release\talib
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.27.29110\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\ta-lib\c\include -Ic:\users\alexm\appdata\local\programs\python\python39\lib\site-packages\numpy\core\include -Ic:\users\alexm\appdata\local\programs\python\python39\include -Ic:\users\alexm\appdata\local\programs\python\python39\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.27.29110\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /Tctalib/_ta_lib.c /Fobuild\temp.win-amd64-3.9\Release\talib/_ta_lib.obj
    _ta_lib.c
    talib/_ta_lib.c(609): fatal error C1083: Não é possível abrir arquivo incluir: 'ta_libc.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\alexm\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\alexm\\AppData\\Local\\Temp\\pip-install-waj3majk\\ta-lib\\setup.py'"'"'; __file__='"'"'C:\\Users\\alexm\\AppData\\Local\\Temp\\pip-install-waj3majk\\ta-lib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\alexm\AppData\Local\Temp\pip-record-6l9ekcsq\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\alexm\appdata\local\programs\python\python39\Include\TA-Lib' Check the logs for full command output.

For number 2, I am currently getting this error message:
C:\Users\alexm\Downloads\talib>pip install TALib-0.4.19-cp39-cp39-winamd64.whl
WARNING: Requirement 'TALib-0.4.19-cp39-cp39-winamd64.whl' looks like a filename, but the file does not exist
ERROR: TALib-0.4.19-cp39-cp39-winamd64.whl is not a supported wheel on this platform.

I know this is a long post but I would REALLY appreaciated some help because I am stuck for hours.

**Comment by mrjbq7** [comment]
Your error with #1 is not having the TA-Lib C library installed, see these directions for Windows 64-bit:

https://github.com/mrjbq7/ta-lib#windows

Your error with #2 appears to be that the file you want is not in that location ``but the file does not exist``... maybe it's in ``C:\Users\alexm\Downloads\``

**Comment by AlexMouss** [comment]
THANK YOU!!
I just used your second solution and it worked. Thanks again
