### ISSUE TITLE
MaxIndex MinIndex return wrong index of array

### ISSUE THREAD

**Issue by chuchiring** [mrjbq7/ta-lib#358]
when the array has np.nan ahead.

for example: 

right: idx = talib.MaxIndex(df.close, 14)

wrong: 
arr = talib.ADX(df.high, df.low, df.close, 14)
idx = talib.MaxIndex(arr, 14)

because of ADX will fill 14 np.nan in the head of arr, so MaxIndex returns wrong index result.

**Comment by mrjbq7** [comment]
I believe that's just how MAXINDEX is defined: that it skips over the NaN and then works the way it does when there are no NaN... Part of this is that NaN is not comparable, what behavior did you expect?

**Comment by chuchiring** [comment]
> I believe that's just how MAXINDEX is defined: that it skips over the NaN and then works the way it does when there are no NaN... Part of this is that NaN is not comparable, what behavior did you expect?

when I got the idx from MaxIndex, I will use it to get the df.close[idx] , but now the idx is wrong.

**Comment by mrjbq7** [comment]
Are you looking to have NaN in the MAXINDEX result?

**Comment by chuchiring** [comment]
> Are you looking to have NaN in the MAXINDEX result?

hi mrjbq7,

I wrote sample code:

`l = [1., 2, 3, 4, 5, 6, 7, 8, 7, 7, 3, 4, 5, 6, 7, 8, 9, 2, 3, 4, 5, 15]
close_price = np.array(l)

ma10 = talib.MA(close_price, 10)
idxs = talib.MAXINDEX(ma10, 10)

print(len(close_price))
print(close_price)
print(ma10)
print(idxs)
print('When ma10 cross prior high value, close price is:', close_price[idxs[-1]])`

the result:

`close price: [ 1.  2.  3.  4.  5.  6.  7.  8.  7.  7.  3.  4.  5.  6.  7.  8.  9.  2. 3.  4.  5. 15.]
        ma10 :  [nan nan nan nan nan nan nan nan nan 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 5.8 5.4 5.1 5.3 6.4]
    max idxs: [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  7  7  7 12]
When ma10 cross prior high value, close price is: 5.0`

in fact, when ma10 cross prior high value in days, the close price should be 15, not 5.

i want the max idxs return:
`max idxs: [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  16  16  16  21]`

**Comment by mrjbq7** [comment]
It does seem like it's not handling NaN properly, but I'd have to look through the code to know why.

https://github.com/TA-Lib/ta-lib/blob/master/src/ta_func/ta_MAXINDEX.c

**Comment by mrjbq7** [comment]
I try not to modify the behavior of the underlying C library, preferring to be a lightweight wrapper.  It's unfortunate that upstream doesn't seem to be releasing new versions.

**Comment by chuchiring** [comment]
I see, i checked ta-lib github issue, seemed only one question created by you....

is C-ta-lib a dead project?

**Comment by mrjbq7** [comment]
That GitHub repository is a copy of the main upstream project which was using sourceforge last I checked. 

I know that a couple small bugs were fixed but not yet released as version 0.5.0, but I haven’t looked deeply into that yet.

**Comment by chuchiring** [comment]
nice, when ta-lib python upgrade to 0.50?

**Comment by mrjbq7** [comment]
Not anytime soon probably... the original maintainer doesn’t appear to be doing a new release that I’m aware of.

**Comment by Hungryarie** [comment]
Any news on this topic? Run in the same issue as discribed by Chuchiring

**Comment by mrjbq7** [comment]
Hi @Hungryarie,

I just realized that I might be able to fix this.

Would you want this result?

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  2,  3,  4,  5,  6,  7,
        8, 16, 16, 16, 21], dtype=int32)

**Comment by Hungryarie** [comment]
Hi mrjbq7!

Ideally I want NaNs for where the max_idx could not be calculated for that period, because it does not have enough data to make a good calculation. 
Going forward with the provided example data by @chuchiring, I would like to have to outcome of the MAXINDEX(ma10, period=10) to be this:
`max idxs: [ nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan 16 16 16 21]`

my workaround righ now is
`max_idxs = talib.MAXINDEX(ma10, 10)`
`max_idxs  += np.isnan(ma10).sum()`
which results in:
`max idxs: [ 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 21]`

**Comment by mrjbq7** [comment]
I was hoping to return an int array, would you prefer:

[-1, -1, … , 16]

Or

[nan, nan, … 16.0]

**Comment by Hungryarie** [comment]
-1 would work as well for me. As long as I can retrieve/distill a correct value I'm happy ;-)

**Comment by mrjbq7** [comment]
Fixed in 0dce79b9804e06938cbabbc8fd9662231b1aa8bd.

Released as 0.4.21.

Very sorry I didn't pay attention to this bug earlier.

**Comment by Hungryarie** [comment]
thanks for the fix!
I checked with my code and my workaround is no longer necessary
