### ISSUE TITLE
TA lib can`t install Ubuntu

### ISSUE THREAD

**Issue by kravtsls** [mrjbq7/ta-lib#363]
Hi @ mrjbq7  thank you for writing open source codes for people and for helping and being always response. there is the problem with TA lib installation. When I check folders with Atom or ls -la there is no ta lib but it is in built helpers, did TA lib install or no? thank you so much. here is what i see when i try to install TA lib

lissa@LissaVB:~$ python3
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Ubuntu 18.04

lissa@LissaVB:~$ pip install TA-Lib
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: TA-Lib in ./.local/lib/python3.6/site-packages (0.4.19)
Requirement already satisfied: numpy in ./.local/lib/python3.6/site-packages (from TA-Lib) (1.19.4)
lissa@LissaVB:~$ 

Looking forward to hearing from you, 
lissa

**Comment by mrjbq7** [comment]
Can you use ta-lib?

```
$ python3
>>> import talib
>>> print(talib.__version__)
0.4.19
```

**Comment by kravtsls** [comment]
> Can you use ta-lib?
> 
> ```
> $ python3
> >>> import talib
> >>> print(talib.__version__)
> 0.4.19
> ```

i wrote it  

python3
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import talib
>>> print(talib.__version__)

and got 
0.4.19


Thank you Mario!

**Comment by kravtsls** [comment]
@mrjbq7 John sorry, does it mean that TA lib works as should work and everything alright even if it is in build helpers and not in the separate folder TA lib?

Thank you 
Lissa

**Comment by mrjbq7** [comment]
Hi @kravtsls I have no idea how you intend to run it, but if you can call it from ``python3`` then it is "working"...

```
$ python3
>>> import talib
>>> import numpy
>>> a = numpy.random.randn(100)
>>> talib.EMA(a)
```

**Comment by kravtsls** [comment]
@mrjbq7 thank you, following steps from freqtrade.io 

does it means that it was called?

lissa@LissaVB:~$ python3
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import talib
>>> import numpy
>>> a = numpy.random.randn(100)
>>> talib.EMA(a)
array([        nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan, -0.00259015,
       -0.07147372, -0.1007241 , -0.01407768, -0.10157987, -0.14476016,
       -0.14957718, -0.19549287, -0.19824203, -0.24120874, -0.19762649,
       -0.23608205, -0.2370478 , -0.33596807, -0.35725354, -0.35333372,
       -0.45838396, -0.48694508, -0.54277242, -0.51333074, -0.55362147,
       -0.50816457, -0.47279072, -0.41773844, -0.35023266, -0.33220625,
       -0.39299632, -0.39912168, -0.44002546, -0.34002476, -0.39765291,
       -0.35296577, -0.32656075, -0.43472672, -0.37513853, -0.32183527,
       -0.27148433, -0.19844855, -0.24384399, -0.1226931 , -0.10171062,
       -0.17317227, -0.15938849, -0.09458052, -0.1705246 , -0.14197829,
       -0.24316145, -0.17906851, -0.17014695, -0.25285768, -0.25452532,
       -0.36374143, -0.40246121, -0.42630001, -0.37016933, -0.33271604,
       -0.21415135, -0.21360759, -0.28634148, -0.2314095 , -0.24416697,
       -0.22555428, -0.14489097, -0.16517156, -0.13957198, -0.18847891,
       -0.14383795, -0.02872334, -0.04946944, -0.02673768, -0.07448899])
>>>

**Comment by mrjbq7** [comment]
Yes!

**Comment by kravtsls** [comment]
@mrjbq7 wow John thank you soooo much! thank you for helping and your time! thank you! 

Best!,
Lissa
