### ISSUE TITLE
STOCHRSI results not accurate AT ALL ... anyone having the same issue ?

### ISSUE THREAD

**Issue by bluetyphoon77** [mrjbq7/ta-lib#365]
Hi guyz !
I don't understand what's the point to be able to grab stochrsi data if we have totally wrong results ;)
I've tested on binance and the results I get are totally different than what I see on Tradingview.
Can someone help please ? thanks a lot

**Comment by mrjbq7** [comment]
The definition is different. 

See other issues reporter: #149, #170, #203, 

This comment might be useful for you:

https://github.com/mrjbq7/ta-lib/issues/203#issuecomment-462143312

**Comment by bluetyphoon77** [comment]
Thanks for your answer. But what is the final conclusion ? TA-lib is not able to provide accurate results ?
If not what library could I use ?
Thanks a lot

________________________________

**Comment by bluetyphoon77** [comment]
Hi, I've checked your links but it is unclear what the final conclusion is. Could you just tell me if ta-lib is capable of grabbing accurate values for stochrsi or not ? 
Do we have to use Tulip for just this stochrsi indicator ?
Thanks

**Comment by mrjbq7** [comment]
TA-LIB has an implementation of STOCHRSI.

It works.  It's just a different definition than the one TradingView uses apparently.

You can build your own that does it the way TradingView does it.

See this comment for details: https://github.com/mrjbq7/ta-lib/issues/203#issuecomment-462161352

Without seeing test data that you are working with, I can't say for sure, but probably calling ``talib.STOCH`` with the results of``talib.RSI`` would be the same thing.

**Comment by bluetyphoon77** [comment]
Hey John thanks again, I will give the info to the dev 😉 This is chinese to me 😉
Happy if you can get the same values as int TV.
I'll transfer him your advice :)
Do you know how much time it could take from scratch to write a bot that will send on telegram signals for 3 simple indicators like rsi, mfi, stochrsi ? Approximatively ? thanks :) I will try to find someone efficient.... not easy .... I've teste upwork and ... negative experiences there .....

________________________________

**Comment by mrjbq7** [comment]
I bet you could figure it out and write it yourself! 

Here's a tutorial on writing a telegram bot in Python:

https://github.com/python-telegram-bot/python-telegram-bot/wiki/Extensions-–-Your-first-Bot

And getting prices, applying a few ``talib`` indicators, isn't probably too many lines of code...!

**Comment by bluetyphoon77** [comment]
very friendly from you john ! :)
ok I'll do my best :)
cheeeers

________________________________

**Comment by Elyasnz** [comment]
if a Python implementation of STOCHRSI is needed this [comment](https://github.com/TA-Lib/ta-lib-python/issues/594#issuecomment-1560640283) is useful
