### ISSUE TITLE
Error when Pip installing

### ISSUE THREAD

**Issue by bcka** [mrjbq7/ta-lib#367]
Hi there people,

I receive the following error when I try to pip install talib. Any ideas how to fix this (pretty new to this and just learning)

`  Using cached TA-Lib-0.4.19.tar.gz (267 kB)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from TA-Lib) (1.19.4)
Using legacy 'setup.py install' for TA-Lib, since package 'wheel' is not installed.
Installing collected packages: TA-Lib
    Running setup.py install for TA-Lib ... error
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/cp/yh6ljx6n0j94tdqmxbx480300000gn/T/pip-install-scllndpm/ta-lib_c7f78ed5c74847589f654415465d81b3/setup.py'"'"'; __file__='"'"'/private/var/folders/cp/yh6ljx6n0j94tdqmxbx480300000gn/T/pip-install-scllndpm/ta-lib_c7f78ed5c74847589f654415465d81b3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/cp/yh6ljx6n0j94tdqmxbx480300000gn/T/pip-record-3wdlt756/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.9/include/python3.9/TA-Lib
         cwd: /private/var/folders/cp/yh6ljx6n0j94tdqmxbx480300000gn/T/pip-install-scllndpm/ta-lib_c7f78ed5c74847589f654415465d81b3/
    Complete output (24 lines):
    /private/var/folders/cp/yh6ljx6n0j94tdqmxbx480300000gn/T/pip-install-scllndpm/ta-lib_c7f78ed5c74847589f654415465d81b3/setup.py:71: UserWarning: Cannot find ta-lib library, installation may fail.
      warnings.warn('Cannot find ta-lib library, installation may fail.')
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.9
    creating build/lib.macosx-10.9-x86_64-3.9/talib
    copying talib/abstract.py -> build/lib.macosx-10.9-x86_64-3.9/talib
    copying talib/test_abstract.py -> build/lib.macosx-10.9-x86_64-3.9/talib
    copying talib/deprecated.py -> build/lib.macosx-10.9-x86_64-3.9/talib
    copying talib/__init__.py -> build/lib.macosx-10.9-x86_64-3.9/talib
    copying talib/stream.py -> build/lib.macosx-10.9-x86_64-3.9/talib
    copying talib/test_pandas.py -> build/lib.macosx-10.9-x86_64-3.9/talib
    copying talib/test_data.py -> build/lib.macosx-10.9-x86_64-3.9/talib
    copying talib/test_func.py -> build/lib.macosx-10.9-x86_64-3.9/talib
    copying talib/test_stream.py -> build/lib.macosx-10.9-x86_64-3.9/talib
    running build_ext
    building 'talib._ta_lib' extension
    creating build/temp.macosx-10.9-x86_64-3.9
    creating build/temp.macosx-10.9-x86_64-3.9/talib
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/usr/include -I/usr/local/include -I/opt/include -I/opt/local/include -I/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c talib/_ta_lib.c -o build/temp.macosx-10.9-x86_64-3.9/talib/_ta_lib.o
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command '/usr/bin/gcc' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/cp/yh6ljx6n0j94tdqmxbx480300000gn/T/pip-install-scllndpm/ta-lib_c7f78ed5c74847589f654415465d81b3/setup.py'"'"'; __file__='"'"'/private/var/folders/cp/yh6ljx6n0j94tdqmxbx480300000gn/T/pip-install-scllndpm/ta-lib_c7f78ed5c74847589f654415465d81b3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/cp/yh6ljx6n0j94tdqmxbx480300000gn/T/pip-record-3wdlt756/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.9/include/python3.9/TA-Lib Check the logs for full command output.`

**Comment by mrjbq7** [comment]
Your error is buried in that:

```
_ta_lib.o xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun error: command '/usr/bin/gcc' failed with exit code 1 ---------------------------------------- 
```

**Comment by mrjbq7** [comment]
Maybe try ``xcode-select --install``

**Comment by bcka** [comment]
Did help thanks but created a new error

Using cached TA-Lib-0.4.19.tar.gz (267 kB)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from TA-Lib) (1.19.4)
Using legacy 'setup.py install' for TA-Lib, since package 'wheel' is not installed.
Installing collected packages: TA-Lib
    Running setup.py install for TA-Lib ... error
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/cp/yh6ljx6n0j94tdqmxbx480300000gn/T/pip-install-iyu3edjk/ta-lib_ce99cb7f1c36432591303e3077a7b24f/setup.py'"'"'; __file__='"'"'/private/var/folders/cp/yh6ljx6n0j94tdqmxbx480300000gn/T/pip-install-iyu3edjk/ta-lib_ce99cb7f1c36432591303e3077a7b24f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/cp/yh6ljx6n0j94tdqmxbx480300000gn/T/pip-record-tijl16iu/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.9/include/python3.9/TA-Lib
         cwd: /private/var/folders/cp/yh6ljx6n0j94tdqmxbx480300000gn/T/pip-install-iyu3edjk/ta-lib_ce99cb7f1c36432591303e3077a7b24f/
    Complete output (27 lines):
    /private/var/folders/cp/yh6ljx6n0j94tdqmxbx480300000gn/T/pip-install-iyu3edjk/ta-lib_ce99cb7f1c36432591303e3077a7b24f/setup.py:71: UserWarning: Cannot find ta-lib library, installation may fail.
      warnings.warn('Cannot find ta-lib library, installation may fail.')
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.9
    creating build/lib.macosx-10.9-x86_64-3.9/talib
    copying talib/abstract.py -> build/lib.macosx-10.9-x86_64-3.9/talib
    copying talib/test_abstract.py -> build/lib.macosx-10.9-x86_64-3.9/talib
    copying talib/deprecated.py -> build/lib.macosx-10.9-x86_64-3.9/talib
    copying talib/__init__.py -> build/lib.macosx-10.9-x86_64-3.9/talib
    copying talib/stream.py -> build/lib.macosx-10.9-x86_64-3.9/talib
    copying talib/test_pandas.py -> build/lib.macosx-10.9-x86_64-3.9/talib
    copying talib/test_data.py -> build/lib.macosx-10.9-x86_64-3.9/talib
    copying talib/test_func.py -> build/lib.macosx-10.9-x86_64-3.9/talib
    copying talib/test_stream.py -> build/lib.macosx-10.9-x86_64-3.9/talib
    running build_ext
    building 'talib._ta_lib' extension
    creating build/temp.macosx-10.9-x86_64-3.9
    creating build/temp.macosx-10.9-x86_64-3.9/talib
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/usr/include -I/usr/local/include -I/opt/include -I/opt/local/include -I/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c talib/_ta_lib.c -o build/temp.macosx-10.9-x86_64-3.9/talib/_ta_lib.o
    talib/_ta_lib.c:611:10: fatal error: 'ta-lib/ta_defs.h' file not found
    #include "ta-lib/ta_defs.h"
             ^~~~~~~~~~~~~~~~~~
    1 error generated.
    error: command '/usr/bin/gcc' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/cp/yh6ljx6n0j94tdqmxbx480300000gn/T/pip-install-iyu3edjk/ta-lib_ce99cb7f1c36432591303e3077a7b24f/setup.py'"'"'; __file__='"'"'/private/var/folders/cp/yh6ljx6n0j94tdqmxbx480300000gn/T/pip-install-iyu3edjk/ta-lib_ce99cb7f1c36432591303e3077a7b24f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/cp/yh6ljx6n0j94tdqmxbx480300000gn/T/pip-record-tijl16iu/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.9/include/python3.9/TA-Lib Check the logs for full command output.

**Comment by mrjbq7** [comment]
If you look at the README for macOS, you need to install the ``TA-Lib`` C library first, it is not bundled with this python project:

```
brew install ta-lib
```
