### ISSUE TITLE
ImportError: cannot import name common - don't run in ta-lib dir

### ISSUE THREAD

**Issue by militantwalrus** [mrjbq7/ta-lib#37]
SuSE linux
64-bit python
64-bit Cython
ta-lib builds and installs to /usr/lib64/python2.7/site-packages/talib/

> > > import talib
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "talib/**init**.py", line 4, in <module>
> > >     from . import common
> > > ImportError: cannot import name common

Then I had a funny idea.... I was running the python shell in the checkout dir.
Running the python shell _elsewhere_ let me import talib just fine....

Just posting this in case it helps someone.

Thanks much for the module.

**Comment by girigk** [comment]
I did below steps  and it worked perfectly well. I was getting error -
cannot import name '__TA_FUNCTION_NAMES__'
1. Closed anaconda
2. Went into site packages folder and found talib folders 
3. Deleted the folders
4. Opened Anaconda prompt
5. Upgraded numpy - **pip install -U numpy --user**
6. Installed TA_Lib-0.4.17-cp36-cp36m-win_amd64.whl which I had downloaded using pip install
This

**Comment by mrjbq7** [comment]
Closing all installation issues, if someone has a specific problem please open a new one.
