### ISSUE TITLE
Ta-lib with pyinstaller (.py -> .exe)

### ISSUE THREAD

**Issue by tuansacer** [mrjbq7/ta-lib#373]
I using pyinstaller for convert from .py to .exe, but found error:
```
...site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "talib\__init__.py", line 72, in <module>
ModuleNotFoundError: No module named 'talib.stream'
```
Python: 3.6
Pyiinstaller: 4.1
Ta-Lib: 0.4.19
Please help me soved this one.

**Comment by mrjbq7** [comment]
I have not ever tried to use pyinstaller, but that error looks like the Cython modules were not built first before importing.

**Comment by tuansacer** [comment]
@mrjbq7 I used --hidden-import function on pyinstaller and working now. thank for your response~

**Comment by Chadonillo** [comment]
thank you so much for updating us with the solution I have had two sleepless nights because of this

**Comment by tuansacer** [comment]
> thank you so much for updating us with the solution I have had two sleepless nights because of this

Haha. You are wellcome

**Comment by mrjbq7** [comment]
If anyone wants to add a note to the README to help others doing this that would be great. I’m not familiar with pyinstaller...

**Comment by copypasteearth** [comment]
can you provide the exact pyinstaller command you used with hidden imports. I cant seem to get it to work still.  Should i use TA-Lib, talib, or talib.stream with hidden imports?

**Comment by zhnagchulan** [comment]
How to solve this?using --hidden-import, tell some detail plesase...

**Comment by codeandnote** [comment]
> How to solve this?using --hidden-import, tell some detail plesase...

I just solve it, this method may help you

For example, if your error is "No module named 'talib.stream'", you can add the command  argument " --hidden-import talib.stream", 

So the full command should be like this：
pyinstaller   --hidden-import talib.stream "replaceToYourFileName.py"

**Comment by mrjbq7** [comment]
Added this as a note in the README, thanks!

54019f7ea0b84102d3d5f409959d2627900db7db
