### ISSUE TITLE
TA-LIB install fail

### ISSUE THREAD

**Issue by karenjh2** [mrjbq7/ta-lib#374]
I have ta-lib in c:\ta-lib so the install process can find files. There were other errors. The OS is Windows 10. See attached screenshot of errors.
![image](https://user-images.githubusercontent.com/46858944/103324345-eace4780-4a92-11eb-8a18-4ca1572af67e.png)

**Comment by mrjbq7** [comment]
It looks like you downloaded the 32-bit binary release but expected it to work on your 64-bit Windows and Python?

**Comment by karenjh2** [comment]
It is possible. There was only one file to download for Windows on the page that I downloaded it from.

 

I will search for one one.

 

Karen Higgins

**Comment by mrjbq7** [comment]
https://github.com/mrjbq7/ta-lib#windows

**Comment by mrjbq7** [comment]
Closing all installation issues, if someone has a specific problem please open a new one.
