### ISSUE TITLE
Incorrect install directory

### ISSUE THREAD

**Issue by noahhuerta4** [mrjbq7/ta-lib#375]
Hello, I have tried installing TA-Lib on both Mac and Ubuntu systems and in both cases I have managed to get them installed. However, they are being placed in directories not reachable by my python code. I have tried using virtual environments as a work around to this issue but was unsuccessful. I have spent many hours over the past couple weeks trying to get this to work and scrolling endless forums but could not find any clear way to install create a proper install path. Any help would be greatly appreciated preferably for Ubuntu. Thank you.

Best regards,
Noah Huerta

**Comment by mrjbq7** [comment]
How did you install it?

Where did it put the files?

Where did you expect it to put the files?

Maybe I can help...

**Comment by noahhuerta4** [comment]
Thank you for responding. I used the same method for installation as outlined on your github post along with variations in the ./configure line and using both the pip install and python setup.py install. I have also tried conda install -c quantopian ta-lib. It saved to the file path: /home/noah/.local/lib/python3.8/site-packages there actually isn't even any python executable file in any of the directories parented by /home/noah/.local. It seemed to have created this path all on its own which is the weird part. However, I could be wrong about that. I need to install it to /home/noah/anaconda3/lib/python3.7/site-packages.

**Comment by mrjbq7** [comment]
Sounds like you have multiple Python installations and your conda is using Python 3.8 and you want Python 3.7?

Might be an issue with conflicting pip installations. 

Try 

python3.7 -m pip install ta-lib

But make sure you have the underlying TA-Lib C library installed first.  You can see some suggestions for that in the README.

**Comment by mrjbq7** [comment]
Closing all installation issues, if someone has a specific problem please open a new one.
