### ISSUE TITLE
Installation issue with python setup.py install

### ISSUE THREAD

**Issue by Ankitgelda8** [mrjbq7/ta-lib#382]
Hello team , 

I'm  installing TA-LIB in GoDaddy shared Linux environment, I am able to install tab-lib and set path according to guide you have provided in the readme 
I am facing some different issue and unable to solve it 
the is as follows.

talib/_ta_lib.c:201901: error: too many arguments to function ‘__pyx_f_5talib_7_ta_lib__ta_check_success’
talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_622stream_SIN’:
talib/_ta_lib.c:201970: error: ‘TA_RetCode’ undeclared (first use in this function)
talib/_ta_lib.c:201970: error: expected ‘;’ before ‘__pyx_v_retCode’
talib/_ta_lib.c:202063: warning: assignment from incompatible pointer type
talib/_ta_lib.c:202112: error: ‘__pyx_v_retCode’ undeclared (first use in this function)
talib/_ta_lib.c:202121: error: too many arguments to function ‘__pyx_f_5talib_7_ta_lib__ta_check_success’
talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_624stream_SINH’:
talib/_ta_lib.c:202189: error: ‘TA_RetCode’ undeclared (first use in this function)
talib/_ta_lib.c:202189: error: expected ‘;’ before ‘__pyx_v_retCode’
talib/_ta_lib.c:202282: warning: assignment from incompatible pointer type
talib/_ta_lib.c:202331: error: ‘__pyx_v_retCode’ undeclared (first use in this function)
talib/_ta_lib.c:202340: error: too many arguments to function ‘__pyx_f_5talib_7_ta_lib__ta_check_success’
talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_626stream_SMA’:
talib/_ta_lib.c:202463: error: ‘TA_RetCode’ undeclared (first use in this function)
talib/_ta_lib.c:202463: error: expected ‘;’ before ‘__pyx_v_retCode’
talib/_ta_lib.c:202556: warning: assignment from incompatible pointer type
talib/_ta_lib.c:202605: error: ‘__pyx_v_retCode’ undeclared (first use in this function)
talib/_ta_lib.c:202614: error: too many arguments to function ‘__pyx_f_5talib_7_ta_lib__ta_check_success’
talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_628stream_SQRT’:
talib/_ta_lib.c:202682: error: ‘TA_RetCode’ undeclared (first use in this function)
talib/_ta_lib.c:202682: error: expected ‘;’ before ‘__pyx_v_retCode’
talib/_ta_lib.c:202775: warning: assignment from incompatible pointer type
talib/_ta_lib.c:202824: error: ‘__pyx_v_retCode’ undeclared (first use in this function)
talib/_ta_lib.c:202833: error: too many arguments to function ‘__pyx_f_5talib_7_ta_lib__ta_check_success’
talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_630stream_STDDEV’:
talib/_ta_lib.c:202972: error: ‘TA_RetCode’ undeclared (first use in this function)
talib/_ta_lib.c:202972: error: expected ‘;’ before ‘__pyx_v_retCode’
talib/_ta_lib.c:203065: warning: assignment from incompatible pointer type
talib/_ta_lib.c:203114: error: ‘__pyx_v_retCode’ undeclared (first use in this function)
talib/_ta_lib.c:203123: error: too many arguments to function ‘__pyx_f_5talib_7_ta_lib__ta_check_success’
talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_632stream_STOCH’:
talib/_ta_lib.c:203334: error: ‘TA_RetCode’ undeclared (first use in this function)
talib/_ta_lib.c:203334: error: expected ‘;’ before ‘__pyx_v_retCode’
talib/_ta_lib.c:203434: warning: assignment from incompatible pointer type
talib/_ta_lib.c:203539: warning: assignment from incompatible pointer type
talib/_ta_lib.c:203644: warning: assignment from incompatible pointer type
talib/_ta_lib.c:203766: error: ‘__pyx_v_retCode’ undeclared (first use in this function)
talib/_ta_lib.c:203775: error: too many arguments to function ‘__pyx_f_5talib_7_ta_lib__ta_check_success’
talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_634stream_STOCHF’:
talib/_ta_lib.c:203968: error: ‘TA_RetCode’ undeclared (first use in this function)
talib/_ta_lib.c:203968: error: expected ‘;’ before ‘__pyx_v_retCode’
talib/_ta_lib.c:204068: warning: assignment from incompatible pointer type
talib/_ta_lib.c:204173: warning: assignment from incompatible pointer type
talib/_ta_lib.c:204278: warning: assignment from incompatible pointer type
talib/_ta_lib.c:204400: error: ‘__pyx_v_retCode’ undeclared (first use in this function)
talib/_ta_lib.c:204409: error: too many arguments to function ‘__pyx_f_5talib_7_ta_lib__ta_check_success’
talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_636stream_STOCHRSI’:
talib/_ta_lib.c:204594: error: ‘TA_RetCode’ undeclared (first use in this function)
talib/_ta_lib.c:204594: error: expected ‘;’ before ‘__pyx_v_retCode’
talib/_ta_lib.c:204690: warning: assignment from incompatible pointer type
talib/_ta_lib.c:204748: error: ‘__pyx_v_retCode’ undeclared (first use in this function)
talib/_ta_lib.c:204757: error: too many arguments to function ‘__pyx_f_5talib_7_ta_lib__ta_check_success’
talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_638stream_SUB’:
talib/_ta_lib.c:204886: error: ‘TA_RetCode’ undeclared (first use in this function)
talib/_ta_lib.c:204886: error: expected ‘;’ before ‘__pyx_v_retCode’
talib/_ta_lib.c:204981: warning: assignment from incompatible pointer type
talib/_ta_lib.c:205086: warning: assignment from incompatible pointer type
talib/_ta_lib.c:205167: error: ‘__pyx_v_retCode’ undeclared (first use in this function)
talib/_ta_lib.c:205176: error: too many arguments to function ‘__pyx_f_5talib_7_ta_lib__ta_check_success’
talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_640stream_SUM’:
talib/_ta_lib.c:205300: error: ‘TA_RetCode’ undeclared (first use in this function)
talib/_ta_lib.c:205300: error: expected ‘;’ before ‘__pyx_v_retCode’
talib/_ta_lib.c:205393: warning: assignment from incompatible pointer type
talib/_ta_lib.c:205442: error: ‘__pyx_v_retCode’ undeclared (first use in this function)
talib/_ta_lib.c:205451: error: too many arguments to function ‘__pyx_f_5talib_7_ta_lib__ta_check_success’
talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_642stream_T3’:
talib/_ta_lib.c:205590: error: ‘TA_RetCode’ undeclared (first use in this function)
talib/_ta_lib.c:205590: error: expected ‘;’ before ‘__pyx_v_retCode’
talib/_ta_lib.c:205683: warning: assignment from incompatible pointer type
talib/_ta_lib.c:205732: error: ‘__pyx_v_retCode’ undeclared (first use in this function)
talib/_ta_lib.c:205741: error: too many arguments to function ‘__pyx_f_5talib_7_ta_lib__ta_check_success’
talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_644stream_TAN’:
talib/_ta_lib.c:205809: error: ‘TA_RetCode’ undeclared (first use in this function)
talib/_ta_lib.c:205809: error: expected ‘;’ before ‘__pyx_v_retCode’
talib/_ta_lib.c:205902: warning: assignment from incompatible pointer type
talib/_ta_lib.c:205951: error: ‘__pyx_v_retCode’ undeclared (first use in this function)
talib/_ta_lib.c:205960: error: too many arguments to function ‘__pyx_f_5talib_7_ta_lib__ta_check_success’
talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_646stream_TANH’:
talib/_ta_lib.c:206028: error: ‘TA_RetCode’ undeclared (first use in this function)
talib/_ta_lib.c:206028: error: expected ‘;’ before ‘__pyx_v_retCode’
talib/_ta_lib.c:206121: warning: assignment from incompatible pointer type
talib/_ta_lib.c:206170: error: ‘__pyx_v_retCode’ undeclared (first use in this function)
talib/_ta_lib.c:206179: error: too many arguments to function ‘__pyx_f_5talib_7_ta_lib__ta_check_success’
talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_648stream_TEMA’:
talib/_ta_lib.c:206302: error: ‘TA_RetCode’ undeclared (first use in this function)
talib/_ta_lib.c:206302: error: expected ‘;’ before ‘__pyx_v_retCode’
talib/_ta_lib.c:206395: warning: assignment from incompatible pointer type
talib/_ta_lib.c:206444: error: ‘__pyx_v_retCode’ undeclared (first use in this function)
talib/_ta_lib.c:206453: error: too many arguments to function ‘__pyx_f_5talib_7_ta_lib__ta_check_success’
talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_650stream_TRANGE’:
talib/_ta_lib.c:206582: error: ‘TA_RetCode’ undeclared (first use in this function)
talib/_ta_lib.c:206582: error: expected ‘;’ before ‘__pyx_v_retCode’
talib/_ta_lib.c:206679: warning: assignment from incompatible pointer type
talib/_ta_lib.c:206784: warning: assignment from incompatible pointer type
talib/_ta_lib.c:206889: warning: assignment from incompatible pointer type
talib/_ta_lib.c:207002: error: ‘__pyx_v_retCode’ undeclared (first use in this function)
talib/_ta_lib.c:207011: error: too many arguments to function ‘__pyx_f_5talib_7_ta_lib__ta_check_success’
talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_652stream_TRIMA’:
talib/_ta_lib.c:207136: error: ‘TA_RetCode’ undeclared (first use in this function)
talib/_ta_lib.c:207136: error: expected ‘;’ before ‘__pyx_v_retCode’
talib/_ta_lib.c:207229: warning: assignment from incompatible pointer type
talib/_ta_lib.c:207278: error: ‘__pyx_v_retCode’ undeclared (first use in this function)
talib/_ta_lib.c:207287: error: too many arguments to function ‘__pyx_f_5talib_7_ta_lib__ta_check_success’
talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_654stream_TRIX’:
talib/_ta_lib.c:207410: error: ‘TA_RetCode’ undeclared (first use in this function)
talib/_ta_lib.c:207410: error: expected ‘;’ before ‘__pyx_v_retCode’
talib/_ta_lib.c:207503: warning: assignment from incompatible pointer type
talib/_ta_lib.c:207552: error: ‘__pyx_v_retCode’ undeclared (first use in this function)
talib/_ta_lib.c:207561: error: too many arguments to function ‘__pyx_f_5talib_7_ta_lib__ta_check_success’
talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_656stream_TSF’:
talib/_ta_lib.c:207684: error: ‘TA_RetCode’ undeclared (first use in this function)
talib/_ta_lib.c:207684: error: expected ‘;’ before ‘__pyx_v_retCode’
talib/_ta_lib.c:207777: warning: assignment from incompatible pointer type
talib/_ta_lib.c:207826: error: ‘__pyx_v_retCode’ undeclared (first use in this function)
talib/_ta_lib.c:207835: error: too many arguments to function ‘__pyx_f_5talib_7_ta_lib__ta_check_success’
talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_658stream_TYPPRICE’:
talib/_ta_lib.c:207964: error: ‘TA_RetCode’ undeclared (first use in this function)
talib/_ta_lib.c:207964: error: expected ‘;’ before ‘__pyx_v_retCode’
talib/_ta_lib.c:208061: warning: assignment from incompatible pointer type
talib/_ta_lib.c:208166: warning: assignment from incompatible pointer type
talib/_ta_lib.c:208271: warning: assignment from incompatible pointer type
talib/_ta_lib.c:208384: error: ‘__pyx_v_retCode’ undeclared (first use in this function)
talib/_ta_lib.c:208393: error: too many arguments to function ‘__pyx_f_5talib_7_ta_lib__ta_check_success’
talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_660stream_ULTOSC’:
talib/_ta_lib.c:208574: error: ‘TA_RetCode’ undeclared (first use in this function)
talib/_ta_lib.c:208574: error: expected ‘;’ before ‘__pyx_v_retCode’
talib/_ta_lib.c:208671: warning: assignment from incompatible pointer type
talib/_ta_lib.c:208776: warning: assignment from incompatible pointer type
talib/_ta_lib.c:208881: warning: assignment from incompatible pointer type
talib/_ta_lib.c:208994: error: ‘__pyx_v_retCode’ undeclared (first use in this function)
talib/_ta_lib.c:209003: error: too many arguments to function ‘__pyx_f_5talib_7_ta_lib__ta_check_success’
talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_662stream_VAR’:
talib/_ta_lib.c:209144: error: ‘TA_RetCode’ undeclared (first use in this function)
talib/_ta_lib.c:209144: error: expected ‘;’ before ‘__pyx_v_retCode’
talib/_ta_lib.c:209237: warning: assignment from incompatible pointer type
talib/_ta_lib.c:209286: error: ‘__pyx_v_retCode’ undeclared (first use in this function)
talib/_ta_lib.c:209295: error: too many arguments to function ‘__pyx_f_5talib_7_ta_lib__ta_check_success’
talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_664stream_WCLPRICE’:
talib/_ta_lib.c:209424: error: ‘TA_RetCode’ undeclared (first use in this function)
talib/_ta_lib.c:209424: error: expected ‘;’ before ‘__pyx_v_retCode’
talib/_ta_lib.c:209521: warning: assignment from incompatible pointer type
talib/_ta_lib.c:209626: warning: assignment from incompatible pointer type
talib/_ta_lib.c:209731: warning: assignment from incompatible pointer type
talib/_ta_lib.c:209844: error: ‘__pyx_v_retCode’ undeclared (first use in this function)
talib/_ta_lib.c:209853: error: too many arguments to function ‘__pyx_f_5talib_7_ta_lib__ta_check_success’
talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_666stream_WILLR’:
talib/_ta_lib.c:210002: error: ‘TA_RetCode’ undeclared (first use in this function)
talib/_ta_lib.c:210002: error: expected ‘;’ before ‘__pyx_v_retCode’
talib/_ta_lib.c:210099: warning: assignment from incompatible pointer type
talib/_ta_lib.c:210204: warning: assignment from incompatible pointer type
talib/_ta_lib.c:210309: warning: assignment from incompatible pointer type
talib/_ta_lib.c:210422: error: ‘__pyx_v_retCode’ undeclared (first use in this function)
talib/_ta_lib.c:210431: error: too many arguments to function ‘__pyx_f_5talib_7_ta_lib__ta_check_success’
talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_668stream_WMA’:
talib/_ta_lib.c:210556: error: ‘TA_RetCode’ undeclared (first use in this function)
talib/_ta_lib.c:210556: error: expected ‘;’ before ‘__pyx_v_retCode’
talib/_ta_lib.c:210649: warning: assignment from incompatible pointer type
talib/_ta_lib.c:210698: error: ‘__pyx_v_retCode’ undeclared (first use in this function)
talib/_ta_lib.c:210707: error: too many arguments to function ‘__pyx_f_5talib_7_ta_lib__ta_check_success’
talib/_ta_lib.c: In function ‘PyInit__ta_lib’:
talib/_ta_lib.c:243887: warning: implicit declaration of function ‘TA_GetVersionString’
talib/_ta_lib.c:243887: warning: passing argument 1 of ‘PyBytes_FromString’ makes pointer from integer without a cast
/opt/alt/python35/include/python3.5m/bytesobject.h:52: note: expected ‘const char *’ but argument is of type ‘int’
talib/_ta_lib.c: At top level:
talib/_ta_lib.c:253063: error: expected ‘)’ before ‘value’
talib/_ta_lib.c:253156: error: expected ‘)’ before ‘value’
talib/_ta_lib.c:253218: error: expected ‘)’ before ‘value’
talib/_ta_lib.c:253249: error: expected ‘)’ before ‘value’
talib/_ta_lib.c:253280: error: expected ‘)’ before ‘value’
**talib/_ta_lib.c:253652: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘__Pyx_PyInt_As_TA_RetCode’
talib/_ta_lib.c:254030: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘__Pyx_PyInt_As_TA_FuncUnstId’
talib/_ta_lib.c:254408: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘__Pyx_PyInt_As_TA_CandleSettingType’
talib/_ta_lib.c:254597: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘__Pyx_PyInt_As_TA_RangeType’
error: command 'gcc' failed with exit status 1**

@mrjbq7   can you help on this

**Comment by mrjbq7** [comment]
Looks strange.

Partly looks like not having TA-LIB C Library dependency installed.

Partly looks like funny C parsing issues.

**Comment by mrjbq7** [comment]
Closing all installation issues, if someone has a specific problem please open a new one.
