### ISSUE TITLE
Cannot install on M1 Mac Mini

### ISSUE THREAD

**Issue by joris1995** [mrjbq7/ta-lib#384]
I just got a Mac Mini M1 as a server and am now setting it up to run my trading algorithm. Ive been able to install most things as one normally would (homebrew, python). Numpy and pandas would not install that way, but using [this](https://github.com/numpy/numpy/issues/17807#issuecomment-731014921) answer I managed to get those setup. I then proceeded to install TA-Lib using home-brew, which went fine, but when I ran pip install TA-Lib, I got this:

```
ERROR: Command errored out with exit status 1:
     command: /Applications/Xcode.app/Contents/Developer/usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/pf/k3f1p6b56nd18fym9vxhcr800000gn/T/pip-install-ilky43_u/ta-lib_cced6d53bef14a41ba8ae4468eeca09d/setup.py'"'"'; __file__='"'"'/private/var/folders/pf/k3f1p6b56nd18fym9vxhcr800000gn/T/pip-install-ilky43_u/ta-lib_cced6d53bef14a41ba8ae4468eeca09d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/pf/k3f1p6b56nd18fym9vxhcr800000gn/T/pip-record-9m3vn6u4/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /Users/stockbot/Library/Python/3.8/include/python3.8/TA-Lib
         cwd: /private/var/folders/pf/k3f1p6b56nd18fym9vxhcr800000gn/T/pip-install-ilky43_u/ta-lib_cced6d53bef14a41ba8ae4468eeca09d/
    Complete output (27 lines):
    /private/var/folders/pf/k3f1p6b56nd18fym9vxhcr800000gn/T/pip-install-ilky43_u/ta-lib_cced6d53bef14a41ba8ae4468eeca09d/setup.py:71: UserWarning: Cannot find ta-lib library, installation may fail.
      warnings.warn('Cannot find ta-lib library, installation may fail.')
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.14.6-arm64-3.8
    creating build/lib.macosx-10.14.6-arm64-3.8/talib
    copying talib/abstract.py -> build/lib.macosx-10.14.6-arm64-3.8/talib
    copying talib/test_abstract.py -> build/lib.macosx-10.14.6-arm64-3.8/talib
    copying talib/deprecated.py -> build/lib.macosx-10.14.6-arm64-3.8/talib
    copying talib/__init__.py -> build/lib.macosx-10.14.6-arm64-3.8/talib
    copying talib/stream.py -> build/lib.macosx-10.14.6-arm64-3.8/talib
    copying talib/test_pandas.py -> build/lib.macosx-10.14.6-arm64-3.8/talib
    copying talib/test_data.py -> build/lib.macosx-10.14.6-arm64-3.8/talib
    copying talib/test_func.py -> build/lib.macosx-10.14.6-arm64-3.8/talib
    copying talib/test_stream.py -> build/lib.macosx-10.14.6-arm64-3.8/talib
    running build_ext
    building 'talib._ta_lib' extension
    creating build/temp.macosx-10.14.6-arm64-3.8
    creating build/temp.macosx-10.14.6-arm64-3.8/talib
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -I/usr/include -I/usr/local/include -I/opt/include -I/opt/local/include -I/Users/stockbot/Library/Python/3.8/lib/python/site-packages/numpy/core/include -I/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -c talib/_ta_lib.c -o build/temp.macosx-10.14.6-arm64-3.8/talib/_ta_lib.o
    talib/_ta_lib.c:611:10: fatal error: 'ta-lib/ta_defs.h' file not found
    #include "ta-lib/ta_defs.h"
             ^~~~~~~~~~~~~~~~~~
    1 error generated.
    error: command 'clang' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Applications/Xcode.app/Contents/Developer/usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/pf/k3f1p6b56nd18fym9vxhcr800000gn/T/pip-install-ilky43_u/ta-lib_cced6d53bef14a41ba8ae4468eeca09d/setup.py'"'"'; __file__='"'"'/private/var/folders/pf/k3f1p6b56nd18fym9vxhcr800000gn/T/pip-install-ilky43_u/ta-lib_cced6d53bef14a41ba8ae4468eeca09d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/pf/k3f1p6b56nd18fym9vxhcr800000gn/T/pip-record-9m3vn6u4/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /Users/stockbot/Library/Python/3.8/include/python3.8/TA-Lib Check the logs for full command output.
``` 

At the beginning of this error, one can see the message "UserWarning: Cannot find ta-lib library, installation may fail.". From online investigation I learned that this occurs when it can't find the underlying TA-Lib installation, which I installed with Homebrew. This is interesting, since I followed the exact same steps as I did on my intel MBP, and there it works fine.

How do I fix this?

**Comment by joris1995** [comment]
Apparently posted this twice, so closing this one

**Comment by dark724** [comment]
Hey there, how did you solve this issue? 
You wrote you have opened it twice. Can you please give the link to the solution or describe yours?
Thanks

**Comment by mrjbq7** [comment]
brew install ta-lib
export TA_INCLUDE_PATH="$(brew --prefix ta-lib)/include"
export TA_LIBRARY_PATH="$(brew --prefix ta-lib)/lib"
pip install ta-lib

**Comment by mrjbq7** [comment]
﻿
brew install ta-lib
export TA_INCLUDE_PATH="$(brew --prefix ta-lib)/include"
export TA_LIBRARY_PATH="$(brew --prefix ta-lib)/lib"
pip install ta-lib

**Comment by A3-88** [comment]
Hi. This solution is not working for me. I am getting this error:
ImportError: dlopen(/Users/.../venv/lib/python3.9/site-packages/talib/_ta_lib.cpython-39-darwin.so, 2): Symbol not found: _TA_ACOS

I am using Python 3.9 and a virtual environment.

Any help is appreciated!
Thanks :)

**Comment by totorochina** [comment]
If you don't mind using anaconda,
conda install -c conda-forge ta-lib
works find for M1.

**Comment by ManuelSchneid3r** [comment]
> conda install -c conda-forge ta-lib

PackagesNotFoundError. Did I miss something?

**Comment by 42piratas** [comment]
I'm on a Mac M1 Max with macOS Ventura 13.1. Channels that I have tried:

```
conda install -c conda-forge ta-lib
conda install -c masdeseiscaracteres ta-lib
conda install -c quantopian ta-lib   
conda install -c developer ta-lib
```

But I always get the same:

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - ta-lib

Current channels:

  - https://conda.anaconda.org/developer/osx-arm64
  - https://conda.anaconda.org/developer/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by mrjbq7** [comment]
I don’t use conda personally, but the package being discussed is not available on osx-arm64:

https://anaconda.org/conda-forge/ta-lib

Is there a reason installing with pip does not work for you?

**Comment by 42piratas** [comment]
Usually, I don't use conda either, but it looked like the main solution people were finding to install it when facing installation issues. In my case, `pip install ta-lib` returns:

```
Collecting ta-lib
  Using cached TA-Lib-0.4.25.tar.gz (271 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy
  Using cached numpy-1.24.2-cp310-cp310-macosx_11_0_arm64.whl (13.9 MB)
Building wheels for collected packages: ta-lib
  Building wheel for ta-lib (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for ta-lib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      <string>:77: UserWarning: Cannot find ta-lib library, installation may fail.
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-11.1-arm64-cpython-310
      creating build/lib.macosx-11.1-arm64-cpython-310/talib
      copying talib/abstract.py -> build/lib.macosx-11.1-arm64-cpython-310/talib
      copying talib/test_polars.py -> build/lib.macosx-11.1-arm64-cpython-310/talib
      copying talib/test_abstract.py -> build/lib.macosx-11.1-arm64-cpython-310/talib
      copying talib/deprecated.py -> build/lib.macosx-11.1-arm64-cpython-310/talib
      copying talib/__init__.py -> build/lib.macosx-11.1-arm64-cpython-310/talib
      copying talib/stream.py -> build/lib.macosx-11.1-arm64-cpython-310/talib
      copying talib/test_pandas.py -> build/lib.macosx-11.1-arm64-cpython-310/talib
      copying talib/test_data.py -> build/lib.macosx-11.1-arm64-cpython-310/talib
      copying talib/test_func.py -> build/lib.macosx-11.1-arm64-cpython-310/talib
      copying talib/test_stream.py -> build/lib.macosx-11.1-arm64-cpython-310/talib
      running build_ext
      building 'talib._ta_lib' extension
      creating build/temp.macosx-11.1-arm64-cpython-310
      creating build/temp.macosx-11.1-arm64-cpython-310/talib
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/42piratas/miniconda3/include -arch arm64 -fPIC -O2 -isystem /Users/42piratas/miniconda3/include -arch arm64 -I/usr/include -I/usr/local/include -I/opt/include -I/opt/local/include -I/opt/homebrew/include -I/opt/homebrew/opt/ta-lib/include -I/private/var/folders/sk/gtzzsxh125n78sjknct325c40000gn/T/pip-build-env-kxxpzotf/normal/lib/python3.10/site-packages/numpy/core/include -I/Users/42piratas/miniconda3/include/python3.10 -c talib/_ta_lib.c -o build/temp.macosx-11.1-arm64-cpython-310/talib/_ta_lib.o
      xcrun: error: unable to load libxcrun (dlopen(/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib, 0x0005): tried: '/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need '')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib' (no such file), '/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need ''))).
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ta-lib
Failed to build ta-lib
ERROR: Could not build wheels for ta-lib, which is required to install pyproject.toml-based projects
```

**Comment by mrjbq7** [comment]
That error with xcrun implies you have the Intel version of Xcode command line tools installed? 

Which makes me wonder if you migrated from an Intel mac and need to run ``xcode-select --install`` and get the apple silicon ones, or if the python you are using is Intel or not?

if the python is Intel , you can use the previous conda conmand prefix with `arch -x86_64 conda …``

**Comment by 42piratas** [comment]
I am using Python 3.11, which supports the m1. 

I even  suppose this is what `but is an incompatible architecture (have 'x86_64', need '')))` mean, no?

**Comment by mrjbq7** [comment]
Apple laptops run natively arm64, and with Rosetta support x86_64.

If you want to use arm64, or if you want to use x86_64, both will work on the M1.

BUT.

You can't mix architectures.

```
$ which python3.11
/opt/homebrew/opt/python@3.11/bin/python3.11

$ file /opt/homebrew/opt/python@3.11/bin/python3.11
/opt/homebrew/opt/python@3.11/bin/python3.11: Mach-O 64-bit executable arm64
```

My python3.11 is native arm64.

What is yours?

**Comment by mrjbq7** [comment]
Did you try installing arm64 developer tools using ``xcode-select --install``?

Did it change the error message you get?

**Comment by 42piratas** [comment]
You're right, something changed after upgrading the dev tools.

There's a new error now, though.

` Collecting ta-lib
  Using cached TA-Lib-0.4.25.tar.gz (271 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy
  Using cached numpy-1.24.2-cp311-cp311-macosx_11_0_arm64.whl (13.8 MB)
Building wheels for collected packages: ta-lib
  Building wheel for ta-lib (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for ta-lib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      <string>:77: UserWarning: Cannot find ta-lib library, installation may fail.
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-cpython-311
      creating build/lib.macosx-10.9-universal2-cpython-311/talib
      copying talib/abstract.py -> build/lib.macosx-10.9-universal2-cpython-311/talib
      copying talib/test_polars.py -> build/lib.macosx-10.9-universal2-cpython-311/talib
      copying talib/test_abstract.py -> build/lib.macosx-10.9-universal2-cpython-311/talib
      copying talib/deprecated.py -> build/lib.macosx-10.9-universal2-cpython-311/talib
      copying talib/__init__.py -> build/lib.macosx-10.9-universal2-cpython-311/talib
      copying talib/stream.py -> build/lib.macosx-10.9-universal2-cpython-311/talib
      copying talib/test_pandas.py -> build/lib.macosx-10.9-universal2-cpython-311/talib
      copying talib/test_data.py -> build/lib.macosx-10.9-universal2-cpython-311/talib
      copying talib/test_func.py -> build/lib.macosx-10.9-universal2-cpython-311/talib
      copying talib/test_stream.py -> build/lib.macosx-10.9-universal2-cpython-311/talib
      running build_ext
      building 'talib._ta_lib' extension
      creating build/temp.macosx-10.9-universal2-cpython-311
      creating build/temp.macosx-10.9-universal2-cpython-311/talib
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/usr/include -I/usr/local/include -I/opt/include -I/opt/local/include -I/opt/homebrew/include -I/opt/homebrew/opt/ta-lib/include -I/private/var/folders/sk/gtzzsxh125n78sjknct325c40000gn/T/pip-build-env-he643hlk/normal/lib/python3.11/site-packages/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c talib/_ta_lib.c -o build/temp.macosx-10.9-universal2-cpython-311/talib/_ta_lib.o
      talib/_ta_lib.c:747:10: fatal error: 'ta-lib/ta_defs.h' file not found
      #include "ta-lib/ta_defs.h"
               ^~~~~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ta-lib
Failed to build ta-lib
ERROR: Could not build wheels for ta-lib, which is required to install pyproject.toml-based projects`

**Comment by mrjbq7** [comment]
>  <string>:77: UserWarning: Cannot find ta-lib library, installation may fail.
      
You need to install the TA-Lib C library. 

Look at the README but basically “brew install ta-lib” first. And you want it to match the architecture of your python.

**Comment by 42piratas** [comment]
@mrjbq7 Thank you so much for all your quick and always thoughtful replies. It works now. Cheers! 🍻
