### ISSUE TITLE
Cannot install on M1 Mac mini

### ISSUE THREAD

**Issue by joris1995** [mrjbq7/ta-lib#385]
I just got a Mac Mini M1 as a server and am now setting it up to run my trading algorithm. Ive been able to install most things as one normally would (homebrew, python). Numpy and pandas would not install that way, but using [this](https://github.com/numpy/numpy/issues/17807#issuecomment-731014921) answer I managed to get those setup. I then proceeded to install TA-Lib using Homebrew, which went fine, but when I ran pip install TA-Lib, I got this:

```
ERROR: Command errored out with exit status 1:
     command: /Applications/Xcode.app/Contents/Developer/usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/pf/k3f1p6b56nd18fym9vxhcr800000gn/T/pip-install-ilky43_u/ta-lib_cced6d53bef14a41ba8ae4468eeca09d/setup.py'"'"'; __file__='"'"'/private/var/folders/pf/k3f1p6b56nd18fym9vxhcr800000gn/T/pip-install-ilky43_u/ta-lib_cced6d53bef14a41ba8ae4468eeca09d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/pf/k3f1p6b56nd18fym9vxhcr800000gn/T/pip-record-9m3vn6u4/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /Users/stockbot/Library/Python/3.8/include/python3.8/TA-Lib
         cwd: /private/var/folders/pf/k3f1p6b56nd18fym9vxhcr800000gn/T/pip-install-ilky43_u/ta-lib_cced6d53bef14a41ba8ae4468eeca09d/
    Complete output (27 lines):
    /private/var/folders/pf/k3f1p6b56nd18fym9vxhcr800000gn/T/pip-install-ilky43_u/ta-lib_cced6d53bef14a41ba8ae4468eeca09d/setup.py:71: UserWarning: Cannot find ta-lib library, installation may fail.
      warnings.warn('Cannot find ta-lib library, installation may fail.')
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.14.6-arm64-3.8
    creating build/lib.macosx-10.14.6-arm64-3.8/talib
    copying talib/abstract.py -> build/lib.macosx-10.14.6-arm64-3.8/talib
    copying talib/test_abstract.py -> build/lib.macosx-10.14.6-arm64-3.8/talib
    copying talib/deprecated.py -> build/lib.macosx-10.14.6-arm64-3.8/talib
    copying talib/__init__.py -> build/lib.macosx-10.14.6-arm64-3.8/talib
    copying talib/stream.py -> build/lib.macosx-10.14.6-arm64-3.8/talib
    copying talib/test_pandas.py -> build/lib.macosx-10.14.6-arm64-3.8/talib
    copying talib/test_data.py -> build/lib.macosx-10.14.6-arm64-3.8/talib
    copying talib/test_func.py -> build/lib.macosx-10.14.6-arm64-3.8/talib
    copying talib/test_stream.py -> build/lib.macosx-10.14.6-arm64-3.8/talib
    running build_ext
    building 'talib._ta_lib' extension
    creating build/temp.macosx-10.14.6-arm64-3.8
    creating build/temp.macosx-10.14.6-arm64-3.8/talib
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -I/usr/include -I/usr/local/include -I/opt/include -I/opt/local/include -I/Users/stockbot/Library/Python/3.8/lib/python/site-packages/numpy/core/include -I/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -c talib/_ta_lib.c -o build/temp.macosx-10.14.6-arm64-3.8/talib/_ta_lib.o
    talib/_ta_lib.c:611:10: fatal error: 'ta-lib/ta_defs.h' file not found
    #include "ta-lib/ta_defs.h"
             ^~~~~~~~~~~~~~~~~~
    1 error generated.
    error: command 'clang' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Applications/Xcode.app/Contents/Developer/usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/pf/k3f1p6b56nd18fym9vxhcr800000gn/T/pip-install-ilky43_u/ta-lib_cced6d53bef14a41ba8ae4468eeca09d/setup.py'"'"'; __file__='"'"'/private/var/folders/pf/k3f1p6b56nd18fym9vxhcr800000gn/T/pip-install-ilky43_u/ta-lib_cced6d53bef14a41ba8ae4468eeca09d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/pf/k3f1p6b56nd18fym9vxhcr800000gn/T/pip-record-9m3vn6u4/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /Users/stockbot/Library/Python/3.8/include/python3.8/TA-Lib Check the logs for full command output.
``` 

At the beginning of this error, one can see the message "UserWarning: Cannot find ta-lib library, installation may fail.". From online investigation I learned that this occurs when it can't find the underlying TA-Lib installation, which I installed with Homebrew. This is interesting, since I followed the exact same steps as I did on my intel MBP, and there it works fine. My python version is 3.8.2

How do I fix this? Any guidance would be highly appreciated

**Comment by mrjbq7** [comment]
That error indicates ``TA-Lib`` C library is not installed, or is installed for the wrong architecture.

I added paths for ``/opt/homebrew`` in 947f48078c3cf403c5560b26c6587e59ffec7aa1, so it shouldn't require additional work to support if you use the latest git master, otherwise you need to patch the locations your self or use the environment variable to override.

Typically the debug process would be to:

1) Check the architecture of libta_lib.dylib:

```
$ file /opt/homebrew/opt/ta-lib/lib/libta_lib.dylib 
/opt/homebrew/opt/ta-lib/lib/libta_lib.dylib: Mach-O 64-bit dynamically linked shared library arm64
```

2) Check the architecture of python:

```
$ file $(which python3.9)
/opt/homebrew/bin/python3.9: Mach-O 64-bit executable arm64
```

3) Make sure you are installing with the right ``pip``:

```
$ python3.9 -m pip install ta-lib
```

etc.

**Comment by mrjbq7** [comment]
If you want to use the last pypi release:

```
$ TA_INCLUDE_PATH=/opt/homebrew/include
$ TA_LIBRARY_PATH=/opt/homebrew/lib
$ python3.9 -m pip install ta-lib
```

**Comment by joris1995** [comment]
Thanks for your quick response. I followed through the steps of your first answer. I used python3 rather than python3.9 commands as I currently have python 3.8.2 installed. The results are:

1: 
`$ file /opt/homebrew/opt/ta-lib/lib/libta_lib.dylib
/opt/homebrew/opt/ta-lib/lib/libta_lib.dylib: Mach-O 64-bit dynamically linked shared library arm64`

2:
$ file $(which python3)
```
/usr/bin/python3: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64e:Mach-O 64-bit executable arm64e]
/usr/bin/python3 (for architecture x86_64):	Mach-O 64-bit executable x86_64
/usr/bin/python3 (for architecture arm64e):	Mach-O 64-bit executable arm64e
```

Step 3 results in the same error as I reported in my original issue. The same goed when I follow the steps from your second answer, adding those paths manually.

I know it's not much, but hopefully my output clarifies it a bit to you. The only thing that comes to my mind right now that might cause this, is the Homebrew installed TA-Lib in the 'wrong' location, meaning that something is wrong with homebrew. I would find this weird though, since I only installed just now and everything worked as expected. When I run brew list, I can also see it installed ta-lib...

Would you have any other suggestion(s) how I can solve this issue and install TA-lib?

**Comment by mrjbq7** [comment]
If it’s not in /opt/homebrew/lib

Then maybe try

$ brew link ta-lib

Or use the path to where it was installed which from memory is something
like:

/opt/homebrew/opt/ta-lib

It’s possible you need to export the TA_LIBRARY_PATH or put them on the
same command line as your pip install.

**Comment by ashtianicode** [comment]
I've been trying to install ta-lib on a mac m1 and didn't ever get `error: command 'clang' failed with exit status 1`.
after `brew install ta-lib` and `python3.8 -m pip install ta-lib ` or `python3 setup.py install`, when I `import talib` I get:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/involved/opt/anaconda3/lib/python3.8/site-packages/talib/__init__.py", line 52, in <module>
    from ._ta_lib import (
ImportError: dlopen(/Users/involved/opt/anaconda3/lib/python3.8/site-packages/talib/_ta_lib.cpython-38-darwin.so, 2): Symbol not found: _TA_ACOS
  Referenced from: /Users/involved/opt/anaconda3/lib/python3.8/site-packages/talib/_ta_lib.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/involved/opt/anaconda3/lib/python3.8/site-packages/talib/_ta_lib.cpython-38-darwin.so`

I removed my homebrew, and installed it under Rosetta2, and a new python3.9 but got even more complicated to resolve. 

my pythons are:
` file $(which python3.9)
/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64]
/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 (for architecture x86_64):	Mach-O 64-bit executable x86_64
/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 (for architecture arm64):	Mach-O 64-bit executable arm64
`

and 

`file $(which python3.8)         
/Users/involved/opt/anaconda3/bin/python3.8: Mach-O 64-bit executable x86_64
`

**Comment by ashtianicode** [comment]
I switched to Rosetta2 terminal and this finally worked very well:

arch -x86_64 brew install python@3.9
arch -x86_64 brew install ta-lib
arch -x86_64 python3.9 -m pip install ta-lib

**Comment by joris1995** [comment]
@mrjbq7 Setting TA_LIBRARY_PATH did not help either, but I can confirm that the solution of @ashtianicode, installing it under rosetta2, works. Thanks a lot for your assistance!

**Comment by twopirllc** [comment]
Hello @mrjbq7,

Just want to 2nd the solution provided by @ashtianicode. I use TA-Lib for correlation testing with my [Pandas TA Library](https://github.com/twopirllc/pandas-ta). Thanks again more making this lightweight TA-Lib wrapper @mrjbq7.

Kind Regards,
KJ

**Comment by mrjbq7** [comment]
It's true you can always just run it all under Rosetta, which is what that solution provides.

However, ``ta-lib`` should be installable using ``arm64`` as well, if your architectures are all consistent.

**Comment by johnxiongs** [comment]
hello ,do you install talib on m1 mac success now? I met the problem

**Comment by matanume** [comment]
> That error indicates `TA-Lib` C library is not installed, or is installed for the wrong architecture.
> 
> I added paths for `/opt/homebrew` in [947f480](https://github.com/mrjbq7/ta-lib/commit/947f48078c3cf403c5560b26c6587e59ffec7aa1), so it shouldn't require additional work to support if you use the latest git master, otherwise you need to patch the locations your self or use the environment variable to override.
> 
> Typically the debug process would be to:
> 
> 1. Check the architecture of libta_lib.dylib:
> 
> ```
> $ file /opt/homebrew/opt/ta-lib/lib/libta_lib.dylib 
> /opt/homebrew/opt/ta-lib/lib/libta_lib.dylib: Mach-O 64-bit dynamically linked shared library arm64
> ```
> 
> 1. Check the architecture of python:
> 
> ```
> $ file $(which python3.9)
> /opt/homebrew/bin/python3.9: Mach-O 64-bit executable arm64
> ```
> 
> 1. Make sure you are installing with the right `pip`:
> 
> ```
> $ python3.9 -m pip install ta-lib
> ```
> 
> etc.

Work for me I do uninstall old ta-libs then follow your instruction.
