### ISSUE TITLE
Installation changes for Windows 7

### ISSUE THREAD

**Issue by bkelemen56** [mrjbq7/ta-lib#4]
I performed these steps to get the wrapper to work under Windows 7. It may help someone.
Regards
Bill
# Preparation steps:

Get Microsoft C++ 2008 and TA-Lib installed on Windows. I'm using Windows 7 64-bit but this should work also on 32-bit.
1. If you don't have "Microsoft Visual Studio 2008 Express Editions with SP1" installed, get it from: http://www.microsoft.com/en-us/download/details.aspx?id=14597
2. Download ta-lib-0.4.0-msvc.zip from http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-msvc.zip, unpack into c:\ta-lib. No need to re-build ta-lib on Windows as the distribution zip file already has the library built.
# Building mrjbq7-ta-lib for Windows:

I got the latest version of the Python wrapper for TA-Lib from https://github.com/mrjbq7/ta-lib using the ZIP button. I unpacked the zip file into C:\python-lib (you can pick any other folder). In my case, the zip was unpacked into C:\python-lib\mrjbq7-ta-lib-629b6c6.

In this folder I did the following:
## I) Modified setup.py as follows:
1. Changed paths for win32 platform to use my installation of ta-lib in c:\ta-lib"

elif sys.platform == "win32":
    include_talib_dir = r"c:\ta-lib\c\include"
    lib_talib_dir = r"c:\ta-lib\c\lib"
1. Changed ta-lib library name from "ta_lib" to "ta_libc_cdr" 
   (pre-built ta-lib library cdr as described in TA-Lib C/C++ API Documentation for Windows MSVC http://ta-lib.org/d_api/d_api.html#How%20to%20start%20using%20TA-LIB)

ext = Extension("talib", ["talib.pyx"],
    include_dirs=[numpy.get_include(), include_talib_dir],
    library_dirs=[lib_talib_dir],
    libraries=["ta_libc_cdr"]
## II) Modified talib.c:

I know this file is generated by Cython so there should be a way to place my change (#define) in the talib.pyx file, but as I'm not an expert on Cython I will leave this change to John.

Because I was getting "unresolved external symbol _isnan" while linking the wrapper with Visual Studio 2008 (apparently VS 2008 doesn't expose _isnan but does isnan), I added this line to the talib.c file:
# define isnan(x) _isnan(x)              /\* Added BK 2012-07-02 */

I placed it inside the following #if statement in talib.c so it only applies to Windows: 
# if defined(WIN32) || defined(MS_WINDOWS)
# define _USE_MATH_DEFINES
# define isnan(x) _isnan(x)              /\* Added BK 2012-07-02 */
# endif
## III) Build:

Then open a command window and change directory to where you unpacked the wrapper. In my case this is C:\python-lib\mrjbq7-ta-lib-629b6c6. Then run:

python setup.py install

and it should build.

I did get a lot of warnings like:
talib.c(4095) : warning C4146: unary minus operator applied to unsigned type, result still unsigned

as well as these two warnings:
talib.c(117719) : warning C4101: 'getbuffer_cobj' : unreferenced local variable
talib.c(117759) : warning C4101: 'releasebuffer_cobj' : unreferenced local variable

but the code compiled, linked, installed and ran perfectly.

**Comment by skytalemcc** [comment]
Hi ,I install the ta-lib in the centos 6.8 but also meet the gcc issue .could you please kindly advise it ,thanks
 talib/common.c: At top level:
  talib/common.c:3590: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘__Pyx_PyInt_As_TA_RetCode’
  talib/common.c:3685: error: expected ‘)’ before ‘value’
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for TA-Lib
  Running setup.py clean for TA-Lib
Failed to build TA-Lib
Installing collected packages: TA-Lib
  Running setup.py install for TA-Lib ... error
    Complete output from command /root/anaconda2/bi

  talib/common.c: At top level:
    talib/common.c:3590: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘__Pyx_PyInt_As_TA_RetCode’
    talib/common.c:3685: error: expected ‘)’ before ‘value’
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/root/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-wJvMYP/TA-Lib/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-3d1YYA-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-wJvMYP/TA-Lib/
[root@localhost ~]#

**Comment by mrjbq7** [comment]
Hi @MaximusIndus,

You'd have to provide the actual failure.  It's hard to tell what is wrong since that command doesn't have the output, maybe look for where that output is.  Or try and install it yourself not using ``pip``...
