### ISSUE TITLE
RSI returns all nan for the period

### ISSUE THREAD

**Issue by ssprowls** [mrjbq7/ta-lib#404]
Hey,

I am trying to get an RSI calculation for a period of 14 (the default) but end up with a list of all nans. Below is a simplified use case of my code.

```python
import numpy as np
import talib 

close_prices = [29.685, 29.685, 29.685, 29.695, 29.715, 29.715, 29.735, 29.735, 29.725, 29.715, 29.705, 29.715, 29.675, 29.615]
close_prices = np.asarray(close_prices, dtype=np.float64)
rsi = talib.RSI(close_prices, 14)
print(rsi)
```

The output is just ...
```python
[nan nan nan nan nan nan nan nan nan nan nan nan nan nan]
```

If I set the period to 13, with the same input I get an RSI value.

Am I misunderstanding something? I expect that when I provide 14 price points and a period of 14 then I should be getting an RSI value at that point in time of the 14th price point. In other words, with 14 values and a period of 14, it should have enough information to calculate the value I am expecting, no?

Thanks for any replies.

**Comment by mrjbq7** [comment]
Period of 14 requires 14 observations to generate a value (on the 15th data point).

**Comment by mrjbq7** [comment]
Oh I see what you’re saying.

**Comment by ssprowls** [comment]
Yea, so I was expecting that given 14, it would use all 14, but I think you're saying each price point it looks back for the period size...

**Comment by ssprowls** [comment]
If you have to wait for another price point, is your RSI not just going to be outdated by the time interval between candles?

So if I have 14 price points each a 5 min candle, and I have to wait for a 15th to get the RSI of the previous 14 price points, my RSI is already 5 min old?

Unless I am misunderstanding something about the actual calculation of RSI I am looking for a way to get the value immediately if possible, is that supported by this library?

**Comment by ssprowls** [comment]
Sorry to spam you with messages.

In regards to my previous comment ...

> I guess I can just append a ‘dummy’ value to the end of my list of candle close prices to get the current RSI, but I’m trying to understand the reasoning behind this implementation.

... I did some testing and realized this is not a solution. When I append a number, it appears that number goes into the calculation of the RSI, so the 15th value is affecting the RSI of period 14.

For example adding
```python
close.append(-1)
```

resulted in a RSI of 0.19477358 while instead adding

```python
close.append(30)
```

resulted in a RSI of 77.39130435.

So, now I really don't get why the 15th value is affecting the calculation of period 14 when just having 14 values does not produce a result.

**Comment by mrjbq7** [comment]
Okay, so it is simpler here... there isn't an off-by-one, but that a ``n`` period RSI requires ``n+1`` periods of observations.

This is due to the fact that ``RSI`` needs ``n`` observations of the ``RS`` (Relative Strength) which itself uses a daily difference calculation (e.g., ``MOM``) which brings in the ``+1``.

It's not lagged, it's just in the way it's defined.

**Comment by ssprowls** [comment]
Interesting, thanks for the insight. I will mark this as closed.
