### ISSUE TITLE
Can't import ta-lib

### ISSUE THREAD

**Issue by h84221605** [mrjbq7/ta-lib#407]
Hello, my laptop is M1 macbook Air.

I use

$ brew install ta-lib
$ pip3 install ta-lib

but show up this error  when i import talib

What should i do ?? 
---------------------------------------------------------------------------

ImportError                               Traceback (most recent call last)
<ipython-input-5-1ee486ccef90> in <module>
----> 1 import talib

~/miniforge3/lib/python3.8/site-packages/talib/__init__.py in <module>
     50         return wrapper
     51 
---> 52 from ._ta_lib import (
     53     _ta_initialize, _ta_shutdown, MA_Type, __ta_version__,
     54     _ta_set_unstable_period as set_unstable_period,

ImportError: dlopen(/Users/chenqinghong/miniforge3/lib/python3.8/site-packages/talib/_ta_lib.cpython-38-darwin.so, 2): Symbol not found: _TA_ACOS
  Referenced from: /Users/chenqinghong/miniforge3/lib/python3.8/site-packages/talib/_ta_lib.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/chenqinghong/miniforge3/lib/python3.8/site-packages/talib/_ta_lib.cpython-38-darwin.so

**Comment by mrjbq7** [comment]
You need to:

1. ``brew install ta-lib``

2. Set these in the environment:

```
export TA_INCLUDE_PATH="$(brew --prefix ta-lib)/include"
export TA_LIBRARY_PATH="$(brew --prefix ta-lib)/lib"
```

3. ``python3 -m pip install ta-lib``

**Comment by h84221605** [comment]
I follow what you say but sill show same error

![1616208170795](https://user-images.githubusercontent.com/39433193/111856958-49f07980-8969-11eb-88b3-1eb06f03b35e.jpg)

**Comment by mrjbq7** [comment]
It looks like pip install didn’t try and rebuild it. You should remove it and try to reinstall. 

$ python3 -m pip uninstall ta-lib

**Comment by h84221605** [comment]
Still can't work

![1616211531389](https://user-images.githubusercontent.com/39433193/111858056-e8340d80-8970-11eb-8e9f-b32ce7b22eff.jpg)

**Comment by kohnech** [comment]
@h84221605 
Are you using apple silicon M1? 
Which version of brew do you use?

$ brew --version

Did you try ?
$ brew uninstall ta-lib
$ brew update
$ arch -arm64 brew install ta-lib
$ python3 -m pip install ta-lib

It worked for me when uninstall ta-lib completely and update brew and install again.
Make sure you have a dylib for your architecture.

$ file /opt/homebrew/lib/libta_lib.0.0.0.dylib 
/opt/homebrew/lib/libta_lib.0.0.0.dylib: Mach-O 64-bit dynamically linked shared library arm64

for M1 for example.
