### ISSUE TITLE
Install Error, not sure whats going wrong. I have also installed Visual Studio that it was first asking me to.

### ISSUE THREAD

**Issue by varadjoshi90** [mrjbq7/ta-lib#410]
Full error given below.
I am using Pycharm as my IDE.

python --version
Python 3.8.8

Windows 10 64bit OS

Error:
collecting TA-Lib==0.4.19
  Using cached TA-Lib-0.4.19.tar.gz (267 kB)
Requirement already satisfied: numpy in c:\users\mmt6150\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\
site-packages (from TA-Lib==0.4.19) (1.20.2)
Using legacy 'setup.py install' for TA-Lib, since package 'wheel' is not installed.
Installing collected packages: TA-Lib
    Running setup.py install for TA-Lib ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\mmt6150\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe' -u -c 'import sys, setuptools, toke
nize; sys.argv[0] = '"'"'C:\\Users\\mmt6150\\AppData\\Local\\Temp\\pip-install-0to6hsl2\\ta-lib_437a3a9d9d36471ea66b4e860472e1d9\\setup.py'"'"'; __file__='"'"'C:\\Us
ers\\mmt6150\\AppData\\Local\\Temp\\pip-install-0to6hsl2\\ta-lib_437a3a9d9d36471ea66b4e860472e1d9\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);
code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\mmt6150\AppData\Local\Temp\pi
p-record-5h1lwj36\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\mmt6150\AppData\Local\Packages\Pytho
nSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Include\TA-Lib'
         cwd: C:\Users\mmt6150\AppData\Local\Temp\pip-install-0to6hsl2\ta-lib_437a3a9d9d36471ea66b4e860472e1d9\
    Complete output (26 lines):
    C:\Users\mmt6150\AppData\Local\Temp\pip-install-0to6hsl2\ta-lib_437a3a9d9d36471ea66b4e860472e1d9\setup.py:71: UserWarning: Cannot find ta-lib library, installati
on may fail.
      warnings.warn('Cannot find ta-lib library, installation may fail.')
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\talib
    copying talib\abstract.py -> build\lib.win-amd64-3.8\talib
    copying talib\deprecated.py -> build\lib.win-amd64-3.8\talib
    copying talib\stream.py -> build\lib.win-amd64-3.8\talib
    copying talib\test_abstract.py -> build\lib.win-amd64-3.8\talib
    copying talib\test_data.py -> build\lib.win-amd64-3.8\talib
    copying talib\test_func.py -> build\lib.win-amd64-3.8\talib
    copying talib\test_pandas.py -> build\lib.win-amd64-3.8\talib
    copying talib\test_stream.py -> build\lib.win-amd64-3.8\talib
    copying talib\__init__.py -> build\lib.win-amd64-3.8\talib
    running build_ext
    building 'talib._ta_lib' extension
    creating build\temp.win-amd64-3.8
    creating build\temp.win-amd64-3.8\Release
    creating build\temp.win-amd64-3.8\Release\talib
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\ta-lib\c\
include -IC:\Users\mmt6150\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\numpy\core\inclu
de "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\include" "-IC:\Program Files\WindowsApps\PythonSoftwareFoundatio
n.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\ATLMFC\include" "-IC:\
Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-
IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Win
dows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" /Tctalib/_ta_lib.c /Fobuild\temp.win-amd64-3.8\Rele
ase\talib/_ta_lib.obj
    _ta_lib.c
    talib/_ta_lib.c(609): fatal error C1083: Cannot open include file: 'ta_libc.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29910\\bin\\HostX86\\x64\\cl.exe' failed with exit stat
us 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\mmt6150\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe' -u
 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\mmt6150\\AppData\\Local\\Temp\\pip-install-0to6hsl2\\ta-lib_437a3a9d9d36471ea66b4e860472e1d9\\se
tup.py'"'"'; __file__='"'"'C:\\Users\\mmt6150\\AppData\\Local\\Temp\\pip-install-0to6hsl2\\ta-lib_437a3a9d9d36471ea66b4e860472e1d9\\setup.py'"'"';f=getattr(tokenize,
 '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Us
ers\mmt6150\AppData\Local\Temp\pip-record-5h1lwj36\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\mmt
6150\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Include\TA-Lib' Check the logs for full command outp
ut.

**Comment by mrjbq7** [comment]
This is your error:

UserWarning: Cannot find ta-lib library, installation may fail.
warnings.warn('Cannot find ta-lib library, installation may fail.')

Please see the README for installation instructions. On win64, it is easier to install from the unofficial binaries linked from that.

**Comment by mrjbq7** [comment]
Closing all installation issues, if someone has a specific problem please open a new one.
