### ISSUE TITLE
[BUG] stream.RSI != talib.RSI[-1]

### ISSUE THREAD

**Issue by ismailbayram** [mrjbq7/ta-lib#412]
```
rsi = talib.RSI(ticker.df["Close"])
latest = stream.RSI(ticker.df["Close"])
```

Output:
Date
2020-09-28 07:00:00          NaN
2020-09-28 07:05:00          NaN
2020-09-28 07:10:00          NaN
2020-09-28 07:15:00          NaN
2020-09-28 07:20:00          NaN
                         ...
2021-04-10 18:20:00    49.848603
2021-04-10 18:25:00    46.860749
2021-04-10 18:30:00    49.023091
2021-04-10 18:35:00    49.882496
2021-04-10 18:40:00    49.384385
Length: 55910, dtype: float64
53.18021201413421
-----------
As you see 49.38.. != 53.18

**Comment by mrjbq7** [comment]
The streaming method looks only at the previous timeperiod datapoints.

It is "correct" for the first, but since RSI is defined using all previous datapoints, it will trend to slight differences:

```python
$ python3
Python 3.9.2 (default, Mar 26 2021, 15:28:17) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import talib
>>> import talib.stream
>>> import numpy

>>> c = numpy.random.randn(30)
       
>>> talib.RSI(c, 20)
array([        nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
       46.08409854, 45.37512807, 51.83523698, 49.95375546, 48.67162047,
       52.60431591, 52.13261948, 50.2941003 , 48.55130744, 45.27502415])
       
# needs 21 data points
>>> talib.stream.RSI(c[:20], 20)
nan

# is "correct" or "same"
>>> talib.stream.RSI(c[:21], 20)
46.08409854484472

# starts to diverge
>>> talib.stream.RSI(c[:22], 20)
49.572164742044514
>>> 
```
