### ISSUE TITLE
Visual Studio C++ 14.0 Error

### ISSUE THREAD

**Issue by TheXe0N** [mrjbq7/ta-lib#419]
![image](https://user-images.githubusercontent.com/83131171/115966015-5c476f80-a534-11eb-936e-89b28441c9b6.png)

So the link doesn't work, while searching for a solution I found the file http://go.microsoft.com/fwlink/?LinkId=691126&fixForIE=.exe. from this Stackoverflow question https://stackoverflow.com/questions/44951456/pip-error-microsoft-visual-c-14-0-is-required
Well I downloaded the file but I keep getting this error
![image](https://user-images.githubusercontent.com/83131171/115966311-a3823000-a535-11eb-80a4-2c426aec30ed.png)
I have tried both options but neither works. How can I solve this issue?

**Comment by mrjbq7** [comment]
I’m sorry, I don’t know.

**Comment by TheXe0N** [comment]
Thanks for your response. I asked one of my friends to install the package too (After installing ta-lib to C:\) to see if the problem was about my computer, but he faced the same problem too.

Also, this is the full error.
![image](https://user-images.githubusercontent.com/83131171/115975485-d0ead000-a56d-11eb-9f0e-c323b03bd8e1.png)
