### ISSUE TITLE
Install failed on Windows 8 x64

### ISSUE THREAD

**Issue by shura-v** [mrjbq7/ta-lib#42]
http://monosnap.com/image/BL25i7BS6i4cyWuS1zSY23bgQ/#

D:\Dropbox\mygit\ta-lib>python setup.py install
running install
running build
running build_py
running build_ext
skipping 'talib\common.c' Cython extension (up-to-date)
building 'talib.common' extension
C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\lib\site-packages\numpy\core\include -Ic:\ta-lib\c\include -IC:\Python27\include -IC:\Python27\PC /Tctalib\common.c /Fobuild\temp.wi
n-amd64-2.7\Release\talib\common.obj
common.c
C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\amd64\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:c:\ta-lib\c\lib /LIBPATH:C:\Python27\libs /LIBPATH:C:\Python27\PCbuild\amd64 ta_libc_cdr.lib /EXPORT:initcommon build\temp.win-amd64-2.7\Releas
e\talib\common.obj /OUT:build\lib.win-amd64-2.7\talib\common.pyd /IMPLIB:build\temp.win-amd64-2.7\Release\talib\common.lib /MANIFESTFILE:build\temp.win-amd64-2.7\Release\talib\common.pyd.manifest
common.obj : warning LNK4197: export 'initcommon' specified multiple times; using first specification
   Creating library build\temp.win-amd64-2.7\Release\talib\common.lib and object build\temp.win-amd64-2.7\Release\talib\common.exp
common.obj : error LNK2019: unresolved external symbol TA_Initialize referenced in function __pyx_pf_5talib_6common_2_ta_initialize
common.obj : error LNK2019: unresolved external symbol TA_Shutdown referenced in function __pyx_pf_5talib_6common_4_ta_shutdown
common.obj : error LNK2019: unresolved external symbol TA_GetVersionString referenced in function initcommon
build\lib.win-amd64-2.7\talib\common.pyd : fatal error LNK1120: 3 unresolved externals
error: command '"C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\amd64\link.exe"' failed with exit status 1120

**Comment by StarenseN** [comment]
Hello, same problem here with win7 64x.

What is @hknust meaning with "rebuild the library" ? What am I supposed to write in the MS Command prompt for VS2015 (mine) ?

**Comment by mrjbq7** [comment]
The ta-lib C library as distributed for Windows is 32-bit, I believe.  So if you want to use it with 64-bit Windows you have to compile it on Windows yourself (not sure how, as I've never looked into it, but I imagine the build instructions are part of their distribution).

**Comment by mrjbq7** [comment]
You can always use 32-bit Python with 32-bit ta-lib on 64-bit Windows, but I imagine that's annoying, too.

**Comment by StarenseN** [comment]
Thanks for the reply, I'm not sure I'll dig any deeper. I'll try to find a workaround unfortunately.

**Comment by yuanhuanglin** [comment]
I had the same issue.

Environment: Python3.5.2 + IPython 5.0.0 + Visual Studio 14.0 + Windows 10 64bit

Error message:
`(d:\Anaconda3) E:\OneDrive\01.Coding\07.Python>pip install ta-lib
Collecting ta-lib
  Using cached TA-Lib-0.4.9.zip
Building wheels for collected packages: ta-lib
  Running setup.py bdist_wheel for ta-lib ... error
  Complete output from command d:\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='G:\\Temp\\pip-build-e8wv9boz\\ta-lib\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d G:\Temp\tmpx37bqxdgpip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.5
  creating build\lib.win-amd64-3.5\talib
  copying talib\deprecated.py -> build\lib.win-amd64-3.5\talib
  copying talib\test_abstract.py -> build\lib.win-amd64-3.5\talib
  copying talib\test_data.py -> build\lib.win-amd64-3.5\talib
  copying talib\test_func.py -> build\lib.win-amd64-3.5\talib
  copying talib\__init__.py -> build\lib.win-amd64-3.5\talib
  running build_ext
  skipping 'talib\common.c' Cython extension (up-to-date)
  building 'talib.common' extension
  creating build\temp.win-amd64-3.5
  creating build\temp.win-amd64-3.5\Release
  creating build\temp.win-amd64-3.5\Release\talib
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Id:\Anaconda3\lib\site-packages\numpy\core\include -Ic:\ta-lib\c\include -Id:\Anaconda3\include -Id:\Anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tctalib\common.c /Fobuild\temp.win-amd64-3.5\Release\talib\common.obj
  common.c
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:c:\ta-lib\c\lib /LIBPATH:d:\Anaconda3\libs /LIBPATH:d:\Anaconda3\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64" ta_libc_cdr.lib /EXPORT:PyInit_common build\temp.win-amd64-3.5\Release\talib\common.obj /OUT:build\lib.win-amd64-3.5\talib\common.cp35-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.5\Release\talib\common.cp35-win_amd64.lib
  common.obj : warning LNK4197: export 'PyInit_common' specified multiple times; using first specification
     Creating library build\temp.win-amd64-3.5\Release\talib\common.cp35-win_amd64.lib and object build\temp.win-amd64-3.5\Release\talib\common.cp35-win_amd64.exp
  common.obj : error LNK2001: unresolved external symbol TA_Shutdown
  common.obj : error LNK2001: unresolved external symbol TA_Initialize
  common.obj : error LNK2001: unresolved external symbol TA_GetVersionString
  build\lib.win-amd64-3.5\talib\common.cp35-win_amd64.pyd : fatal error LNK1120: 3 unresolved externals
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1120


  Failed building wheel for ta-lib
  Running setup.py clean for ta-lib
Failed to build ta-lib
Installing collected packages: ta-lib
  Running setup.py install for ta-lib ... error
    Complete output from command d:\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='G:\\Temp\\pip-build-e8wv9boz\\ta-lib\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record G:\Temp\pip-rfdcs2it-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.5
    creating build\lib.win-amd64-3.5\talib
    copying talib\deprecated.py -> build\lib.win-amd64-3.5\talib
    copying talib\test_abstract.py -> build\lib.win-amd64-3.5\talib
    copying talib\test_data.py -> build\lib.win-amd64-3.5\talib
    copying talib\test_func.py -> build\lib.win-amd64-3.5\talib
    copying talib\__init__.py -> build\lib.win-amd64-3.5\talib
    running build_ext
    skipping 'talib\common.c' Cython extension (up-to-date)
    building 'talib.common' extension
    creating build\temp.win-amd64-3.5
    creating build\temp.win-amd64-3.5\Release
    creating build\temp.win-amd64-3.5\Release\talib
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Id:\Anaconda3\lib\site-packages\numpy\core\include -Ic:\ta-lib\c\include -Id:\Anaconda3\include -Id:\Anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tctalib\common.c /Fobuild\temp.win-amd64-3.5\Release\talib\common.obj
    common.c
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:c:\ta-lib\c\lib /LIBPATH:d:\Anaconda3\libs /LIBPATH:d:\Anaconda3\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64" ta_libc_cdr.lib /EXPORT:PyInit_common build\temp.win-amd64-3.5\Release\talib\common.obj /OUT:build\lib.win-amd64-3.5\talib\common.cp35-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.5\Release\talib\common.cp35-win_amd64.lib
    common.obj : warning LNK4197: export 'PyInit_common' specified multiple times; using first specification
       Creating library build\temp.win-amd64-3.5\Release\talib\common.cp35-win_amd64.lib and object build\temp.win-amd64-3.5\Release\talib\common.cp35-win_amd64.exp
    common.obj : error LNK2001: unresolved external symbol TA_Shutdown
    common.obj : error LNK2001: unresolved external symbol TA_Initialize
    common.obj : error LNK2001: unresolved external symbol TA_GetVersionString
    build\lib.win-amd64-3.5\talib\common.cp35-win_amd64.pyd : fatal error LNK1120: 3 unresolved externals
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1120

Command "d:\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='G:\\Temp\\pip-build-e8wv9boz\\ta-lib\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record G:\Temp\pip-rfdcs2it-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in G:\Temp\pip-build-e8wv9boz\ta-lib\
`

**Comment by mrjbq7** [comment]
I suggest petitioning the owner of the ``ta-lib`` C library to make a 64-bit build available for Windows that would solve most people's problems here.

**Comment by CJ1995** [comment]
@hknust Thank you. Just rebuild cdr directory, using 'nmake', now we could install TA-LIb library successfully.

**Comment by prabuinet** [comment]
this solved the issue for me:
pip --no-cache-dir install ta-lib

**Comment by mjallman** [comment]
I managed to install successfully on my 64-bit Windows machine using the file "TA_Lib-0.4.10-cp27-cp27m-win_amd64.whl" found here: https://www.lfd.uci.edu/~gohlke/pythonlibs/#ta-lib

**Comment by EugeneRymarev** [comment]
@mrjbq7, same problem on Windows 11 22H2. File `C:\ta-lib\c\lib\ta_libc_cdr.lib` already exists. Full log on pastebin are [here](https://pastebin.com/raw/UduLJkZ0).

**Comment by mrjbq7** [comment]
I would suggest deleting ``C:\ta-lib`` which is probably the 32-bit version you might have downloaded, and build the 64-bit version using the instructions in the README.

Or use the unofficial wheels which work unless you're on python 3.11.

**Comment by EugeneRymarev** [comment]
@mrjbq7, Unfortunately, I didn't find a whl package for Python 3.11. Only for 3.10 and previous versions of library. To build the library, did I just use the [link](https://github.com/TA-Lib/ta-lib-python/blob/master/README.md#windows) instruction or are we talking about some other instruction?

**Comment by mrjbq7** [comment]
Correct, you need to build the underlying TA-Lib C library, which is required for pip to install.

**Comment by EugeneRymarev** [comment]
@mrjbq7, I realized my mistake. I opened a shared console for a build, not an x64 build. Thanks for your help and very prompt replies. You are super!

**Comment by mrjbq7** [comment]
Glad it worked! I hope Gohlke is able to build Python 3.11 wheels soon.

The real answer is to finish merging that PR that allows us to make our own wheels.
