### ISSUE TITLE
Import Error - Please Help

### ISSUE THREAD

**Issue by dinenis** [mrjbq7/ta-lib#420]
MAC M1 , with OS Big Sur
Installed via :
$ brew install ta-lib
https://github.com/mrjbq7/ta-lib

Get the following error:
`
ImportError: dlopen(/Users/georgedinenis/opt/anaconda3/lib/python3.8/site-packages/talib/_ta_lib.cpython-38-darwin.so, 2): Symbol not found: _TA_ACOS
  Referenced from: /Users/georgedinenis/opt/anaconda3/lib/python3.8/site-packages/talib/_ta_lib.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/georgedinenis/opt/anaconda3/lib/python3.8/site-packages/talib/_ta_lib.cpython-38-darwin.so`

**Comment by mrjbq7** [comment]
I think your issue is mixed CPU architectures. 

You’ll want to make sure brew installs TA-Lib with the architecture your Python uses. 

Look at the README for instructions on setting TA_LIBRARY_PATH and TA_INCLUDE_PATH before doing pip install. 

I also recommend “python -m pip install” to make sure pip is using the python you intend to use.

**Comment by tomjamescn** [comment]
+1

Mine is M1 too, same problem. Additionally I using virtual env created by `conda create -n xxx python=3.7`.

@mrjbq7 I have followed your instruction.

```
export TA_INCLUDE_PATH="$(brew --prefix ta-lib)/include"
export TA_LIBRARY_PATH="$(brew --prefix ta-lib)/lib"
arch -arm64 brew install ta-lib

python -m pip install --no-cache-dir TA-Lib
```

output is：
```
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting TA-Lib
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/78/f5/59f1d7d0c43d3d96e93249ae9d5415b42591362bfcf2f4e50574ad063312/TA-Lib-0.4.24.tar.gz (269 kB)
     |████████████████████████████████| 269 kB 8.4 MB/s 
Requirement already satisfied: numpy in /opt/homebrew/Caskroom/miniconda/base/envs/realmarket/lib/python3.7/site-packages (from TA-Lib) (1.21.5)
Building wheels for collected packages: TA-Lib
  Building wheel for TA-Lib (setup.py) ... done
  Created wheel for TA-Lib: filename=TA_Lib-0.4.24-cp37-cp37m-macosx_10_9_x86_64.whl size=431444 sha256=81d34e9af2ffc50eddd8789009b835e72eee4f015cbe00d0566092b834f1a6ea
  Stored in directory: /private/var/folders/4w/87w36g9n71qdjskv6ck8_zc00000gn/T/pip-ephem-wheel-cache-zqv9n3_9/wheels/47/73/70/eb41dca50f91412885766186f72055984965f008183601216a
Successfully built TA-Lib
Installing collected packages: TA-Lib
```

I think `filename=TA_Lib-0.4.24-cp37-cp37m-macosx_10_9_x86_64.whl` is NOT correct, but I do NOT know how to set arm64 arc to it.

Please help, thanks!

**Comment by tomjamescn** [comment]
I solved the problem. The key resean is my conda (miniconda) is installed from brew which install x86_64 version conda, resulting x86_64 version python.

reinstall the conda from `https://docs.conda.io/en/latest/miniconda.html`, and done!
`Created wheel for ta-lib: filename=TA_Lib-0.4.24-cp38-cp38-macosx_11_0_arm64.whl size=386804 `

full log is:
```
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting ta-lib
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/78/f5/59f1d7d0c43d3d96e93249ae9d5415b42591362bfcf2f4e50574ad063312/TA-Lib-0.4.24.tar.gz (269 kB)
     |████████████████████████████████| 269 kB 6.2 MB/s 
Requirement already satisfied: numpy in /Users/tangwei/miniconda3/envs/realmarket/lib/python3.8/site-packages (from ta-lib) (1.22.0)
Building wheels for collected packages: ta-lib
  Building wheel for ta-lib (setup.py) ... done
  Created wheel for ta-lib: filename=TA_Lib-0.4.24-cp38-cp38-macosx_11_0_arm64.whl size=386804 sha256=96963ab7f0ea86d797fdbfde8147a5f8577d1af9080087602a866f00ef8a37e0
  Stored in directory: /private/var/folders/4w/87w36g9n71qdjskv6ck8_zc00000gn/T/pip-ephem-wheel-cache-aofm3jk9/wheels/74/23/d4/5de2dac4adb62f6217234cb724d6534307615c28579f919438
Successfully built ta-lib
Installing collected packages: ta-lib
Successfully installed ta-lib-0.4.24
```

> +1
> 
> Mine is M1 too, same problem. Additionally I using virtual env created by `conda create -n xxx python=3.7`.
> 
> @mrjbq7 I have followed your instruction.
> 
> ```
> export TA_INCLUDE_PATH="$(brew --prefix ta-lib)/include"
> export TA_LIBRARY_PATH="$(brew --prefix ta-lib)/lib"
> arch -arm64 brew install ta-lib
> 
> python -m pip install --no-cache-dir TA-Lib
> ```
> 
> output is：
> 
> ```
> Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
> Collecting TA-Lib
>   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/78/f5/59f1d7d0c43d3d96e93249ae9d5415b42591362bfcf2f4e50574ad063312/TA-Lib-0.4.24.tar.gz (269 kB)
>      |████████████████████████████████| 269 kB 8.4 MB/s 
> Requirement already satisfied: numpy in /opt/homebrew/Caskroom/miniconda/base/envs/realmarket/lib/python3.7/site-packages (from TA-Lib) (1.21.5)
> Building wheels for collected packages: TA-Lib
>   Building wheel for TA-Lib (setup.py) ... done
>   Created wheel for TA-Lib: filename=TA_Lib-0.4.24-cp37-cp37m-macosx_10_9_x86_64.whl size=431444 sha256=81d34e9af2ffc50eddd8789009b835e72eee4f015cbe00d0566092b834f1a6ea
>   Stored in directory: /private/var/folders/4w/87w36g9n71qdjskv6ck8_zc00000gn/T/pip-ephem-wheel-cache-zqv9n3_9/wheels/47/73/70/eb41dca50f91412885766186f72055984965f008183601216a
> Successfully built TA-Lib
> Installing collected packages: TA-Lib
> ```
> 
> I think `filename=TA_Lib-0.4.24-cp37-cp37m-macosx_10_9_x86_64.whl` is NOT correct, but I do NOT know how to set arm64 arc to it.
> 
> Please help, thanks!

**Comment by mrjbq7** [comment]
Closing all installation issues, if someone has a specific problem please open a new one.

**Comment by Macdad1213** [comment]
File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/talib/__init__.py", line 93, in <module>
    from ._ta_lib import (
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/talib/_ta_lib.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace (_TA_ACOS)

Process finished with exit code 1

Hi I have the same problem. I am using M1 too. Please help

**Comment by mrjbq7** [comment]
I don’t recommend mixed architecture on M1 without being purposeful about it. Homebrew has an apple silicon version installed to /opt and an Intel version installed to /usr. Having Intel pythons seem silly unless you have a library that’s not ported yet. All of these issues stem from migration assistant and not replacing Intel versions with clean ARM64 versions. You’ll have to figure that out yourself as it’s a local configuration issue and it’s not as obvious the specific command to run for you. When I’m doubt uninstall / reinstall clean.
