### ISSUE TITLE
ta-lib is not installed on Mac

### ISSUE THREAD

**Issue by amirzarbakhsh** [mrjbq7/ta-lib#422]
Hello
I run the following command on the Mac terminal:
-----------------------
$ brew install ta-lib
-----------------------
But I get the following errors :

Updating Homebrew...
fatal: Could not resolve HEAD to a revision
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
==> Updated Casks
Updated 15 casks.
==> Deleted Casks
hubic                      swift-explorer             vrep

==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "ta-lib".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.

**Comment by mrjbq7** [comment]
It looks like your homebrew installation isn’t working, or perhaps you don’t have git to perform an update with. 

Try reinstalling it per their instructions.

**Comment by mrjbq7** [comment]
Closing all installation issues, if someone has a specific problem please open a new one.
