### ISSUE TITLE
Install TA-Lib on Linux without sudo-rights?

### ISSUE THREAD

**Issue by Rapid1898-code** [mrjbq7/ta-lib#427]
Hello - is there any way to install TA-Lib on a Linux-machine without sudo rights (eg. shared server like A2Hosting)?

The normal "pip install TA-Lib" is not working

And the mentioned solution i can´t use without the sudo-rights...
$ tar -xzf ta-lib-0.4.0-src.tar.gz
$ cd ta-lib/
$ ./configure --prefix=/usr
$ make
$ sudo make install

The only probably solution i found here - but this doesn´t work for me...
https://github.com/mrjbq7/ta-lib/issues/210

**Comment by Muhammed-Salih-Karademir** [comment]
Hey, maybe this link can help you.
https://askubuntu.com/questions/2167/how-to-build-application-without-sudo-privileges

**Comment by Rapid1898-code** [comment]
thanks for the response but unfortunately this doesn´t help - i am still not able to install ta-lib on the machine

**Comment by mrjbq7** [comment]
Closing all installation issues, if someone has a specific problem please open a new one.
