### ISSUE TITLE
some install error

### ISSUE THREAD

**Issue by Leonard-sc** [mrjbq7/ta-lib#429]
os: ubuntu 20.04LTS
python: 3.8 64bit
I have installed c library
But when pip install ta-lib, it prompts:

> ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-523xq_hy/ta-lib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-523xq_hy/ta-lib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-p1tpfrlt
       cwd: /tmp/pip-install-523xq_hy/ta-lib/
  Complete output (80 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/talib
  copying talib/deprecated.py -> build/lib.linux-x86_64-3.8/talib
  copying talib/test_abstract.py -> build/lib.linux-x86_64-3.8/talib
  copying talib/test_data.py -> build/lib.linux-x86_64-3.8/talib
  copying talib/stream.py -> build/lib.linux-x86_64-3.8/talib
  copying talib/abstract.py -> build/lib.linux-x86_64-3.8/talib
  copying talib/test_pandas.py -> build/lib.linux-x86_64-3.8/talib
  copying talib/test_stream.py -> build/lib.linux-x86_64-3.8/talib
  copying talib/test_func.py -> build/lib.linux-x86_64-3.8/talib
  copying talib/__init__.py -> build/lib.linux-x86_64-3.8/talib
  running build_ext
  building 'talib._ta_lib' extension
  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/talib
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include -I/usr/local/include -I/opt/include -I/opt/local/include -I/opt/homebrew/include -I/opt/homebrew/opt/ta-lib/include -I/tmp/pip-install-523xq_hy/ta-lib/.eggs/numpy-1.20.3-py3.8-linux-x86_64.egg/numpy/core/include -I/usr/include/python3.8 -c talib/_ta_lib.c -o build/temp.linux-x86_64-3.8/talib/_ta_lib.o
  In file included from /tmp/pip-install-523xq_hy/ta-lib/.eggs/numpy-1.20.3-py3.8-linux-x86_64.egg/numpy/core/include/numpy/ndarraytypes.h:1944,
                   from /tmp/pip-install-523xq_hy/ta-lib/.eggs/numpy-1.20.3-py3.8-linux-x86_64.egg/numpy/core/include/numpy/ndarrayobject.h:12,
                   from /tmp/pip-install-523xq_hy/ta-lib/.eggs/numpy-1.20.3-py3.8-linux-x86_64.egg/numpy/core/include/numpy/arrayobject.h:4,
                   from talib/_ta_lib.c:620:
  /tmp/pip-install-523xq_hy/ta-lib/.eggs/numpy-1.20.3-py3.8-linux-x86_64.egg/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     17 | #warning "Using deprecated NumPy API, disable it with " \
        |  ^~~~~~~
  talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_348_ta_getFuncInfo’:
  talib/_ta_lib.c:38240:104: warning: passing argument 2 of ‘TA_GetFuncInfo’ from incompatible pointer type [-Wincompatible-pointer-types]
  38240 |   __pyx_v_retCode = TA_GetFuncInfo(__pyx_f_5talib_7_ta_lib___ta_getFuncHandle(__pyx_v_function_name), (&__pyx_v_info));
        |                                                                                                       ~^~~~~~~~~~~~~~
        |                                                                                                        |
        |                                                                                                        TA_FuncInfo ** {aka struct TA_FuncInfo **}
  In file included from talib/_ta_lib.c:615:
  /usr/include/ta-lib/ta_abstract.h:211:48: note: expected ‘const TA_FuncInfo **’ {aka ‘const struct TA_FuncInfo **’} but argument is of type ‘TA_FuncInfo **’ {aka ‘struct TA_FuncInfo **’}
    211 |                            const TA_FuncInfo **funcInfo );
        |                            ~~~~~~~~~~~~~~~~~~~~^~~~~~~~
  talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_350_ta_getInputParameterInfo’:
  talib/_ta_lib.c:38511:127: warning: passing argument 3 of ‘TA_GetInputParameterInfo’ from incompatible pointer type [-Wincompatible-pointer-types]
  38511 |   __pyx_v_retCode = TA_GetInputParameterInfo(__pyx_f_5talib_7_ta_lib___ta_getFuncHandle(__pyx_v_function_name), __pyx_v_idx, (&__pyx_v_info));
        |                                                                                                                              ~^~~~~~~~~~~~~~
        |                                                                                                                               |
        |                                                                                                                               TA_InputParameterInfo ** {aka struct TA_InputParameterInfo **}
  In file included from talib/_ta_lib.c:615:
  /usr/include/ta-lib/ta_abstract.h:442:68: note: expected ‘const TA_InputParameterInfo **’ {aka ‘const struct TA_InputParameterInfo **’} but argument is of type ‘TA_InputParameterInfo **’ {aka ‘struct TA_InputParameterInfo **’}
    442 |                                      const TA_InputParameterInfo **info );
        |                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
  talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_352_ta_getOptInputParameterInfo’:
  talib/_ta_lib.c:38761:130: warning: passing argument 3 of ‘TA_GetOptInputParameterInfo’ from incompatible pointer type [-Wincompatible-pointer-types]
  38761 |   __pyx_v_retCode = TA_GetOptInputParameterInfo(__pyx_f_5talib_7_ta_lib___ta_getFuncHandle(__pyx_v_function_name), __pyx_v_idx, (&__pyx_v_info));
        |                                                                                                                                 ~^~~~~~~~~~~~~~
        |                                                                                                                                  |
        |                                                                                                                                  TA_OptInputParameterInfo ** {aka struct TA_OptInputParameterInfo **}
  In file included from talib/_ta_lib.c:615:
  /usr/include/ta-lib/ta_abstract.h:446:74: note: expected ‘const TA_OptInputParameterInfo **’ {aka ‘const struct TA_OptInputParameterInfo **’} but argument is of type ‘TA_OptInputParameterInfo **’ {aka ‘struct TA_OptInputParameterInfo **’}
    446 |                                         const TA_OptInputParameterInfo **info );
        |                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
  talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_354_ta_getOutputParameterInfo’:
  talib/_ta_lib.c:39007:128: warning: passing argument 3 of ‘TA_GetOutputParameterInfo’ from incompatible pointer type [-Wincompatible-pointer-types]
  39007 |   __pyx_v_retCode = TA_GetOutputParameterInfo(__pyx_f_5talib_7_ta_lib___ta_getFuncHandle(__pyx_v_function_name), __pyx_v_idx, (&__pyx_v_info));
        |                                                                                                                               ~^~~~~~~~~~~~~~
        |                                                                                                                                |
        |                                                                                                                                TA_OutputParameterInfo ** {aka struct TA_OutputParameterInfo **}
  In file included from talib/_ta_lib.c:615:
  /usr/include/ta-lib/ta_abstract.h:450:70: note: expected ‘const TA_OutputParameterInfo **’ {aka ‘const struct TA_OutputParameterInfo **’} but argument is of type ‘TA_OutputParameterInfo **’ {aka ‘struct TA_OutputParameterInfo **’}
    450 |                                       const TA_OutputParameterInfo **info );
        |                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
  talib/_ta_lib.c: In function ‘__pyx_f_5talib_7_ta_lib___ta_getFuncHandle’:
  talib/_ta_lib.c:39606:126: warning: passing argument 2 of ‘TA_GetFuncHandle’ from incompatible pointer type [-Wincompatible-pointer-types]
  39606 |   __pyx_t_1 = __pyx_f_5talib_7_ta_lib__ta_check_success(__pyx_n_s_TA_GetFuncHandle, TA_GetFuncHandle(__pyx_v_function_name, (&__pyx_v_handle)), 0); if (unlikely(!__pyx_t_1)) __PYX_ERR(1, 720, __pyx_L1_error)
        |                                                                                                                             ~^~~~~~~~~~~~~~~~
        |                                                                                                                              |
        |                                                                                                                              TA_FuncHandle ** {aka unsigned int **}
  In file included from talib/_ta_lib.c:615:
  /usr/include/ta-lib/ta_abstract.h:155:52: note: expected ‘const TA_FuncHandle **’ {aka ‘const unsigned int **’} but argument is of type ‘TA_FuncHandle **’ {aka ‘unsigned int **’}
    155 |                              const TA_FuncHandle **handle );
        |                              ~~~~~~~~~~~~~~~~~~~~~~^~~~~~
  x86_64-linux-gnu-gcc: fatal error: Killed signal terminated program cc1
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for ta-lib

I don't see what's wrong

**Comment by mrjbq7** [comment]
How much RAM is available?

I’ve seen a similar failure on small 1 GB VMs

**Comment by Leonard-sc** [comment]
> Available memory is about 800MB.
After adjusting the memory, it can be installed normally. Thank you very much
> How much RAM is available? I’ve seen a similar failure on small 1 GB VMs
> […](#)
> On Jun 2, 2021, at 12:14 AM, S Sun ***@***.***> wrote: ﻿ os: ubuntu 20.04LTS python: 3.8 64bit I have installed c library But when pip install ta-lib, it prompts: ERROR: Command errored out with exit status 1: command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-523xq_hy/ta-lib/setup.py'"'"'; file='"'"'/tmp/pip-install-523xq_hy/ta-lib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-p1tpfrlt cwd: /tmp/pip-install-523xq_hy/ta-lib/ Complete output (80 lines): running bdist_wheel running build running build_py creating build creating build/lib.linux-x86_64-3.8 creating build/lib.linux-x86_64-3.8/talib copying talib/deprecated.py -> build/lib.linux-x86_64-3.8/talib copying talib/test_abstract.py -> build/lib.linux-x86_64-3.8/talib copying talib/test_data.py -> build/lib.linux-x86_64-3.8/talib copying talib/stream.py -> build/lib.linux-x86_64-3.8/talib copying talib/abstract.py -> build/lib.linux-x86_64-3.8/talib copying talib/test_pandas.py -> build/lib.linux-x86_64-3.8/talib copying talib/test_stream.py -> build/lib.linux-x86_64-3.8/talib copying talib/test_func.py -> build/lib.linux-x86_64-3.8/talib copying talib/init.py -> build/lib.linux-x86_64-3.8/talib running build_ext building 'talib._ta_lib' extension creating build/temp.linux-x86_64-3.8 creating build/temp.linux-x86_64-3.8/talib x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include -I/usr/local/include -I/opt/include -I/opt/local/include -I/opt/homebrew/include -I/opt/homebrew/opt/ta-lib/include -I/tmp/pip-install-523xq_hy/ta-lib/.eggs/numpy-1.20.3-py3.8-linux-x86_64.egg/numpy/core/include -I/usr/include/python3.8 -c talib/_ta_lib.c -o build/temp.linux-x86_64-3.8/talib/_ta_lib.o In file included from /tmp/pip-install-523xq_hy/ta-lib/.eggs/numpy-1.20.3-py3.8-linux-x86_64.egg/numpy/core/include/numpy/ndarraytypes.h:1944, from /tmp/pip-install-523xq_hy/ta-lib/.eggs/numpy-1.20.3-py3.8-linux-x86_64.egg/numpy/core/include/numpy/ndarrayobject.h:12, from /tmp/pip-install-523xq_hy/ta-lib/.eggs/numpy-1.20.3-py3.8-linux-x86_64.egg/numpy/core/include/numpy/arrayobject.h:4, from talib/_ta_lib.c:620: /tmp/pip-install-523xq_hy/ta-lib/.eggs/numpy-1.20.3-py3.8-linux-x86_64.egg/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp] 17 | #warning "Using deprecated NumPy API, disable it with " | ^~~~~~~ talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_348_ta_getFuncInfo’: talib/_ta_lib.c:38240:104: warning: passing argument 2 of ‘TA_GetFuncInfo’ from incompatible pointer type [-Wincompatible-pointer-types] 38240 | __pyx_v_retCode = TA_GetFuncInfo(__pyx_f_5talib_7_ta_lib___ta_getFuncHandle(__pyx_v_function_name), (&__pyx_v_info)); | ~^~~~~~~~~~~~~~ | | | TA_FuncInfo ** {aka struct TA_FuncInfo **} In file included from talib/_ta_lib.c:615: /usr/include/ta-lib/ta_abstract.h:211:48: note: expected ‘const TA_FuncInfo **’ {aka ‘const struct TA_FuncInfo **’} but argument is of type ‘TA_FuncInfo **’ {aka ‘struct TA_FuncInfo **’} 211 | const TA_FuncInfo **funcInfo ); | ~~~~~~~~~~~~~~~~~~~~^~~~~~~~ talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_350_ta_getInputParameterInfo’: talib/_ta_lib.c:38511:127: warning: passing argument 3 of ‘TA_GetInputParameterInfo’ from incompatible pointer type [-Wincompatible-pointer-types] 38511 | __pyx_v_retCode = TA_GetInputParameterInfo(__pyx_f_5talib_7_ta_lib___ta_getFuncHandle(__pyx_v_function_name), __pyx_v_idx, (&__pyx_v_info)); | ~^~~~~~~~~~~~~~ | | | TA_InputParameterInfo ** {aka struct TA_InputParameterInfo **} In file included from talib/_ta_lib.c:615: /usr/include/ta-lib/ta_abstract.h:442:68: note: expected ‘const TA_InputParameterInfo **’ {aka ‘const struct TA_InputParameterInfo **’} but argument is of type ‘TA_InputParameterInfo **’ {aka ‘struct TA_InputParameterInfo **’} 442 | const TA_InputParameterInfo **info ); | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~ talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_352_ta_getOptInputParameterInfo’: talib/_ta_lib.c:38761:130: warning: passing argument 3 of ‘TA_GetOptInputParameterInfo’ from incompatible pointer type [-Wincompatible-pointer-types] 38761 | __pyx_v_retCode = TA_GetOptInputParameterInfo(__pyx_f_5talib_7_ta_lib___ta_getFuncHandle(__pyx_v_function_name), __pyx_v_idx, (&__pyx_v_info)); | ~^~~~~~~~~~~~~~ | | | TA_OptInputParameterInfo ** {aka struct TA_OptInputParameterInfo **} In file included from talib/_ta_lib.c:615: /usr/include/ta-lib/ta_abstract.h:446:74: note: expected ‘const TA_OptInputParameterInfo **’ {aka ‘const struct TA_OptInputParameterInfo **’} but argument is of type ‘TA_OptInputParameterInfo **’ {aka ‘struct TA_OptInputParameterInfo **’} 446 | const TA_OptInputParameterInfo **info ); | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~ talib/_ta_lib.c: In function ‘__pyx_pf_5talib_7_ta_lib_354_ta_getOutputParameterInfo’: talib/_ta_lib.c:39007:128: warning: passing argument 3 of ‘TA_GetOutputParameterInfo’ from incompatible pointer type [-Wincompatible-pointer-types] 39007 | __pyx_v_retCode = TA_GetOutputParameterInfo(__pyx_f_5talib_7_ta_lib___ta_getFuncHandle(__pyx_v_function_name), __pyx_v_idx, (&__pyx_v_info)); | ~^~~~~~~~~~~~~~ | | | TA_OutputParameterInfo ** {aka struct TA_OutputParameterInfo **} In file included from talib/_ta_lib.c:615: /usr/include/ta-lib/ta_abstract.h:450:70: note: expected ‘const TA_OutputParameterInfo **’ {aka ‘const struct TA_OutputParameterInfo **’} but argument is of type ‘TA_OutputParameterInfo **’ {aka ‘struct TA_OutputParameterInfo **’} 450 | const TA_OutputParameterInfo **info ); | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~ talib/_ta_lib.c: In function ‘__pyx_f_5talib_7_ta_lib___ta_getFuncHandle’: talib/_ta_lib.c:39606:126: warning: passing argument 2 of ‘TA_GetFuncHandle’ from incompatible pointer type [-Wincompatible-pointer-types] 39606 | __pyx_t_1 = __pyx_f_5talib_7_ta_lib__ta_check_success(__pyx_n_s_TA_GetFuncHandle, TA_GetFuncHandle(__pyx_v_function_name, (&__pyx_v_handle)), 0); if (unlikely(!__pyx_t_1)) __PYX_ERR(1, 720, __pyx_L1_error) | ~^~~~~~~~~~~~~~~~ | | | TA_FuncHandle ** {aka unsigned int **} In file included from talib/_ta_lib.c:615: /usr/include/ta-lib/ta_abstract.h:155:52: note: expected ‘const TA_FuncHandle **’ {aka ‘const unsigned int **’} but argument is of type ‘TA_FuncHandle **’ {aka ‘unsigned int **’} 155 | const TA_FuncHandle **handle ); | ~~~~~~~~~~~~~~~~~~~~~~^~~~~~ x86_64-linux-gnu-gcc: fatal error: Killed signal terminated program cc1 compilation terminated. error: command 'x86_64-linux-gnu-gcc' failed with exit status 1 ERROR: Failed building wheel for ta-lib I don't see what's wrong — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
