### ISSUE TITLE
Request for additional indicators.

### ISSUE THREAD

**Issue by manishmanuja** [mrjbq7/ta-lib#431]
Hi Team,

Can you add the below indicators as well:
keltner channel
supertrend
vwap
stochastic momentum index

Thanks.

**Comment by redbullpeter** [comment]
This request needs to be directed to the ta-lib development team here: https://sourceforge.net/p/ta-lib/feature-requests/

This project is only for the python wrapper for ta-lib.

**Comment by manishmanuja** [comment]
Ok
