### ISSUE TITLE
I cant import Talib . help me pls.

### ISSUE THREAD

**Issue by fggh14** [mrjbq7/ta-lib#432]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-1ee486ccef90> in <module>
----> 1 import talib

~\anaconda3\lib\site-packages\talib\__init__.py in <module>
     50         return wrapper
     51 
---> 52 from ._ta_lib import (
     53     _ta_initialize, _ta_shutdown, MA_Type, __ta_version__,
     54     _ta_set_unstable_period as set_unstable_period,

talib\_ta_lib.pyx in init talib._ta_lib()

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

**Comment by mrjbq7** [comment]
Some online suggestions say you should try uninstalling and reinstalling numpy:

```
pip uninstall numpy
pip install numpy
```

**Comment by mrjbq7** [comment]
This might relate to some numpy changes in 1.20, I've seen this when it's building against a different numpy than it runs with.

**Comment by mujeebishaque** [comment]
```
pip uninstall numpy
pip install --upgrade numpy
```
Had issues with installation and it was as easy as upgrading numpy while I was running nmake commands, SMH.

**Comment by NicolasGuigui** [comment]
Hi,

I use ta-lib with the Freqtrade robot and I have an error when I have update ta-lib and I can't understand why.

I also try to unistall and re-install numpy but it doesn't work.

Do you have found something else to fix this ?

Thank you for your help

I put here my log:

```
(.env) ubuntu@ubuntu:~/freqtrade$ python3 -c "import numpy; print(numpy.__version__)"
1.21.5
(.env) ubuntu@ubuntu:~/freqtrade$ python3 -c "import talib; print(talib.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/freqtrade/.env/lib/python3.8/site-packages/talib/__init__.py", line 93, in <module>
    from ._ta_lib import (
  File "talib/_ta_lib.pyx", line 1, in init talib._ta_lib
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
(.env) ubuntu@ubuntu:~/freqtrade$ sudo pip install ta-lib --force
Processing /root/.cache/pip/wheels/9e/9d/2b/eb5593690a0ccd184bf19016a82e9a651477c0ef6f2ba63921/TA_Lib-0.4.24-cp38-cp38-linux_aarch64.whl
Collecting numpy
  Using cached numpy-1.22.0-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (13.4 MB)
Installing collected packages: numpy, ta-lib
  Attempting uninstall: numpy
    Found existing installation: numpy 1.22.0
    Uninstalling numpy-1.22.0:
      Successfully uninstalled numpy-1.22.0
  Attempting uninstall: ta-lib
    Found existing installation: TA-Lib 0.4.24
    Uninstalling TA-Lib-0.4.24:
      Successfully uninstalled TA-Lib-0.4.24
Successfully installed numpy-1.22.0 ta-lib-0.4.24
(.env) ubuntu@ubuntu:~/freqtrade$ python3 -c "import numpy; print(numpy.__version__)"
1.21.5
(.env) ubuntu@ubuntu:~/freqtrade$ python3 -c "import talib; print(talib.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/freqtrade/.env/lib/python3.8/site-packages/talib/__init__.py", line 93, in <module>
    from ._ta_lib import (
  File "talib/_ta_lib.pyx", line 1, in init talib._ta_lib
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```
