### ISSUE TITLE
cannot install pip at virtual environment

### ISSUE THREAD

**Issue by albertwong08** [mrjbq7/ta-lib#434]
after activate the venv, I cannot install ta-lib by pip with error as follows:

    ERROR: Command errored out with exit status 1:
     command: 'C:\Workspace\TradingBot\venv\Scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\alber\\AppData\\Local\\Temp\\pip-install-svy_u3_8\\ta-lib_7f8d9873104945428af3a713eac01254\\setup.py'"'"'; __file__='"'"'C:\\Users\\alber\\AppData\\Local\\Temp\\pip-install-svy_u3_8\\ta-lib_7f8d9873104945428af3a713eac01254\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\alber\AppData\Local\Temp\pip-record-qb48ktdx\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Workspace\TradingBot\venv\include\site\python3.7\ta-lib'  
         cwd: C:\Users\alber\AppData\Local\Temp\pip-install-svy_u3_8\ta-lib_7f8d9873104945428af3a713eac01254\
    Complete output (24 lines):
    C:\Users\alber\AppData\Local\Temp\pip-install-svy_u3_8\ta-lib_7f8d9873104945428af3a713eac01254\setup.py:75: UserWarning: Cannot 
find ta-lib library, installation may fail.
      warnings.warn('Cannot find ta-lib library, installation may 
fail.')
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\talib
    copying talib\abstract.py -> build\lib.win-amd64-3.7\talib    
    copying talib\deprecated.py -> build\lib.win-amd64-3.7\talib  
    copying talib\stream.py -> build\lib.win-amd64-3.7\talib      
    copying talib\test_abstract.py -> build\lib.win-amd64-3.7\talib
    copying talib\test_data.py -> build\lib.win-amd64-3.7\talib   
    copying talib\test_func.py -> build\lib.win-amd64-3.7\talib   
    copying talib\test_pandas.py -> build\lib.win-amd64-3.7\talib 
    copying talib\test_stream.py -> build\lib.win-amd64-3.7\talib 
    copying talib\__init__.py -> build\lib.win-amd64-3.7\talib    
    running build_ext
    building 'talib._ta_lib' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\talib
    cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Ic:\ta-lib\c\inclulude -IC:\Workspace\TradingBot\venv\include -IC:\ProgramData\Anaconda3\include -IC:\ProgramData\Anaconda3\include "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" /Tctalib/_ta_lib.c /Fobuild\temp.win-amd64-3.7\Release\talib/_ta_lib.obj
    error: command 'cl.exe' failed: No such file or directory     
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Workspace\TradingBot\venv\Scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\alber\\AppData\\Local\\Temp\\pip-install-svy_u3_8\\ta-lib_7f8d9873104945428af3a713eac012\Temp\\pip-install-svy_u3_8\\ta-lib_7f8d9873104945428af3a713eac01254\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\alber\AppData\Local\Temp\pip-record-qb48ktdx\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Workspace\TradingBot\venv\include\site\python3.7\ta-lib' Check the logs for full command output.

Any help??

**Comment by mrjbq7** [comment]
UserWarning: Cannot

find ta-lib library, installation may fail.
warnings.warn('Cannot find ta-lib library, installation may
fail.')


Look in the README for installation instructions

**Comment by mrjbq7** [comment]
Closing all installation issues, if someone has a specific problem please open a new one.
