### ISSUE TITLE
Conda Installation

### ISSUE THREAD

**Issue by Sinansi** [mrjbq7/ta-lib#437]
Hello,

You forgot to mention on the home page, that installation is possible through Conda Forge

conda install -c conda-forge ta-lib

https://anaconda.org/conda-forge/ta-lib

**Comment by mrjbq7** [comment]
I have never used that, but if it’s useful I could mention it. Make a PR?

**Comment by Sinansi** [comment]
Honestly, I dont know how to make PR. If you are not planning to test it, you can just add a note on the home page?

**Comment by mrjbq7** [comment]
Fixed in b66eeb70a78bb99d8b42b207af6897b6013f6d17
