### ISSUE TITLE
Cant install talib in Anaconda.

### ISSUE THREAD

**Issue by pawarison** [mrjbq7/ta-lib#438]
ERROR: Command errored out with exit status 1:
   command: 'C:\Users\WINDOWS\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\WINDOWS\\AppData\\Local\\Temp\\pip-install-9r_3h1_7\\ta-lib_cad0e7279ce04d80a546679be8c1de9a\\setup.py'"'"'; __file__='"'"'C:\\Users\\WINDOWS\\AppData\\Local\\Temp\\pip-install-9r_3h1_7\\ta-lib_cad0e7279ce04d80a546679be8c1de9a\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\WINDOWS\AppData\Local\Temp\pip-wheel-y311dz_u'
       cwd: C:\Users\WINDOWS\AppData\Local\Temp\pip-install-9r_3h1_7\ta-lib_cad0e7279ce04d80a546679be8c1de9a\
  Complete output (21 lines):
  C:\Users\WINDOWS\AppData\Local\Temp\pip-install-9r_3h1_7\ta-lib_cad0e7279ce04d80a546679be8c1de9a\setup.py:75: UserWarning: Cannot find ta-lib library, installation may fail.
    warnings.warn('Cannot find ta-lib library, installation may fail.')
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\talib
  copying talib\abstract.py -> build\lib.win-amd64-3.8\talib
  copying talib\deprecated.py -> build\lib.win-amd64-3.8\talib
  copying talib\stream.py -> build\lib.win-amd64-3.8\talib
  copying talib\test_abstract.py -> build\lib.win-amd64-3.8\talib
  copying talib\test_data.py -> build\lib.win-amd64-3.8\talib
  copying talib\test_func.py -> build\lib.win-amd64-3.8\talib
  copying talib\test_pandas.py -> build\lib.win-amd64-3.8\talib
  copying talib\test_stream.py -> build\lib.win-amd64-3.8\talib
  copying talib\__init__.py -> build\lib.win-amd64-3.8\talib
  running build_ext
  skipping 'talib\_ta_lib.c' Cython extension (up-to-date)
  building 'talib._ta_lib' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for TA-Lib
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\WINDOWS\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\WINDOWS\\AppData\\Local\\Temp\\pip-install-9r_3h1_7\\ta-lib_cad0e7279ce04d80a546679be8c1de9a\\setup.py'"'"'; __file__='"'"'C:\\Users\\WINDOWS\\AppData\\Local\\Temp\\pip-install-9r_3h1_7\\ta-lib_cad0e7279ce04d80a546679be8c1de9a\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\WINDOWS\AppData\Local\Temp\pip-record-s512i_gb\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\WINDOWS\anaconda3\Include\TA-Lib'
         cwd: C:\Users\WINDOWS\AppData\Local\Temp\pip-install-9r_3h1_7\ta-lib_cad0e7279ce04d80a546679be8c1de9a\
    Complete output (21 lines):
    C:\Users\WINDOWS\AppData\Local\Temp\pip-install-9r_3h1_7\ta-lib_cad0e7279ce04d80a546679be8c1de9a\setup.py:75: UserWarning: Cannot find ta-lib library, installation may fail.
      warnings.warn('Cannot find ta-lib library, installation may fail.')
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\talib
    copying talib\abstract.py -> build\lib.win-amd64-3.8\talib
    copying talib\deprecated.py -> build\lib.win-amd64-3.8\talib
    copying talib\stream.py -> build\lib.win-amd64-3.8\talib
    copying talib\test_abstract.py -> build\lib.win-amd64-3.8\talib
    copying talib\test_data.py -> build\lib.win-amd64-3.8\talib
    copying talib\test_func.py -> build\lib.win-amd64-3.8\talib
    copying talib\test_pandas.py -> build\lib.win-amd64-3.8\talib
    copying talib\test_stream.py -> build\lib.win-amd64-3.8\talib
    copying talib\__init__.py -> build\lib.win-amd64-3.8\talib
    running build_ext
    skipping 'talib\_ta_lib.c' Cython extension (up-to-date)
    building 'talib._ta_lib' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\WINDOWS\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\WINDOWS\\AppData\\Local\\Temp\\pip-install-9r_3h1_7\\ta-lib_cad0e7279ce04d80a546679be8c1de9a\\setup.py'"'"'; __file__='"'"'C:\\Users\\WINDOWS\\AppData\\Local\\Temp\\pip-install-9r_3h1_7\\ta-lib_cad0e7279ce04d80a546679be8c1de9a\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\WINDOWS\AppData\Local\Temp\pip-record-s512i_gb\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\WINDOWS\anaconda3\Include\TA-Lib' Check the logs for full command output.

Help me please , Im Beginner in python.

**Comment by fggh14** [comment]
![image](https://user-images.githubusercontent.com/53029638/124446639-cee19080-ddaa-11eb-8c72-433a314a2721.png)

**Comment by mrjbq7** [comment]
You need the cp38 wheel for Python 3.8

**Comment by universewill** [comment]
> 

How to get cp38 or cp37 wheel?

**Comment by universewill** [comment]
> You need the cp38 wheel for Python 3.8
> […](#)
> On Jul 5, 2021, at 2:05 AM, fggh14 ***@***.***> wrote: ﻿ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

How to get cp38 or cp37 wheel?

**Comment by mrjbq7** [comment]
Well the error in the above issue is not having Microsoft Build Tools installed:

building 'talib._ta_lib' extension
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/



But you can also get wheels for Windows from here:

https://www.lfd.uci.edu/~gohlke/pythonlibs/#ta-lib

**Comment by mrjbq7** [comment]
Closing all installation issues, if someone has a specific problem please open a new one.
