### ISSUE TITLE
How to install Ta-lib on google colab

### ISSUE THREAD

**Issue by thangdh73** [mrjbq7/ta-lib#440]
Hi, I'm trying to install Ta-lib on google colab but I got an error (Using cached https://files.pythonhosted.org/packages/40/36/ea7b36b5d46b489d3b7aba4281cb430279ef1980974ea513164e85261547/TA-Lib-0.4.21.tar.gz
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from Ta-Lib) (1.19.5)
Building wheels for collected packages: Ta-Lib
  Building wheel for Ta-Lib (setup.py) ... error
  ERROR: Failed building wheel for Ta-Lib
  Running setup.py clean for Ta-Lib
Failed to build Ta-Lib
Installing collected packages: Ta-Lib
    Running setup.py install for Ta-Lib ... error
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_4f1se9_/Ta-Lib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_4f1se9_/Ta-Lib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-dc0t35cx/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.)

Please guide me on how to fix it. Thank you.

**Comment by mrjbq7** [comment]
Do you have the TALib underlying C library dependency installed first?

**Comment by pavelxx1** [comment]
take
```
%%capture
%%shell
cd /content/
wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
tar -xzf ta-lib-0.4.0-src.tar.gz
cd ta-lib/
./configure --prefix=/usr
make
sudo make install
pip install TA-Lib
```

**Comment by vbmvbm** [comment]
i have similar issues on my ubuntu 18.04,  python 3.6 or 3.7 or 3.8 all failed;
but i can install success on docker with python3.7;   but fail on on docker with python3.8,  dont know why;
the install script is the same. 
[install_batch3.txt](https://github.com/mrjbq7/ta-lib/files/6951056/install_batch3.txt)

and output log:
[talib.txt](https://github.com/mrjbq7/ta-lib/files/6951062/talib.txt)

**Comment by mrjbq7** [comment]
Closing all installation issues, if someone has a specific problem please open a new one.
