### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by pawarison** [mrjbq7/ta-lib#447]
![image](https://user-images.githubusercontent.com/53029638/128441161-12f73586-7460-404c-b884-a4ba590d4227.png)
~\anaconda3\lib\site-packages\talib\__init__.py in <module>
     50         return wrapper
     51 
---> 52 from ._ta_lib import (
     53     _ta_initialize, _ta_shutdown, MA_Type, __ta_version__,
     54     _ta_set_unstable_period as set_unstable_period,

talib\_ta_lib.pyx in init talib._ta_lib()

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

**Comment by AlgoQ** [comment]
+1

**Comment by mrjbq7** [comment]
Closing all installation issues, if someone has a specific problem please open a new one.
