### ISSUE TITLE
RSI returning none

### ISSUE THREAD

**Issue by hrithik321** [mrjbq7/ta-lib#460]
from binance import Client
import pandas as pd
import talib

client = Client(api_key,api_secret)

def get_kline_data(symbol, interval, lookback):
    frame=pd.DataFrame(client.get_historical_klines(symbol , interval , lookback + 'min ago UTC'))
    frame=frame.iloc[:,:5]
    frame.columns=['Time','Open','High','Low','Close']
    frame=frame.astype(float)
    a=frame.iloc[:,4:5]
    closes=a.to_string(index=False)
    return closes

def calculate_RSI():
    rsi = talib.RSI(get_kline_data('BTCUSDT','1m','60'), 14)
    print(rsi)

calculate_RSI()

**Comment by hrithik321** [comment]
Can anyone please help with the code . the rsi function is returning none even after taking 60 candles kline data

**Comment by mrjbq7** [comment]
Are you saying ``rsi = talib.RSI(...)`` is producing an ``rsi`` value of ``None``?

That's unusual.

If you're saying ``calculate_RSI()`` produces ``None``, that's because you aren't returning anything from the function.

**Comment by mrjbq7** [comment]
This appears to be solved.

**Comment by algopy** [comment]
Choose frame.iloc(:,4) to select close value, Checks RSI field, it takes only single value, here is close.
