### ISSUE TITLE
I was installing succesfully Ta-lib but i cant import to use it

### ISSUE THREAD

**Issue by minhlegend** [mrjbq7/ta-lib#461]
![image](https://user-images.githubusercontent.com/90884482/133719963-4879312d-0527-4126-adb6-eb2af1cd13d8.png)
![image](https://user-images.githubusercontent.com/90884482/133720042-09c05e97-32d0-46a5-8c34-6756f5e8eea8.png)
i already installed through anaconda, and install .whl but still cant import talib.
Im using python 3.8.8 and windows 10

**Comment by mrjbq7** [comment]
Closing all installation issues, if someone has a specific problem please open a new one.
