### ISSUE TITLE
install talib error in jupyter

### ISSUE THREAD

**Issue by TinkerJueBerg** [mrjbq7/ta-lib#466]
when input 
if !python path install:
the error is:    package directory 'talib' does not exist
I think the program has something wrong

elif !pip install ta-lib:
the erorr is:    command 'gcc' failed with exit status 1
I think the jupyter context is not suitable for command gcc

how to solve this question ?

**Comment by mrjbq7** [comment]
The gcc error probably means you don't have the underlying TA-Lib C library installed.  See the README.

**Comment by TinkerJueBerg** [comment]
why not default python3 context, rather than python3-dev? It's not a good resolution for jupyter.

**Comment by trufanov-nok** [comment]
Try:
```
!wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz

!tar -xzf ta-lib-0.4.0-src.tar.gz
%cd ta-lib/
!./configure --prefix=$HOME
!make
!make install

!TA_LIBRARY_PATH=~/lib TA_INCLUDE_PATH=~/include pip install ta-lib
```

**Comment by mrjbq7** [comment]
Closing all installation issues, if someone has a specific problem please open a new one.
