### ISSUE TITLE
Different values (TradingView/Binance, ta-lib)

### ISSUE THREAD

**Issue by tratteo** [mrjbq7/ta-lib#469]
I am getting substantially different values from ta-lib with respect to both Binance and Trading view. All three indicators: STOCH, RSI, MACD return different values. Sometimes the difference is negligible, other times it goes as high as 10 points for the stochastic.
What is causing this?
Code for reference

```
import websocket, json, pprint, talib, numpy
import config
from binance.client import Client
from binance.enums import *
import time

SOCKET = "wss://stream.binance.com:9443/ws/ethusdt@kline_1m"
RSI_PERIOD = 14
TRADE_SYMBOL = 'ETHUSDT'
TRADE_QUANTITY = 0.005

macds = []
closes = []
highs = []
lows = []

is_long = False
client = Client(config.API_KEY, config.API_SECRET)
current_timestamp = round(time.time() * 1000)
print(current_timestamp)
val = current_timestamp - (200 * 60000)
hist = client.get_historical_klines(TRADE_SYMBOL, '1m', val, None, 200, HistoricalKlinesType.SPOT)

for a in hist:
    closes.append(float(a[4]))
    highs.append(float(a[2]))
    lows.append(float(a[3]))

def on_open(ws):
    print('opened connection')

def on_close(ws):
    print('closed connection')

def on_message_event(ws, message):
    json_message = json.loads(message)
    # pprint.pprint(json_message)
    candle = json_message['k']

    is_candle_closed = candle['x']
    close = candle['c']
    if is_candle_closed:
        print("candle closed at {}".format(candle))
        closes.append(float(close))
        highs.append(float(candle['h']))
        lows.append(float(candle['l']))
        np_closes = numpy.array(closes)
        macd, signal, hist = talib.MACD(np_closes)
        rsi = talib.RSI(np_closes, RSI_PERIOD)
        stoch_k, stoch_d = talib.STOCH(numpy.array(highs), numpy.array(lows), np_closes, fastk_period=14,
                                       slowk_period=1,
                                       slowd_period=3, slowk_matype=0, slowd_matype=0)
        print("Stochastic: [k, d] > [" + str(stoch_k[-1]) + ", " + str(stoch_d[-1]) + "]")
        print("RSI: " + str(rsi[-1]))
        print("MACD: [macd, sig] > [" + str(macd[-1]) + ", " + str(signal[-1]) + "]")

        # print("checking")
        # can = can_long(rsi, [macd, signal], [stoch_k, stoch_d])
        # if can:
        #     print("Long entered")


ws = websocket.WebSocketApp(SOCKET, on_open=on_open, on_close=on_close, on_message=on_message_event)
ws.run_forever()
```

**Comment by tratteo** [comment]
Thanks for the replies. It probably is simple a lack in my knowledge, however, if i set a certain period P for a certain indicator on Binance/TradingView, in a selected time frame, doesn't it mean that the indicator is calculated on that time frame using the last P candles?
So if i set the same period P for the indicator and i calculate it over the same time frame in ta-lib, shouldn't they necessarily be the same? Where does the "memory" come from if i am using the period P and the indicator is calculated only by using the last P candles?

**Comment by mrjbq7** [comment]
I think it uses a moving average of period P with longer history in the calculation.

**Comment by tratteo** [comment]
> > I am getting substantially different values from ta-lib with respect to both Binance and Trading view.
> 
> Are you sure they are displaying STOCH and not STOCHRSI? I couldn't find STOCH on Binance. TA-Lib has STOCHRSI indicator too. Perhaps you should use it instead of STOCH.

Well yes both on Binance and Trading view there are both the stochastic and the stochastic RSI, they have different values and ta-lib too has STOCH and STOCHRSI

**Comment by trufanov-nok** [comment]
I've registered on Binance, opened any graphic, selected settings of currently displayed indicator and able to see only:
```Main (0/5)
MA EMA WMA BOLL VWAP AVL TRIX SAR 
Sub (1/5)
VOL MACD RSI KDJ OBV CCI StochRSI WR DMI MTM EMV
```
And no STOCH...

**Comment by tratteo** [comment]
The chart must be in Trading View mode, on the top right corner of the chart

**Comment by DILIPSKUMAR1410** [comment]
Any luck here ?
Mine RSI value coming different from binance

import numpy
import redis
import tulipy as ti
from talib import stream
import time
r = redis.StrictRedis(
    host='localhost', port=6379, connection_pool=None, db=0, decode_responses=True)

while True:
	candles = r.lrange("FETUSDT", -15, -1)
	y = `[]`
	for candle in candles:
		y.append(float(candle.split(',')[3]))

	if len(y) > 0
		y = numpy.array(y)
		latest = stream.RSI(y)

		print("FETUSDT",latest)
	time.sleep(2)

<img width="1434" alt="Screenshot 2021-11-13 at 11 07 13 PM" src="https://user-images.githubusercontent.com/3807536/141653563-dd63671a-9a16-412a-8440-1edd8294301e.png">
<img width="1433" alt="Screenshot 2021-11-13 at 11 07 28 PM" src="https://user-images.githubusercontent.com/3807536/141653571-679091e9-ca0a-4f2b-98f9-4645ba72abc6.png">

**Comment by DILIPSKUMAR1410** [comment]
> Any luck here ? Mine RSI value coming different from binance
> 
> import numpy import redis import tulipy as ti from talib import stream import time r = redis.StrictRedis( host='localhost', port=6379, connection_pool=None, db=0, decode_responses=True)
> 
> while True: candles = r.lrange("FETUSDT", -15, -1) y = `[]` for candle in candles: y.append(float(candle.split(',')[3]))
> 
> ```
> if len(y) > 0
> 	y = numpy.array(y)
> 	latest = stream.RSI(y)
> 
> 	print("FETUSDT",latest)
> time.sleep(2)
> ```
> 
> <img alt="Screenshot 2021-11-13 at 11 07 13 PM" width="1434" src="https://user-images.githubusercontent.com/3807536/141653563-dd63671a-9a16-412a-8440-1edd8294301e.png">
> 
> <img alt="Screenshot 2021-11-13 at 11 07 28 PM" width="1433" src="https://user-images.githubusercontent.com/3807536/141653571-679091e9-ca0a-4f2b-98f9-4645ba72abc6.png">

Any luck here?
