### ISSUE TITLE
Installing ta-lib c library on Ubuntu

### ISSUE THREAD

**Issue by psmuts** [mrjbq7/ta-lib#47]
Hi, 

I can't seem to get this to work.  I am a noob for sure.  I have an ssh connection into my virtual machine and when I run sudo apt-get install http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz  I get

'unable to locate package.'  Sorry for such a newbie question but going crazy here.  

Thanks,

Peter

**Comment by timkofu** [comment]
Is there a .deb package available? I'm looking for one for heroku.

**Comment by kumkee** [comment]
> 
> That puts it into `/usr/local` I think, if you'd prefer `/usr` then do `./configure --prefix=/usr`.
> 

If you don't want to install ta-lib as root and `./configure --prefix=$HOME/env/`, who do I pip install the wrapper then?
