### ISSUE TITLE
Add support for Polars Dataframe

### ISSUE THREAD

**Issue by teneon** [mrjbq7/ta-lib#471]
Hi there,

thank you for this great wrapper lib :-)

Would it be possible to add support for Polars as you have added support for Pandas? Polars is a rising star Dataframe, which is much faster than Pandas, therefore we are switching everything over to Polaras.

If you are using Pandas, you can simply pass Dataframe as an argument, like this.
```
import talib.abstract as ta
# TEMA - Triple Exponential Moving Average
dataframe['tema'] = ta.TEMA(dataframe, timeperiod=9)
```
Currently, it is not possible to directly pass Polars Dataframe the same way as you can pass Pandas.
Could you perhaps add support for Polars as well?

best regards,
Neon

**Comment by mrjbq7** [comment]
@teneon do you think this is ready to release?

**Comment by teneon** [comment]
Hi @mrjbq7 ,
sorry for long reply, we've been coding. It looks quite good i think. We've also benchmarked it (quickly) and it calculates the same indicators about 50% faster than Pandas, which is also great (probably because of zero copy numpy?). I did find one more issue, but this has nothing to do with Polars implementation. I will prepare an example and show it to you so you can give your input about what u think. I will try to prepare it today!
Thanks for adding Polars support in your talib, it's amazing :D

**Comment by ritchie46** [comment]
> indicators about 50% faster than Pandas, which is also great (probably because of zero copy numpy?)

Pandas is definitely zero copy. So I don't think that's the case. Maybe because polars parallelizes expression execution?

**Comment by mrjbq7** [comment]
Pandas used to provide numpy compatible arrays of column data, and then changed their API so the cost to represent as Numpy is now slowing it down. I should find out if there is a more efficient way to get a pointer to the start of the data.

**Comment by teneon** [comment]
@mrjbq7 Hi there :) Sorry for a long reply, we've been very busy, but we have been using your Talib Polars support all the time in the meanwhile. It looks like everything works fine. But if something would come up, we will report it. Thanks a lot, you are great!

**Comment by mrjbq7** [comment]
Awesome, thanks!

Released it as version 0.4.22!

**Comment by collinsethans** [comment]
@mrjbq7

First, thank you for the talib-python library (and polars too!). I am 2 days new to polars and talib is the first library that I am using :)

The [test_polars.py](https://github.com/TA-Lib/ta-lib-python/blob/0bcfa81a211c88485a775091589906f118adf15f/talib/test_polars.py) file is currently failing. Here is a snippet from the file:

    >>> import talib
    >>> values = pl.Series([90.0,88.0,89.0])
    >>> talib.MOM(values, timeperiod=1)
    Traceback (most recent call last):
      ... snip ...
      talib/__init__.py", line 27, in wrapper
        return func(*args, **kwargs)
    TypeError: Argument 'real' has incorrect type (expected numpy.ndarray, got Series)

The [usage of talib APIs with .map()](https://github.com/TA-Lib/ta-lib-python/issues/511#issuecomment-1247008987) also fails. I am not sure if these failures are due to changes in talib-python or in polars. Hence, posting it here.

Float64:
I notice that talib-py is forcing input of dtype Float64. Can this be relaxed to Float32? For the Financial data, we have 10s of thousands of dataframes (~5K stocks x mode:eod/intraday x several-timeframes) and saving space on both SSD and on RAM (especially during intraday) is important to us. (we actually have been storing in Float32 and haven't faced any inconsistencies).

**Comment by mrjbq7** [comment]
It is working for me:

```
➜  ~ python3
Python 3.11.1 (main, Dec 23 2022, 09:28:24) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import talib
>>> import polars as pl
>>> values = pl.Series([90.0,88.0,89.0])
>>> talib.MOM(values, timeperiod=1)
shape: (3,)
Series: '' [f64]
[
	NaN
	-2.0
	1.0
]
>>> 
```

I'm happy to make adjustments to the API.  Regarding float32 versus float64. The TA-Lib library supports C functions with ``double`` arguments and ``float`` arguments, and I am currently only wrapping the 64-bit versions.  It would probably be easy to wrap both with minimal effort, and then I guess would want something to dispatch to the 64-bit or 32-bit based on the polars datatype?

**Comment by collinsethans** [comment]
@mrjbq7

Sigh! My mistake - with the version. Yesterday I had created a new conda env with ta-lib and polars and little did I anticipate that conda-forge is stuck with old version of both of them. Thanks, I did pip install for both of them and they are working, as expected.

Float32:
It will be a good option to auto swtich based on input dtype. Will look forward to it as you release.

Thank you.

**Comment by collinsethans** [comment]
@mrjbq7 (and others)

I had 1 more query for you regarding TAlib usage with polars.

The current method of using an indicator is applying it on the whole input column for a full computation. However, for financial data timeframes where there are 10s of thousands of rows, this will likely be costly when the need is only to compute for the latest 1 row of new ohlcv data. With the intent to compute the indicator in a continuous form, I need to provide additional immediately preceeding rows - eg. say 50 backfill rows for EMA (assuming I don't use polars ema) using when/then/otherwise - but want to get only the last row's value inserted in the respective indicator column.

Currently, I find the only option is to create a temp column with input 1+50 backfill data, and run on it the second time with another when/then/otherwise to filter out only the last row's computed value. This will be costly if I have to do for 4-5K stocks with multiple timeframes, especially if realtime update freq is 1 min.

Do you have any suggestion on alternate methods for this in polars?

**Comment by mrjbq7** [comment]
We have a stream version of the indicators that generate a "latest value":

https://github.com/TA-Lib/ta-lib-python#streaming-api

It works great, but you should know that some indicators have memory and the "latest values" generated by looking at the minimal number of past observations to generate them might have slight numerical differences from that value generated from a larger dataset.

**Comment by mrjbq7** [comment]
Regarding the ``f32`` data type, is your expectation that the output would be generated by doing 32-bit calculations without converting the input data?

**Comment by collinsethans** [comment]
> We have a stream version of the indicators that generate a "latest value":

I actually had a glance at streaming before, but didn't indulge more as it's marked as experimental (may hinder our s/w it to production stage). I will still have a look again. A couple of queries:

- Is it tested enough to ensure no memory leaks exist?

- A good point you mention is slight deviation from larger dataset. Will you know how much will be the deviation? (If not, I will try it out myself). For us, 2 decimal points of accuracy seems to be ok as of now. Not sure of future needs though, if we need a 100 multiplier for any indicator.

- TA-lib is no more supported since the last 9/10 yrs. Will there be any chance streaming support to mature beyond experimental state?

Thanks much for your quality support :)

> 
> https://github.com/TA-Lib/ta-lib-python#streaming-api
> 
> It works great, but you should know that some indicators have memory and the "latest values" generated by looking at the minimal number of past observations to generate them might have slight numerical differences from that value generated from a larger dataset.

**Comment by mrjbq7** [comment]
The streaming API isn't really *experimental* per-se, except as so far as I wanted to see if people found it useful.

It has no memory leaks, and is in fact just the same as the function API, except we tell TA-Lib to look only at the necessary amount of lookback to generate a new value.

**Comment by mrjbq7** [comment]
Regarding TA-Lib support, I have been working with the original author to transition the project to github under the TA-Lib organization (https://github.com/ta-lib/ta-lib) and hope to make a new release at some point with some of the community improvements.

**Comment by collinsethans** [comment]
> Regarding the `f32` data type, is your expectation that the output would be generated by doing 32-bit calculations without converting the input data or the output to 64-bit?

@mrjbq7 
We will be using Float32 as input data and expect return in Float32 - gets saved in Float32 column. Our objective is having most of the columns in Float32, where possible. Internally, TAlib can cast the data to Float64 for calculations, preferably in C function calls. (Do you expect any issue there?)

Let me know if I haven't answered you.

**Comment by collinsethans** [comment]
> The streaming API isn't really _experimental_ per-se, except as so far as I wanted to see if people found it useful.

Glad to get your confidence on it. Will definitely try it.

> 
> It has no memory leaks, and is in fact just the same as the function API, except we tell TA-Lib to look only at the necessary amount of lookback to generate a new value.

lookback - I hope we can give the lookback period for the respective TAlib indicator call. We do maintain tested lookback periods in config table, deduced from our testings. So, being able to specify it helps.

**Comment by collinsethans** [comment]
> Regarding TA-Lib support, I have been working with the original author to transition the project to github under the TA-Lib organization (https://github.com/ta-lib/ta-lib) and hope to make a new release at some point with some of the community improvements.

Very happy to know that TA-lib C lib is getting your support! Can I take this opportunity to request 2 things:
- Rust bindings
- Better candlestick support. It's not possible to call all 50+ candlestick indicators APIs in realtime intraday. Any better way of doing it will be very helpful. And I think people typically will store it's return as bitmask - we do so (for EOD).
-

**Comment by mrjbq7** [comment]
> lookback - I hope we can give the lookback period for the respective TAlib indicator call. We do maintain tested lookback periods in config table, deduced from our testings. So, being able to specify it helps.

You shouldn't need a config table like that -- TA-Lib provides a function to calculate it for each indicator, and then you just pass your entire array:

```python
>>> import numpy as np
>>> import talib as ta

>>> # random prices
>>> c = np.random.randn(100)

>>> # the last data point calculated using the Function API
>>> ta.MOM(c)[-1]
0.17279821427623404

>>> # the last data point calculated using the Streaming API
>>> ta.stream.MOM(c)
0.17279821427623404

>>> # those previous two are identical, but indicators with memory
>>> # like EMA can have different values
>>> ta.EMA(c)[-1]
0.02687581489039577

>>> # versus streaming, which only looks at the lookback period
>>> ta.stream.EMA(c)
0.0026940228851210944

>>> # see, you can replicate by using the fewest possible observations
>>> ta.EMA(c[-30:])[-1]
0.0026940228851210944
```

**Comment by collinsethans** [comment]
Sorry for the delayed reply and thank you much for samples of stream APIs with explanation. Much appreciated.

For the ones with memory, like the EMA, we find that we will not be able to use them. We need the values to be same as the Function API and with stream there's a good deviation. So, what we currently do with Function API by providing `minimal data for continuity` is using a `lookback period` (as I had mentioned earlier), like:

    # lookback: 170 (just a sample val)
    ta.EMA(c[-200:])[-1]

With polars, using the expressions with `.map()`, we are facing the problem as it needs us to create a temporary column - poses time overhead risk with realtime intraday.

Another thing that is missing with stream API is that it returns only the last value. Now, there can be scenarios where last 1/2/few data were not received, say for network issue, or app restart, a practical possibility. In such cases, the app identifies the missing rows, gets `backfill data` and needs now last 2/3/few computations (which with stream API will require multiple calls).

Essentially, our need is, like:

    # lookback: L
    # backfill count: n
    # timeperiod: 30
    ta.EMA(c[-30 - L + 1:])[-n]

Thanks again for your help!

**Comment by tlk3** [comment]
Getting the same error as mentioned above, but pretty sure I have the correct version installed. Thoughts?

df = pl.DataFrame(...)

high = df['high']
low = df['low']
close = df['close']
atr = talib.ATR(high, low, close, timeperiod=14)


Traceback (most recent call last):
  File "/Users/TLK3/PycharmProjects/stratbot2/venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3550, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-93-ff6cc2efc169>", line 7, in <module>
    atr = talib.ATR(high, low, close, timeperiod=14)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/TLK3/PycharmProjects/stratbot2/venv/lib/python3.12/site-packages/talib/__init__.py", line 64, in wrapper
    result = func(*_args, **_kwds)
             ^^^^^^^^^^^^^^^^^^^^^
TypeError: Argument 'high' has incorrect type (expected numpy.ndarray, got Series)

**Comment by mrjbq7** [comment]
What version of ta-lib do you have? and what version of polars?

That works for me:

```python
>>> import numpy as np
>>> import polars as pl
>>> import talib as ta

>>> size = 50
>>> df = pl.DataFrame(
...         {
...             "open": np.random.uniform(low=0.0, high=100.0, size=size).astype("float32"),
...             "high": np.random.uniform(low=0.0, high=100.0, size=size).astype("float32"),
...             "low": np.random.uniform(low=0.0, high=100.0, size=size).astype("float32"),
...             "close": np.random.uniform(low=0.0, high=100.0, size=size).astype("float32"),
...             "volume": np.random.uniform(low=0.0, high=100.0, size=size).astype("float32")
...         }
...     )

>>> high = df['high']

>>> low = df['low']

>>> close = df['close']

>>> ta.ATR(high, low, close, timeperiod=14)
shape: (50,)
Series: '' [f64]
[
	NaN
	NaN
	NaN
	NaN
	NaN
	NaN
	NaN
	NaN
	NaN
	NaN
	NaN
	NaN
	…
	40.476675
	41.916938
	43.717916
	44.007206
	46.32909
	47.186069
	48.298291
	48.115971
	51.015277
	50.433759
	50.355243
	51.364692
	49.708971
]

>>> ta.__version__
'0.4.28'

>>> np.__version__
'1.23.2'

>>> pl.__version__
'0.20.3'
```
