### ISSUE TITLE
Ta-lib installation issue

### ISSUE THREAD

**Issue by wu12345** [mrjbq7/ta-lib#48]
Hi! I'm very new to programming, so I apologize in advance. Can you help me troubleshoot what's going on? Thank you!

I've been following the instructions you've posted here: 
https://github.com/mrjbq7/ta-lib/issues/47

Everything works until I run make and I get:
cp: ../../../bin: Permission denied
make[2]: **\* [all-local] Error 1
make[1]: **\* [all-recursive] Error 1
make: **\* [all-recursive] Error 1

I ran sudo make install anyway, and I get:
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for`install-data-am'.
Making install in ta_regtest
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for`install-data-am'.
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for`install-data-am'.

**Comment by AdamJacobus** [comment]
Hi, I find myself with the same problem. I have followed steps above and printed my version of takin. I have the same error, using anaconda's spyder as an IDE, I receive an error when importing talib. No module named talib. I am also using a mac. 

Please could you assist in some way.
![screen shot 2017-11-13 at 6 21 45 pm](https://user-images.githubusercontent.com/24210770/32736352-e7189262-c89f-11e7-8517-0fdc1746a60e.png)

**Comment by mrjbq7** [comment]
Looks like you have two different pythons installed, one that has talib and the other that doesn’t. So I suppose if you need it working with both then install for both. They probably have different site-packages.

**Comment by AdamJacobus** [comment]
Thank you so much for the quick response. I used brew to install TA-Lib. How can I go about installing it for both. I am fairly new to python and would like this error not to be repeated in the future. I am sure I probably don't need both versions of python. I am only using python 3 through Anaconda. Can I get rid of the other python or how would I install it for the other python?

**Comment by mrjbq7** [comment]
Brew installs the library.  Either easy_install or pip installs ta-lib. Probably those aliases are for the usr local python. Not the usr python. 

Why would you need it in both? Just use one of them?

**Comment by AdamJacobus** [comment]
Hi. I do apologize, I am battling to understand what you mean. I have taken the steps to uninstall talib, installed it with the pip file and then brew. please see below. I am also using python 3. Importing the takin, I still receive module not found error.
![screen shot 2017-11-13 at 9 10 11 pm](https://user-images.githubusercontent.com/24210770/32744210-75703bde-c8b7-11e7-981f-d2250acedf88.png)

**Comment by mrjbq7** [comment]
That screenshot looks successful.  And the previous one also looked successful for usr/local/bin/python?

**Comment by AdamJacobus** [comment]
Do you have any idea as to why I still can't import the library?
![screen shot 2017-11-13 at 9 55 20 pm](https://user-images.githubusercontent.com/24210770/32746151-729febba-c8bd-11e7-8371-55fec675c65b.png)

**Comment by mrjbq7** [comment]
Which python is that using? And if you have python2 and python3 you might need to use pip3 to install it.

**Comment by AdamJacobus** [comment]
This is using python 3.6
I have successfully installed it using pip3 command and ran brew install afterwards.
Unfortunately I still have the same error when importing.
![screen shot 2017-11-13 at 10 19 37 pm](https://user-images.githubusercontent.com/24210770/32747286-f5f94e90-c8c0-11e7-87fb-0a90ec393245.png)

**Comment by mrjbq7** [comment]
Does Spyder come with it's own Python3?  Or does it use ``/usr/local/bin/python3``?

**Comment by mrjbq7** [comment]
Meaning, if you try to use ``/usr/local/bin/python3`` to ``import talib``, does it work?
