### ISSUE TITLE
C ta-lib issues with tmake: generating Makefiles

### ISSUE THREAD

**Issue by 4trade** [mrjbq7/ta-lib#481]
Hi,
I had to change instances of 'tmake' in .pl scripts to 'perl c:\tmake\bin\tmake'
but that is not the main issue. After those changes tmake executes fine, opens the target directories (cdr, ..) one by one but does not generate the output Makefiles. I'm not sure there is a version problem with tmake , the only version I found was the current one 2.x

https://pastebin.com/vUy6UECx

**Comment by mrjbq7** [comment]
I don’t maintain the C library, just this Python wrapper.

**Comment by 4trade** [comment]
Yes, it seems nobody maintains the C library.

**Comment by trufanov-nok** [comment]
According to the gen_make readme:
```
TMake version tested: V1.7 and V1.8

A bug in V1.9 and 1.10 prevents tmake to work.
For now, use an older tmake version.
```
I'm maintaining my own fork of this C library: TA-Lib RT. Never used these gen_make scripts. I guess they are broken and useless now. Building TA-Lib on Windows was always a pain.   
What exactly you're trying to do? Build the library as dll? Build it with other compiler?  
I guess all you need is CMake GUI other the root folder and to forget about make/ subfolder.   
And once you need to launch the internal gen_code tool or to debug the dll, I have added a set of manually created .pro files into c/ide/qt/. They may be backported to original project and used to tweak the codebase with QtCreator IDE.

**Comment by mrjbq7** [comment]
Closing all installation issues, if someone has a specific problem please open a new one.
