### ISSUE TITLE
can not install ta-lib

### ISSUE THREAD

**Issue by gitlong** [mrjbq7/ta-lib#484]
mac, M1-MAX, OSX 12.0,  did everything, export to brew and pip update, 
then
>>. python3.8 -m pip install --no-cache-dir ta-lib
then it said

ERROR: Failed building wheel for ta-lib
Failed to build ta-lib
ERROR: Could not build wheels for ta-lib, which is required to install pyproject.toml-based projects

**Comment by pranjii** [comment]
Suffering same issue everywhere including windows and google colab

**Comment by mrjbq7** [comment]
Perhaps my attempts at using a ``pyproject.toml`` caused some problems.

I just deleted that file and made a new 0.4.23 release. 

Can you try again?

**Comment by mrjbq7** [comment]
@pranjii and @gitlong did the new release fix this for you?

**Comment by Azam999** [comment]
> @pranjii and @gitlong did the new release fix this for you?

Nope, still doesn't work

**Comment by Azam999** [comment]
All version give the same error

**Comment by Arin626** [comment]
Had the same issues on one of my Macs. Has possibly something to do that the Command Line Tools on MacOS are not installed or up-to-date and the building failed. Try the following in the Terminal: 

`xcode-select --install`

If that doesn't work try to reset them: 

`sudo xcode-select --install`

**Comment by mrjbq7** [comment]
Closing all installation issues, if someone has a specific problem please open a new one.
