### ISSUE TITLE
Cannot install using setup.py

### ISSUE THREAD

**Issue by rellyrell24** [mrjbq7/ta-lib#490]
I am getting an error where setup.py does not know about 'runtime_library_dirs' and is unable to set the search path.

Does anyone understand what is going on?

I followed the dependencies instructions for my windows 10 machine and it still giving same error message.

Attached is the output of `python setup.py install`

[ta-lib-setuppy-output.txt](https://github.com/mrjbq7/ta-lib/files/7834112/ta-lib-setuppy-output.txt)

**Comment by mrjbq7** [comment]
Sorry about that!

It might be fixed in c6cdea5f8dbd61d39a6c8db94669d86f5ff82100.

Can you verify that ``git`` master works for you?

I can do a new release if that fixes it.

**Comment by rellyrell24** [comment]
I downloaded the new source code from master and made sure the dependencies were handled by running `python setup.py install`. 

The command successfully executed, unlike before. Thanks for the fix!

I assume since the release is not on PyPI, then I would have to wait on that.

**Comment by mrjbq7** [comment]
I released 0.4.24 just now with this fix, so you can PyPi install.
