### ISSUE TITLE
Error: sudo make install make: getcwd: No such file or directory

### ISSUE THREAD

**Issue by hhashim1** [mrjbq7/ta-lib#499]
I have followed the instructions to install on Linux however I am the below errors on the last step which is `sudo make install'. Can someone please tell me what I need to do to fix this? I am installing it on Ubuntu. I was unable to install via pip as it gives me an error about a file/dependencies missing.

Here are the instructions from github:
$ tar -xzf ta-lib-0.4.0-src.tar.gz
$ cd ta-lib/
$ ./configure --prefix=/usr
$ make
$ sudo make install

**### Error:**
`
root@FALCONXTREME:/mnt/e/dropbox/documents/visual studio 2019/repos/ta4j/deephaven-core/ta-lib# sudo make install
make: getcwd: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Making install in src
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
make: getcwd: No such file or directory
make[1]: Entering directory ''
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Making install in ta_abstract
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
make: getcwd: No such file or directory
make[2]: Entering directory ''
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
make: getcwd: No such file or directory
make[3]: Entering directory ''
make[3]: Nothing to be done for 'install-exec-am'.
test -z "/usr/include/ta-lib/" || /usr/bin/mkdir -p "/usr/include/ta-lib/"
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
 /usr/bin/install -c -m 644 '../../include/ta_defs.h' '/usr/include/ta-lib//ta_defs.h'
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
 /usr/bin/install -c -m 644 '../../include/ta_libc.h' '/usr/include/ta-lib//ta_libc.h'
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
 /usr/bin/install -c -m 644 '../../include/ta_abstract.h' '/usr/include/ta-lib//ta_abstract.h'
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
make[3]: Leaving directory ''
make[2]: Leaving directory ''
Making install in ta_common
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
make: getcwd: No such file or directory
make[2]: Entering directory ''
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
make: getcwd: No such file or directory
make[3]: Entering directory ''
make[3]: Nothing to be done for 'install-exec-am'.
test -z "/usr/include/ta-lib/" || /usr/bin/mkdir -p "/usr/include/ta-lib/"
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
 /usr/bin/install -c -m 644 '../../include/ta_defs.h' '/usr/include/ta-lib//ta_defs.h'
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
 /usr/bin/install -c -m 644 '../../include/ta_libc.h' '/usr/include/ta-lib//ta_libc.h'
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
 /usr/bin/install -c -m 644 '../../include/ta_common.h' '/usr/include/ta-lib//ta_common.h'
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
make[3]: Leaving directory ''
make[2]: Leaving directory ''
Making install in ta_func
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
make: getcwd: No such file or directory
make[2]: Entering directory ''
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
make: getcwd: No such file or directory
make[3]: Entering directory ''
make[3]: Nothing to be done for 'install-exec-am'.
test -z "/usr/include/ta-lib/" || /usr/bin/mkdir -p "/usr/include/ta-lib/"
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
 /usr/bin/install -c -m 644 '../../include/ta_defs.h' '/usr/include/ta-lib//ta_defs.h'
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
 /usr/bin/install -c -m 644 '../../include/ta_libc.h' '/usr/include/ta-lib//ta_libc.h'
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
 /usr/bin/install -c -m 644 '../../include/ta_func.h' '/usr/include/ta-lib//ta_func.h'
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
make[3]: Leaving directory ''
make[2]: Leaving directory ''`

**Comment by mrjbq7** [comment]
``getcwd: cannot access parent directories``

**Comment by mrjbq7** [comment]
(Does the user you are using have write permissions to ``/usr``?)

**Comment by hhashim1** [comment]
I am the user and I am logged in as root.

**Comment by mrjbq7** [comment]
It’s possible it doesn’t support install from a directory with a space in
it.

***@***.***:/mnt/e/dropbox/documents/visual studio
2019/repos/ta4j/deephaven-core/ta-lib#

**Comment by hhashim1** [comment]
So I ran it again and this is what I got. Does this mean that it was installed successfully?

`root@FALCONXTREME:/mnt/e/dropbox/documents/visual studio 2019/repos/ta4j/deephaven-core# cd ta-lib
root@FALCONXTREME:/mnt/e/dropbox/documents/visual studio 2019/repos/ta4j/deephaven-core/ta-lib# sudo make install
Making install in src
make[1]: Entering directory '/mnt/e/dropbox/documents/visual studio 2019/repos/ta4j/deephaven-core/ta-lib/src'
Making install in ta_abstract
make[2]: Entering directory '/mnt/e/dropbox/documents/visual studio 2019/repos/ta4j/deephaven-core/ta-lib/src/ta_abstract'
make[3]: Entering directory '/mnt/e/dropbox/documents/visual studio 2019/repos/ta4j/deephaven-core/ta-lib/src/ta_abstract'
make[3]: Nothing to be done for 'install-exec-am'.
test -z "/usr/include/ta-lib/" || /usr/bin/mkdir -p "/usr/include/ta-lib/"
 /usr/bin/install -c -m 644 '../../include/ta_defs.h' '/usr/include/ta-lib//ta_defs.h'
 /usr/bin/install -c -m 644 '../../include/ta_libc.h' '/usr/include/ta-lib//ta_libc.h'
 /usr/bin/install -c -m 644 '../../include/ta_abstract.h' '/usr/include/ta-lib//ta_abstract.h'
make[3]: Leaving directory '/mnt/e/dropbox/documents/visual studio 2019/repos/ta4j/deephaven-core/ta-lib/src/ta_abstract'
make[2]: Leaving directory '/mnt/e/dropbox/documents/visual studio 2019/repos/ta4j/deephaven-core/ta-lib/src/ta_abstract'
Making install in ta_common
make[2]: Entering directory '/mnt/e/dropbox/documents/visual studio 2019/repos/ta4j/deephaven-core/ta-lib/src/ta_common'
make[3]: Entering directory '/mnt/e/dropbox/documents/visual studio 2019/repos/ta4j/deephaven-core/ta-lib/src/ta_common'
make[3]: Nothing to be done for 'install-exec-am'.
test -z "/usr/include/ta-lib/" || /usr/bin/mkdir -p "/usr/include/ta-lib/"
 /usr/bin/install -c -m 644 '../../include/ta_defs.h' '/usr/include/ta-lib//ta_defs.h'
 /usr/bin/install -c -m 644 '../../include/ta_libc.h' '/usr/include/ta-lib//ta_libc.h'
 /usr/bin/install -c -m 644 '../../include/ta_common.h' '/usr/include/ta-lib//ta_common.h'
make[3]: Leaving directory '/mnt/e/dropbox/documents/visual studio 2019/repos/ta4j/deephaven-core/ta-lib/src/ta_common'
make[2]: Leaving directory '/mnt/e/dropbox/documents/visual studio 2019/repos/ta4j/deephaven-core/ta-lib/src/ta_common'
Making install in ta_func
make[2]: Entering directory '/mnt/e/dropbox/documents/visual studio 2019/repos/ta4j/deephaven-core/ta-lib/src/ta_func'
make[3]: Entering directory '/mnt/e/dropbox/documents/visual studio 2019/repos/ta4j/deephaven-core/ta-lib/src/ta_func'
make[3]: Nothing to be done for 'install-exec-am'.
test -z "/usr/include/ta-lib/" || /usr/bin/mkdir -p "/usr/include/ta-lib/"
 /usr/bin/install -c -m 644 '../../include/ta_defs.h' '/usr/include/ta-lib//ta_defs.h'
 /usr/bin/install -c -m 644 '../../include/ta_libc.h' '/usr/include/ta-lib//ta_libc.h'
 /usr/bin/install -c -m 644 '../../include/ta_func.h' '/usr/include/ta-lib//ta_func.h'
make[3]: Leaving directory '/mnt/e/dropbox/documents/visual studio 2019/repos/ta4j/deephaven-core/ta-lib/src/ta_func'
make[2]: Leaving directory '/mnt/e/dropbox/documents/visual studio 2019/repos/ta4j/deephaven-core/ta-lib/src/ta_func'
make[2]: Entering directory '/mnt/e/dropbox/documents/visual studio 2019/repos/ta4j/deephaven-core/ta-lib/src'
/bin/bash ../libtool --tag=CC   --mode=link gcc  -g -O2 -version-info 0:0:0  -o libta_lib.la -rpath /usr/lib  ta_abstract/libta_abstract.la ta_func/libta_func.la ta_common/libta_common.la -lpthread -ldl
rm -fr  .libs/libta_lib.lax .libs/libta_lib.so .libs/libta_lib.so.0 .libs/libta_lib.so.0.0.0
gcc -shared  -Wl,--whole-archive ta_abstract/.libs/libta_abstract.a ta_func/.libs/libta_func.a ta_common/.libs/libta_common.a -Wl,--no-whole-archive  -lpthread -ldl  -Wl,-soname -Wl,libta_lib.so.0 -o .libs/libta_lib.so.0.0.0
(cd .libs && rm -f libta_lib.so.0 && ln -s libta_lib.so.0.0.0 libta_lib.so.0)
(cd .libs && rm -f libta_lib.so && ln -s libta_lib.so.0.0.0 libta_lib.so)
rm -fr .libs/libta_lib.lax
mkdir .libs/libta_lib.lax
rm -fr .libs/libta_lib.lax/libta_abstract.a
mkdir .libs/libta_lib.lax/libta_abstract.a
(cd .libs/libta_lib.lax/libta_abstract.a && ar x /mnt/e/dropbox/documents/visual studio 2019/repos/ta4j/deephaven-core/ta-lib/src/ta_abstract/.libs/libta_abstract.a)
ar: /mnt/e/dropbox/documents/visual: No such file or directory
make[2]: *** [Makefile:262: libta_lib.la] Error 9
make[2]: Leaving directory '/mnt/e/dropbox/documents/visual studio 2019/repos/ta4j/deephaven-core/ta-lib/src'
make[1]: *** [Makefile:283: install-recursive] Error 1
make[1]: Leaving directory '/mnt/e/dropbox/documents/visual studio 2019/repos/ta4j/deephaven-core/ta-lib/src'
make: *** [Makefile:283: install-recursive] Error 1
root@FALCONXTREME:/mnt/e/dropbox/documents/visual studio 2019/repos/ta4j/deephaven-core/ta-lib#
`

**Comment by hhashim1** [comment]
it does look like the directory with space is getting chopped off.  What can be done at this point?

` /mnt/e/dropbox/documents/visual: No such file or directory`

**Comment by mrjbq7** [comment]
No, you need to not have spaces in the directories, see this error in that
log output for example:

/mnt/e/dropbox/documents/visual: No such file or directory make[2]: ***
[Makefile:262: libta_lib.la] Error 9 make[2]: Leaving directory

**Comment by mrjbq7** [comment]
Move it to a directory without spaces! Try again.

**Comment by hhashim1** [comment]
That worked. Maybe in future revisions can you update the code to address spaces in directory names?

**Comment by mrjbq7** [comment]
I do not support or maintain the underlying C library, sorry.

**Comment by mrjbq7** [comment]
You have to install this python project.

    https://github.com/mrjbq7/ta-lib#installation

The original problem you have above is installing the underlying TA-Lib C library that this python project uses.

**Comment by hhashim1** [comment]
So looks like I got the lib installed now but my IDE still says No module named 'talib'

`
Type: <class 'ModuleNotFoundError'>
Value: No module named 'talib'
Line: 2`

![image](https://user-images.githubusercontent.com/62855649/153719592-c967b19c-ce30-4526-bc22-6d90099fa0d7.png)

**Comment by hhashim1** [comment]
says already satisfied but IDE won't pick it up. I will play around with it.

**Comment by mrjbq7** [comment]
The most frequent issue is having multiple python's and having the IDE using a different one than you had installed to... sorry it's frustrating... obligatory XKCD:

https://xkcd.com/1987/

**Comment by mrjbq7** [comment]
Closing all installation issues, if someone has a specific problem please open a new one.
