### ISSUE TITLE
fatal error: 'ta-lib/ta_defs.h' file not found

### ISSUE THREAD

**Issue by kvyaswanth** [mrjbq7/ta-lib#508]
MacOS Big Sur, Intel

talib/_ta_lib.c:682:10: fatal error: 'ta-lib/ta_defs.h' file not found
    #include "ta-lib/ta_defs.h"
             ^~~~~~~~~~~~~~~~~~
    1 error generated.
    error: command '/usr/bin/clang' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1

[complete output on pastebin](https://pastebin.com/irTTukke)

**Comment by idreamsfy** [comment]
yes, it's working for me on sonoma
