### ISSUE TITLE
AttributeError: 'module' object has no attribute 'EMA'

### ISSUE THREAD

**Issue by studioguy** [mrjbq7/ta-lib#51]
Hello!

I'm not much of a coder, so this might be irritating, I'm trying to calculate an EMA in python, but i keep getting this error code, and can't use any functions. What am I missing?

My code is the same as posted on the site:

import numpy
import talib

close = numpy.random.random(100)
output = talib.EMA(close)

Thanks for Your help!

**Comment by alizain5693** [comment]
sorry could u elaborate on how u fixed it.

**Comment by mrjbq7** [comment]
Are you also having this problem?

Please post a stacktrace and we can try and help.
