### ISSUE TITLE
talib.SMA returns the same results as talib.EMA

### ISSUE THREAD

**Issue by sdrdis** [mrjbq7/ta-lib#52]
Hi,

It seems that talib.SMA returns the same results as talib.EMA ?

Tested on a recent version:

```
import numpy as np
import talib
A = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0])
print talib.SMA(A, 3)
# prints [ nan  nan   2.   3.   4.   5.   6.   7.   8.   9.]
print talib.EMA(A, 3)
# prints [ nan  nan   2.   3.   4.   5.   6.   7.   8.   9.] => the same thing
```

Thanks !

**Comment by fortier** [comment]
Sorry for late reply. 

This is normal. The values returned by TA-Lib are correct.

SMA(3) and EMA(3) of a time series that increments by one are equivalent. Calculating a few manually should be convincing.

Alternatively, you can verify that changing your input to not be monotonic with constant increment will produce different outputs. In other word, try with something like {1,2,3,4,6,5,7,8,9}

\Mario Fortier
