### ISSUE TITLE
Calculating Z-score?

### ISSUE THREAD

**Issue by Synthacon** [mrjbq7/ta-lib#530]
Is it possible to calculate z-score using Ta-lib functions/ indicators? 

It's very easy to do using Pine script build in functions:
src = close, len = input(2000, minval=1, title="Length")
aver= sma(src, len)
stdev = stdev(src, len)
a= (src-aver)
out =(a/stdev)

Is it possible to do same with Ta-lib?

**Comment by mrjbq7** [comment]
``SMA`` and ``STDDEV`` are available in TA-Lib...
