### ISSUE TITLE
Ta-lib Import error- I have installed python 3.8 by using brew and followed your steps brew install ta-lib and so on

### ISSUE THREAD

**Issue by surendrakandru** [mrjbq7/ta-lib#533]
ImportError: dlopen(/Users/surendrakandru/Desktop/pythonProject/venv/lib/python3.8/site-packages/talib/_ta_lib.cpython-38-darwin.so, 0x0002): tried: '/Users/suri/Desktop/pythonProject/venv/lib/python3.8/site-packages/talib/_ta_lib.cpython-38-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))

**Comment by mrjbq7** [comment]
That error seems to be pretty obviously related to having mixed architectures. You are on Apple Silicon and likely need the ARM64 version instead of x86-64 or vice versa.

See the README for some suggestions.

**Comment by mrjbq7** [comment]
Unless there's something else you need help with, closing for now.
