### ISSUE TITLE
Symbol not found in flat namespace (_TA_ACOS)

### ISSUE THREAD

**Issue by yashmitawa122333** [mrjbq7/ta-lib#550]
<img width="1381" alt="Screenshot 2022-10-01 at 12 19 48 AM" src="https://user-images.githubusercontent.com/90521962/193337873-122b871e-fc76-4025-91ed-6a7d9943b3fb.png">

**Comment by mrjbq7** [comment]
Did you install it following the directions in the rEADME?

https://github.com/mrjbq7/ta-lib#installation

**Comment by yashmitawa122333** [comment]
Yes I install it as mention in the READme file but won't work

**Comment by yashmitawa122333** [comment]
<img width="668" alt="Screenshot 2022-10-01 at 12 40 30 PM" src="https://user-images.githubusercontent.com/90521962/193397637-c00d99ca-26ca-487f-9f4e-a7873221a7b6.png">


I try to import in my terminal but it won't work please check this and if you have any solution related to this please share with me

**Comment by trufanov-nok** [comment]
Have you did `brew install ta-lib` as in readme? What was the output? What outputs `brew --prefix ta-lib` ?

**Comment by yashmitawa122333** [comment]
![Uploading Screenshot 2022-10-02 at 1.50.19 PM.png…]()


This is the output of the `brew --prefix ta-lib
`

**Comment by yashmitawa122333** [comment]
<img width="336" alt="Screenshot 2022-10-02 at 1 54 24 PM" src="https://user-images.githubusercontent.com/90521962/193445067-7515c0cc-4a0f-46cd-a070-3435a516b7f5.png">

This is the output of the `brew --prefix ta-lib`

**Comment by yashmitawa122333** [comment]
Hello Thank you for you assistance to solve this issue related to the ta-lib module, thanks for helping me and now this issue is solved now

**Comment by mrjbq7** [comment]
Can you let us know what the resolution was? Maybe I can add a note to the Troubleshooting section of the README. On Oct 2, 2022, at 10:39 AM, Yash Mitawa ***@***.***> wrote:﻿
Closed #550 as completed.

**Comment by yashmitawa122333** [comment]
Hello sir,
i don't know how to solve this issue that i created so i need you
assistance to install this package and work with this package,
so, if you got some free time in you daily routing please can you connect
with me and help me to solve this problem.
please let me know is you agree to connect with me, i try to do this by
myself but i recently shift on the macOS so i don't know much about that so
please help
me to solve this issue.

Thank you so much

**Comment by QST23** [comment]
Did you manage to solve it in the end? I'm experiencing the same for a while now. Feel like I tried everything..

**Comment by mrjbq7** [comment]
You just need the underlying TA-Lib C library. On Jan 2, 2023, at 10:35 AM, QST23 ***@***.***> wrote:﻿
Did you manage to solve it in the end? I'm experiencing the same for a while now. Feel like I tried everything..
