### ISSUE TITLE
Can not pass `pd.Series` when using pandas 0.13.0

### ISSUE THREAD

**Issue by ehebert** [mrjbq7/ta-lib#56]
When using pandas 0.12.0, the recent support for pandas structures in the TA-Lib library allows a `pd.Series` to be passed to the tailb function wrapper, e.g. the following code snippet:

```
import numpy as np
import pandas as pd
import talib

print("pandas=={0}".format(pd.__version__))
print("talib=={0}".format(talib.__version__))

s = pd.Series(range(30), index=range(30), dtype=np.float)

ma = talib.MA(s)

print ma[-1]
```

Results in:

```
pandas==0.12.0
talib==0.4.8
14.5
```

However with pandas >= 0.13.0, the same script creates the following exception on the call to `ma = talib.MA(s)`:

```
TypeError: Argument 'real' has incorrect type (expected numpy.ndarray, got Series)
```

In pandas >=f 0.13.0 the type which `pd.Series` sub-classes is no longer `numpy.ndarray`.
For reference, see the current Warning in the documentation of pandas `Series`,
http://pandas.pydata.org/pandas-docs/stable/dsintro.html#series

(Copy/pasted below:)

```
Warning In 0.13.0 Series has internaly been refactored to no longer sub-class ndarray but instead subclass NDFrame, similarly to the rest of the pandas containers. This should be a transparent change with only very limited API implications (See the Internal Refactoring)
```

It looks like https://github.com/mrjbq7/ta-lib/commit/21a27ed9c026eb2c0fa5386b9c8fe49688f2059a extracts the `.values` when a Series is detected, but that code path appears not be hit in my example.

**Comment by cilia** [comment]
This caught me as well with `pandas 0.16.1` and `ta-lib 0.4.9`. The fix by @anddam works, and I think it'd be better to update the doc to reflect this.

**Comment by mrjbq7** [comment]
@cilia Thanks for the note, I would like to fix this sometime - maybe option #2 above is the best?  Or just document that the function interface does not support pandas.Series anymore since they changed them to not subclass ndarray?

**Comment by anddam** [comment]
@mrjbq7 I'd suggest the latter, follow upstream and just document it clearly to the user.

**Comment by cilia** [comment]
@mrjbq7 I think an updated documentation will do. Thanks.
