### ISSUE TITLE
ValueError: numpy.ndarray size changed

### ISSUE THREAD

**Issue by drulye** [mrjbq7/ta-lib#570]
1. install:

cd ~/Downloads
wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz 
tar -xzf ta-lib-0.4.0-src.tar.gz
cd ta-lib/
./configure --prefix=/usr
make
sudo make install
pip install TA-Lib

2. run:

(base) drulye@drulye-MS-7885:~$ python
Python 3.9.13 (main, Aug 25 2022, 23:26:10) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
import numpy
print (numpy.version.version)
1.21.5
import talib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/drulye/anaconda3/lib/python3.9/site-packages/talib/__init__.py", line 93, in <module>
    from ._ta_lib import (
  File "talib/_ta_lib.pyx", line 1, in init talib._ta_lib
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

**Comment by drulye** [comment]
My installation process:

cd ~/Downloads
wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz 
tar -xzf ta-lib-0.4.0-src.tar.gz
cd ta-lib/
./configure --prefix=/usr
make
sudo make install

pip install TA-Lib

**Comment by mrjbq7** [comment]
The easiest fix is to use a newer numpy.

**Comment by drulye** [comment]
Thank you!
The commands below helped me solve the error:

pip uninstall numpy
pip install numpy
