### ISSUE TITLE
talib Import Error

### ISSUE THREAD

**Issue by jasonstrimpel** [mrjbq7/ta-lib#6]
Greetings,

I've installed TA-Lib to its default location:

```
bash$ ls -la /usr/local/include/ta-lib/
total 240
drwxr-xr-x 2 root root   4096 2012-08-04 08:54 .
drwxr-xr-x 3 root root   4096 2012-08-04 08:54 ..
-rw-r--r-- 1 root root  19930 2012-08-04 08:54 ta_abstract.h
-rw-r--r-- 1 root root   4792 2012-08-04 08:54 ta_common.h
-rw-r--r-- 1 root root  12391 2012-08-04 08:54 ta_defs.h
-rw-r--r-- 1 root root 181115 2012-08-04 08:54 ta_func.h
-rw-r--r-- 1 root root   1849 2012-08-04 08:54 ta_libc.h

bash$ ls -la /usr/local/lib
total 4956
drwxr-xr-x  3 root root    4096 2012-08-04 08:54 .
drwxr-xr-x 12 root root    4096 2011-04-06 23:47 ..
-rw-r--r--  1 root root 3063180 2012-08-04 08:54 libta_lib.a
-rwxr-xr-x  1 root root     837 2012-08-04 08:54 libta_lib.la
lrwxrwxrwx  1 root root      18 2012-08-04 08:54 libta_lib.so -> libta_lib.so.0.0.0
lrwxrwxrwx  1 root root      18 2012-08-04 08:54 libta_lib.so.0 -> libta_lib.so.0.0.0
-rwxr-xr-x  1 root root 1983243 2012-08-04 08:54 libta_lib.so.0.0.0
drwxr-xr-x 11 root root    4096 2011-04-07 17:10 pythonEPD
```

I run your setuptools install script:

```
bash$ python setup.py install
running install
running build
running build_ext
skipping 'talib.c' Cython extension (up-to-date)
building 'talib' extension
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -O2 -I/usr/local/lib/pythonEPD/include -fPIC -I/usr/local/lib/pythonEPD/lib/python2.7/site-packages/numpy/core/include -I/usr/local/include/ta-lib/ -I/usr/local/lib/pythonEPD/include/python2.7 -c talib.c -o build/temp.linux-i686-2.7/talib.o

...
[truncated - lots of warnings regarding pointer types]

---

gcc -pthread -shared -g -L/usr/local/lib/pythonEPD/lib build/temp.linux-i686-2.7/talib.o -L/usr/local/lib/ -L. -lta_lib -lpython2.7 -o build/lib.linux-i686-2.7/talib.so
running install_lib
copying build/lib.linux-i686-2.7/talib.so -> /usr/local/lib/pythonEPD/lib/python2.7/site-packages
running install_egg_info
Writing /usr/local/lib/pythonEPD/lib/python2.7/site-packages/TA_Lib-0.4.0-py2.7.egg-info
```

Yet when I attempt to run the example scripts or import talib, I get the following:

```
bash$ python
Enthought Python Distribution -- www.enthought.com
Version: 7.0-2 (32-bit)

Python 2.7.1 |EPD 7.0-2 (32-bit)| (r271:86832, Nov 29 2010, 13:52:51) 
[GCC 4.1.2 20080704 (Red Hat 4.1.2-44)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import talib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libta_lib.so.0: cannot open shared object file: No such file or directory
```

The setup.py script clearly includes the appropriate paths to the compiled TA-Lib code in the Extension class.

Can you shed some light on the problem?

Platform is linux2, Python 2.7.

Thanks and great work on the software. Looking forward to getting it running.

**Comment by skytalemcc** [comment]
me too .found the issue ,please advis how to fix it .thanks

Python 2.7.11 |Anaconda 4.0.0 (64-bit)| (default, Dec  6 2015, 18:08:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import talib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda2/lib/python2.7/site-packages/talib/__init__.py", line 4, in <module>
    from . import common
ImportError: libta_lib.so.0: cannot open shared object file: No such file or directory
>>> exit()
[root@localhost ~]# cat /etc/ld.so.conf
include ld.so.conf.d/*.conf
include /usr/local/lib
[root@localhost ~]#  /sbin/ldconfig
[root@localhost ~]#

**Comment by mrjbq7** [comment]
Please advise? Have you tried all the debugging suggestions in this issue above? The error message says it can't find the underlying ta-lib C library so you have to figure out why... Probably an issue with LD_LIBRARY_PATH.

**Comment by Pranav-Srinivasan** [comment]
Hey,
I'm also getting the same error
I have python installed using anaconda and I run RHEL

**Comment by mrjbq7** [comment]
@Pranav-Srinivasan where is your ``libta_lib.so.0`` file installed?  Mine, for example, is in ``/usr/local/lib/libta_lib.so.0``.  I wonder if you have a similar issue to this one:

https://github.com/mrjbq7/ta-lib/issues/6#issuecomment-7515753

**Comment by Pranav-Srinivasan** [comment]
How do I find out the location of the file?

**Comment by mrjbq7** [comment]
```python
>>> import ctypes.util
>>> ctypes.util.find_library('libta_lib')
```

**Comment by Pranav-Srinivasan** [comment]
Both the commands got executed without any output?

**Comment by mrjbq7** [comment]
```print ctypes.util.find_library('libta_lib')```

**Comment by Pranav-Srinivasan** [comment]
![capture](https://cloud.githubusercontent.com/assets/11709251/19776480/d94711f8-9c91-11e6-941f-02d04ef3b060.PNG)

It says none. :/

**Comment by Pranav-Srinivasan** [comment]
![capture](https://cloud.githubusercontent.com/assets/11709251/19776761/0b3233cc-9c93-11e6-8d37-61b1762bbdf5.PNG)

Yes, it does work if I start python like that.

**Comment by mrjbq7** [comment]
No, I mean does ``ctypes`` find the library when you start python like that?

**Comment by Pranav-Srinivasan** [comment]
No, it still says None.

To install TA-Lib, I did

Download ta-lib-0.4.0-src.tar.gz and:

$ untar and cd
$ ./configure --prefix=/usr
$ make
$ sudo make install

and then pip install TA-Lib. All the commands got executed without any error.

I'm new to all this so sorry if I am making any silly mistakes. Thanks for bearing with me.

**Comment by mrjbq7** [comment]
Well if you did ``--prefix=/usr`` then the library is probably in ``/usr/lib/libta_lib.so.0``?

**Comment by Pranav-Srinivasan** [comment]
![capture](https://cloud.githubusercontent.com/assets/11709251/19777053/20d9764e-9c94-11e6-965d-c92aceec133a.PNG)

Well, I did find /usr/lib/libta_lib.so.0 ->libta_lib.so.0.0.0

**Comment by mrjbq7** [comment]
That's weird that python couldn't find it... what about using this?

```
$ LD_LIBRARY_PATH="/usr/lib:$LD_LIBRARY_PATH" python
```

**Comment by Pranav-Srinivasan** [comment]
![capture](https://cloud.githubusercontent.com/assets/11709251/19777197/bc98f46a-9c94-11e6-8f4f-dd16b795b8e2.PNG)

Still says None.

**Comment by mrjbq7** [comment]
Hmm, not sure what's wrong with your setup!

**Comment by Pranav-Srinivasan** [comment]
Should I reinstall anything that may fix this?

**Comment by Pranav-Srinivasan** [comment]
Hey Hey!

if I import talib it's getting imported now! 😄 
![capture](https://cloud.githubusercontent.com/assets/11709251/19777492/0eee74e6-9c96-11e6-8398-5b63f3752b5e.PNG)

But if I normally import talib by just typing python, it's giving the same error again.

So I exported the environment variable using
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
and it's importing normally now

However if I open the terminal again, it gives the error again. So how do I put the export in .bashrc file like you said?

Also, running ldconfig -v | grep ta_lib gives the following

![capture](https://cloud.githubusercontent.com/assets/11709251/19777676/002d1682-9c97-11e6-87df-16511360b954.PNG)

**Comment by Pranav-Srinivasan** [comment]
I ran with sudo and it gave the following output

![capture](https://cloud.githubusercontent.com/assets/11709251/19777735/3aead372-9c97-11e6-9b02-9f1d9f6afd63.PNG)

**Comment by mrjbq7** [comment]
Great!

You can add this line to your ``~/.bashrc`` file (assuming you use bash as a shell):

```
export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
```

That should make sure it's changed for the next terminal window you open.

**Comment by Pranav-Srinivasan** [comment]
And it's working! Thanks a ton! 😃

**Comment by mrjbq7** [comment]
Glad I could help, it's sometimes hard to debug remotely.

If you have any feedback after using it, let me know!
