### ISSUE TITLE
Need Help how to install ta-lib

### ISSUE THREAD

**Issue by hugebaozi** [mrjbq7/ta-lib#60]
I have ta-lib in C:\
I have vs 2012
After I downloaded the ta-lib for python and call python setup.py install i get some errors.
common.obj : error LNK2019: unresolved external symbol TA_GetVersionString refer
enced in function initcommon
common.obj : error LNK2019: unresolved external symbol TA_Initialize referenced
in function __pyx_pf_5talib_6common_2_ta_initialize
common.obj : error LNK2019: unresolved external symbol TA_Shutdown referenced in
 function __pyx_pf_5talib_6common_4_ta_shutdown
build\lib.win-amd64-2.7\talib\common.pyd : fatal error LNK1120: 3 unresolved ext
ernals
error: command '"D:\Program Files\Microsoft Visual Studio 11.0\VC\BIN\amd64\link
.exe"' failed with exit status 1120

Help plz!

**Comment by uberscientist** [comment]
The original problem was solved by re-compiling ta-lib:

> Unresolved Symbols

> TA-Lib was compiled for 32-bit systems. If you are on a 64-bit system you most likely have a 64-bit version of Python. Due to this mismatch, symbols cannot be resolved and will result in the following errors:
> 
> common.obj : error LNK2019: unresolved external symbol TA_Initialize referenced in function __pyx_pf_5talib_6common_2_ta_initialize
> common.obj : error LNK2019: unresolved external symbol TA_Shutdown referenced in function __pyx_pf_5talib_6common_4_ta_shutdown
> common.obj : error LNK2019: unresolved external symbol TA_GetVersionString referenced in function initcommon
> build\lib.win-amd64-2.7\talib\common.pyd : fatal error LNK1120: 3 unresolved externals
> error: command ‘C:\\Users\\robert\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\link.exe’ failed with exit status 1120
> 
> To resolve this issue we have to recompile TA-Lib in 64-bit. First open the “Visual C++ 2008 64-bit Command Prompt” which was installed with the “Microsoft Visual Studio C++ 9.0” compiler (the internal version 9.0 is the official 2008 version).
> In the command prompt change the directory to where the MAKEFILE for TA-Lib is, i.e. cd C:\ta-lib\c\make\cdr\win32\msvc. Then compile TA-Lib by entering nmake.

[Source: Robert's Blog](http://familiemeier.ch/robertsblog/2016/03/06/quantiacs-ta-lib/)

**Comment by mrjbq7** [comment]
Closing all installation issues, if someone has a specific problem please open a new one.
