### ISSUE TITLE
ta-lib failed to install on windows and i tried mac os i failed again

### ISSUE THREAD

**Issue by hugebaozi** [mrjbq7/ta-lib#61]
Error message:
'''
 4 from . import common
      5 from . import abstract
      6 from .common import MA_Type, **ta_version**

ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/talib/common.so, 2): Symbol not found: _TA_GetVersionString
  Referenced from: /Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/talib/common.so
  Expected in: dynamic lookup
'''
after compile below
file `which python` it returns..
/Library/Frameworks/Python.framework/Versions/Current/bin/python: Mach-O executable i386

what should i do.. Plz give some steps what to do..

**Comment by akbarboghani** [comment]
> I'm sorry you are having problems.
> 
> Unlike on Windows, installing on Linux and Mac OS X should be easy to do.
> 
> On the Mac, you need to have the `ta-lib` underlying C library (you can get this by `brew install ta-lib` if you are using Homebrew http://brew.sh/, or by downloading `ta-lib-0.4.0-src.tar.gz` from http://ta-lib.org/hdr_dw.html and running `./configure; make; make install`).
> 
> Then you can just `python setup.py install` my python `ta-lib` module (or run `easy_install ta-lib` to install from PyPI).

I am able to install ta-lib usig brew on my mac successfully. But when i run command 'import talib', I get the message ' No module named 'talib''

**Comment by akbarboghani** [comment]
I am able to install ta-lib usig brew on my mac successfully. But when i run command 'import talib', I get the message ' No module named 'talib''

**Comment by Mohita21** [comment]
I'm getting similar error @akbarboghani

**Comment by MadalinGeorge** [comment]
Yes, I spent like 2 hours trying to install it in windows and after that in Mac, and it's impossible :( I installed it with brew but I can´t do the step with pip

**Comment by mrjbq7** [comment]
Have you tried “brew link ta-lib”?

Are you on an M1?

**Comment by MadalinGeorge** [comment]
Yes, I tried a lot of things :( I´m a little frustrated, but it´s ok, thank you for your help

**Comment by mrjbq7** [comment]
I hear you, but it’s not magic, if it’s not working it’s either architecture mismatch, library path not found, or similar configuration issue. 

I realize you run pip which maybe hid the errors, can you try Python3 setup.py install with the Python you are using?

**Comment by MadalinGeorge** [comment]
I just tried, it throw me this error /Library/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'setup.py': [Errno 2] No such file or directory

But I just tried again pip3 install TA-Lib and looks like works, maybe because I just update to Big Sur 11.2.2? 
I don't understand it, because I tried a lot of tutorials, and reinstalling everything and didn´t work...

**Comment by mrjbq7** [comment]
Well you have to run it with a download of the python project you want to install, of course otherwise the setup.py file is not found. 

Well, if it worked that’s great. If it did not, I would be happy to help troubleshoot further. Did there is something I can do to improve the documentation, let me know. 

Best,

**Comment by jpcam** [comment]
Similar issue when I try to import talib I get module not found error even though the ta-lib files have been downloaded
"==> Downloading https://homebrew.bintray.com/bottles/ta-lib-0.4.0.sierra.bottle.
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/0229a85f2bdaa14baabe8
######################################################################## 100.0%
==> Pouring ta-lib-0.4.0.sierra.bottle.1.tar.gz
🍺  /usr/local/Cellar/ta-lib/0.4.0: 14 files, 2.4MB
 "
Any suggestions? tried python3 setyup.py from the same location as brew. I also got Errno 2
when I tried python setup.py install, python3 setup.py, etc
Thank you!

**Comment by mrjbq7** [comment]
Did you try “brew link ta-lib” before setup.py?

**Comment by jpcam** [comment]
just tried that still get same error

**Comment by mrjbq7** [comment]
What is the error you see when you try and setup.py?

**Comment by jpcam** [comment]
python3: can't open file 'setup.py': [Errno 2] No such file or directory
and
python: can't open file 'setup.py': [Errno 2] No such file or directory
not sure if this is useful :
(base) MacBook-Pro-2:~ EPIC$ brew list
autoconf		libmpc			python
autoconf-archive	libpng			python@3.9
automake		libtiff			readline
bison			libtool			sphinx-doc
cmake			little-cms2		sqlite
doxygen			mpdecimal		ta-lib
gdbm			mpfr			tcl-tk
giflib			openjpeg		tesseract
gmp			openssl@1.1		webp
isl			pkg-config		xz
jpeg			platypus
leptonica		pyinstaller

**Comment by mrjbq7** [comment]
Well, I mean you need to either pip install ta-lib or download this project
(git clone) and change to the directory and run setup.py.

**Comment by jpcam** [comment]
can you share a simple py script to test to see if ta-lib has imported?

**Comment by mrjbq7** [comment]
$ python3 -c “import ta-lib”

**Comment by jpcam** [comment]
sequence of events:
brew install pyinstaller
brew install ta-lib
pip install ta-lib
works as follows:
``import numpy
import talib

close = numpy.random.random(25)
output = talib.SMA(close)
output``

Jupyter out:
array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

Thanks

**Comment by mrjbq7** [comment]
Sounds like it’s working maybe, not sure what the default window size is on SMA but try a smaller window.

**Comment by pietrop80** [comment]
to me it worked with sudo pip install ta-lib. Without sudo it fails.

**Comment by mrjbq7** [comment]
That use of sudo depends entirely on your write permissions to your Python installation site resource directory, or wherever pip installs Python modules.

**Comment by bitbitterbit** [comment]
I ran command "pip install Ta-lib" and I got the following error :/

Collecting ta-lib
  Using cached TA-Lib-0.4.19.tar.gz (267 kB)
Requirement already satisfied: numpy in ./opt/anaconda3/lib/python3.8/site-packages (from ta-lib) (1.19.2)
Building wheels for collected packages: ta-lib
  Building wheel for ta-lib (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/sahasmac/opt/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/3l/xjcqcbfs2mxfz_jxms67wg3m0000gn/T/pip-install-4z7ruqq7/ta-lib/setup.py'"'"'; __file__='"'"'/private/var/folders/3l/xjcqcbfs2mxfz_jxms67wg3m0000gn/T/pip-install-4z7ruqq7/ta-lib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/3l/xjcqcbfs2mxfz_jxms67wg3m0000gn/T/pip-wheel-h1brs5lz
       cwd: /private/var/folders/3l/xjcqcbfs2mxfz_jxms67wg3m0000gn/T/pip-install-4z7ruqq7/ta-lib/
  Complete output (28 lines):
  /private/var/folders/3l/xjcqcbfs2mxfz_jxms67wg3m0000gn/T/pip-install-4z7ruqq7/ta-lib/setup.py:71: UserWarning: Cannot find ta-lib library, installation may fail.
    warnings.warn('Cannot find ta-lib library, installation may fail.')
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.8
  creating build/lib.macosx-10.9-x86_64-3.8/talib
  copying talib/abstract.py -> build/lib.macosx-10.9-x86_64-3.8/talib
  copying talib/test_abstract.py -> build/lib.macosx-10.9-x86_64-3.8/talib
  copying talib/deprecated.py -> build/lib.macosx-10.9-x86_64-3.8/talib
  copying talib/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/talib
  copying talib/stream.py -> build/lib.macosx-10.9-x86_64-3.8/talib
  copying talib/test_pandas.py -> build/lib.macosx-10.9-x86_64-3.8/talib
  copying talib/test_data.py -> build/lib.macosx-10.9-x86_64-3.8/talib
  copying talib/test_func.py -> build/lib.macosx-10.9-x86_64-3.8/talib
  copying talib/test_stream.py -> build/lib.macosx-10.9-x86_64-3.8/talib
  running build_ext
  skipping 'talib/_ta_lib.c' Cython extension (up-to-date)
  building 'talib._ta_lib' extension
  creating build/temp.macosx-10.9-x86_64-3.8
  creating build/temp.macosx-10.9-x86_64-3.8/talib
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/sahasmac/opt/anaconda3/include -arch x86_64 -I/Users/sahasmac/opt/anaconda3/include -arch x86_64 -I/usr/include -I/usr/local/include -I/opt/include -I/opt/local/include -I/Users/sahasmac/opt/anaconda3/lib/python3.8/site-packages/numpy/core/include -I/Users/sahasmac/opt/anaconda3/include/python3.8 -c talib/_ta_lib.c -o build/temp.macosx-10.9-x86_64-3.8/talib/_ta_lib.o
  talib/_ta_lib.c:611:10: fatal error: 'ta-lib/ta_defs.h' file not found
  #include "ta-lib/ta_defs.h"
           ^~~~~~~~~~~~~~~~~~
  1 error generated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for ta-lib
  Running setup.py clean for ta-lib
Failed to build ta-lib
Installing collected packages: ta-lib
    Running setup.py install for ta-lib ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/sahasmac/opt/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/3l/xjcqcbfs2mxfz_jxms67wg3m0000gn/T/pip-install-4z7ruqq7/ta-lib/setup.py'"'"'; __file__='"'"'/private/var/folders/3l/xjcqcbfs2mxfz_jxms67wg3m0000gn/T/pip-install-4z7ruqq7/ta-lib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/3l/xjcqcbfs2mxfz_jxms67wg3m0000gn/T/pip-record-n5i67ckj/install-record.txt --single-version-externally-managed --compile --install-headers /Users/sahasmac/opt/anaconda3/include/python3.8/ta-lib
         cwd: /private/var/folders/3l/xjcqcbfs2mxfz_jxms67wg3m0000gn/T/pip-install-4z7ruqq7/ta-lib/
    Complete output (28 lines):
    /private/var/folders/3l/xjcqcbfs2mxfz_jxms67wg3m0000gn/T/pip-install-4z7ruqq7/ta-lib/setup.py:71: UserWarning: Cannot find ta-lib library, installation may fail.
      warnings.warn('Cannot find ta-lib library, installation may fail.')
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.8
    creating build/lib.macosx-10.9-x86_64-3.8/talib
    copying talib/abstract.py -> build/lib.macosx-10.9-x86_64-3.8/talib
    copying talib/test_abstract.py -> build/lib.macosx-10.9-x86_64-3.8/talib
    copying talib/deprecated.py -> build/lib.macosx-10.9-x86_64-3.8/talib
    copying talib/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/talib
    copying talib/stream.py -> build/lib.macosx-10.9-x86_64-3.8/talib
    copying talib/test_pandas.py -> build/lib.macosx-10.9-x86_64-3.8/talib
    copying talib/test_data.py -> build/lib.macosx-10.9-x86_64-3.8/talib
    copying talib/test_func.py -> build/lib.macosx-10.9-x86_64-3.8/talib
    copying talib/test_stream.py -> build/lib.macosx-10.9-x86_64-3.8/talib
    running build_ext
    skipping 'talib/_ta_lib.c' Cython extension (up-to-date)
    building 'talib._ta_lib' extension
    creating build/temp.macosx-10.9-x86_64-3.8
    creating build/temp.macosx-10.9-x86_64-3.8/talib
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/sahasmac/opt/anaconda3/include -arch x86_64 -I/Users/sahasmac/opt/anaconda3/include -arch x86_64 -I/usr/include -I/usr/local/include -I/opt/include -I/opt/local/include -I/Users/sahasmac/opt/anaconda3/lib/python3.8/site-packages/numpy/core/include -I/Users/sahasmac/opt/anaconda3/include/python3.8 -c talib/_ta_lib.c -o build/temp.macosx-10.9-x86_64-3.8/talib/_ta_lib.o
    talib/_ta_lib.c:611:10: fatal error: 'ta-lib/ta_defs.h' file not found
    #include "ta-lib/ta_defs.h"
             ^~~~~~~~~~~~~~~~~~
    1 error generated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/sahasmac/opt/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/3l/xjcqcbfs2mxfz_jxms67wg3m0000gn/T/pip-install-4z7ruqq7/ta-lib/setup.py'"'"'; __file__='"'"'/private/var/folders/3l/xjcqcbfs2mxfz_jxms67wg3m0000gn/T/pip-install-4z7ruqq7/ta-lib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/3l/xjcqcbfs2mxfz_jxms67wg3m0000gn/T/pip-record-n5i67ckj/install-record.txt --single-version-externally-managed --compile --install-headers /Users/sahasmac/opt/anaconda3/include/python3.8/ta-lib Check the logs for full command output.

**Comment by mrjbq7** [comment]
UserWarning: Cannot find ta-lib library, installation may fail.


You need to install the TA-Lib underlying C library first.

See the README for details for your platform.

**Comment by bitbitterbit** [comment]
I already installed C but It still doesn't work 
%brew install gcc
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 7 formulae.

Warning: gcc 11.1.0 is already installed and up-to-date.
To reinstall 11.1.0, run:
  brew reinstall gcc

**Comment by mrjbq7** [comment]
$ brew install ta-lib

Are you on an M1?

**Comment by bitbitterbit** [comment]
yes M1, "$ brew install ta-lib" works but "pip install ta-lib" doesn't

**Comment by mrjbq7** [comment]
Please just read the README when I suggest:

If you are using a M1 laptop and Homebrew, then you can set these before installing:

export TA_INCLUDE_PATH="$(brew --prefix ta-lib)/include"
export TA_LIBRARY_PATH="$(brew --prefix ta-lib)/lib”

**Comment by bitbitterbit** [comment]
I added PATH and it worked.
Cheers!

**Comment by mrjbq7** [comment]
Closing all installation issues, if someone has a specific problem please open a new one.
