### ISSUE TITLE
RSI Calculation Requires One Extra Data Point (`timeperiod + 1`) Compared to Other Indicators (e.g., SMA)

### ISSUE THREAD

**Issue by gitctrlx** [mrjbq7/ta-lib#686]
I’ve encountered a discrepancy in the behavior of the RSI (Relative Strength Index) calculation in the TA-Lib library. Unlike other indicators such as the SMA (Simple Moving Average), which requires exactly `timeperiod` data points, the RSI calculation appears to require `timeperiod + 1` data points. This discrepancy can cause confusion, especially when working with smaller datasets.

When using `timeperiod` data points, the RSI calculation returns `NaN` for the initial values, and only starts providing valid RSI values after `timeperiod + 1` data points are provided. This behavior is different from the SMA function, which calculates valid values with exactly `timeperiod` data points.

Could you please clarify whether this behavior is intentional, and if so, provide an explanation as to why it differs from other indicators like SMA? It would also be helpful to document this behavior in the official documentation for clarity and to avoid confusion for other users.

### Steps to Reproduce:
1. Import the TA-Lib library.
2. Create a sample DataFrame with a single column of data.
3. Calculate the RSI with a window size of `timeperiod - 1` using the `talib.RSI()` function.
4. Print the RSI values.
5. Compare the behavior with the SMA function.

### Code to Reproduce the Issue:

```python
import pandas as pd
import talib

# Create a sample DataFrame with 10 values
data = {
    'col1': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
}

df = pd.DataFrame(data)

# Calculate RSI with 'timeperiod - 1'
rsi = talib.RSI(df['col1'], timeperiod=9)

# Print the RSI values
print(rsi)
```

### Expected Behavior:
- For RSI with a `timeperiod` of 9, the first valid RSI value should appear at index 8 (i.e., `timeperiod - 1`), consistent with other indicators like SMA.

### Actual Behavior:
- When using `timeperiod=9`, the RSI calculation returns `NaN` for the first 9 data points. The first valid RSI value appears only after `timeperiod + 1` data points (i.e., at the 10th data point).

#### RSI:
```python
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
5      NaN
6      NaN
7      NaN
8      NaN
9    100.0
dtype: float64
```

#### SMA:
```python
0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    5.0
9    6.0
dtype: float64
```

### Code to Compare with SMA:

```python
import pandas as pd
import talib

# Create a sample DataFrame with 10 values
data = {
    'col1': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
}

df = pd.DataFrame(data)

# Calculate SMA with a window size of 9
sma = talib.SMA(df['col1'], timeperiod=9)

# Print the SMA values
print(sma)
```

### Additional Information:
- **TA-Lib Version**: 0.5.1
- **Python Version**: Python 3.12

### Request:
Could you please confirm whether this behavior is intentional for the RSI function? If it is, could you provide an explanation for why it requires `timeperiod + 1` data points? Additionally, it would be useful to document this behavior in the official TA-Lib documentation to prevent confusion for other users.

Thank you for your time and consideration!

**Comment by mrjbq7** [comment]
I don't think that is wrong, it uses ``timeperiod`` observations, but those observations are price changes, so it requires one more data point to get the first non-NaN.

Do you have an example where you think it should produce something different?
