### ISSUE TITLE
TA-lib import fails on Fedora 21 using Anaconda python

### ISSUE THREAD

**Issue by dcottle** [mrjbq7/ta-lib#70]
import talib gives the following errors:

/home/dave/anaconda/lib/python2.7/site-packages/setuptools-7.0-py2.7.egg/pkg_resources.py:1045: UserWarning: /home/dave/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).

ImportError                               Traceback (most recent call last)
<ipython-input-1-9bc7b4202a1f> in <module>()
----> 1 import talib

/home/dave/build/bdist.linux-x86_64/egg/talib/__init__.py in <module>()
/home/dave/build/bdist.linux-x86_64/egg/talib/common.py in <module>()
/home/dave/build/bdist.linux-x86_64/egg/talib/common.py in __bootstrap__()
ImportError: libta_lib.so.0: cannot open shared object file: No such file or directory

I installed TA-Lib into /usr using the instructions provided for linux. TA-lib was installed in /usr/lib which contains libta_lib.a, libta_lib.la, libta_lib.so.0, and libta_lib.so.0.0.0.

I used easy_install TA-Lib, which seemed to work since TA_Lib-0.4.8-py2.7-linux-x86_64.egg was added to ~/anaconda/lib/python2.7/site-packages.

Did I make a mistake somewhere in the installation of either the library or the module, or is there a way that I can point the module to the location of the libraries?

There is another default python installation included with Fedora, but I used the version of easy_install included with Anaconda.

**Comment by mrjbq7** [comment]
The ``setup.py`` looks for the required C libraries (https://github.com/mrjbq7/ta-lib/blob/master/setup.py#L46), although the check is not very thorough.  I would think that if you are having a problem you might have an issue of either:

1) Installing 32-bit C libraries when you need 64-bit, or vice versa, or...

2) Not having your library path working properly, maybe try:

```
$ LD_LIBRARY_PATH=/usr/lib python -c "import talib; print talib.__ta_version__"
```

**Comment by mrjbq7** [comment]
Also, you might be able to see what path to ``libta_lib.so.0`` it is trying to open by doing:

```
$ strace python -c "import talib"
```

**Comment by dcottle** [comment]
I tried:

LD_LIBRARY_PATH=/usr/lib python -c "import talib; print talib.__ta_version__"

and it returned 0.4.0, so the library loaded successfully.

I tried:
 
LD_LIBRARY_PATH=/usr/lib
export LD_LIBRARY_PATH
python

in a terminal.
I was able to import talib without error.

Thanks for your help. I really like TA-lib and your efforts in bringing it to python.

**Comment by mrjbq7** [comment]
Sweet! Glad it's working!

The ``LD_LIBRARY_PATH`` is a workaround, exporting that might cause problems for other applications.  You might look into the "right" way to do it for your system (such as adding a file to ``/etc/ld.so.conf.d`` maybe if that fits your platform), or perhaps just set it like this where you are adding it to whatever was already set, instead of just overwriting it:

```
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/lib
```

**Comment by hotea** [comment]
I solved this by reinstall ta-lib with `libdir` configure option:
P.S. my system is centos7

```
wget wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
tar zxvf ta-lib-0.4.0-src.tar.gz
cd ta-lib/
./configure --prefix=/usr  --exec-prefix=/usr --libdir=/usr/lib64
make
make install
```

then, reinstall ta-lib by pip
```
pip uninstall ta-lib
pip install ta-lib
```
