### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by timkofu** [mrjbq7/ta-lib#73]
This is cool work. Thank you.

**Comment by mrjbq7** [comment]
Hi @timkofu, thanks for saying that!  I'm very glad its working for you and others with interests in finance.  Let me know if you have any feedback or improvements that could be made for your use-case.  I've been meaning to add better ``pandas`` support, but haven't had a chance yet.

**Comment by mike-upshon** [comment]
@mrjbq7 Great work thanks

**Comment by femtotrader** [comment]
@mrjbq7 Thanks too!

**Comment by mrjbq7** [comment]
Thanks guys!
