### ISSUE TITLE
Docs for install are out of date

### ISSUE THREAD

**Issue by metaperl** [mrjbq7/ta-lib#81]
The [docs for installing Python ta-lib](http://mrjbq7.github.io/ta-lib/install.html) are out of date. As [shown  in this thread](https://github.com/mrjbq7/ta-lib/issues/37) installation on mac is as simple as 

    $ brew install ta-lib
    $ pip install ta-lib

But the docs do not say that.

**Comment by mrjbq7** [comment]
Fixed, thanks!
