### ISSUE TITLE
Williams %R returns negative values

### ISSUE THREAD

**Issue by mike-upshon** [mrjbq7/ta-lib#82]
Hi

Looks like somthing may be wrong with the WILLR - Williams Percent R implementation, It returns negative values.

``` python
import pandas as pd
import talib
from pandas.io.data import DataReader
from datetime import datetime

end = datetime.now()
start = datetime(end.year - 1, end.month, end.day)

df = DataReader('SPY', 'yahoo', start, end)

df['PctR'] = talib.WILLR(df.High.values, df.Low.values, df.Close.values, timeperiod=4)

df.PctR.tail()
```

Result is:

```
Date
2015-04-27   -47.765230
2015-04-28   -33.015873
2015-04-29   -60.634603
2015-04-30   -82.715844
2015-05-01   -20.103093
Name: PctR, dtype: float64
```

**Comment by mrjbq7** [comment]
Looks like maybe it's always returning a negative value?

This would be a version in Python, which seems to produce the same values but positive?

```python
import numpy as np
import pandas as pd

def WILLR(h, l, c, n):
    hh = pd.rolling_max(h, n, min_periods=1)
    ll = pd.rolling_min(l, n, min_periods=1)
    spread = hh - ll
    willr = np.select([spread != 0.], [100 * (hh - c) / spread], default=0.)
    return willr
```

**Comment by mrjbq7** [comment]
Seems to be exactly what it's doing.

```python
>>> import numpy as np

>>> h = np.array([5, 7, 10, 4, 8], dtype=float)
>>> l = np.array([1, 4, 8, 2, 7], dtype=float)
>>> c = np.array([5, 6, 9, 3, 8], dtype=float)

>>> import talib

>>> talib.WILLR(h, l, c, timeperiod=2)
array([         nan, -16.66666667, -16.66666667, -87.5       ,  -0.        ])
```

versus our function above

```python
>>> WILLR(h, l, c, 2)
array([  0.        ,  16.66666667,  16.66666667,  87.5       ,   0.        ])
```

I suspect it is this line in the underlying C code:

http://sourceforge.net/p/ta-lib/code/HEAD/tree/trunk/ta-lib/c/src/ta_func/ta_WILLR.c#l290

Which makes ``diff`` negative (dividing by ``-100.0``), making this line produce negative output:

http://sourceforge.net/p/ta-lib/code/HEAD/tree/trunk/ta-lib/c/src/ta_func/ta_WILLR.c#l294

**Comment by Kapik1337** [comment]
What's the problem? Williams %R is *supposed* to return negative values, ranging from -100 to 0.

**Comment by mike-upshon** [comment]
Not according to Larry Williams

**Comment by adnls** [comment]
williams %r returns allways negative values -> under -70 it's oversold; above -30 it's overbought... I don't understand the question asked. Is there something i missed in %r interpretation?

**Comment by cod3min3** [comment]
I don't mean to nitpick, but shouldn't this issue be closed?
