### ISSUE TITLE
Function to set TA_SetUnstablePeriod?

### ISSUE THREAD

**Issue by marcomayer** [mrjbq7/ta-lib#84]
Hi,

thanks for that great lib, it really saved me a lot of time already.

What I'm missing is a way to set TA_SetUnstablePeriod, see http://ta-lib.org/d_api/ta_setunstableperiod.html

Maybe I just missed it but couldn't find it. Would it be hard to add it?

Thanks,

Marco

**Comment by mrjbq7** [comment]
Okay, added support in 31a0349e82ac97adf9c628b3e9a4856dd5aaa149.

You can use it like this:

```python
import talib

talib.set_unstable_period('EMA', 100)
talib.EMA(data, 20)
```

You can also ``get_unstable_period('EMA')`` to see what it is set to.

The constants ``'ALL'`` and ``'NONE'`` are available similarly to the C API.

Let me know if that works for you.

**Comment by marcomayer** [comment]
Works like a charm, thanks! This lib really saves me a ton of time already and will probably continue to do so in the future, is there a way to donate a few bucks to keep it going and support it?

**Comment by mrjbq7** [comment]
Hi @marcomayer thats a really generous and kind offer, but I'm not really setup for donations.  I'm not sure where in the world you call home, but I'd love to grab a beer with you if you're ever in San Francisco or if we cross paths somewhere.

**Comment by marcomayer** [comment]
@mrjbq7 I'll let you know when I'm over there. I live in Berlin so should you ever be in town let me know! :)
