### ISSUE TITLE
Did you have plan to  add "begidx" and "endidx" arguments to interface?

### ISSUE THREAD

**Issue by wondereamer** [mrjbq7/ta-lib#91]
ta-lib is a very powerful tool. I think the interface right now  plays well for back testing.
In some situation, like realtime trading, I would like to calculate the last value rather than all values.
Did you have plan to add index arguments to interface?

**Comment by mrjbq7** [comment]
Easier than trying to compute the lookback and then slicing the data?

I originally removed them to avoid giving back arrays full of NaNs, but maybe that was a mistake.

**Comment by mrjbq7** [comment]
Oh, I remember, I removed them because I thought they were a little complicated and wanted a simpler interface... it wouldn't be difficult to add them back, though.

**Comment by wondereamer** [comment]
Computing the lookback and then slicing the data works, but it would be slower. I could help to add them
back, if you think it's a good idea :P.

**Comment by mrjbq7** [comment]
I have a nice script in ``tools/generate.py`` that makes ``func.pyx`` for me based on parsing the ``libta_lib`` header files.  I don't mind modifying it.

Should we have ``startIdx``, ``endIdx`` both?  If we do that, should we somehow return the ``outBegIdx`` and ``outNBElement``?

What should the variable names be called?  And if they are keyword arguments, they'd have to be at the end with a default value of None meaning start at ``0`` and end at ``length``.

**Comment by wondereamer** [comment]
Yeath, you have made the point. Adding `startIdx` and `endIdx` did over complicate the interface, particularly the return value. 
Do you think it make sense to add just one argument `rolling`(default=False) to the interface, 
like `talib.SMA(data, n, true)` , which make the function to calculate and return the last "sma" of `data`?
In this way, the interface would meet two most common demand: backtesting and realtime trading, 
without over complicate the interface.

**Comment by mrjbq7** [comment]
I'm not sure my point was that it over complicates it. And I do want to support realtime more effectively, so... 

Adding a `rolling` keyword is one option, another might be a "full" interface that exposes all the capabilities of the C library, another is to just add some keyword arguments and forget the return values, another might be to return those values also.

I'm not really hung up on design, would prefer to get some things working, so if you want I could try commuting a "real time" version of `talib.func` that exposes this capability in a way that you can use and go from there?

Do you need the outBegIdx and outNBElements?

**Comment by wondereamer** [comment]
Thanks so much.
 I don't need `outBegIdx` or `outNBElements :)

**Comment by mrjbq7** [comment]
Do you have a sense for the performance difference and whether it matters for your application?

Another level of performance would be to pre-allocate the ``out`` array and re-use from one call to the next...?

**Comment by wondereamer** [comment]
I think performace is always one of the major concerns of trading system. Though not all users care 
about them that much, some does. 

Yes, pre-allocating the `out` array is another level of performance, and may be we would pre-allocating the `input` too, which means we should pass a `index` argument(instead of `rolling`) to calculate the "last" value. I'm not sure if we should pass a `out` array as a argument.
[quantdigger](https://github.com/QuantFans/quantdigger) is a backtesting system of mine. I'm reimplementing it to support backtesting thousands of stocks step by step. I use a sliding window to save
results(because of memory issue), which have a different way of indexing. So I think if we don't pass a `out` array as arguments, users could choose the right way to assign the result, of course, the could still pre-allocate the `out` array. This may be a better option than adding a `rolling` argument.

A 'full' interface is another option. I guess it's for research purpose, not realtime trading or massive backtesting. It's a hard choice, i prefer the simpler one :P 
Thanks.

**Comment by wondereamer** [comment]
Sorry, I mean loop-sliding-window array for output.

**Comment by Thorbinator** [comment]
Hello, I have run into this same issue. My ultimate preference for implementation is whatever is quickest+easiest for the implementer. Otherwise, a rolling flag works. My use cases are massive backtesting (aka generating data for deep learning algos) and realtime. With second-level resolution my program is bogging down when computing the indicator across the full series and only keeping[-1].

**Comment by mrjbq7** [comment]
Hi @wondereamer, I have pushed an experimental "Streaming API" to git master.  If you are only interested in the "last value", you can do this:

```python
import talib.stream as ta
ta.MOM(close)
```

Instead of this:

```python
import talib as ta
ta.MOM(close)[-1]
```

Does this help with your use-case?

I'd like to generalize it for returning the last ``n`` results, but wanted to push a quick attempt at helping @Thorbinator and you.
