### ISSUE TITLE
ta-lib python for Cygwin failing with the below error

### ISSUE THREAD

**Issue by ashgen** [mrjbq7/ta-lib#94]
python -c "import talib"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/talib/__init__.py", line 5, in <module>
    from . import abstract
ImportError: dynamic module does not define init function (initabstract)

**Comment by mrjbq7** [comment]
What version of this module?  Is it latest git master?

Did you compile it yourself or download a package?

What version of cython did you use to build it?

**Comment by ashgen** [comment]
I downloaded the latest git version and then installed with adding cywing
in setup.py with Unix sources . it compiled with some error but then when I
import talib it gives me the error

**Comment by mrjbq7** [comment]
Hi, I'm sorry but I finally looked and realized a bad commit had messed up ``abstract.c``.  It is fixed now if you want to try and update.  It didn't affect the previous released version on PyPI if you were installing from ``pip``, but only the git master I think.

Fixed now!!

**Comment by ashgen** [comment]
Hi John,
Thanks for the mail. I have checked the latest git version and though the
python setup went fine it gave me an error while importing common. Can you
please look into it.

**Comment by ashgen** [comment]
Take the world's best courses, online. Coursera envisions a world where 
anyone, anywhere can transform their life by accessing the world’s best 
learning experience.
[Ready to learn something new?]
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvP3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLl94LWJVUDduRWVXVzloTDYwci1hS1EiLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDYzNDliMzA1MzUzNmY2NWZmOTY0MWI2MmU4Zjg4MzNkZTQxN2E0YzMwNmQ0M2Q5MmNmMDAwMDAwMDExMjkyN2NkNTkyYTE2OWNlMDc1ZWViYjBAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uX3gtYlVQN25FZVdXOWhMNjByLWFLUSJ9fSwidXNlcklkIjotMX0.9UpunURt-R9t77V2Hz8MXadzUkaOcGIEimn0dbzsrjA> 	
My Courses
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvP3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLl94LWJVUDduRWVXVzloTDYwci1hS1EiLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDYzNDliMzA1MzUzNmY2NWZmOTY0MWI2MmU4Zjg4MzNkZTQxN2E0YzMwNmQ0M2Q5MmNmMDAwMDAwMDExMjkyN2NkNTkyYTE2OWNlMDc1ZWViYjBAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uX3gtYlVQN25FZVdXOWhMNjByLWFLUSJ9fSwidXNlcklkIjotMX0.9UpunURt-R9t77V2Hz8MXadzUkaOcGIEimn0dbzsrjA> 
Course Catalog
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvY291cnNlcz91dG1fbWVkaXVtPWVtYWlsJnV0bV9zb3VyY2U9aW52aXRhdGlvbnMmdXRtX2NhbXBhaWduPW5vdGlmaWNhdGlvbnMuYXV0by5feC1iVVA3bkVlV1c5aEw2MHItYUtRIiwidHJhY2tpbmciOnsidXNlcklkIjotMSwidXNlckVtYWlsIjoicmVwbHkrMDA2MzQ5YjMwNTM1MzZmNjVmZjk2NDFiNjJlOGY4ODMzZGU0MTdhNGMzMDZkNDNkOTJjZjAwMDAwMDAxMTI5MjdjZDU5MmExNjljZTA3NWVlYmIwQHJlcGx5LmdpdGh1Yi5jb20iLCJub3RpZmljYXRpb25UeXBlIjoiZ3Jvd3RoLmludml0YXRpb24iLCJjYW1wYWlnbklkIjoibm90aWZpY2F0aW9ucy5hdXRvLl94LWJVUDduRWVXVzloTDYwci1hS1EifX0sInVzZXJJZCI6LTF9.xnX-rI5rN3pNaMbIvzt-bZS3wPoGzZgwQl-A89ufqkg>


ashish sachan thinks you'll love learning on Coursera

We envision a world where anyone, anywhere can transform their life by 
accessing the world’s best learning experience. We offer hundreds open 
online courses, in dozens of subject areas, all from top universities and 
institutions.

Course topics range from business and management, to computer science, to 
medicine, music, education, and more.

Millions of our learners have advanced their careers, discovered new 
passions, and built lasting friendships through their Coursera courses. We 
hope you'll join us in learning without limits!

The Coursera Team

Explore Coursera
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvb25ib2FyZGluZy8_dG9rZW49MDNhMmNiMjdjYzg4NGQ2NTVlNjhjMjM3YjY1NjIyYTcmZW1haWw9cmVwbHkrMDA2MzQ5YjMwNTM1MzZmNjVmZjk2NDFiNjJlOGY4ODMzZGU0MTdhNGMzMDZkNDNkOTJjZjAwMDAwMDAxMTI5MjdjZDU5MmExNjljZTA3NWVlYmIwQHJlcGx5LmdpdGh1Yi5jb20mbmFtZT1tcmpicTcvdGEtbGliP3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLl94LWJVUDduRWVXVzloTDYwci1hS1EiLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDYzNDliMzA1MzUzNmY2NWZmOTY0MWI2MmU4Zjg4MzNkZTQxN2E0YzMwNmQ0M2Q5MmNmMDAwMDAwMDExMjkyN2NkNTkyYTE2OWNlMDc1ZWViYjBAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uX3gtYlVQN25FZVdXOWhMNjByLWFLUSJ9fSwidXNlcklkIjotMX0.6pS0kAPhXpchS2d49qg9SX2tSpKciLDZQfaNWNy3fVI>
Download our App:  iOS
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL2l0dW5lcy5hcHBsZS5jb20vYXBwL2FwcGxlLXN0b3JlL2lkNzM2NTM1OTYxP2N0PU1vYmlsZSUyMFByb21vJTIwRW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZtdD04JnB0PTIzMzQxNTAmdXRtX2NhbXBhaWduPW5vdGlmaWNhdGlvbnMuYXV0by5feC1iVVA3bkVlV1c5aEw2MHItYUtRJnV0bV9tZWRpdW09ZW1haWwiLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDYzNDliMzA1MzUzNmY2NWZmOTY0MWI2MmU4Zjg4MzNkZTQxN2E0YzMwNmQ0M2Q5MmNmMDAwMDAwMDExMjkyN2NkNTkyYTE2OWNlMDc1ZWViYjBAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uX3gtYlVQN25FZVdXOWhMNjByLWFLUSJ9fSwidXNlcklkIjotMX0.rG4uIAJy90XKbuzUvXdywpyLd8vS5zgu6IBtFQDHPEg> 
  |  Android
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3BsYXkuZ29vZ2xlLmNvbS9zdG9yZS9hcHBzL2RldGFpbHM_aWQ9b3JnLmNvdXJzZXJhLmFuZHJvaWQmdXRtX21lZGl1bT1lbWFpbCZ1dG1fc291cmNlPWludml0YXRpb25zJnV0bV9jYW1wYWlnbj1ub3RpZmljYXRpb25zLmF1dG8uX3gtYlVQN25FZVdXOWhMNjByLWFLUSIsInRyYWNraW5nIjp7InVzZXJJZCI6LTEsInVzZXJFbWFpbCI6InJlcGx5KzAwNjM0OWIzMDUzNTM2ZjY1ZmY5NjQxYjYyZThmODgzM2RlNDE3YTRjMzA2ZDQzZDkyY2YwMDAwMDAwMTEyOTI3Y2Q1OTJhMTY5Y2UwNzVlZWJiMEByZXBseS5naXRodWIuY29tIiwibm90aWZpY2F0aW9uVHlwZSI6Imdyb3d0aC5pbnZpdGF0aW9uIiwiY2FtcGFpZ25JZCI6Im5vdGlmaWNhdGlvbnMuYXV0by5feC1iVVA3bkVlV1c5aEw2MHItYUtRIn19LCJ1c2VySWQiOi0xfQ.aWQfF6jq59wwJy2tMSeHq6c6cz77dpFZMa0srWWlTV8>
Learner Help Center
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL2xlYXJuZXIuY291cnNlcmEuaGVscC8_dXRtX21lZGl1bT1lbWFpbCZ1dG1fc291cmNlPWludml0YXRpb25zJnV0bV9jYW1wYWlnbj1ub3RpZmljYXRpb25zLmF1dG8uX3gtYlVQN25FZVdXOWhMNjByLWFLUSIsInRyYWNraW5nIjp7InVzZXJJZCI6LTEsInVzZXJFbWFpbCI6InJlcGx5KzAwNjM0OWIzMDUzNTM2ZjY1ZmY5NjQxYjYyZThmODgzM2RlNDE3YTRjMzA2ZDQzZDkyY2YwMDAwMDAwMTEyOTI3Y2Q1OTJhMTY5Y2UwNzVlZWJiMEByZXBseS5naXRodWIuY29tIiwibm90aWZpY2F0aW9uVHlwZSI6Imdyb3d0aC5pbnZpdGF0aW9uIiwiY2FtcGFpZ25JZCI6Im5vdGlmaWNhdGlvbnMuYXV0by5feC1iVVA3bkVlV1c5aEw2MHItYUtRIn19LCJ1c2VySWQiOi0xfQ.FZ5r-vAaiqd082UyYq_44V19REXQ9vVuqdf3pPJYaAE> 
  | Please do not reply directly to this email
To no longer receive invitations from your friends on Coursera, 
Unsubscribe
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvYWNjb3VudC91bnN1YnNjcmliZS9PVmM0NU1CYWhZWTR6S1E0Z1dTMVFTZHE5SWRSNTFVeUtsR3ZmN3BRY2tyb3R1VE1OdlBBeVoyMU9oZE1oQTZfck4xMF9pRXF1Z1cxODBuQzZvZjl2US5lUmJmZlQ0M3NpQmJhYXJIWWdOLU93LlhIZ0hfRnAwWWM1aWRkdlBwRko2R1E2TElhZWs2RXpsNGg2d2gtT0t3WHEzVEh3UFF2WVU3M3EyaC16Nkd2Y1hCWkhPWF93T1RmTTFVT01xdFczdDhERWNueHl6Q2V4bUNLOGdJVk5YSFFHQW05RDBydm5ra093TXBxa1RoZzE4WHlDdV9NZ2Nfcm53S3I4NEo3RDVTSDJweDJkeUNEWUxleUFDRVVPSE5tWEU2Y1Bodm8yMjNMMU4zWk13RmhCSTdyRGRNemJUbGk1MFF6a2xJVDRhaVpEdHctc2tHcUp3VWtpQlItelYwaDh2WUwxckZqS0dWd0xscmF2US1oOXliWGxrSExhbWZfWHZVN25QMUZvLU15dGM3d3I4b0NHWTJOQkJUX1k4eHJ3P3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLl94LWJVUDduRWVXVzloTDYwci1hS1EiLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDYzNDliMzA1MzUzNmY2NWZmOTY0MWI2MmU4Zjg4MzNkZTQxN2E0YzMwNmQ0M2Q5MmNmMDAwMDAwMDExMjkyN2NkNTkyYTE2OWNlMDc1ZWViYjBAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uX3gtYlVQN25FZVdXOWhMNjByLWFLUSJ9fSwidXNlcklkIjotMX0.MxNjq6sTVGjshCqrxKJWjcus8zRuOvLTWblVdKNZjA0>
Copyright © 2016, Coursera Inc. | 381 E. Evelyn Ave, Mountain View, CA 
94041 USA

**Comment by ashgen** [comment]
Take the world's best courses, online. Coursera envisions a world where 
anyone, anywhere can transform their life by accessing the world’s best 
learning experience.
[Ready to learn something new?]
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvP3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLl95RWh5UDduRWVXQjV3NHF1YlhmV3ciLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDYzNDliM2VlNGYzMDU4NmI3YzM1ZmQ0MTBiODRjYjViZDJiOGM5ZGYxOGY1NjM5MmNmMDAwMDAwMDExMmEzZDViMDkyYTE2OWNlMDc1ZWViYjBAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uX3lFaHlQN25FZVdCNXc0cXViWGZXdyJ9fSwidXNlcklkIjotMX0.u5Wk5q46Qhl40nOxV_LTr6oFxC7LYn02pE7577uavlE> 	
My Courses
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvP3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLl95RWh5UDduRWVXQjV3NHF1YlhmV3ciLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDYzNDliM2VlNGYzMDU4NmI3YzM1ZmQ0MTBiODRjYjViZDJiOGM5ZGYxOGY1NjM5MmNmMDAwMDAwMDExMmEzZDViMDkyYTE2OWNlMDc1ZWViYjBAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uX3lFaHlQN25FZVdCNXc0cXViWGZXdyJ9fSwidXNlcklkIjotMX0.u5Wk5q46Qhl40nOxV_LTr6oFxC7LYn02pE7577uavlE> 
Course Catalog
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvY291cnNlcz91dG1fbWVkaXVtPWVtYWlsJnV0bV9zb3VyY2U9aW52aXRhdGlvbnMmdXRtX2NhbXBhaWduPW5vdGlmaWNhdGlvbnMuYXV0by5feUVoeVA3bkVlV0I1dzRxdWJYZld3IiwidHJhY2tpbmciOnsidXNlcklkIjotMSwidXNlckVtYWlsIjoicmVwbHkrMDA2MzQ5YjNlZTRmMzA1ODZiN2MzNWZkNDEwYjg0Y2I1YmQyYjhjOWRmMThmNTYzOTJjZjAwMDAwMDAxMTJhM2Q1YjA5MmExNjljZTA3NWVlYmIwQHJlcGx5LmdpdGh1Yi5jb20iLCJub3RpZmljYXRpb25UeXBlIjoiZ3Jvd3RoLmludml0YXRpb24iLCJjYW1wYWlnbklkIjoibm90aWZpY2F0aW9ucy5hdXRvLl95RWh5UDduRWVXQjV3NHF1YlhmV3cifX0sInVzZXJJZCI6LTF9.Om4PQsyE7MzZXL9CYT4aLQooggBqjd7djv7SY-6YUvM>


ashish sachan thinks you'll love learning on Coursera

We envision a world where anyone, anywhere can transform their life by 
accessing the world’s best learning experience. We offer hundreds open 
online courses, in dozens of subject areas, all from top universities and 
institutions.

Course topics range from business and management, to computer science, to 
medicine, music, education, and more.

Millions of our learners have advanced their careers, discovered new 
passions, and built lasting friendships through their Coursera courses. We 
hope you'll join us in learning without limits!

The Coursera Team

Explore Coursera
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvb25ib2FyZGluZy8_dG9rZW49M2Q5OTNhNmU2MGYwNWRmZWQyZTkyYWQwN2JjZDA5MjUmZW1haWw9cmVwbHkrMDA2MzQ5YjNlZTRmMzA1ODZiN2MzNWZkNDEwYjg0Y2I1YmQyYjhjOWRmMThmNTYzOTJjZjAwMDAwMDAxMTJhM2Q1YjA5MmExNjljZTA3NWVlYmIwQHJlcGx5LmdpdGh1Yi5jb20mbmFtZT1tcmpicTcvdGEtbGliP3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLl95RWh5UDduRWVXQjV3NHF1YlhmV3ciLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDYzNDliM2VlNGYzMDU4NmI3YzM1ZmQ0MTBiODRjYjViZDJiOGM5ZGYxOGY1NjM5MmNmMDAwMDAwMDExMmEzZDViMDkyYTE2OWNlMDc1ZWViYjBAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uX3lFaHlQN25FZVdCNXc0cXViWGZXdyJ9fSwidXNlcklkIjotMX0.cxstNW-syf0knHsl3u9wVsTZP2FSta1zHgIkiO8Yrkk>
Download our App:  iOS
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL2l0dW5lcy5hcHBsZS5jb20vYXBwL2FwcGxlLXN0b3JlL2lkNzM2NTM1OTYxP2N0PU1vYmlsZSUyMFByb21vJTIwRW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZtdD04JnB0PTIzMzQxNTAmdXRtX2NhbXBhaWduPW5vdGlmaWNhdGlvbnMuYXV0by5feUVoeVA3bkVlV0I1dzRxdWJYZld3JnV0bV9tZWRpdW09ZW1haWwiLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDYzNDliM2VlNGYzMDU4NmI3YzM1ZmQ0MTBiODRjYjViZDJiOGM5ZGYxOGY1NjM5MmNmMDAwMDAwMDExMmEzZDViMDkyYTE2OWNlMDc1ZWViYjBAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uX3lFaHlQN25FZVdCNXc0cXViWGZXdyJ9fSwidXNlcklkIjotMX0.W2XDFn_qMsWpfn0bujt6AGUfiGGxXwVyCngZZ-54cb0> 
  |  Android
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3BsYXkuZ29vZ2xlLmNvbS9zdG9yZS9hcHBzL2RldGFpbHM_aWQ9b3JnLmNvdXJzZXJhLmFuZHJvaWQmdXRtX21lZGl1bT1lbWFpbCZ1dG1fc291cmNlPWludml0YXRpb25zJnV0bV9jYW1wYWlnbj1ub3RpZmljYXRpb25zLmF1dG8uX3lFaHlQN25FZVdCNXc0cXViWGZXdyIsInRyYWNraW5nIjp7InVzZXJJZCI6LTEsInVzZXJFbWFpbCI6InJlcGx5KzAwNjM0OWIzZWU0ZjMwNTg2YjdjMzVmZDQxMGI4NGNiNWJkMmI4YzlkZjE4ZjU2MzkyY2YwMDAwMDAwMTEyYTNkNWIwOTJhMTY5Y2UwNzVlZWJiMEByZXBseS5naXRodWIuY29tIiwibm90aWZpY2F0aW9uVHlwZSI6Imdyb3d0aC5pbnZpdGF0aW9uIiwiY2FtcGFpZ25JZCI6Im5vdGlmaWNhdGlvbnMuYXV0by5feUVoeVA3bkVlV0I1dzRxdWJYZld3In19LCJ1c2VySWQiOi0xfQ.9oM2FjKKWrVLODe1LQ03lKbz-mmgqdCSyJZe23yk9r0>
Learner Help Center
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL2xlYXJuZXIuY291cnNlcmEuaGVscC8_dXRtX21lZGl1bT1lbWFpbCZ1dG1fc291cmNlPWludml0YXRpb25zJnV0bV9jYW1wYWlnbj1ub3RpZmljYXRpb25zLmF1dG8uX3lFaHlQN25FZVdCNXc0cXViWGZXdyIsInRyYWNraW5nIjp7InVzZXJJZCI6LTEsInVzZXJFbWFpbCI6InJlcGx5KzAwNjM0OWIzZWU0ZjMwNTg2YjdjMzVmZDQxMGI4NGNiNWJkMmI4YzlkZjE4ZjU2MzkyY2YwMDAwMDAwMTEyYTNkNWIwOTJhMTY5Y2UwNzVlZWJiMEByZXBseS5naXRodWIuY29tIiwibm90aWZpY2F0aW9uVHlwZSI6Imdyb3d0aC5pbnZpdGF0aW9uIiwiY2FtcGFpZ25JZCI6Im5vdGlmaWNhdGlvbnMuYXV0by5feUVoeVA3bkVlV0I1dzRxdWJYZld3In19LCJ1c2VySWQiOi0xfQ.ksDdtjesol2psDhpm2OzQIlAmSw7LMFIKroO4VtPBGs> 
  | Please do not reply directly to this email
To no longer receive invitations from your friends on Coursera, 
Unsubscribe
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvYWNjb3VudC91bnN1YnNjcmliZS9XYklwNVdQaW02NDVyT0RMQmo1Nk9BWlZXQ3EwS0NpbjM0RzlyS0xMYW5ZaExSS2hndlhZQVZNMDd2aHE3bXp5cWo1cGt1bmZ6SG5lUFNTV05ycUc4Zy5oMjkxekMzRWdiNFlpN3FFMDlXQkZBLmt4LVZ3YWtJYlV3TXNLUzdHVVo2NkROUlNITzljQzZvZUNDa3R1bUhKUFdaWllueUd5SF9yT3BDZ096X2dDSHV4Q2ZrZkxCeEE2ZmlNTkx3dDhNT2hlbHF3eFpMS3VROF9IR2tlNC1xbXdHVlVBZUpDeHVvYXA5UHVoaU44bDdnOTlIcnVKbkxZVmY0ejdUd19hZndTUUsyRmM5RXl0S3F3cW5zbTZnS3A1NXJpYUNVMGloUk12Q2pFZkx6aVdKT3RtZUhycmdGYXAxSmpONTRPbEhDbmlOdUdKd1NvYWtMbjVGaU1ZZFdXa3FTczJqTGFTNDJiQ0tvMUZ6bDVvM0Mzem1HcmQwbHNJSFZ1NXY1Y1pMcjFFUUxuWjVUSlZoWHczZ3loRHViSHZZP3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLl95RWh5UDduRWVXQjV3NHF1YlhmV3ciLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDYzNDliM2VlNGYzMDU4NmI3YzM1ZmQ0MTBiODRjYjViZDJiOGM5ZGYxOGY1NjM5MmNmMDAwMDAwMDExMmEzZDViMDkyYTE2OWNlMDc1ZWViYjBAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uX3lFaHlQN25FZVdCNXc0cXViWGZXdyJ9fSwidXNlcklkIjotMX0.5nApQpmgywnsz-QexCyFRUzZ_Y1xc3DKrWnRb2m3mjM>
Copyright © 2016, Coursera Inc. | 381 E. Evelyn Ave, Mountain View, CA 
94041 USA
